// src/routes/org/$slug/space/index.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { useConvexAuth, useMutation, useQuery } from 'convex/react'
import { addMonths, endOfMonth, format, getDay, startOfMonth } from 'date-fns'
import {
  AlertCircle,
  Building2,
  Calendar,
  CalendarDays,
  CheckCircle2,
  Clock,
  Coffee,
  Loader2,
  LogIn,
  MapPin,
  Monitor,
  Printer,
  ScrollText,
  ShowerHead,
  Sparkles,
  Users,
  Wifi,
} from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { api } from '../../../../../convex/_generated/api'
import type { Id } from '../../../../../convex/_generated/dataModel'
import { AuthHeader } from '~/components/layout/auth-header'
import { GradientBg } from '~/components/layout/GradientBg'
import {
  BookingCalendar,
  BookingCalendarLegend,
} from '~/components/space/BookingCalendar'
import { TimeRangePicker } from '~/components/space/TimeRangePicker'
import { AttendeeList } from '~/components/space/AttendeeList'
import { Button } from '~/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { Checkbox } from '~/components/ui/checkbox'
import { Label } from '~/components/ui/label'
import { Textarea } from '~/components/ui/textarea'

export const Route = createFileRoute('/org/$slug/space/')({
  component: SpaceLandingPage,
})

// Map known amenity names to lucide icons
const AMENITY_ICONS: Record<string, React.ElementType> = {
  WiFi: Wifi,
  'External Monitors': Monitor,
  'Coffee/Tea': Coffee,
  Printer: Printer,
  Showers: ShowerHead,
}

const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat']

function formatMinutes(minutes: number): string {
  const h = Math.floor(minutes / 60)
  const m = minutes % 60
  const period = h >= 12 ? 'PM' : 'AM'
  const hour12 = h === 0 ? 12 : h > 12 ? h - 12 : h
  return m === 0
    ? `${hour12} ${period}`
    : `${hour12}:${String(m).padStart(2, '0')} ${period}`
}

function SpaceLandingPage() {
  const { slug } = Route.useParams()
  const { isAuthenticated, isLoading: authLoading } = useConvexAuth()

  // Public query — no auth required
  const spaceLanding = useQuery(api.coworkingSpaces.getSpaceLanding, { slug })

  // Membership query — only if authenticated and we have an orgId
  const membership = useQuery(
    api.orgs.membership.getMembership,
    isAuthenticated && spaceLanding ? { orgId: spaceLanding.orgId } : 'skip',
  )

  // Loading
  if (spaceLanding === undefined) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-4xl mx-auto">
            <div className="animate-pulse space-y-6">
              <div className="h-64 bg-slate-100 rounded-xl" />
              <div className="h-16 bg-slate-100 rounded-xl" />
              <div className="h-40 bg-slate-100 rounded-xl" />
            </div>
          </div>
        </main>
      </GradientBg>
    )
  }

  // Not found
  if (spaceLanding === null) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Building2 className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-display text-foreground mb-4">
              Space Not Found
            </h1>
            <p className="text-slate-600 mb-6">
              This organization doesn&apos;t have a co-working space, or the
              link is incorrect.
            </p>
            <Button asChild>
              <Link to="/org/$slug" params={{ slug }}>
                Back to Organization
              </Link>
            </Button>
          </div>
        </main>
      </GradientBg>
    )
  }

  const isMember = membership !== null && membership !== undefined

  return (
    <GradientBg>
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto space-y-8">
          {/* Hero / Cover Image */}
          {spaceLanding.coverImageUrl ? (
            <div className="relative rounded-2xl overflow-hidden">
              <img
                src={spaceLanding.coverImageUrl}
                alt={spaceLanding.spaceName}
                className="w-full h-64 sm:h-80 object-cover"
              />
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 to-transparent" />
              <div className="absolute bottom-0 left-0 right-0 p-6">
                <SpaceTitle landing={spaceLanding} light />
              </div>
            </div>
          ) : (
            <Card className="p-6">
              <SpaceTitle landing={spaceLanding} />
            </Card>
          )}

          {/* Description */}
          {spaceLanding.description && (
            <section>
              <p className="text-muted-foreground leading-relaxed whitespace-pre-line">
                {spaceLanding.description}
              </p>
            </section>
          )}

          {/* Amenities */}
          {spaceLanding.amenities && spaceLanding.amenities.length > 0 && (
            <section>
              <h2 className="text-lg font-semibold mb-3">Amenities</h2>
              <div className="flex flex-wrap gap-2">
                {spaceLanding.amenities.map((amenity) => {
                  const Icon = AMENITY_ICONS[amenity] ?? Sparkles
                  return (
                    <span
                      key={amenity}
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-full bg-slate-100 text-sm text-slate-700"
                    >
                      <Icon className="size-4" />
                      {amenity}
                    </span>
                  )
                })}
              </div>
            </section>
          )}

          {/* House Rules */}
          {spaceLanding.houseRules && (
            <section>
              <h2 className="text-lg font-semibold mb-3 flex items-center gap-2">
                <ScrollText className="size-5" />
                House Rules
              </h2>
              <ul className="space-y-1.5 text-muted-foreground">
                {spaceLanding.houseRules
                  .split('\n')
                  .filter((r) => r.trim())
                  .map((rule, i) => (
                    <li key={i} className="flex items-start gap-2">
                      <span className="text-primary mt-0.5">&#8226;</span>
                      {rule.trim()}
                    </li>
                  ))}
              </ul>
            </section>
          )}

          {/* Operating Hours */}
          <section>
            <h2 className="text-lg font-semibold mb-3 flex items-center gap-2">
              <Clock className="size-5" />
              Operating Hours
            </h2>
            <div className="grid grid-cols-2 sm:grid-cols-4 gap-2">
              {spaceLanding.operatingHours
                .slice()
                .sort((a, b) => a.dayOfWeek - b.dayOfWeek)
                .map((h) => (
                  <div
                    key={h.dayOfWeek}
                    className={`rounded-lg border px-3 py-2 text-sm ${
                      h.isClosed
                        ? 'bg-slate-50 text-muted-foreground'
                        : 'bg-background'
                    }`}
                  >
                    <div className="font-medium">{DAY_NAMES[h.dayOfWeek]}</div>
                    <div className="text-muted-foreground">
                      {h.isClosed
                        ? 'Closed'
                        : `${formatMinutes(h.openMinutes)} - ${formatMinutes(h.closeMinutes)}`}
                    </div>
                  </div>
                ))}
            </div>
          </section>

          {/* Divider */}
          <hr className="border-slate-200" />

          {/* Booking Section (gated) */}
          <BookingSection
            spaceLanding={spaceLanding}
            isMember={isMember}
            isAuthenticated={isAuthenticated}
            authLoading={authLoading}
            slug={slug}
          />
        </div>
      </main>
    </GradientBg>
  )
}

interface SpaceLandingData {
  spaceId: Id<'coworkingSpaces'>
  spaceName: string
  orgId: Id<'organizations'>
  orgName: string
  orgSlug?: string
  orgLogoUrl?: string
  capacity: number
  timezone: string
  operatingHours: Array<{
    dayOfWeek: number
    openMinutes: number
    closeMinutes: number
    isClosed: boolean
  }>
  guestAccessEnabled: boolean
  description?: string
  address?: string
  addressNote?: string
  coverImageUrl?: string
  amenities?: Array<string>
  houseRules?: string
}

function SpaceTitle({
  landing,
  light,
}: {
  landing: SpaceLandingData
  light?: boolean
}) {
  return (
    <div className="flex items-center gap-4">
      {landing.orgLogoUrl ? (
        <img
          src={landing.orgLogoUrl}
          alt={landing.orgName}
          className="size-12 rounded-lg object-cover"
        />
      ) : (
        <div
          className={`size-12 rounded-lg flex items-center justify-center ${
            light ? 'bg-white/20' : 'bg-primary/10'
          }`}
        >
          <Building2
            className={`size-6 ${light ? 'text-white' : 'text-primary'}`}
          />
        </div>
      )}
      <div>
        <div
          className={`flex items-center gap-2 text-sm mb-0.5 ${
            light ? 'text-white/80' : 'text-muted-foreground'
          }`}
        >
          <Link
            to="/org/$slug"
            params={{ slug: landing.orgSlug || '' }}
            className={`hover:underline ${light ? 'text-white/80' : ''}`}
          >
            {landing.orgName}
          </Link>
          <span>/</span>
          <span>Space</span>
        </div>
        <h1
          className={`text-xl font-display ${
            light ? 'text-white' : 'text-foreground'
          }`}
        >
          <MapPin className="size-5 inline-block mr-1.5 -mt-0.5" />
          {landing.spaceName}
        </h1>
        {landing.address && (
          <p
            className={`text-sm mt-0.5 ${
              light ? 'text-white/70' : 'text-muted-foreground'
            }`}
          >
            {landing.address}
            {landing.addressNote && ` — ${landing.addressNote}`}
          </p>
        )}
      </div>
    </div>
  )
}

function BookingSection({
  spaceLanding,
  isMember,
  isAuthenticated,
  authLoading,
  slug,
}: {
  spaceLanding: SpaceLandingData
  isMember: boolean
  isAuthenticated: boolean
  authLoading: boolean
  slug: string
}) {
  // If authenticated member, show booking form
  if (isAuthenticated && isMember) {
    return (
      <MemberBookingForm
        spaceId={spaceLanding.spaceId}
        spaceLanding={spaceLanding}
        slug={slug}
      />
    )
  }

  // CTA for non-members / unauthenticated
  return (
    <Card className="text-center p-8">
      <div className="max-w-md mx-auto space-y-4">
        <Calendar className="size-12 mx-auto text-muted-foreground/50" />
        <h2 className="text-xl font-display">Book a Spot</h2>
        {authLoading ? (
          <Loader2 className="size-6 mx-auto animate-spin text-muted-foreground" />
        ) : !isAuthenticated ? (
          <>
            <p className="text-muted-foreground">
              Sign in to book a spot at this space.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <Button asChild>
                <Link to="/login">
                  <LogIn className="size-4 mr-2" />
                  Sign In to Book
                </Link>
              </Button>
              {spaceLanding.guestAccessEnabled && (
                <Button variant="outline" asChild>
                  <Link to="/org/$slug/visit" params={{ slug }}>
                    Request a Visit
                  </Link>
                </Button>
              )}
            </div>
          </>
        ) : (
          <>
            <p className="text-muted-foreground">
              Join {spaceLanding.orgName} to book a spot.
            </p>
            <div className="flex flex-col sm:flex-row items-center justify-center gap-3">
              <Button asChild>
                <Link
                  to="/org/$slug/join"
                  params={{ slug }}
                  search={{ token: '' }}
                >
                  Join to Book
                </Link>
              </Button>
              {spaceLanding.guestAccessEnabled && (
                <Button variant="outline" asChild>
                  <Link to="/org/$slug/visit" params={{ slug }}>
                    Request a Visit
                  </Link>
                </Button>
              )}
            </div>
          </>
        )}
      </div>
    </Card>
  )
}

function MemberBookingForm({
  spaceId,
  spaceLanding,
  slug,
}: {
  spaceId: Id<'coworkingSpaces'>
  spaceLanding: SpaceLandingData
  slug: string
}) {
  const [selectedDate, setSelectedDate] = useState<Date | undefined>(undefined)
  const [calendarMonth, setCalendarMonth] = useState(new Date())
  const [startMinutes, setStartMinutes] = useState(540)
  const [endMinutes, setEndMinutes] = useState(1020)
  const [workingOn, setWorkingOn] = useState('')
  const [consentChecked, setConsentChecked] = useState(false)
  const [isBooking, setIsBooking] = useState(false)

  const capacityStartDate = format(startOfMonth(calendarMonth), 'yyyy-MM-dd')
  const capacityEndDate = format(
    endOfMonth(addMonths(calendarMonth, 1)),
    'yyyy-MM-dd',
  )

  const capacityData = useQuery(api.spaceBookings.getCapacityForDateRange, {
    spaceId,
    startDate: capacityStartDate,
    endDate: capacityEndDate,
  })

  const selectedDateStr = selectedDate
    ? format(selectedDate, 'yyyy-MM-dd')
    : undefined
  const attendees = useQuery(
    api.spaceBookings.getBookingAttendees,
    selectedDateStr ? { spaceId, date: selectedDateStr } : 'skip',
  )

  const createBooking = useMutation(api.spaceBookings.createMemberBooking)

  const selectedDayOfWeek = selectedDate ? getDay(selectedDate) : undefined
  const selectedDayHours =
    selectedDayOfWeek !== undefined
      ? spaceLanding.operatingHours.find(
          (h) => h.dayOfWeek === selectedDayOfWeek,
        )
      : undefined

  const handleDateSelect = (date: Date | undefined) => {
    setSelectedDate(date)
    if (date) {
      const dayOfWeek = getDay(date)
      const dayHours = spaceLanding.operatingHours.find(
        (h) => h.dayOfWeek === dayOfWeek,
      )
      if (dayHours && !dayHours.isClosed) {
        setStartMinutes(dayHours.openMinutes)
        setEndMinutes(dayHours.closeMinutes)
      }
    }
  }

  const selectedDateCapacity = selectedDateStr
    ? capacityData?.dates[selectedDateStr]
    : undefined
  const currentCount = selectedDateCapacity?.count ?? 0
  const capacityStatus = selectedDateCapacity?.status ?? 'available'

  const handleBooking = async () => {
    if (!selectedDateStr || !consentChecked) return

    setIsBooking(true)
    try {
      const result = await createBooking({
        spaceId,
        date: selectedDateStr,
        startMinutes,
        endMinutes,
        workingOn: workingOn.trim() || undefined,
        consentToProfileSharing: true,
      })

      if (result.capacityWarning === 'at_capacity') {
        toast.success('Booking confirmed! Note: Space is now at capacity.')
      } else if (result.capacityWarning === 'nearing') {
        toast.success('Booking confirmed! Note: Space is filling up.')
      } else {
        toast.success('Booking confirmed!')
      }

      setSelectedDate(undefined)
      setWorkingOn('')
      setConsentChecked(false)
    } catch (error) {
      console.error('Failed to book:', error)
      toast.error(
        error instanceof Error ? error.message : 'Failed to book. Try again.',
      )
    } finally {
      setIsBooking(false)
    }
  }

  return (
    <section>
      <div className="flex items-center justify-between mb-4">
        <h2 className="text-lg font-semibold">Book a Spot</h2>
        <Button variant="outline" size="sm" asChild>
          <Link to="/org/$slug/space/bookings" params={{ slug }}>
            <CalendarDays className="size-4 mr-2" />
            My Bookings
          </Link>
        </Button>
      </div>

      <div className="grid gap-6 lg:grid-cols-2">
        {/* Calendar */}
        <Card>
          <CardHeader>
            <CardTitle className="flex items-center gap-2">
              <Calendar className="size-5" />
              Select a Date
            </CardTitle>
          </CardHeader>
          <CardContent>
            <BookingCalendar
              selectedDate={selectedDate}
              onSelectDate={handleDateSelect}
              capacityData={capacityData}
              operatingHours={spaceLanding.operatingHours}
              onMonthChange={setCalendarMonth}
            />
            <BookingCalendarLegend />
          </CardContent>
        </Card>

        {/* Booking form */}
        <div className="space-y-6">
          {selectedDate ? (
            <>
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Clock className="size-5" />
                    {format(selectedDate, 'EEEE, MMMM d, yyyy')}
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-4">
                  {/* Capacity indicator */}
                  <div className="flex items-center gap-2">
                    <Users className="size-4 text-muted-foreground" />
                    <span
                      className={
                        capacityStatus === 'at_capacity'
                          ? 'text-red-600 font-medium'
                          : capacityStatus === 'nearing'
                            ? 'text-yellow-600 font-medium'
                            : 'text-muted-foreground'
                      }
                    >
                      {currentCount} /{' '}
                      {capacityData?.capacity ?? spaceLanding.capacity} booked
                    </span>
                  </div>

                  {capacityStatus === 'at_capacity' && (
                    <div className="p-3 rounded-lg bg-red-50 border border-red-200 text-red-800 text-sm flex items-start gap-2">
                      <AlertCircle className="size-4 mt-0.5 flex-shrink-0" />
                      <div>
                        <p className="font-medium">Space is at capacity</p>
                        <p>You can still book, but the space may be crowded.</p>
                      </div>
                    </div>
                  )}
                  {capacityStatus === 'nearing' && (
                    <div className="p-3 rounded-lg bg-yellow-50 border border-yellow-200 text-yellow-800 text-sm flex items-start gap-2">
                      <AlertCircle className="size-4 mt-0.5 flex-shrink-0" />
                      <div>
                        <p className="font-medium">Space is filling up</p>
                        <p>Book soon to secure your spot!</p>
                      </div>
                    </div>
                  )}

                  <TimeRangePicker
                    startMinutes={startMinutes}
                    endMinutes={endMinutes}
                    onChange={(start, end) => {
                      setStartMinutes(start)
                      setEndMinutes(end)
                    }}
                    operatingHours={selectedDayHours}
                  />

                  <div className="space-y-2">
                    <Label htmlFor="workingOn">
                      How can you help others? (optional)
                    </Label>
                    <Textarea
                      id="workingOn"
                      value={workingOn}
                      onChange={(e) =>
                        setWorkingOn(e.target.value.slice(0, 140))
                      }
                      placeholder="e.g., ML expertise, grant writing, policy analysis..."
                      rows={2}
                    />
                    <p className="text-xs text-muted-foreground">
                      {workingOn.length}/140 characters
                    </p>
                  </div>

                  <div className="flex items-start gap-3 p-3 rounded-lg border bg-muted/50">
                    <Checkbox
                      id="consent"
                      checked={consentChecked}
                      onCheckedChange={(checked) =>
                        setConsentChecked(checked === true)
                      }
                    />
                    <Label
                      htmlFor="consent"
                      className="text-sm font-normal cursor-pointer leading-relaxed"
                    >
                      I agree that others booked on this day can see my full
                      profile
                    </Label>
                  </div>

                  <Button
                    onClick={handleBooking}
                    disabled={!consentChecked || isBooking}
                    className="w-full"
                  >
                    {isBooking ? (
                      <>
                        <Loader2 className="size-4 mr-2 animate-spin" />
                        Booking...
                      </>
                    ) : (
                      <>
                        <CheckCircle2 className="size-4 mr-2" />
                        Book This Date
                      </>
                    )}
                  </Button>
                </CardContent>
              </Card>

              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <Users className="size-5" />
                    Who&apos;s coming on {format(selectedDate, 'MMM d')}
                  </CardTitle>
                </CardHeader>
                <CardContent>
                  <AttendeeList attendees={attendees ?? []} title="" />
                </CardContent>
              </Card>
            </>
          ) : (
            <Card className="h-full flex items-center justify-center min-h-[300px]">
              <div className="text-center p-6">
                <Calendar className="size-12 mx-auto mb-4 text-muted-foreground/50" />
                <p className="text-muted-foreground">
                  Select a date to see availability and book
                </p>
              </div>
            </Card>
          )}
        </div>
      </div>
    </section>
  )
}

// src/routes/(app)/org/[slug]/space/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { format } from 'date-fns'
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import {
    AlertCircle,
    Building2,
    Calendar,
    CalendarDays,
    CheckCircle2,
    Clock,
    Coffee,
    LoaderCircle,
    LogIn,
    MapPin,
    Monitor,
    Printer,
    ScrollText,
    ShowerHead,
    Sparkles,
    Users,
    Wifi,
  } from 'lucide-svelte'
  import { api } from '$convex/_generated/api'
  import { getClerkContext } from '$lib/stores/clerk.svelte'
  import AuthHeader from '~/components/layout/auth-header.svelte'
  import GradientBg from '~/components/layout/GradientBg.svelte'

  const AMENITY_ICONS = {
    WiFi: Wifi,
    'External Monitors': Monitor,
    'Coffee/Tea': Coffee,
    Printer,
    Showers: ShowerHead,
  } as const

  const DAY_NAMES = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'] as const

  const clerkContext = getClerkContext()
  const convex = useConvexClient()
  const slug = $derived(page.params.slug ?? null)

  const spaceLanding = useQuery(api.coworkingSpaces.getSpaceLanding, () =>
    slug
      ? {
          slug,
        }
      : 'skip',
  )

  const membership = useQuery(
    api.orgs.membership.getMembership,
    () =>
      clerkContext.currentUser && spaceLanding.data
        ? {
            orgId: spaceLanding.data.orgId,
          }
        : 'skip',
  )

  const memberSpace = useQuery(
    api.coworkingSpaces.getSpaceByOrgPublic,
    () =>
      clerkContext.currentUser && spaceLanding.data
        ? {
            orgId: spaceLanding.data.orgId,
          }
        : 'skip',
  )

  let selectedDate = $state('')
  let startMinutes = $state(540)
  let endMinutes = $state(1020)
  let workingOn = $state('')
  let interestedInMeeting = $state('')
  let consentChecked = $state(false)
  let isBooking = $state(false)

  const selectedDateObj = $derived(
    selectedDate ? new Date(`${selectedDate}T12:00:00`) : null,
  )
  const selectedDayHours = $derived.by(() => {
    if (!selectedDateObj || !spaceLanding.data) {
      return null
    }
    return (
      spaceLanding.data.operatingHours.find(
        (hours) => hours.dayOfWeek === selectedDateObj.getDay(),
      ) ?? null
    )
  })

  const selectedMonthRange = $derived.by(() => {
    const base = selectedDateObj ?? new Date()
    const start = new Date(base.getFullYear(), base.getMonth(), 1)
    const end = new Date(base.getFullYear(), base.getMonth() + 1, 0)
    return {
      startDate: format(start, 'yyyy-MM-dd'),
      endDate: format(end, 'yyyy-MM-dd'),
    }
  })

  const capacityData = useQuery(
    api.spaceBookings.getCapacityForDateRange,
    () =>
      memberSpace.data
        ? {
            spaceId: memberSpace.data._id,
            startDate: selectedMonthRange.startDate,
            endDate: selectedMonthRange.endDate,
          }
        : 'skip',
  )

  const attendees = useQuery(
    api.spaceBookings.getBookingAttendees,
    () =>
      memberSpace.data && selectedDate
        ? {
            spaceId: memberSpace.data._id,
            date: selectedDate,
          }
        : 'skip',
  )

  $effect(() => {
    if (!selectedDayHours || selectedDayHours.isClosed) {
      return
    }

    startMinutes = selectedDayHours.openMinutes
    endMinutes = Math.min(selectedDayHours.closeMinutes, selectedDayHours.openMinutes + 480)
  })

  const formatMinutes = (minutes: number) => {
    const hours = Math.floor(minutes / 60)
    const mins = minutes % 60
    const period = hours >= 12 ? 'PM' : 'AM'
    const displayHours = hours === 0 ? 12 : hours > 12 ? hours - 12 : hours
    return `${displayHours}:${String(mins).padStart(2, '0')} ${period}`
  }

  const timeOptions = $derived.by(() => {
    if (!selectedDayHours || selectedDayHours.isClosed) {
      return []
    }

    const values: Array<number> = []
    for (
      let minutes = selectedDayHours.openMinutes;
      minutes <= selectedDayHours.closeMinutes;
      minutes += 30
    ) {
      values.push(minutes)
    }
    return values
  })

  const selectedCapacity = $derived(
    selectedDate ? capacityData.data?.dates[selectedDate] : undefined,
  )

  const handleBooking = async () => {
    if (!memberSpace.data || !selectedDate || !consentChecked) {
      return
    }

    isBooking = true

    try {
      const result = await convex.mutation(api.spaceBookings.createMemberBooking, {
        spaceId: memberSpace.data._id,
        date: selectedDate,
        startMinutes,
        endMinutes,
        workingOn: workingOn.trim() || undefined,
        interestedInMeeting: interestedInMeeting.trim() || undefined,
        consentToProfileSharing: true,
      })

      if (result.capacityWarning === 'at_capacity') {
        toast.success('Booking confirmed. The space is now at capacity.')
      } else if (result.capacityWarning === 'nearing') {
        toast.success('Booking confirmed. The space is filling up.')
      } else {
        toast.success('Booking confirmed')
      }

      selectedDate = ''
      workingOn = ''
      interestedInMeeting = ''
      consentChecked = false
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to book space')
    } finally {
      isBooking = false
    }
  }
</script>

<svelte:head>
  <title>{spaceLanding.data ? `${spaceLanding.data.spaceName} | ASTN` : 'Space | ASTN'}</title>
</svelte:head>

<GradientBg>
  <AuthHeader />

  <main class="container mx-auto px-4 py-8">
    {#if spaceLanding.isLoading}
      <div class="flex min-h-[60vh] items-center justify-center">
        <LoaderCircle class="size-8 animate-spin text-slate-400" />
      </div>
    {:else if !spaceLanding.data || !slug}
      <div class="mx-auto max-w-lg rounded-[2rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">
        <div class="mx-auto mb-4 grid size-16 place-items-center rounded-full bg-slate-100 text-slate-400">
          <Building2 class="size-8" />
        </div>
        <h1 class="font-display text-3xl text-slate-950">Space not found</h1>
        <p class="mt-3 text-sm leading-6 text-slate-600">
          This organization doesn’t have a co-working space configured.
        </p>
      </div>
    {:else}
      <div class="mx-auto max-w-5xl space-y-8">
        {#if spaceLanding.data.coverImageUrl}
          <div class="relative overflow-hidden rounded-[2rem]">
            <img
              src={spaceLanding.data.coverImageUrl}
              alt={spaceLanding.data.spaceName}
              class="h-72 w-full object-cover"
            />
            <div class="absolute inset-0 bg-gradient-to-t from-black/65 to-transparent"></div>
            <div class="absolute bottom-0 left-0 right-0 p-6 text-white">
              <p class="text-sm text-white/75">{spaceLanding.data.orgName}</p>
              <h1 class="mt-1 font-display text-3xl">{spaceLanding.data.spaceName}</h1>
              {#if spaceLanding.data.address}
                <p class="mt-2 text-sm text-white/80">
                  {spaceLanding.data.address}
                  {#if spaceLanding.data.addressNote}
                    {' '}• {spaceLanding.data.addressNote}
                  {/if}
                </p>
              {/if}
            </div>
          </div>
        {:else}
          <section class="rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
            <p class="text-sm text-slate-500">{spaceLanding.data.orgName}</p>
            <h1 class="mt-1 font-display text-3xl text-slate-950">{spaceLanding.data.spaceName}</h1>
            {#if spaceLanding.data.address}
              <p class="mt-3 text-sm text-slate-600">
                {spaceLanding.data.address}
                {#if spaceLanding.data.addressNote}
                  {' '}• {spaceLanding.data.addressNote}
                {/if}
              </p>
            {/if}
          </section>
        {/if}

        {#if spaceLanding.data.description}
          <section class="rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
            <p class="text-sm leading-6 text-slate-600">{spaceLanding.data.description}</p>
          </section>
        {/if}

        {#if spaceLanding.data.amenities?.length}
          <section class="rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
            <h2 class="text-lg font-semibold text-slate-950">Amenities</h2>
            <div class="mt-4 flex flex-wrap gap-2">
              {#each spaceLanding.data.amenities as amenity}
                {@const Icon = AMENITY_ICONS[amenity as keyof typeof AMENITY_ICONS] ?? Sparkles}
                <span class="inline-flex items-center gap-1.5 rounded-full bg-slate-100 px-3 py-1.5 text-sm text-slate-700">
                  <Icon class="size-4" />
                  {amenity}
                </span>
              {/each}
            </div>
          </section>
        {/if}

        <div class="grid gap-6 lg:grid-cols-[minmax(0,0.9fr)_minmax(0,1.1fr)]">
          <section class="rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
            <div class="mb-4 flex items-center gap-2">
              <Clock class="size-5 text-coral-600" />
              <h2 class="text-lg font-semibold text-slate-950">Operating hours</h2>
            </div>

            <div class="grid grid-cols-2 gap-2">
              {#each spaceLanding.data.operatingHours.slice().sort((a, b) => a.dayOfWeek - b.dayOfWeek) as hours}
                <div class="rounded-xl border border-border/70 bg-slate-50/80 px-3 py-2 text-sm">
                  <div class="font-medium text-slate-800">{DAY_NAMES[hours.dayOfWeek]}</div>
                  <div class="text-slate-500">
                    {#if hours.isClosed}
                      Closed
                    {:else}
                      {formatMinutes(hours.openMinutes)} - {formatMinutes(hours.closeMinutes)}
                    {/if}
                  </div>
                </div>
              {/each}
            </div>

            {#if spaceLanding.data.houseRules}
              <div class="mt-6">
                <div class="mb-2 flex items-center gap-2">
                  <ScrollText class="size-4 text-coral-600" />
                  <h3 class="text-sm font-semibold uppercase tracking-[0.18em] text-slate-500">House rules</h3>
                </div>
                <div class="space-y-2 text-sm leading-6 text-slate-600">
                  {#each spaceLanding.data.houseRules.split('\n').filter(Boolean) as rule}
                    <p>{rule}</p>
                  {/each}
                </div>
              </div>
            {/if}
          </section>

          <section class="rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
            <div class="mb-4 flex items-center justify-between gap-3">
              <div class="flex items-center gap-2">
                <Calendar class="size-5 text-coral-600" />
                <h2 class="text-lg font-semibold text-slate-950">Book a spot</h2>
              </div>
              {#if clerkContext.currentUser && membership.data}
                <a
                  href={`/org/${slug}/space/bookings`}
                  class="inline-flex items-center gap-2 rounded-xl border border-border bg-white px-3 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
                >
                  <CalendarDays class="size-4" />
                  My bookings
                </a>
              {/if}
            </div>

            {#if !clerkContext.isClerkLoaded}
              <div class="flex min-h-[16rem] items-center justify-center">
                <LoaderCircle class="size-6 animate-spin text-slate-400" />
              </div>
            {:else if !clerkContext.currentUser}
              <div class="space-y-4 text-center">
                <p class="text-sm leading-6 text-slate-600">Sign in to book a spot at this space.</p>
                <div class="flex flex-col gap-3 sm:flex-row sm:justify-center">
                  <a
                    href="/login"
                    class="inline-flex items-center justify-center gap-2 rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600"
                  >
                    <LogIn class="size-4" />
                    Sign in
                  </a>
                  {#if spaceLanding.data.guestAccessEnabled}
                    <a
                      href={`/org/${slug}/visit`}
                      class="inline-flex items-center justify-center rounded-xl border border-border bg-white px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
                    >
                      Request a visit
                    </a>
                  {/if}
                </div>
              </div>
            {:else if !membership.data}
              <div class="space-y-4 text-center">
                <p class="text-sm leading-6 text-slate-600">
                  Join {spaceLanding.data.orgName} to book a spot.
                </p>
                <div class="flex flex-col gap-3 sm:flex-row sm:justify-center">
                  <a
                    href={`/org/${slug}/join`}
                    class="inline-flex items-center justify-center rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600"
                  >
                    Join organization
                  </a>
                  {#if spaceLanding.data.guestAccessEnabled}
                    <a
                      href={`/org/${slug}/visit`}
                      class="inline-flex items-center justify-center rounded-xl border border-border bg-white px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
                    >
                      Request a visit
                    </a>
                  {/if}
                </div>
              </div>
            {:else if !memberSpace.data}
              <div class="text-sm text-slate-600">Unable to load member booking details.</div>
            {:else}
              <div class="space-y-4">
                <label class="block">
                  <span class="mb-1 block text-sm font-medium text-slate-800">Date</span>
                  <input
                    type="date"
                    bind:value={selectedDate}
                    class="h-10 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
                  />
                </label>

                {#if selectedDate && selectedDayHours?.isClosed}
                  <div class="flex items-start gap-2 rounded-[1.25rem] border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-800">
                    <AlertCircle class="mt-0.5 size-4 shrink-0" />
                    <span>This space is closed on the selected date.</span>
                  </div>
                {/if}

                {#if selectedCapacity}
                  <div class="flex items-center gap-2 rounded-[1.25rem] border border-border/70 bg-slate-50 px-4 py-3 text-sm text-slate-700">
                    <Users class="size-4 text-slate-500" />
                    <span>
                      {selectedCapacity.count} / {capacityData.data?.capacity ?? spaceLanding.data.capacity} booked
                    </span>
                    {#if selectedCapacity.status !== 'available'}
                      <span class={`ml-auto rounded-full px-2 py-0.5 text-xs font-medium ${
                        selectedCapacity.status === 'at_capacity'
                          ? 'bg-red-100 text-red-700'
                          : 'bg-amber-100 text-amber-700'
                      }`}>
                        {selectedCapacity.status === 'at_capacity' ? 'At capacity' : 'Filling up'}
                      </span>
                    {/if}
                  </div>
                {/if}

                <div class="grid gap-4 sm:grid-cols-2">
                  <label class="block">
                    <span class="mb-1 block text-sm font-medium text-slate-800">Start time</span>
                    <select
                      bind:value={startMinutes}
                      class="h-10 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
                    >
                      {#each timeOptions as option}
                        <option value={option}>{formatMinutes(option)}</option>
                      {/each}
                    </select>
                  </label>

                  <label class="block">
                    <span class="mb-1 block text-sm font-medium text-slate-800">End time</span>
                    <select
                      bind:value={endMinutes}
                      class="h-10 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
                    >
                      {#each timeOptions.filter((option) => option > startMinutes) as option}
                        <option value={option}>{formatMinutes(option)}</option>
                      {/each}
                    </select>
                  </label>
                </div>

                <label class="block">
                  <span class="mb-1 block text-sm font-medium text-slate-800">Can help with</span>
                  <textarea
                    bind:value={workingOn}
                    rows={2}
                    maxlength={140}
                    placeholder="e.g. ML expertise, grant writing, research feedback"
                    class="min-h-24 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
                  ></textarea>
                </label>

                <label class="block">
                  <span class="mb-1 block text-sm font-medium text-slate-800">Looking to meet</span>
                  <textarea
                    bind:value={interestedInMeeting}
                    rows={2}
                    maxlength={140}
                    placeholder="e.g. policy collaborators, startup operators, other researchers"
                    class="min-h-24 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
                  ></textarea>
                </label>

                <label class="flex items-start gap-3 rounded-[1.25rem] border border-border/70 bg-slate-50 px-4 py-3 text-sm text-slate-700">
                  <input
                    type="checkbox"
                    bind:checked={consentChecked}
                    class="mt-0.5 rounded border-slate-300"
                  />
                  <span>I agree that others booked that day can view my profile details.</span>
                </label>

                <button
                  type="button"
                  class="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600 disabled:pointer-events-none disabled:opacity-50"
                  disabled={!selectedDate || !consentChecked || isBooking || !!selectedDayHours?.isClosed}
                  onclick={() => {
                    void handleBooking()
                  }}
                >
                  {#if isBooking}
                    <LoaderCircle class="size-4 animate-spin" />
                    Booking...
                  {:else}
                    <CheckCircle2 class="size-4" />
                    Confirm booking
                  {/if}
                </button>

                {#if attendees.data?.length}
                  <div class="rounded-[1.25rem] border border-border/70 bg-slate-50 px-4 py-4">
                    <h3 class="mb-3 text-sm font-semibold uppercase tracking-[0.18em] text-slate-500">
                      Others booked that day
                    </h3>
                    <div class="space-y-3">
                      {#each attendees.data as attendee}
                        <div class="rounded-xl border border-border/70 bg-white px-4 py-3 text-sm">
                          <div class="font-medium text-slate-900">
                            {attendee.profile?.name ?? 'Anonymous member'}
                          </div>
                          {#if attendee.profile?.headline}
                            <div class="mt-1 text-slate-500">{attendee.profile.headline}</div>
                          {/if}
                          {#if attendee.workingOn}
                            <div class="mt-2 text-slate-700">
                              <strong>Can help with:</strong> {attendee.workingOn}
                            </div>
                          {/if}
                          {#if attendee.interestedInMeeting}
                            <div class="mt-1 text-slate-700">
                              <strong>Looking to meet:</strong> {attendee.interestedInMeeting}
                            </div>
                          {/if}
                        </div>
                      {/each}
                    </div>
                  </div>
                {/if}
              </div>
            {/if}
          </section>
        </div>
      </div>
    {/if}
  </main>
</GradientBg>
