// src/routes/(app)/org/[slug]/programs/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { useQuery } from 'convex-svelte'
  import { Building2, GraduationCap } from 'lucide-svelte'
  import { api } from '$convex/_generated/api'
  import { getClerkContext } from '$lib/stores/clerk.svelte'
  import { programStatusColors, programTypeLabels } from '$lib/program-constants'
  import AuthHeader from '~/components/layout/auth-header.svelte'
  import GradientBg from '~/components/layout/GradientBg.svelte'
  import { formatProgramDateRange } from '~/components/public-org/utils'

  const clerkContext = getClerkContext()
  const slug = $derived(page.params.slug ?? null)

  const org = useQuery(api.orgs.directory.getOrgBySlug, () =>
    slug
      ? {
          slug,
        }
      : 'skip',
  )

  const myPrograms = useQuery(api.programs.getMyPrograms, () =>
    clerkContext.currentUser && org.data
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )
</script>

<svelte:head>
  <title>{org.data ? `${org.data.name} Programs | ASTN` : 'Programs | ASTN'}</title>
</svelte:head>

<GradientBg>
  <AuthHeader />

  <main class="container mx-auto px-4 py-8">
    {#if org.isLoading || !clerkContext.isClerkLoaded}
      <div class="mx-auto max-w-4xl space-y-6">
        <div class="h-20 animate-pulse rounded-[2rem] bg-slate-100"></div>
        <div class="h-72 animate-pulse rounded-[2rem] bg-slate-100"></div>
      </div>
    {:else if !org.data}
      <div class="mx-auto max-w-lg rounded-[2rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">
        <div class="mx-auto mb-4 flex size-16 items-center justify-center rounded-full bg-slate-100 text-slate-400">
          <Building2 class="size-8" />
        </div>
        <h1 class="font-display text-3xl text-slate-950">Organization not found</h1>
      </div>
    {:else}
      <div class="mx-auto max-w-4xl space-y-6">
        <section class="rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
          <div class="flex items-center gap-4">
            {#if org.data.logoUrl}
              <img
                src={org.data.logoUrl}
                alt={org.data.name}
                class="size-12 rounded-2xl object-cover"
              />
            {:else}
              <div class="flex size-12 items-center justify-center rounded-2xl bg-coral-50 text-coral-600">
                <Building2 class="size-6" />
              </div>
            {/if}

            <div>
              <div class="flex items-center gap-2 text-sm text-slate-500">
                <a href={`/org/${page.params.slug}`} class="transition hover:text-slate-700">
                  {org.data.name}
                </a>
                <span>/</span>
                <span class="text-slate-700">Programs</span>
              </div>
              <h1 class="mt-1 font-display text-2xl text-slate-950">
                <GraduationCap class="mr-2 inline-block size-5 -translate-y-0.5" />
                My Programs
              </h1>
            </div>
          </div>
        </section>

        {#if !clerkContext.currentUser}
          <div class="rounded-[2rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">
            <div class="mx-auto mb-4 flex size-16 items-center justify-center rounded-full bg-coral-50 text-coral-600">
              <GraduationCap class="size-8" />
            </div>
            <h2 class="font-display text-3xl text-slate-950">Sign in to view programs</h2>
            <p class="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-600">
              Program pages are only available to signed-in participants and
              organization members.
            </p>
            <a
              href="/login"
              class="mt-6 inline-flex rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600"
            >
              Sign in
            </a>
          </div>
        {:else if myPrograms.isLoading}
          <div class="space-y-3">
            {#each Array.from({ length: 2 }) as _, index (`loading-${index}`)}
              <div class="h-24 animate-pulse rounded-[1.5rem] bg-slate-100"></div>
            {/each}
          </div>
        {:else if !myPrograms.data?.length}
          <div class="rounded-[2rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">
            <div class="mx-auto mb-4 flex size-16 items-center justify-center rounded-full bg-slate-100 text-slate-400">
              <GraduationCap class="size-8" />
            </div>
            <h2 class="text-xl font-semibold text-slate-950">No programs yet</h2>
            <p class="mt-3 text-sm leading-6 text-slate-600">
              You’re not enrolled in any programs for this organization.
            </p>
          </div>
        {:else}
          <div class="grid gap-4 sm:grid-cols-2">
            {#each myPrograms.data as program (program._id)}
              <a
                href={`/org/${page.params.slug}/program/${program.slug}`}
                class="group rounded-[1.5rem] border border-border/70 bg-white/92 p-5 shadow-warm-sm transition hover:-translate-y-0.5 hover:shadow-warm-md"
              >
                <div class="flex items-start justify-between gap-3">
                  <h2 class="text-base font-semibold text-slate-950 transition group-hover:text-coral-700">
                    {program.name}
                  </h2>
                  <span class={`shrink-0 rounded-full px-2.5 py-1 text-xs font-medium ${programStatusColors[program.status]}`}>
                    {program.status}
                  </span>
                </div>

                <p class="mt-2 text-sm text-slate-500">
                  {programTypeLabels[program.type]}
                </p>

                {#if formatProgramDateRange(program.startDate, program.endDate)}
                  <p class="mt-2 text-sm text-slate-500">
                    {formatProgramDateRange(program.startDate, program.endDate)}
                  </p>
                {/if}

                {#if program.description}
                  <p class="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">
                    {program.description}
                  </p>
                {/if}

                {#if program.participationStatus === 'completed'}
                  <div class="mt-4 inline-flex rounded-full border border-blue-200 bg-blue-50 px-2.5 py-1 text-xs font-medium text-blue-700">
                    Completed
                  </div>
                {/if}
              </a>
            {/each}
          </div>
        {/if}
      </div>
    {/if}
  </main>
</GradientBg>

// src/routes/org/$slug/programs.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { useQuery } from 'convex/react'
import { Building2, GraduationCap } from 'lucide-react'
import { api } from '../../../../convex/_generated/api'
import { AuthHeader } from '~/components/layout/auth-header'
import { GradientBg } from '~/components/layout/GradientBg'
import { programStatusColors, programTypeLabels } from '~/lib/program-constants'
import { Badge } from '~/components/ui/badge'
import { Button } from '~/components/ui/button'
import { Card } from '~/components/ui/card'

export const Route = createFileRoute('/org/$slug/programs')({
  component: MyProgramsPage,
})

function MyProgramsPage() {
  const { slug } = Route.useParams()
  const org = useQuery(api.orgs.directory.getOrgBySlug, { slug })
  const myPrograms = useQuery(
    api.programs.getMyPrograms,
    org ? { orgId: org._id } : 'skip',
  )

  if (org === undefined) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-4xl mx-auto">
            <div className="animate-pulse space-y-6">
              <div className="h-16 bg-slate-100 rounded-xl" />
              <div className="h-64 bg-slate-100 rounded-xl" />
            </div>
          </div>
        </main>
      </GradientBg>
    )
  }

  if (org === null) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Building2 className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-display text-foreground mb-4">
              Organization Not Found
            </h1>
            <Button asChild>
              <Link to="/">Go Home</Link>
            </Button>
          </div>
        </main>
      </GradientBg>
    )
  }

  return (
    <GradientBg>
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-4xl mx-auto">
          {/* Header */}
          <Card className="p-6 mb-6">
            <div className="flex items-center gap-4">
              {org.logoUrl ? (
                <img
                  src={org.logoUrl}
                  alt={org.name}
                  className="size-12 rounded-lg object-cover"
                />
              ) : (
                <div className="size-12 rounded-lg bg-primary/10 flex items-center justify-center">
                  <Building2 className="size-6 text-primary" />
                </div>
              )}
              <div className="flex-1">
                <div className="flex items-center gap-2 text-slate-500 text-sm mb-1">
                  <Link
                    to="/org/$slug"
                    params={{ slug }}
                    className="hover:text-slate-700 transition-colors"
                  >
                    {org.name}
                  </Link>
                  <span>/</span>
                  <span className="text-slate-700">My Programs</span>
                </div>
                <h1 className="text-xl font-display text-foreground">
                  <GraduationCap className="size-5 inline-block mr-2 -mt-0.5" />
                  My Programs
                </h1>
              </div>
            </div>
          </Card>

          {/* Programs list */}
          {myPrograms === undefined ? (
            <div className="space-y-3">
              {[1, 2].map((i) => (
                <div
                  key={i}
                  className="h-24 bg-slate-100 rounded-xl animate-pulse"
                />
              ))}
            </div>
          ) : myPrograms.length === 0 ? (
            <Card className="p-12 text-center">
              <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
                <GraduationCap className="size-8 text-slate-400" />
              </div>
              <h2 className="text-lg font-semibold text-foreground mb-2">
                No Programs Yet
              </h2>
              <p className="text-slate-600">
                You&apos;re not enrolled in any programs yet.
              </p>
            </Card>
          ) : (
            <div className="grid gap-4 sm:grid-cols-2">
              {myPrograms.map((prog) => (
                <Link
                  key={prog._id}
                  to="/org/$slug/program/$programSlug"
                  params={{ slug, programSlug: prog.slug }}
                  className="block group"
                >
                  <Card className="p-5 hover:shadow-md transition-shadow h-full">
                    <div className="flex items-start justify-between gap-2 mb-2">
                      <h3 className="font-semibold text-foreground group-hover:text-primary transition-colors">
                        {prog.name}
                      </h3>
                      <Badge className={programStatusColors[prog.status]}>
                        {prog.status}
                      </Badge>
                    </div>
                    <p className="text-sm text-slate-500 mb-3">
                      {programTypeLabels[prog.type]}
                    </p>
                    {prog.description && (
                      <p className="text-sm text-slate-600 line-clamp-2">
                        {prog.description}
                      </p>
                    )}
                    {prog.participationStatus === 'completed' && (
                      <Badge className="mt-3 bg-blue-50 text-blue-700 border-blue-200">
                        Completed
                      </Badge>
                    )}
                  </Card>
                </Link>
              ))}
            </div>
          )}
        </div>
      </main>
    </GradientBg>
  )
}
