// src/routes/org/$slug/admin/applications/index.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { useAction, useMutation, useQuery } from 'convex/react'
import { useState } from 'react'
import {
  Building2,
  ChevronDown,
  ChevronUp,
  Download,
  FileText,
  Loader2,
  Shield,
} from 'lucide-react'
import { api } from '../../../../../../convex/_generated/api'
import type { Id } from '../../../../../../convex/_generated/dataModel'
import type { FormField } from '../../../../../../convex/lib/formFields'
import { AuthHeader } from '~/components/layout/auth-header'
import { DynamicResponseViewer } from '~/components/opportunities/DynamicResponseViewer'
import { Card } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Badge } from '~/components/ui/badge'
import { Spinner } from '~/components/ui/spinner'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '~/components/ui/select'
import { useDotGridStyle } from '~/hooks/use-dot-grid-style'

export const Route = createFileRoute('/org/$slug/admin/applications/')({
  component: AdminApplicationsPage,
})

type ApplicationStatus =
  | 'submitted'
  | 'under_review'
  | 'accepted'
  | 'rejected'
  | 'waitlisted'

const STATUS_LABELS: Record<ApplicationStatus, string> = {
  submitted: 'Submitted',
  under_review: 'Under Review',
  accepted: 'Accepted',
  rejected: 'Rejected',
  waitlisted: 'Waitlisted',
}

const STATUS_COLORS: Record<ApplicationStatus, string> = {
  submitted: 'bg-blue-50 text-blue-700 border-blue-200',
  under_review: 'bg-yellow-50 text-yellow-700 border-yellow-200',
  accepted: 'bg-green-50 text-green-700 border-green-200',
  rejected: 'bg-red-50 text-red-700 border-red-200',
  waitlisted: 'bg-purple-50 text-purple-700 border-purple-200',
}

function AdminApplicationsPage() {
  const { slug } = Route.useParams()
  const dotGridStyle = useDotGridStyle()

  const org = useQuery(api.orgs.directory.getOrgBySlug, { slug })
  const membership = useQuery(
    api.orgs.membership.getMembership,
    org ? { orgId: org._id } : 'skip',
  )
  const allOpportunities = useQuery(
    api.orgOpportunities.listAllByOrg,
    org && membership?.role === 'admin' ? { orgId: org._id } : 'skip',
  )

  const [selectedOpportunityId, setSelectedOpportunityId] = useState<string>('')

  // Loading
  if (org === undefined || membership === undefined) {
    return (
      <div className="min-h-screen" style={dotGridStyle}>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-5xl mx-auto">
            <Spinner className="size-8 mx-auto" />
          </div>
        </main>
      </div>
    )
  }

  if (!org) {
    return (
      <div className="min-h-screen" style={dotGridStyle}>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <Building2 className="size-8 text-slate-400 mx-auto mb-4" />
            <h1 className="text-2xl font-display mb-4">
              Organization Not Found
            </h1>
          </div>
        </main>
      </div>
    )
  }

  if (!membership || membership.role !== 'admin') {
    return (
      <div className="min-h-screen" style={dotGridStyle}>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <Shield className="size-8 text-slate-400 mx-auto mb-4" />
            <h1 className="text-2xl font-display mb-4">
              Admin Access Required
            </h1>
            <Button asChild>
              <Link to="/org/$slug" params={{ slug }}>
                Back to Organization
              </Link>
            </Button>
          </div>
        </main>
      </div>
    )
  }

  // Determine which opportunity to show
  const opportunities = allOpportunities ?? []
  const featured = opportunities.find((o) => o.featured)
  const currentId =
    selectedOpportunityId || featured?._id || opportunities[0]?._id || ''
  const currentOpportunity = opportunities.find((o) => o._id === currentId)

  return (
    <div className="min-h-screen" style={dotGridStyle}>
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-5xl mx-auto">
          {/* Breadcrumb */}
          <div className="flex items-center gap-2 text-muted-foreground text-sm mb-2">
            <Link
              to="/org/$slug/admin"
              params={{ slug }}
              className="hover:text-slate-700 transition-colors"
            >
              Admin
            </Link>
            <span>/</span>
            <span className="text-slate-700">Applications</span>
          </div>

          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-2xl font-display font-semibold text-foreground">
                Applications
              </h1>
              <p className="text-muted-foreground mt-1">
                Review and manage opportunity applications
              </p>
            </div>
          </div>

          {/* Opportunity Picker */}
          {opportunities.length > 1 && (
            <div className="mb-4">
              <Select
                value={currentId}
                onValueChange={setSelectedOpportunityId}
              >
                <SelectTrigger className="w-full max-w-md">
                  <SelectValue placeholder="Select opportunity..." />
                </SelectTrigger>
                <SelectContent>
                  {opportunities.map((opp) => (
                    <SelectItem key={opp._id} value={opp._id}>
                      {opp.title}
                      {opp.featured ? ' (Featured)' : ''}
                      {opp.status !== 'active' ? ` [${opp.status}]` : ''}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </div>
          )}

          {currentOpportunity ? (
            <ApplicationsTable
              opportunityId={currentOpportunity._id}
              opportunityTitle={currentOpportunity.title}
              formFields={
                (currentOpportunity.formFields ?? []) as Array<FormField>
              }
            />
          ) : (
            <Card className="p-8 text-center">
              <FileText className="size-8 text-slate-400 mx-auto mb-4" />
              <p className="text-muted-foreground">
                No opportunities created yet. Create an opportunity to start
                receiving applications.
              </p>
            </Card>
          )}
        </div>
      </main>
    </div>
  )
}

function ApplicationsTable({
  opportunityId,
  opportunityTitle,
  formFields,
}: {
  opportunityId: Id<'orgOpportunities'>
  opportunityTitle: string
  formFields: Array<FormField>
}) {
  const [statusFilter, setStatusFilter] = useState<string>('all')
  const [expandedId, setExpandedId] = useState<string | null>(null)
  const [isExporting, setIsExporting] = useState(false)

  const applications = useQuery(api.opportunityApplications.listByOpportunity, {
    opportunityId,
    statusFilter:
      statusFilter !== 'all' ? (statusFilter as ApplicationStatus) : undefined,
  })
  const updateStatus = useMutation(api.opportunityApplications.updateStatus)
  const exportCsv = useAction(api.opportunityApplications.exportApplications)

  const handleExport = async () => {
    setIsExporting(true)
    try {
      const csv = await exportCsv({ opportunityId })
      const blob = new Blob([csv], { type: 'text/csv' })
      const url = URL.createObjectURL(blob)
      const a = document.createElement('a')
      a.href = url
      a.download = `applications-${opportunityTitle.toLowerCase().replace(/\s+/g, '-')}.csv`
      a.click()
      URL.revokeObjectURL(url)
    } catch (err) {
      console.error('Export failed:', err)
    } finally {
      setIsExporting(false)
    }
  }

  const handleStatusChange = async (
    applicationId: Id<'opportunityApplications'>,
    newStatus: ApplicationStatus,
  ) => {
    await updateStatus({ applicationId, status: newStatus })
  }

  // Derive summary columns from first 3 input fields
  const inputFields = formFields.filter((f) => f.kind !== 'section_header')
  const summaryFields = inputFields.slice(0, 3)

  return (
    <div>
      {/* Filters & Export */}
      <div className="flex items-center justify-between mb-4 gap-4">
        <div className="flex items-center gap-2">
          <span className="text-sm text-muted-foreground">Filter:</span>
          <Select value={statusFilter} onValueChange={setStatusFilter}>
            <SelectTrigger className="w-[160px]">
              <SelectValue />
            </SelectTrigger>
            <SelectContent>
              <SelectItem value="all">All statuses</SelectItem>
              <SelectItem value="submitted">Submitted</SelectItem>
              <SelectItem value="under_review">Under Review</SelectItem>
              <SelectItem value="accepted">Accepted</SelectItem>
              <SelectItem value="rejected">Rejected</SelectItem>
              <SelectItem value="waitlisted">Waitlisted</SelectItem>
            </SelectContent>
          </Select>
        </div>

        <Button variant="outline" onClick={handleExport} disabled={isExporting}>
          {isExporting ? (
            <Loader2 className="size-4 mr-2 animate-spin" />
          ) : (
            <Download className="size-4 mr-2" />
          )}
          Export CSV
        </Button>
      </div>

      {/* Table */}
      {applications === undefined ? (
        <div className="py-12 text-center">
          <Spinner className="size-8 mx-auto" />
        </div>
      ) : applications.length === 0 ? (
        <Card className="p-8 text-center">
          <FileText className="size-8 text-slate-400 mx-auto mb-4" />
          <p className="text-muted-foreground">
            {statusFilter !== 'all'
              ? `No ${STATUS_LABELS[statusFilter as ApplicationStatus].toLowerCase()} applications.`
              : 'No applications received yet.'}
          </p>
        </Card>
      ) : (
        <div className="space-y-2">
          {/* Header — dynamic columns */}
          <div
            className="grid gap-2 px-4 py-2 text-xs font-medium text-muted-foreground uppercase tracking-wider"
            style={{
              gridTemplateColumns: `${summaryFields.map(() => '1fr').join(' ')} 120px 100px 32px`,
            }}
          >
            {summaryFields.map((f) => (
              <span key={f.key} className="truncate">
                {f.label}
              </span>
            ))}
            <span>Submitted</span>
            <span>Status</span>
            <span />
          </div>

          {applications.map((app) => {
            const r = app.responses as Record<string, unknown>
            const isExpanded = expandedId === app._id
            return (
              <Card key={app._id}>
                <button
                  type="button"
                  className="w-full text-left"
                  onClick={() => setExpandedId(isExpanded ? null : app._id)}
                >
                  <div
                    className="grid gap-2 items-center px-4 py-3 text-sm"
                    style={{
                      gridTemplateColumns: `${summaryFields.map(() => '1fr').join(' ')} 120px 100px 32px`,
                    }}
                  >
                    {summaryFields.map((f) => (
                      <span
                        key={f.key}
                        className="truncate text-muted-foreground"
                      >
                        {formatCellValue(r[f.key])}
                      </span>
                    ))}
                    <span className="text-muted-foreground text-xs">
                      {new Date(app.submittedAt).toLocaleDateString()}
                    </span>
                    <span>
                      <Badge
                        variant="outline"
                        className={
                          STATUS_COLORS[app.status as ApplicationStatus]
                        }
                      >
                        {STATUS_LABELS[app.status as ApplicationStatus]}
                      </Badge>
                    </span>
                    {isExpanded ? (
                      <ChevronUp className="size-4 text-muted-foreground" />
                    ) : (
                      <ChevronDown className="size-4 text-muted-foreground" />
                    )}
                  </div>
                </button>

                {isExpanded && (
                  <div className="border-t px-4 py-4">
                    <ApplicationDetail
                      responses={r}
                      formFields={formFields}
                      status={app.status as ApplicationStatus}
                      applicationId={app._id}
                      onStatusChange={handleStatusChange}
                    />
                  </div>
                )}
              </Card>
            )
          })}
        </div>
      )}
    </div>
  )
}

function formatCellValue(val: unknown): string {
  if (val === undefined || val === null) return ''
  if (Array.isArray(val)) return val.join(', ')
  if (typeof val === 'boolean') return val ? 'Yes' : 'No'
  return String(val)
}

function ApplicationDetail({
  responses,
  formFields,
  status,
  applicationId,
  onStatusChange,
}: {
  responses: Record<string, unknown>
  formFields: Array<FormField>
  status: ApplicationStatus
  applicationId: Id<'opportunityApplications'>
  onStatusChange: (
    id: Id<'opportunityApplications'>,
    s: ApplicationStatus,
  ) => void
}) {
  return (
    <div className="space-y-6">
      {formFields.length > 0 ? (
        <DynamicResponseViewer formFields={formFields} responses={responses} />
      ) : (
        <FallbackResponseViewer responses={responses} />
      )}

      {/* Status update */}
      <div className="flex items-center gap-3 pt-4 border-t">
        <span className="text-sm font-medium">Update status:</span>
        <Select
          value={status}
          onValueChange={(val) =>
            onStatusChange(applicationId, val as ApplicationStatus)
          }
        >
          <SelectTrigger className="w-[160px]">
            <SelectValue />
          </SelectTrigger>
          <SelectContent>
            <SelectItem value="submitted">Submitted</SelectItem>
            <SelectItem value="under_review">Under Review</SelectItem>
            <SelectItem value="accepted">Accepted</SelectItem>
            <SelectItem value="rejected">Rejected</SelectItem>
            <SelectItem value="waitlisted">Waitlisted</SelectItem>
          </SelectContent>
        </Select>
      </div>
    </div>
  )
}

/** Fallback for opportunities without formFields — shows raw key/value pairs */
function FallbackResponseViewer({
  responses,
}: {
  responses: Record<string, unknown>
}) {
  return (
    <div className="space-y-2">
      {Object.entries(responses)
        .filter(([, v]) => v !== undefined && v !== null && v !== '')
        .map(([key, val]) => (
          <div key={key}>
            <span className="text-xs text-muted-foreground">{key}</span>
            <p className="text-sm whitespace-pre-wrap">
              {formatCellValue(val)}
            </p>
          </div>
        ))}
    </div>
  )
}

// src/routes/(app)/org/[slug]/admin/applications/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import { api } from '$convex/_generated/api'
  import AdminSection from '~/components/org-admin/core/AdminSection.svelte'

  const convex = useConvexClient()
  const slug = $derived(page.params.slug ?? null)

  let selectedOpportunityId = $state<string | null>(null)
  let statusFilter = $state<'all' | 'submitted' | 'under_review' | 'accepted' | 'rejected' | 'waitlisted'>('all')

  const org = useQuery(api.orgs.directory.getOrgBySlug, () => (slug ? { slug } : 'skip'))
  const membership = useQuery(api.orgs.membership.getMembership, () =>
    org.data ? { orgId: org.data._id } : 'skip',
  )
  const opportunities = useQuery(api.orgOpportunities.listAllByOrg, () =>
    org.data && membership.data?.role === 'admin' ? { orgId: org.data._id } : 'skip',
  )

  $effect(() => {
    if (!selectedOpportunityId && opportunities.data?.length) {
      selectedOpportunityId = opportunities.data[0]._id
    }
  })

  const applications = useQuery(api.opportunityApplications.listByOpportunity, () =>
    selectedOpportunityId
      ? {
          opportunityId: selectedOpportunityId as any,
          statusFilter: statusFilter === 'all' ? undefined : statusFilter,
        }
      : 'skip',
  )

  const updateStatus = async (applicationId: string, nextStatus: typeof statusFilter) => {
    if (nextStatus === 'all') return
    try {
      await convex.mutation(api.opportunityApplications.updateStatus, {
        applicationId: applicationId as any,
        status: nextStatus,
      })
      toast.success('Application updated')
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to update application')
    }
  }
</script>

<div class="space-y-6">
  <section class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-6 shadow-warm-sm">
    <p class="text-xs font-semibold uppercase tracking-[0.22em] text-coral-600">Applications</p>
    <h1 class="mt-2 font-display text-3xl text-slate-950">Opportunity applications</h1>
    <p class="mt-3 text-sm leading-6 text-slate-600">Review applicant responses and update decisions for each opportunity.</p>
  </section>

  <AdminSection title="Queue controls">
    <div class="grid gap-4 md:grid-cols-2">
      <label class="space-y-2">
        <span class="text-sm font-medium text-slate-700">Opportunity</span>
        <select bind:value={selectedOpportunityId} class="w-full rounded-2xl border border-border px-4 py-3 text-sm">
          {#each opportunities.data ?? [] as opportunity}
            <option value={opportunity._id}>{opportunity.title}</option>
          {/each}
        </select>
      </label>
      <label class="space-y-2">
        <span class="text-sm font-medium text-slate-700">Status</span>
        <select bind:value={statusFilter} class="w-full rounded-2xl border border-border px-4 py-3 text-sm">
          <option value="all">All</option>
          <option value="submitted">Submitted</option>
          <option value="under_review">Under review</option>
          <option value="accepted">Accepted</option>
          <option value="rejected">Rejected</option>
          <option value="waitlisted">Waitlisted</option>
        </select>
      </label>
    </div>
  </AdminSection>

  <div class="space-y-3">
    {#each applications.data ?? [] as application (application._id)}
      <article class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-4 shadow-warm-sm">
        <div class="flex flex-wrap items-start justify-between gap-4">
          <div>
            <h2 class="text-lg font-semibold text-slate-950">{application.guestEmail || application.userId || 'Applicant'}</h2>
            <p class="mt-1 text-sm text-slate-600">Submitted {new Date(application.submittedAt).toLocaleString()}</p>
            <pre class="mt-3 overflow-x-auto rounded-2xl bg-slate-50 p-3 text-xs text-slate-700">{JSON.stringify(application.responses, null, 2)}</pre>
          </div>
          <div class="space-y-2">
            <span class="block rounded-full border border-border px-3 py-1 text-center text-xs font-medium text-slate-600">{application.status}</span>
            <select
              class="w-full rounded-full border border-border px-3 py-2 text-sm"
              value={application.status}
              onchange={(event) => updateStatus(application._id, event.currentTarget.value as any)}
            >
              <option value="submitted">Submitted</option>
              <option value="under_review">Under review</option>
              <option value="accepted">Accepted</option>
              <option value="rejected">Rejected</option>
              <option value="waitlisted">Waitlisted</option>
            </select>
          </div>
        </div>
      </article>
    {/each}
  </div>
</div>
