// src/components/course/AISidebarToggle.svelte
<script lang="ts">
  import { Bot } from 'lucide-svelte'
  import { getCourseSidebarContext } from '$lib/stores/course-sidebar.svelte'

  const sidebar = getCourseSidebarContext()
</script>

{#if !sidebar.isOpen}
  <button
    type="button"
    class="inline-flex size-9 items-center justify-center rounded-full border border-border/70 bg-white text-slate-700 shadow-sm transition hover:bg-accent"
    onclick={() => sidebar.toggle()}
    title="AI Learning Partner (Cmd+Shift+.)"
  >
    <Bot class="size-4" />
  </button>
{/if}

// src/components/course/AISidebarToggle.tsx
import { Bot } from 'lucide-react'
import { useCourseSidebar } from './AISidebarProvider'
import { Button } from '~/components/ui/button'

export function AISidebarToggle() {
  const { toggle, isOpen } = useCourseSidebar()

  if (isOpen) return null

  return (
    <Button
      onClick={toggle}
      size="icon"
      variant="outline"
      className="size-9"
      title="AI Learning Partner (Cmd+Shift+.)"
    >
      <Bot className="size-4" />
    </Button>
  )
}
