// src/components/course/PromptResponseViewer.svelte
<script lang="ts">
  import { useQuery } from 'convex-svelte'
  import type { Id } from '$convex/_generated/dataModel'
  import { api } from '$convex/_generated/api'
  import { renderMarkdownToHtml } from '$lib/render-markdown'

  let { promptId }: { promptId: Id<'coursePrompts'> } = $props()

  const prompt = useQuery(api.course.prompts.get, () => ({ promptId }))
  const responses = useQuery(api.course.responses.getPromptResponses, () => ({ promptId }))

  const submittedResponses = $derived(
    (responses.data ?? []).filter((response) => response.status === 'submitted'),
  )
</script>

<section class="rounded-[1.5rem] border border-border/70 bg-white p-4">
  <div class="flex items-center justify-between gap-3">
    <div>
      <h4 class="font-medium text-slate-950">{prompt.data?.title || 'Prompt'}</h4>
      <p class="mt-1 text-xs text-slate-500">
        {submittedResponses.length} submitted response{submittedResponses.length === 1 ? '' : 's'}
      </p>
    </div>
  </div>

  {#if prompt.data?.body}
    <div class="prose prose-sm mt-3 max-w-none prose-p:my-2">
      {@html renderMarkdownToHtml(prompt.data.body)}
    </div>
  {/if}

  {#if submittedResponses.length}
    <div class="mt-4 space-y-3">
      {#each submittedResponses as response (response._id)}
        <div class="rounded-2xl bg-slate-50 p-3 text-sm text-slate-700">
          {#each response.fieldResponses as fieldResponse (fieldResponse.fieldId)}
            <div class="mb-2 last:mb-0">
              {#if fieldResponse.textValue}
                <p class="whitespace-pre-wrap">{fieldResponse.textValue}</p>
              {:else if fieldResponse.selectedOptionIds?.length}
                <p>{fieldResponse.selectedOptionIds.join(', ')}</p>
              {/if}
            </div>
          {/each}
        </div>
      {/each}
    </div>
  {/if}
</section>

// src/components/course/PromptResponseViewer.tsx
import { useMutation, useQuery } from 'convex/react'
import { Star } from 'lucide-react'
import { toast } from 'sonner'
import { api } from '../../../convex/_generated/api'
import { PromptRevealControl } from './PromptRevealControl'
import { SpotlightBadge } from './SpotlightBadge'
import type { Id } from '../../../convex/_generated/dataModel'
import { Button } from '~/components/ui/button'
import { Card, CardContent } from '~/components/ui/card'

interface PromptResponseViewerProps {
  promptId: Id<'coursePrompts'>
}

export function PromptResponseViewer({ promptId }: PromptResponseViewerProps) {
  const prompt = useQuery(api.course.prompts.get, { promptId })
  const responses = useQuery(api.course.responses.getPromptResponses, {
    promptId,
  })
  const toggleSpotlight = useMutation(api.course.responses.toggleSpotlight)

  if (!prompt || responses === undefined) {
    return <p className="text-muted-foreground text-sm">Loading...</p>
  }

  const handleToggleSpotlight = async (
    responseId: Id<'coursePromptResponses'>,
  ) => {
    try {
      await toggleSpotlight({ responseId })
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Failed to toggle spotlight')
    }
  }

  return (
    <div className="space-y-4">
      <div className="flex items-center justify-between">
        <h3 className="font-semibold">{prompt.title}</h3>
        <span className="text-muted-foreground text-sm">
          {responses.length} responses
        </span>
      </div>

      <PromptRevealControl
        promptId={promptId}
        revealMode={prompt.revealMode}
        revealedAt={prompt.revealedAt}
      />

      {responses.length === 0 && (
        <p className="text-muted-foreground text-sm">No responses yet</p>
      )}

      {responses.map((response) => (
        <Card key={response._id}>
          <CardContent className="space-y-2 pt-4">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-2">
                <span className="text-muted-foreground text-xs font-mono">
                  {response.userId.slice(0, 12)}...
                </span>
                <span
                  className={`rounded-full px-2 py-0.5 text-xs font-medium ${
                    response.status === 'submitted'
                      ? 'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300'
                      : 'bg-muted text-muted-foreground'
                  }`}
                >
                  {response.status === 'submitted' ? 'Submitted' : 'Draft'}
                </span>
                {response.spotlighted && <SpotlightBadge />}
              </div>
              <div className="flex items-center gap-2">
                {response.submittedAt && (
                  <span className="text-muted-foreground text-xs">
                    {new Date(response.submittedAt).toLocaleString()}
                  </span>
                )}
                <Button
                  variant="ghost"
                  size="sm"
                  className="h-7 w-7 p-0"
                  onClick={() =>
                    handleToggleSpotlight(
                      response._id as Id<'coursePromptResponses'>,
                    )
                  }
                >
                  <Star
                    className={`h-4 w-4 ${
                      response.spotlighted
                        ? 'fill-amber-400 text-amber-400'
                        : 'text-muted-foreground'
                    }`}
                  />
                </Button>
              </div>
            </div>

            {prompt.fields.map((field) => {
              const fr = response.fieldResponses.find(
                (r) => r.fieldId === field.id,
              )
              if (!fr) return null
              return (
                <div key={field.id} className="space-y-0.5">
                  <p className="text-muted-foreground text-xs">{field.label}</p>
                  {field.type === 'text' && (
                    <p className="text-sm">{fr.textValue || '—'}</p>
                  )}
                  {field.type === 'choice' && (
                    <p className="text-sm">
                      {field.options?.find(
                        (o) => o.id === fr.selectedOptionIds?.[0],
                      )?.label || '—'}
                    </p>
                  )}
                  {field.type === 'multiple_choice' && (
                    <div className="flex flex-wrap gap-1">
                      {fr.selectedOptionIds?.map((optId) => (
                        <span
                          key={optId}
                          className="bg-muted rounded px-1.5 py-0.5 text-xs"
                        >
                          {field.options?.find((o) => o.id === optId)?.label ??
                            optId}
                        </span>
                      ))}
                      {(!fr.selectedOptionIds ||
                        fr.selectedOptionIds.length === 0) && (
                        <span className="text-sm">—</span>
                      )}
                    </div>
                  )}
                </div>
              )
            })}
          </CardContent>
        </Card>
      ))}
    </div>
  )
}
