// src/components/facilitator-agent/FacilitatorSidebarAwareWrapper.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { useMediaQuery } from '$lib/stores/media-query.svelte'
  import { getFacilitatorAgentContext } from '$lib/stores/facilitator-agent.svelte'

  let { children }: { children?: Snippet } = $props()

  const agent = getFacilitatorAgentContext()
  const hasRoomForSidebar = useMediaQuery('(min-width: 900px)')
  const shouldPush = $derived(agent.isOpen && $hasRoomForSidebar)
</script>

<div
  class={agent.isResizing ? '' : 'transition-[margin-right] duration-300 ease-in-out'}
  style:margin-right={shouldPush ? `${agent.sidebarWidth}px` : '0px'}
>
  {@render children?.()}
</div>

// src/components/facilitator-agent/FacilitatorSidebarAwareWrapper.tsx
import { useFacilitatorAgentSidebar } from './FacilitatorAgentProvider'
import { useMediaQuery } from '~/hooks/use-media-query'
import { cn } from '~/lib/utils'

export function FacilitatorSidebarAwareWrapper({
  children,
}: {
  children: React.ReactNode
}) {
  const { isOpen, sidebarWidth, isResizing } = useFacilitatorAgentSidebar()
  // Only push content when there's enough room
  // Below 900px, the sidebar overlays content instead
  const hasRoomForSidebar = useMediaQuery('(min-width: 900px)')
  const shouldPush = isOpen && hasRoomForSidebar

  return (
    <div
      className={cn(
        !isResizing && 'transition-[margin-right] duration-300 ease-in-out',
      )}
      style={{ marginRight: shouldPush ? sidebarWidth : 0 }}
    >
      {children}
    </div>
  )
}
