// src/components/facilitator-agent/FacilitatorAgentChat.tsx
import { memo, useEffect, useRef, useState } from 'react'
import { Check, Copy, Send, Terminal, Trash2 } from 'lucide-react'
import { marked } from 'marked'
import DOMPurify from 'dompurify'

import type {
  AdminAgentMessage,
  AgentModel,
  ContentPart,
  ThinkingLevel,
} from '../../../shared/admin-agent/types'
import type { UseFacilitatorAgentReturn } from '~/hooks/use-facilitator-agent'
import { Button } from '~/components/ui/button'
import { Spinner } from '~/components/ui/spinner'
import { cn } from '~/lib/utils'

function renderMarkdown(content: string): string {
  const raw = marked.parse(content, { breaks: true, gfm: true })
  if (typeof raw !== 'string') return content
  return DOMPurify.sanitize(raw)
}

function CopyButton({ text }: { text: string }) {
  const [copied, setCopied] = useState(false)

  const handleCopy = () => {
    navigator.clipboard.writeText(text)
    setCopied(true)
    setTimeout(() => setCopied(false), 2000)
  }

  return (
    <Button
      variant="outline"
      size="sm"
      className="h-8 gap-1.5"
      onClick={handleCopy}
    >
      {copied ? <Check className="size-3.5" /> : <Copy className="size-3.5" />}
      {copied ? 'Copied' : 'Copy'}
    </Button>
  )
}

function ToolCallCard({ part }: { part: ContentPart & { type: 'tool_call' } }) {
  return (
    <details className="my-2 rounded-lg border bg-muted/50 text-sm">
      <summary className="cursor-pointer px-3 py-2 font-medium text-muted-foreground hover:text-foreground">
        <span className="ml-1 font-mono text-xs">{part.name}</span>
        {part.output === undefined && (
          <Spinner size="sm" className="inline-block ml-2 align-text-bottom" />
        )}
      </summary>
      <div className="border-t px-3 py-2 space-y-2">
        {part.input != null && Object.keys(part.input as object).length > 0 && (
          <div>
            <div className="text-xs font-medium text-muted-foreground mb-1">
              Input
            </div>
            <pre className="text-xs whitespace-pre-wrap break-all bg-background rounded p-2 overflow-auto max-h-40">
              {typeof part.input === 'string'
                ? part.input
                : JSON.stringify(part.input, null, 2)}
            </pre>
          </div>
        )}
        {part.output != null && (
          <div>
            <div className="text-xs font-medium text-muted-foreground mb-1">
              Output
            </div>
            <pre className="text-xs whitespace-pre-wrap break-all bg-background rounded p-2 overflow-auto max-h-40">
              {part.output}
            </pre>
          </div>
        )}
        {part.output === undefined && (
          <div className="flex items-center gap-2 text-xs text-muted-foreground">
            Running...
          </div>
        )}
      </div>
    </details>
  )
}

const TextPart = memo(function TextPart({ content }: { content: string }) {
  return (
    <div
      className="prose prose-sm dark:prose-invert max-w-none text-sm [&>*:first-child]:mt-0 [&>*:last-child]:mb-0"
      dangerouslySetInnerHTML={{ __html: renderMarkdown(content) }}
    />
  )
})

function AssistantParts({
  parts,
  isStreaming,
}: {
  parts: Array<ContentPart>
  isStreaming?: boolean
}) {
  return (
    <div className="flex justify-start mb-3">
      <div className="max-w-[85%]">
        {parts.map((part, i) => {
          if (part.type === 'text') {
            return (
              <span key={i}>
                <TextPart content={part.content} />
                {/* Blinking cursor on the last text part while streaming */}
                {isStreaming && i === parts.length - 1 && (
                  <span className="inline-block w-2 h-4 bg-foreground/70 animate-pulse ml-0.5 align-text-bottom" />
                )}
              </span>
            )
          }
          if (part.type === 'tool_call') {
            return <ToolCallCard key={i} part={part} />
          }
          return null
        })}
      </div>
    </div>
  )
}

function MessageBubble({ message }: { message: AdminAgentMessage }) {
  if (message.role === 'user') {
    return (
      <div className="flex justify-end mb-3">
        <div className="max-w-[85%] rounded-2xl rounded-br-sm bg-primary text-primary-foreground px-4 py-2.5 text-sm">
          {message.content}
        </div>
      </div>
    )
  }

  return <AssistantParts parts={message.parts} />
}

function DisconnectedView({
  orgSlug,
  programId,
}: {
  orgSlug: string
  programId: string
}) {
  const command = `bun agent/cli.ts --org=${orgSlug} --program=${programId}`

  return (
    <div className="flex flex-col items-center justify-center h-full px-6">
      <div className="max-w-sm w-full space-y-6 text-center">
        <div className="mx-auto size-12 rounded-full bg-muted flex items-center justify-center">
          <Terminal className="size-6 text-muted-foreground" />
        </div>
        <div>
          <h3 className="text-lg font-semibold text-foreground mb-1">
            Agent Disconnected
          </h3>
          <p className="text-sm text-muted-foreground">
            Start the facilitator agent from your terminal to connect.
          </p>
        </div>
        <div className="bg-muted rounded-lg p-4 space-y-3">
          <code className="block text-sm font-mono text-foreground break-all">
            {command}
          </code>
          <CopyButton text={command} />
        </div>
      </div>
    </div>
  )
}

function ConnectingView() {
  return (
    <div className="flex flex-col items-center justify-center h-full gap-3">
      <Spinner />
      <p className="text-sm text-muted-foreground">Connecting...</p>
    </div>
  )
}

export function FacilitatorAgentChat({
  agent,
  orgSlug,
  programId,
}: {
  agent: UseFacilitatorAgentReturn
  orgSlug: string
  programId: string
}) {
  const { status, messages, streamParts, sendMessage, clearChat, isStreaming } =
    agent

  const [input, setInput] = useState('')
  const [model, setModel] = useState<AgentModel>('claude-sonnet-4-6')
  const [thinking, setThinking] = useState<ThinkingLevel>('off')
  const messagesEndRef = useRef<HTMLDivElement>(null)
  const textareaRef = useRef<HTMLTextAreaElement>(null)

  // Auto-scroll to bottom on new messages
  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' })
  }, [messages, streamParts])

  // Auto-resize textarea
  useEffect(() => {
    const textarea = textareaRef.current
    if (!textarea) return
    textarea.style.height = 'auto'
    textarea.style.height = `${Math.min(textarea.scrollHeight, 150)}px`
  }, [input])

  const handleSend = () => {
    const trimmed = input.trim()
    if (!trimmed || isStreaming) return
    sendMessage(trimmed, model, thinking)
    setInput('')
    if (textareaRef.current) {
      textareaRef.current.style.height = 'auto'
    }
  }

  const handleKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>) => {
    if (e.key === 'Enter' && !e.shiftKey) {
      e.preventDefault()
      handleSend()
    }
  }

  if (status === 'disconnected') {
    return <DisconnectedView orgSlug={orgSlug} programId={programId} />
  }

  if (status === 'connecting') {
    return <ConnectingView />
  }

  return (
    <div className="flex flex-col h-full">
      {/* Header with model/thinking controls */}
      <div className="flex items-center gap-2 px-3 py-2 border-b shrink-0">
        <div className="size-2 rounded-full bg-green-500 shrink-0" />
        <select
          value={model}
          onChange={(e) => setModel(e.target.value as AgentModel)}
          className="text-xs bg-muted rounded px-1.5 py-1 border-none outline-none cursor-pointer"
        >
          <option value="claude-opus-4-6">Opus</option>
          <option value="claude-sonnet-4-6">Sonnet</option>
          <option value="claude-haiku-4-5-20251001">Haiku</option>
        </select>
        <select
          value={thinking}
          onChange={(e) => setThinking(e.target.value as ThinkingLevel)}
          className="text-xs bg-muted rounded px-1.5 py-1 border-none outline-none cursor-pointer"
        >
          <option value="off">No thinking</option>
          <option value="adaptive">Adaptive</option>
          <option value="high">High</option>
          <option value="max">Max</option>
        </select>
        {messages.length > 0 && (
          <Button
            variant="ghost"
            size="icon"
            className="ml-auto size-7 text-muted-foreground hover:text-destructive"
            onClick={clearChat}
            disabled={isStreaming}
            title="Clear chat"
          >
            <Trash2 className="size-3.5" />
          </Button>
        )}
      </div>

      {/* Messages */}
      <div className="flex-1 overflow-y-auto px-4 py-4 min-h-0">
        {messages.length === 0 && !isStreaming && (
          <div className="flex flex-col items-center justify-center h-full text-center">
            <p className="text-sm text-muted-foreground">
              Ask the facilitator agent about participant progress, responses,
              or session prep.
            </p>
          </div>
        )}

        {messages.map((msg, i) => (
          <MessageBubble key={i} message={msg} />
        ))}

        {isStreaming && streamParts.length > 0 && (
          <AssistantParts parts={streamParts} isStreaming />
        )}

        <div ref={messagesEndRef} />
      </div>

      {/* Input area */}
      <div className="border-t px-4 py-3 shrink-0">
        <div className="flex items-end gap-2">
          <textarea
            ref={textareaRef}
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyDown={handleKeyDown}
            placeholder="Ask the facilitator agent..."
            disabled={isStreaming}
            rows={1}
            className={cn(
              'flex-1 resize-none rounded-lg border bg-background px-3 py-2 text-sm',
              'placeholder:text-muted-foreground',
              'focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-1',
              'disabled:opacity-50 disabled:cursor-not-allowed',
              'max-h-[150px]',
            )}
          />
          <Button
            size="icon"
            onClick={handleSend}
            disabled={isStreaming || !input.trim()}
            className="shrink-0 size-9"
          >
            {isStreaming ? <Spinner size="sm" /> : <Send className="size-4" />}
          </Button>
        </div>
      </div>
    </div>
  )
}

// src/components/facilitator-agent/FacilitatorAgentChat.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { Copy, Send, Terminal, Trash2 } from 'lucide-svelte'
  import { getFacilitatorAgentContext } from '$lib/stores/facilitator-agent.svelte'
  import { renderMarkdownToHtml } from '$lib/render-markdown'
  import Spinner from '~/components/ui/spinner.svelte'

  const agent = getFacilitatorAgentContext()

  let input = $state('')
  let messagesContainer = $state<HTMLDivElement | undefined>(undefined)
  let textarea = $state<HTMLTextAreaElement | undefined>(undefined)

  const copyText = async (text: string) => {
    await navigator.clipboard.writeText(text)
  }

  const send = () => {
    const text = input.trim()
    if (!text || agent.isStreaming) {
      return
    }

    agent.sendMessage(text, agent.model, agent.thinking)
    input = ''
  }

  $effect(() => {
    messagesContainer?.scrollTo({
      top: messagesContainer.scrollHeight,
      behavior: 'smooth',
    })
  })

  $effect(() => {
    if (!textarea) {
      return
    }

    textarea.style.height = 'auto'
    textarea.style.height = `${Math.min(textarea.scrollHeight, 150)}px`
  })

  onMount(() => {
    textarea?.focus()
  })

  const command = $derived(`bun agent/cli.ts --org=${agent.orgSlug} --program=${agent.programId}`)
</script>

{#if agent.status === 'disconnected'}
  <div class="flex h-full flex-col items-center justify-center px-6 text-center">
    <div class="mx-auto flex size-12 items-center justify-center rounded-full bg-slate-100 text-slate-500">
      <Terminal class="size-6" />
    </div>
    <h3 class="mt-5 text-lg font-semibold text-slate-950">Agent disconnected</h3>
    <p class="mt-2 max-w-sm text-sm text-slate-600">
      Start the facilitator agent from your terminal to connect this sidebar.
    </p>
    <div class="mt-5 w-full max-w-sm rounded-2xl bg-slate-100 p-4">
      <code class="block break-all text-sm text-slate-900">{command}</code>
      <button
        type="button"
        class="mt-3 inline-flex items-center gap-2 rounded-full border border-border bg-white px-3 py-1.5 text-sm text-slate-700 transition hover:bg-accent"
        onclick={() => void copyText(command)}
      >
        <Copy class="size-3.5" />
        Copy
      </button>
    </div>
  </div>
{:else if agent.status === 'connecting'}
  <div class="flex h-full flex-col items-center justify-center gap-3">
    <Spinner />
    <p class="text-sm text-slate-500">Connecting…</p>
  </div>
{:else}
  <div class="flex h-full min-h-0 flex-col">
    <div class="flex items-center gap-2 border-b border-border/70 px-3 py-2">
      <div class="size-2 rounded-full bg-emerald-500"></div>
      <select
        bind:value={agent.model}
        class="rounded-md bg-slate-100 px-2 py-1 text-xs text-slate-700 outline-none"
      >
        <option value="claude-opus-4-6">Opus</option>
        <option value="claude-sonnet-4-6">Sonnet</option>
        <option value="claude-haiku-4-5-20251001">Haiku</option>
      </select>
      <select
        bind:value={agent.thinking}
        class="rounded-md bg-slate-100 px-2 py-1 text-xs text-slate-700 outline-none"
      >
        <option value="off">No thinking</option>
        <option value="adaptive">Adaptive</option>
        <option value="high">High</option>
        <option value="max">Max</option>
      </select>
      {#if agent.messages.length}
        <button
          type="button"
          class="ml-auto inline-flex size-7 items-center justify-center rounded-full text-slate-500 transition hover:bg-slate-100 hover:text-rose-600"
          onclick={() => agent.clearChat()}
          disabled={agent.isStreaming}
          title="Clear chat"
        >
          <Trash2 class="size-3.5" />
        </button>
      {/if}
    </div>

    <div bind:this={messagesContainer} class="min-h-0 flex-1 overflow-y-auto px-4 py-4">
      {#if !agent.messages.length && !agent.isStreaming}
        <div class="flex h-full items-center justify-center text-center">
          <p class="max-w-sm text-sm leading-6 text-slate-500">
            Ask about participant progress, facilitation plans, attendance, or program health.
          </p>
        </div>
      {/if}

      <div class="space-y-3">
        {#each agent.messages as message, index (`${message.role}-${index}`)}
          {#if message.role === 'user'}
            <div class="flex justify-end">
              <div class="max-w-[85%] rounded-2xl rounded-br-sm bg-slate-950 px-4 py-2.5 text-sm text-white">
                {message.content}
              </div>
            </div>
          {:else}
            <div class="flex justify-start">
              <div class="max-w-[85%]">
                {#each message.parts as part, partIndex (`${index}-${partIndex}`)}
                  {#if part.type === 'text'}
                    <div class="prose prose-sm mb-2 max-w-none rounded-2xl rounded-bl-sm border border-border/60 bg-slate-50 px-4 py-3 text-slate-800 prose-p:text-inherit prose-li:text-inherit prose-strong:text-inherit">
                      {@html renderMarkdownToHtml(part.content)}
                    </div>
                  {:else if part.type === 'tool_call'}
                    <details class="mb-2 rounded-2xl border border-border/60 bg-slate-50 text-sm">
                      <summary class="cursor-pointer px-3 py-2 font-medium text-slate-600">
                        {part.name}
                      </summary>
                      <div class="space-y-2 border-t border-border/60 px-3 py-2">
                        {#if part.input != null && Object.keys(part.input as object).length > 0}
                          <pre class="overflow-auto rounded-xl bg-white p-2 text-xs text-slate-700">{typeof part.input === 'string' ? part.input : JSON.stringify(part.input, null, 2)}</pre>
                        {/if}
                        {#if part.output != null}
                          <pre class="overflow-auto rounded-xl bg-white p-2 text-xs text-slate-700">{part.output}</pre>
                        {:else}
                          <div class="inline-flex items-center gap-2 text-xs text-slate-500">
                            <Spinner size="sm" />
                            Running…
                          </div>
                        {/if}
                      </div>
                    </details>
                  {/if}
                {/each}
              </div>
            </div>
          {/if}
        {/each}

        {#if agent.isStreaming && agent.streamParts.length}
          <div class="flex justify-start">
            <div class="max-w-[85%]">
              {#each agent.streamParts as part, index (`stream-${index}`)}
                {#if part.type === 'text'}
                  <div class="prose prose-sm mb-2 max-w-none rounded-2xl rounded-bl-sm border border-border/60 bg-slate-50 px-4 py-3 text-slate-800 prose-p:text-inherit prose-li:text-inherit prose-strong:text-inherit">
                    {@html renderMarkdownToHtml(part.content)}
                    {#if index === agent.streamParts.length - 1}
                      <span class="ml-1 inline-block h-4 w-2 animate-pulse bg-slate-400 align-text-bottom"></span>
                    {/if}
                  </div>
                {/if}
              {/each}
            </div>
          </div>
        {/if}
      </div>
    </div>

    <div class="border-t border-border/70 px-4 py-3">
      <div class="flex items-end gap-2">
        <textarea
          bind:this={textarea}
          bind:value={input}
          rows="1"
          class="max-h-[150px] min-h-[44px] flex-1 resize-none rounded-2xl border border-border/70 bg-white px-4 py-3 text-sm text-slate-900 outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-100"
          placeholder="Ask the facilitator agent..."
          disabled={agent.isStreaming}
          onkeydown={(event) => {
            if (event.key === 'Enter' && !event.shiftKey) {
              event.preventDefault()
              send()
            }
          }}
        ></textarea>
        <button
          type="button"
          class="inline-flex size-10 items-center justify-center rounded-full bg-coral-500 text-white transition hover:bg-coral-600 disabled:opacity-60"
          onclick={send}
          disabled={agent.isStreaming || !input.trim()}
        >
          {#if agent.isStreaming}
            <Spinner class="border-white/30 border-t-white" size="sm" />
          {:else}
            <Send class="size-4" />
          {/if}
        </button>
      </div>
    </div>
  </div>
{/if}
