// src/routes/org/$slug/admin/programs/index.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { useQuery } from 'convex/react'
import { Building2, FolderPlus, Plus, Shield } from 'lucide-react'
import { useState } from 'react'
import { api } from '../../../../../../convex/_generated/api'
import { AuthHeader } from '~/components/layout/auth-header'
import { ProgramCard } from '~/components/programs/ProgramCard'
import { CreateProgramDialog } from '~/components/programs/CreateProgramDialog'
import { Button } from '~/components/ui/button'
import { Card, CardContent } from '~/components/ui/card'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '~/components/ui/select'
import { Spinner } from '~/components/ui/spinner'

export const Route = createFileRoute('/org/$slug/admin/programs/')({
  component: ProgramsListPage,
})

function ProgramsListPage() {
  const { slug } = Route.useParams()
  const [statusFilter, setStatusFilter] = useState<string>('all')

  const org = useQuery(api.orgs.directory.getOrgBySlug, { slug })
  const membership = useQuery(
    api.orgs.membership.getMembership,
    org ? { orgId: org._id } : 'skip',
  )
  const programs = useQuery(
    api.programs.getOrgPrograms,
    org && membership?.role === 'admin'
      ? {
          orgId: org._id,
          status:
            statusFilter !== 'all'
              ? (statusFilter as
                  | 'planning'
                  | 'active'
                  | 'completed'
                  | 'archived')
              : undefined,
        }
      : 'skip',
  )

  // Loading
  if (org === undefined || membership === undefined) {
    return (
      <div className="min-h-screen bg-slate-50">
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-5xl mx-auto">
            <div className="animate-pulse space-y-6">
              <div className="h-12 bg-slate-100 rounded-xl w-1/3" />
              <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="h-40 bg-slate-100 rounded-xl" />
                ))}
              </div>
            </div>
          </div>
        </main>
      </div>
    )
  }

  if (org === null) {
    return (
      <div className="min-h-screen bg-slate-50">
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <Building2 className="size-16 text-slate-300 mx-auto mb-4" />
            <h1 className="text-2xl font-display text-foreground mb-4">
              Organization Not Found
            </h1>
            <Button asChild>
              <Link to="/">Go Home</Link>
            </Button>
          </div>
        </main>
      </div>
    )
  }

  if (!membership || membership.role !== 'admin') {
    return (
      <div className="min-h-screen bg-slate-50">
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <Shield className="size-16 text-slate-300 mx-auto mb-4" />
            <h1 className="text-2xl font-display text-foreground mb-4">
              Admin Access Required
            </h1>
            <Button asChild>
              <Link to="/org/$slug" params={{ slug }}>
                Back to Organization
              </Link>
            </Button>
          </div>
        </main>
      </div>
    )
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-5xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <div className="flex items-center gap-2 text-slate-500 text-sm mb-2">
              <Link
                to="/org/$slug"
                params={{ slug }}
                className="hover:text-slate-700 transition-colors"
              >
                {org.name}
              </Link>
              <span>/</span>
              <Link
                to="/org/$slug/admin"
                params={{ slug }}
                className="hover:text-slate-700 transition-colors"
              >
                Admin
              </Link>
              <span>/</span>
              <span className="text-slate-700">Programs</span>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-2xl font-display text-foreground">
                  Programs
                </h1>
                <p className="text-slate-600 mt-1">
                  Manage reading groups, fellowships, and other activities
                </p>
              </div>
              <CreateProgramDialog
                orgId={org._id}
                trigger={
                  <Button>
                    <Plus className="size-4 mr-2" />
                    New Program
                  </Button>
                }
              />
            </div>
          </div>

          {/* Filters */}
          <div className="flex items-center gap-4 mb-6">
            <Select value={statusFilter} onValueChange={setStatusFilter}>
              <SelectTrigger className="w-[180px]">
                <SelectValue placeholder="Filter by status" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="all">All Programs</SelectItem>
                <SelectItem value="planning">Planning</SelectItem>
                <SelectItem value="active">Active</SelectItem>
                <SelectItem value="completed">Completed</SelectItem>
                <SelectItem value="archived">Archived</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Programs Grid */}
          {programs === undefined ? (
            <div className="flex justify-center py-12">
              <Spinner className="size-8" />
            </div>
          ) : programs.length === 0 ? (
            <Card>
              <CardContent className="py-12 text-center">
                <FolderPlus className="size-12 text-slate-300 mx-auto mb-4" />
                <h3 className="text-lg font-medium text-foreground mb-2">
                  {statusFilter === 'all'
                    ? 'No programs yet'
                    : `No ${statusFilter} programs`}
                </h3>
                <p className="text-slate-500 text-sm mb-4">
                  Create a program to track member participation in activities
                </p>
                {statusFilter === 'all' && (
                  <CreateProgramDialog
                    orgId={org._id}
                    trigger={
                      <Button>
                        <Plus className="size-4 mr-2" />
                        Create First Program
                      </Button>
                    }
                  />
                )}
              </CardContent>
            </Card>
          ) : (
            <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
              {programs.map((program) => (
                <ProgramCard key={program._id} program={program} slug={slug} />
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  )
}

// src/routes/(app)/org/[slug]/admin/programs/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import { api } from '$convex/_generated/api'

  const convex = useConvexClient()
  const slug = $derived(page.params.slug ?? null)

  const org = useQuery(api.orgs.directory.getOrgBySlug, () => (slug ? { slug } : 'skip'))
  const membership = useQuery(api.orgs.membership.getMembership, () =>
    org.data ? { orgId: org.data._id } : 'skip',
  )
  const programs = useQuery(api.programs.getOrgPrograms, () =>
    org.data && membership.data?.role === 'admin' ? { orgId: org.data._id } : 'skip',
  )

  let name = $state('')
  let description = $state('')
  let type = $state<'reading_group' | 'fellowship' | 'mentorship' | 'cohort' | 'workshop_series' | 'custom'>('reading_group')
  let enrollmentMethod = $state<'admin_only' | 'self_enroll' | 'approval_required'>('admin_only')
  let startDate = $state('')
  let endDate = $state('')

  const createProgram = async () => {
    if (!org.data) return
    try {
      await convex.mutation(api.programs.createProgram, {
        orgId: org.data._id,
        name: name.trim(),
        description: description.trim() || undefined,
        type,
        enrollmentMethod,
        startDate: startDate ? new Date(`${startDate}T00:00:00`).getTime() : undefined,
        endDate: endDate ? new Date(`${endDate}T00:00:00`).getTime() : undefined,
      })
      toast.success('Program created')
      name = ''
      description = ''
      startDate = ''
      endDate = ''
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to create program')
    }
  }
</script>

<div class="space-y-6">
  <section class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-6 shadow-warm-sm">
    <h1 class="font-display text-3xl text-slate-950">Programs</h1>
    <p class="mt-3 text-sm leading-6 text-slate-600">Create cohorts, reading groups, and other structured programs.</p>
  </section>

  <section class="rounded-[1.75rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
    <h2 class="text-lg font-semibold text-slate-950">Create program</h2>
    <div class="mt-4 grid gap-4 md:grid-cols-2">
      <input bind:value={name} class="rounded-2xl border border-border px-4 py-3 text-sm" placeholder="Program name" />
      <select bind:value={type} class="rounded-2xl border border-border px-4 py-3 text-sm">
        <option value="reading_group">Reading group</option>
        <option value="fellowship">Fellowship</option>
        <option value="mentorship">Mentorship</option>
        <option value="cohort">Cohort</option>
        <option value="workshop_series">Workshop series</option>
        <option value="custom">Custom</option>
      </select>
      <select bind:value={enrollmentMethod} class="rounded-2xl border border-border px-4 py-3 text-sm">
        <option value="admin_only">Admin only</option>
        <option value="self_enroll">Self enroll</option>
        <option value="approval_required">Approval required</option>
      </select>
      <input bind:value={startDate} type="date" class="rounded-2xl border border-border px-4 py-3 text-sm" />
      <input bind:value={endDate} type="date" class="rounded-2xl border border-border px-4 py-3 text-sm md:col-span-2" />
    </div>
    <textarea bind:value={description} rows="5" class="mt-4 w-full rounded-2xl border border-border px-4 py-3 text-sm" placeholder="Program description"></textarea>
    <button type="button" class="mt-4 rounded-full bg-slate-950 px-4 py-2 text-sm font-medium text-white" onclick={createProgram}>Create program</button>
  </section>

  <div class="space-y-3">
    {#each programs.data ?? [] as program (program._id)}
      <a href={`/org/${slug}/admin/programs/${program._id}`} class="block rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-4 shadow-warm-sm">
        <div class="flex items-center justify-between gap-4">
          <div>
            <h2 class="text-lg font-semibold text-slate-950">{program.name}</h2>
            <p class="mt-1 text-sm text-slate-600">{program.status} · {program.type}</p>
          </div>
          <span class="text-sm text-slate-500">Open</span>
        </div>
      </a>
    {/each}
  </div>
</div>
