// src/components/profile/upload/FilePreview.svelte
<script lang="ts">
  import { FileText, RefreshCw, X } from 'lucide-svelte'
  import { cn } from '~/lib/utils'

  function formatBytes(bytes: number): string {
    if (bytes < 1024) return `${bytes} B`
    if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`
    return `${(bytes / (1024 * 1024)).toFixed(1)} MB`
  }

  let {
    file,
    onRemove,
    onReplace,
    disabled = false,
  }: {
    file: File
    onRemove: () => void
    onReplace?: () => void
    disabled?: boolean
  } = $props()
</script>

<div
  class={cn(
    'animate-in fade-in-0 slide-in-from-bottom-2 flex items-center gap-3 rounded-lg bg-muted/50 p-4 duration-200',
    disabled && 'opacity-50',
  )}
>
  <div class="flex shrink-0 items-center justify-center rounded-md bg-primary/10 p-2">
    <FileText class="size-5 text-primary" />
  </div>

  <div class="min-w-0 flex-1">
    <p class="truncate text-sm font-medium" title={file.name}>{file.name}</p>
    <p class="text-xs text-muted-foreground">{formatBytes(file.size)}</p>
  </div>

  <div class="flex shrink-0 items-center gap-1">
    {#if onReplace}
      <button
        type="button"
        class="inline-flex size-8 items-center justify-center rounded-md transition-colors hover:bg-accent disabled:pointer-events-none disabled:opacity-50"
        disabled={disabled}
        title="Replace file"
        onclick={onReplace}
      >
        <RefreshCw class="size-4" />
        <span class="sr-only">Replace file</span>
      </button>
    {/if}

    <button
      type="button"
      class="inline-flex size-8 items-center justify-center rounded-md transition-colors hover:bg-destructive/10 hover:text-destructive disabled:pointer-events-none disabled:opacity-50"
      disabled={disabled}
      title="Remove file"
      onclick={onRemove}
    >
      <X class="size-4" />
      <span class="sr-only">Remove file</span>
    </button>
  </div>
</div>

// src/components/profile/upload/FilePreview.tsx
import { FileText, RefreshCw, X } from "lucide-react";
import { cn } from "~/lib/utils";
import { Button } from "~/components/ui/button";

/**
 * Format bytes into human-readable string
 */
function formatBytes(bytes: number): string {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

interface FilePreviewProps {
  file: File;
  onRemove: () => void;
  onReplace?: () => void;
  disabled?: boolean;
}

/**
 * Shows selected file information with remove/replace actions.
 *
 * Displays:
 * - File icon
 * - Filename (truncated if long)
 * - File size in human-readable format
 * - Remove button
 * - Optional replace button
 */
export function FilePreview({
  file,
  onRemove,
  onReplace,
  disabled = false,
}: FilePreviewProps) {
  return (
    <div
      className={cn(
        "flex items-center gap-3 rounded-lg bg-muted/50 p-4 animate-in fade-in-0 slide-in-from-bottom-2 duration-200",
        disabled && "opacity-50"
      )}
    >
      {/* File icon */}
      <div className="flex shrink-0 items-center justify-center rounded-md bg-primary/10 p-2">
        <FileText className="size-5 text-primary" />
      </div>

      {/* File info */}
      <div className="min-w-0 flex-1">
        <p className="truncate text-sm font-medium" title={file.name}>
          {file.name}
        </p>
        <p className="text-xs text-muted-foreground">
          {formatBytes(file.size)}
        </p>
      </div>

      {/* Actions */}
      <div className="flex shrink-0 items-center gap-1">
        {onReplace && (
          <Button
            type="button"
            variant="ghost"
            size="icon"
            className="size-8"
            onClick={onReplace}
            disabled={disabled}
            title="Replace file"
          >
            <RefreshCw className="size-4" />
            <span className="sr-only">Replace file</span>
          </Button>
        )}
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className="size-8 hover:bg-destructive/10 hover:text-destructive"
          onClick={onRemove}
          disabled={disabled}
          title="Remove file"
        >
          <X className="size-4" />
          <span className="sr-only">Remove file</span>
        </Button>
      </div>
    </div>
  );
}
