// src/routes/(app)/profile/attendance/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { format } from 'date-fns'
  import { useQuery } from 'convex-svelte'
  import {
    ArrowLeft,
    CalendarCheck,
    MapPin,
    MessageSquare,
    Monitor,
    Star,
  } from 'lucide-svelte'
  import { api } from '$convex/_generated/api'
  import { getClerkContext } from '$lib/stores/clerk.svelte'
  import AuthHeader from '~/components/layout/auth-header.svelte'
  import GradientBg from '~/components/layout/GradientBg.svelte'
  import Spinner from '~/components/ui/spinner.svelte'

  const clerkContext = getClerkContext()
  const attendance = useQuery(
    api.attendance.queries.getMyAttendanceHistory,
    () => (clerkContext.currentUser ? { limit: 50 } : 'skip'),
  )

  $effect(() => {
    if (clerkContext.isClerkLoaded && !clerkContext.currentUser) {
      void goto('/login')
    }
  })
</script>

<svelte:head>
  <title>Attendance History | ASTN</title>
</svelte:head>

<GradientBg variant="subtle">
  <AuthHeader />

  <main class="container mx-auto px-4 py-8">
    {#if attendance.isLoading}
      <div class="flex min-h-[calc(100vh-65px)] items-center justify-center">
        <Spinner />
      </div>
    {:else}
      <div class="mx-auto max-w-3xl">
        <a
          href="/profile"
          class="mb-4 inline-flex items-center gap-2 text-sm text-slate-500 transition hover:text-slate-900"
        >
          <ArrowLeft class="size-4" />
          Back to profile
        </a>

        <div class="mb-6 flex items-center gap-3">
          <div class="grid size-10 place-items-center rounded-full bg-coral-100 text-coral-700">
            <CalendarCheck class="size-5" />
          </div>
          <h1 class="font-display text-3xl text-slate-950">Attendance history</h1>
        </div>

        {#if !attendance.data?.length}
          <section class="rounded-[2rem] border border-border/70 bg-white/92 p-8 text-center shadow-warm-sm">
            <CalendarCheck class="mx-auto mb-4 size-12 text-slate-300" />
            <h2 class="text-lg font-medium text-foreground">No events attended yet</h2>
            <p class="mt-2 text-slate-500">
              Your attendance history will appear here after you attend events
              from organizations you follow.
            </p>
            <a
              href="/orgs"
              class="mt-6 inline-flex rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600"
            >
              Browse organizations
            </a>
          </section>
        {:else}
          <div class="space-y-4">
            {#each attendance.data as record}
              <section class="rounded-[1.5rem] border border-border/70 bg-white/92 p-5 shadow-warm-sm">
                <div class="flex items-start justify-between gap-4">
                  <div class="min-w-0 flex-1">
                    <h3 class="truncate font-semibold text-foreground">
                      {record.event.title}
                    </h3>
                    {#if record.org}
                      <p class="mt-0.5 text-sm text-slate-500">{record.org.name}</p>
                    {/if}

                    <div class="mt-2 flex flex-wrap items-center gap-x-4 gap-y-1 text-sm text-slate-600">
                      <span>{format(record.event.startAt, 'EEE, MMM d, yyyy')}</span>
                      <span class="flex items-center gap-1">
                        {#if record.event.isVirtual}
                          <Monitor class="size-3.5" />
                          Online
                        {:else}
                          <MapPin class="size-3.5" />
                          {record.event.location || 'In person'}
                        {/if}
                      </span>
                    </div>

                    {#if record.feedbackRating}
                      <div class="mt-3 border-t border-slate-100 pt-3">
                        <div class="flex items-center gap-2">
                          <div class="flex items-center gap-0.5">
                            {#each [1, 2, 3, 4, 5] as star}
                              <Star
                                class={`size-4 ${
                                  star <= record.feedbackRating
                                    ? 'fill-amber-400 text-amber-400'
                                    : 'text-slate-200'
                                }`}
                              />
                            {/each}
                          </div>
                          {#if record.feedbackText}
                            <MessageSquare class="size-4 text-slate-400" />
                          {/if}
                        </div>

                        {#if record.feedbackText}
                          <p class="mt-1.5 line-clamp-2 text-sm text-slate-600">
                            {record.feedbackText}
                          </p>
                        {/if}
                      </div>
                    {/if}
                  </div>

                  <span class="rounded-full bg-slate-100 px-3 py-1 text-xs text-slate-600">
                    {record.status}
                  </span>
                </div>
              </section>
            {/each}
          </div>
        {/if}

        {#if attendance.data?.length}
          <div class="mt-8 text-center text-sm text-slate-500">
            Attendance visibility is controlled in
            {' '}
            <a href="/settings" class="text-coral-700 hover:underline">Settings</a>.
          </div>
        {/if}
      </div>
    {/if}
  </main>
</GradientBg>

// src/routes/profile/attendance.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import {
  AuthLoading,
  Authenticated,
  Unauthenticated,
  useQuery,
} from 'convex/react'
import { format } from 'date-fns'
import {
  ArrowLeft,
  CalendarCheck,
  MapPin,
  MessageSquare,
  Monitor,
  Star,
} from 'lucide-react'
import { api } from '../../../convex/_generated/api'
import { UnauthenticatedRedirect } from '~/components/auth/unauthenticated-redirect'
import { AuthHeader } from '~/components/layout/auth-header'
import { GradientBg } from '~/components/layout/GradientBg'
import { Badge } from '~/components/ui/badge'
import { Button } from '~/components/ui/button'
import { Card } from '~/components/ui/card'
import { Spinner } from '~/components/ui/spinner'

export const Route = createFileRoute('/profile/attendance')({
  component: AttendanceHistoryPage,
})

function AttendanceHistoryPage() {
  return (
    <GradientBg>
      <AuthHeader />
      <AuthLoading>
        <div className="flex items-center justify-center min-h-[calc(100vh-65px)]">
          <Spinner />
        </div>
      </AuthLoading>
      <Unauthenticated>
        <UnauthenticatedRedirect />
      </Unauthenticated>
      <Authenticated>
        <AttendanceContent />
      </Authenticated>
    </GradientBg>
  )
}

function AttendanceContent() {
  const attendance = useQuery(api.attendance.queries.getMyAttendanceHistory, {
    limit: 50,
  })

  if (attendance === undefined) {
    return (
      <div className="flex items-center justify-center min-h-[calc(100vh-65px)]">
        <Spinner />
      </div>
    )
  }

  return (
    <main className="container mx-auto px-4 py-8">
      <div className="max-w-3xl mx-auto">
        {/* Header */}
        <div className="mb-6">
          <Button variant="ghost" size="sm" className="mb-4" asChild>
            <Link to="/profile">
              <ArrowLeft className="size-4 mr-2" />
              Back to Profile
            </Link>
          </Button>
          <div className="flex items-center gap-3">
            <div className="size-10 rounded-full bg-primary/10 flex items-center justify-center">
              <CalendarCheck className="size-5 text-primary" />
            </div>
            <h1 className="text-2xl font-display text-foreground">
              Attendance History
            </h1>
          </div>
        </div>

        {/* Content */}
        {attendance.length === 0 ? (
          <Card className="p-8 text-center">
            <CalendarCheck className="size-12 text-slate-300 mx-auto mb-4" />
            <h2 className="text-lg font-medium text-foreground mb-2">
              No events attended yet
            </h2>
            <p className="text-slate-500 mb-6">
              Your attendance history will appear here after you attend events
              from organizations you follow.
            </p>
            <Button asChild>
              <Link to="/orgs">Browse Organizations</Link>
            </Button>
          </Card>
        ) : (
          <div className="space-y-4">
            {attendance.map((record) => (
              <AttendanceCard key={record._id} record={record} />
            ))}
          </div>
        )}

        {/* Privacy indicator */}
        {attendance.length > 0 && (
          <div className="mt-8 text-center text-sm text-slate-500">
            <p>
              Your attendance visibility is controlled in{' '}
              <Link to="/settings" className="text-primary hover:underline">
                Settings
              </Link>
              . The hosting organization always sees attendance at their events.
            </p>
          </div>
        )}
      </div>
    </main>
  )
}

type AttendanceRecord = NonNullable<
  ReturnType<
    typeof useQuery<typeof api.attendance.queries.getMyAttendanceHistory>
  >
>[number]

function AttendanceCard({ record }: { record: AttendanceRecord }) {
  return (
    <Card className="p-5">
      <div className="flex items-start justify-between gap-4">
        <div className="flex-1 min-w-0">
          {/* Event title and org */}
          <h3 className="font-semibold text-foreground truncate">
            {record.event.title}
          </h3>
          {record.org && (
            <p className="text-sm text-slate-500 mt-0.5">{record.org.name}</p>
          )}

          {/* Event details */}
          <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mt-2 text-sm text-slate-600">
            <span>{format(record.event.startAt, 'EEE, MMM d, yyyy')}</span>
            <span className="flex items-center gap-1">
              {record.event.isVirtual ? (
                <>
                  <Monitor className="size-3.5" />
                  Online
                </>
              ) : (
                <>
                  <MapPin className="size-3.5" />
                  {record.event.location || 'In person'}
                </>
              )}
            </span>
          </div>

          {/* Feedback if exists */}
          {record.feedbackRating && (
            <div className="mt-3 pt-3 border-t border-slate-100">
              <div className="flex items-center gap-2">
                <div className="flex items-center gap-0.5">
                  {[1, 2, 3, 4, 5].map((star) => (
                    <Star
                      key={star}
                      className={`size-4 ${
                        star <= record.feedbackRating!
                          ? 'fill-amber-400 text-amber-400'
                          : 'text-slate-200'
                      }`}
                    />
                  ))}
                </div>
                {record.feedbackText && (
                  <MessageSquare className="size-4 text-slate-400" />
                )}
              </div>
              {record.feedbackText && (
                <p className="text-sm text-slate-600 mt-1.5 line-clamp-2">
                  {record.feedbackText}
                </p>
              )}
            </div>
          )}
        </div>

        {/* Status badge */}
        <StatusBadge status={record.status} />
      </div>
    </Card>
  )
}

function StatusBadge({
  status,
}: {
  status: 'attended' | 'partial' | 'not_attended' | 'unknown'
}) {
  switch (status) {
    case 'attended':
      return (
        <Badge className="bg-green-100 text-green-700 hover:bg-green-100">
          Attended
        </Badge>
      )
    case 'partial':
      return (
        <Badge className="bg-amber-100 text-amber-700 hover:bg-amber-100">
          Partial
        </Badge>
      )
    case 'not_attended':
      return (
        <Badge variant="secondary" className="text-slate-500">
          Did not attend
        </Badge>
      )
    case 'unknown':
      return (
        <Badge variant="outline" className="text-slate-400">
          Unknown
        </Badge>
      )
  }
}
