// src/components/matches/GrowthAreas.tsx
import { BookOpen, Briefcase, TrendingUp, Wrench } from 'lucide-react'
import { Card } from '~/components/ui/card'

interface GrowthAreasProps {
  areas: Array<{
    theme: string
    items: Array<string>
  }>
  hideHeader?: boolean
}

const themeIcons: Record<string, typeof TrendingUp> = {
  'Skills to build': Wrench,
  'Experience to gain': Briefcase,
  'Knowledge to deepen': BookOpen,
}

export function GrowthAreas({ areas, hideHeader = false }: GrowthAreasProps) {
  if (areas.length === 0) return null

  return (
    <Card className="p-6 bg-slate-50">
      {!hideHeader && (
        <>
          <div className="flex items-center gap-2 mb-4">
            <TrendingUp className="size-5 text-primary" />
            <h2 className="text-lg font-semibold text-foreground">
              Your Growth Areas
            </h2>
          </div>
          <p className="text-sm text-slate-500 mb-4">
            Based on your matches, here are areas to focus on to improve your
            fit
          </p>
        </>
      )}

      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {areas.map((area) => {
          const Icon = themeIcons[area.theme] ?? TrendingUp
          return (
            <div key={area.theme} className="bg-white rounded-lg p-4 border">
              <div className="flex items-center gap-2 mb-2">
                <Icon className="size-4 text-slate-400" />
                <h3 className="font-medium text-foreground">{area.theme}</h3>
              </div>
              <ul className="space-y-1 text-sm text-slate-600">
                {area.items.map((item, i) => (
                  <li key={i} className="flex items-start gap-2">
                    <span className="text-primary">-</span>
                    {item}
                  </li>
                ))}
              </ul>
            </div>
          )
        })}
      </div>
    </Card>
  )
}

// src/components/matches/GrowthAreas.svelte
<script lang="ts">
  import { BookOpen, Briefcase, TrendingUp, Wrench } from 'lucide-svelte'
  import type { GrowthArea } from './types'

  const themeIcons: Record<string, any> = {
    'Skills to build': Wrench,
    'Experience to gain': Briefcase,
    'Knowledge to deepen': BookOpen,
  }

  let {
    areas = [],
    hideHeader = false,
  }: {
    areas?: GrowthArea[]
    hideHeader?: boolean
  } = $props()
</script>

{#if areas.length > 0}
  <section class="rounded-[1.75rem] border border-border/70 bg-slate-50 p-6 shadow-warm-sm">
    {#if !hideHeader}
      <div class="mb-4 flex items-center gap-2">
        <TrendingUp class="size-5 text-coral-600" />
        <h2 class="text-lg font-semibold text-slate-950">Your Growth Areas</h2>
      </div>
      <p class="mb-4 text-sm text-slate-600">
        Based on your matches, these are the areas worth strengthening next.
      </p>
    {/if}

    <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {#each areas as area}
        {@const Icon = themeIcons[area.theme] ?? TrendingUp}
        <div class="rounded-2xl border border-border/70 bg-white p-4">
          <div class="mb-2 flex items-center gap-2">
            <Icon class="size-4 text-slate-400" />
            <h3 class="font-medium text-slate-950">{area.theme}</h3>
          </div>

          <ul class="space-y-2 text-sm leading-6 text-slate-600">
            {#each area.items as item}
              <li class="flex items-start gap-2">
                <span class="text-coral-500">-</span>
                <span>{item}</span>
              </li>
            {/each}
          </ul>
        </div>
      {/each}
    </div>
  </section>
{/if}
