// src/components/matches/MatchCard.tsx
import { Link } from '@tanstack/react-router'
import { useEffect, useRef } from 'react'
import { Bookmark, BookmarkX, Check, Clock, X } from 'lucide-react'
import { Card } from '~/components/ui/card'
import { Badge } from '~/components/ui/badge'
import { formatLocation } from '~/lib/formatLocation'
import {
  formatDeadline,
  formatPostedAt,
  getDeadlineUrgency,
  getPostedAtColor,
} from '~/lib/formatDeadline'
import { ROLE_TYPE_COLORS } from '~/lib/roleTypes'
import { computeGlobalFitScore, getFitScoreColor } from '~/lib/matchScoring'
import { cn } from '~/lib/utils'

const ACTIVE_MATCH_KEY = 'view-transition-match-id'

interface MatchCardProps {
  match: {
    _id: string
    tier: 'great' | 'good' | 'exploring'
    score: number
    isNew: boolean
    appliedAt?: number
    explanation: {
      strengths: Array<string>
    }
    opportunity: {
      _id: string
      title: string
      organization: string
      location: string
      isRemote: boolean
      roleType: string
      experienceLevel?: string
      salaryRange?: string
      deadline?: number
      postedAt?: number
      opportunityType?: string
    }
  }
  /** Whether this match is saved/bookmarked */
  isSaved?: boolean
  /** Callback to unsave this match */
  onUnsave?: () => void
  /** Callback to save/bookmark this match (desktop hover action) */
  onSave?: () => void
  /** Callback to dismiss this match (desktop hover action) */
  onDismiss?: () => void
  /** Extra className applied to the Card wrapper */
  className?: string
}

const EXPERIENCE_LEVEL_LABELS: Record<string, string> = {
  entry: 'Entry Level',
  mid: 'Mid Level',
  senior: 'Senior',
  lead: 'Lead',
}

export function MatchCard({
  match,
  isSaved,
  onUnsave,
  onSave,
  onDismiss,
  className,
}: MatchCardProps) {
  const roleColorClass =
    ROLE_TYPE_COLORS[match.opportunity.roleType] || ROLE_TYPE_COLORS.other
  const fitScore = computeGlobalFitScore(match.tier, match.score)

  // Check if this card should have view-transition-name (for back navigation)
  // Must be synchronous so the name is set during first render for view transition capture
  const isActiveTransitionRef = useRef(
    typeof window !== 'undefined' &&
      sessionStorage.getItem(ACTIVE_MATCH_KEY) === match._id,
  )
  const isActiveTransition = isActiveTransitionRef.current

  // Clear sessionStorage after mount — the viewTransitionName was already captured
  useEffect(() => {
    if (isActiveTransitionRef.current) {
      sessionStorage.removeItem(ACTIVE_MATCH_KEY)
      isActiveTransitionRef.current = false
    }
  }, [])

  return (
    <Link
      to="/matches/$id"
      params={{ id: match._id }}
      viewTransition
      preload="render"
      className="block"
      onClick={(e) => {
        // Clear existing view-transition-names to prevent duplicates, then set on clicked card
        document
          .querySelectorAll<HTMLElement>("[style*='view-transition-name']")
          .forEach((el) => {
            el.style.viewTransitionName = ''
          })

        sessionStorage.setItem(ACTIVE_MATCH_KEY, match._id)

        const card = e.currentTarget
        const h3 = card.querySelector('h3')
        if (h3) h3.style.viewTransitionName = 'match-title'
      }}
    >
      <Card
        className={cn(
          'group/card relative p-4 transition-shadow hover:shadow-md cursor-pointer',
          className,
        )}
      >
        {/* Desktop hover actions: save & dismiss */}
        {(onSave || onDismiss) && (
          <div className="absolute top-2 right-2 hidden items-center gap-1 group-hover/card:flex">
            {onSave && !isSaved && (
              <button
                onClick={(e) => {
                  e.preventDefault()
                  e.stopPropagation()
                  onSave()
                }}
                className="rounded-full p-1.5 text-muted-foreground hover:bg-emerald-100 hover:text-emerald-700 transition-colors"
                title="Save match"
              >
                <Bookmark className="size-4" />
              </button>
            )}
            {onDismiss && (
              <button
                onClick={(e) => {
                  e.preventDefault()
                  e.stopPropagation()
                  onDismiss()
                }}
                className="rounded-full p-1.5 text-muted-foreground hover:bg-red-100 hover:text-red-700 transition-colors"
                title="Dismiss match"
              >
                <X className="size-4" />
              </button>
            )}
          </div>
        )}

        {/* Row 1: Badges */}
        <div className="flex flex-wrap items-center gap-2 mb-2">
          <Badge
            className={`${roleColorClass} capitalize flex-shrink-0 rounded-sm border`}
          >
            {match.opportunity.roleType}
          </Badge>
          {match.opportunity.isRemote && (
            <Badge variant="outline" className="text-xs">
              Remote
            </Badge>
          )}
          {isSaved && onUnsave && (
            <button
              onClick={(e) => {
                e.preventDefault()
                e.stopPropagation()
                onUnsave()
              }}
              className="inline-flex items-center gap-1 px-2 py-0.5 rounded-md text-xs font-medium bg-emerald-100 text-emerald-800 hover:bg-red-100 hover:text-red-800 transition-colors group"
            >
              <Bookmark className="size-3 fill-current group-hover:hidden" />
              <BookmarkX className="size-3 hidden group-hover:block" />
              <span className="group-hover:hidden">Saved</span>
              <span className="hidden group-hover:inline">Unsave</span>
            </button>
          )}
          {isSaved && !onUnsave && (
            <Badge
              variant="secondary"
              className="bg-emerald-100 text-emerald-800"
            >
              <Bookmark className="mr-1 size-3 fill-current" />
              Saved
            </Badge>
          )}
          {match.isNew && (
            <Badge
              variant="secondary"
              className="bg-orange-100 text-orange-800"
            >
              New
            </Badge>
          )}
          {match.appliedAt && (
            <Badge
              variant="secondary"
              className="bg-violet-100 text-violet-800"
            >
              <Check className="mr-1 size-3" />
              Applied
            </Badge>
          )}
          <span
            className={`ml-auto text-xs font-medium tabular-nums transition-opacity group-hover/card:opacity-0 ${getFitScoreColor(fitScore)}`}
          >
            {fitScore}% fit
          </span>
        </div>

        {/* Row 2: Title */}
        <div className="group">
          <h3
            suppressHydrationWarning
            style={
              isActiveTransition
                ? { viewTransitionName: 'match-title' }
                : undefined
            }
            className="font-semibold text-foreground group-hover:text-primary"
          >
            {match.opportunity.title}
          </h3>

          {/* Row 3: Org + Location */}
          <p className="text-sm text-muted-foreground">
            {match.opportunity.organization} ·{' '}
            {formatLocation(match.opportunity.location)}
          </p>
        </div>

        {/* Row 4: Deadline or Posted date */}
        {match.opportunity.deadline ? (
          <div
            className={`flex items-center gap-1.5 mt-1.5 text-sm font-medium ${getDeadlineUrgency(match.opportunity.deadline)}`}
          >
            <Clock className="size-3.5" />
            {formatDeadline(match.opportunity.deadline)}
          </div>
        ) : match.opportunity.postedAt &&
          match.opportunity.opportunityType !== 'event' ? (
          <div
            className={`flex items-center gap-1.5 mt-1.5 text-sm ${getPostedAtColor(match.opportunity.postedAt)}`}
          >
            <Clock className="size-3.5" />
            {formatPostedAt(match.opportunity.postedAt)}
          </div>
        ) : null}

        {/* Row 5: Salary + Experience */}
        {(match.opportunity.salaryRange ||
          match.opportunity.experienceLevel) && (
          <div className="flex flex-wrap items-center gap-x-2 gap-y-1 mt-1.5 text-sm text-muted-foreground">
            {match.opportunity.salaryRange &&
              match.opportunity.salaryRange !== 'Not Found' && (
                <span>{match.opportunity.salaryRange}</span>
              )}
            {match.opportunity.salaryRange &&
              match.opportunity.salaryRange !== 'Not Found' &&
              match.opportunity.experienceLevel &&
              EXPERIENCE_LEVEL_LABELS[match.opportunity.experienceLevel] && (
                <span>·</span>
              )}
            {match.opportunity.experienceLevel &&
              EXPERIENCE_LEVEL_LABELS[match.opportunity.experienceLevel] && (
                <span>
                  {EXPERIENCE_LEVEL_LABELS[match.opportunity.experienceLevel]}
                </span>
              )}
          </div>
        )}

        {/* Row 6: One key strength (truncated to 1 line) */}
        {match.explanation.strengths[0] && (
          <p className="mt-2 text-sm text-muted-foreground line-clamp-1">
            <span className="text-emerald-500">+</span>{' '}
            {match.explanation.strengths[0]}
          </p>
        )}
      </Card>
    </Link>
  )
}

// src/components/matches/MatchCard.svelte
<script lang="ts">
  import {
    Bookmark,
    BookmarkMinus,
    Check,
    Clock3,
    X,
  } from 'lucide-svelte'
  import {
    computeGlobalFitScore,
    getFitScoreColor,
  } from '$lib/matchScoring'
  import { formatLocation } from '$lib/formatLocation'
  import {
    formatDeadline,
    formatPostedAt,
    getDeadlineUrgency,
    getPostedAtColor,
  } from '$lib/formatDeadline'
  import { ROLE_TYPE_COLORS } from '$lib/roleTypes'
  import type { MatchSummary } from './types'

  const EXPERIENCE_LEVEL_LABELS: Record<string, string> = {
    entry: 'Entry Level',
    mid: 'Mid Level',
    senior: 'Senior',
    lead: 'Lead',
  }

  let {
    match,
    isSaved = false,
    onSave,
    onUnsave,
    onDismiss,
  }: {
    match: MatchSummary
    isSaved?: boolean
    onSave?: () => void | Promise<void>
    onUnsave?: () => void | Promise<void>
    onDismiss?: () => void | Promise<void>
  } = $props()

  const roleColorClass = $derived(
    ROLE_TYPE_COLORS[match.opportunity.roleType] ?? ROLE_TYPE_COLORS.other,
  )
  const fitScore = $derived(computeGlobalFitScore(match.tier, match.score))

  const stopAndRun = async (
    event: MouseEvent,
    work?: () => void | Promise<void>,
  ) => {
    event.preventDefault()
    event.stopPropagation()
    await work?.()
  }
</script>

<a
  href={`/matches/${match._id}`}
  class="group block rounded-[1.5rem] border border-border/70 bg-white/92 p-4 shadow-warm-sm transition duration-200 hover:-translate-y-0.5 hover:border-coral-200 hover:shadow-md"
>
  <div class="mb-3 flex flex-wrap items-center gap-2">
    <span class={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium capitalize ${roleColorClass}`}>
      {match.opportunity.roleType}
    </span>

    {#if match.opportunity.isRemote}
      <span class="inline-flex rounded-full border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-700">
        Remote
      </span>
    {/if}

    {#if isSaved}
      <button
        type="button"
        class="inline-flex items-center gap-1 rounded-full border border-emerald-200 bg-emerald-50 px-2.5 py-1 text-xs font-medium text-emerald-800 transition hover:border-rose-200 hover:bg-rose-50 hover:text-rose-700"
        onclick={(event) => stopAndRun(event, onUnsave)}
      >
        <BookmarkMinus class="size-3.5" />
        Saved
      </button>
    {:else if onSave}
      <button
        type="button"
        class="inline-flex items-center gap-1 rounded-full border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-600 transition hover:border-emerald-200 hover:bg-emerald-50 hover:text-emerald-700"
        onclick={(event) => stopAndRun(event, onSave)}
      >
        <Bookmark class="size-3.5" />
        Save
      </button>
    {/if}

    {#if match.isNew}
      <span class="inline-flex rounded-full border border-orange-200 bg-orange-50 px-2.5 py-1 text-xs font-medium text-orange-800">
        New
      </span>
    {/if}

    {#if match.appliedAt}
      <span class="inline-flex items-center gap-1 rounded-full border border-violet-200 bg-violet-50 px-2.5 py-1 text-xs font-medium text-violet-800">
        <Check class="size-3.5" />
        Applied
      </span>
    {/if}

    <span class={`ml-auto text-xs font-semibold tabular-nums ${getFitScoreColor(fitScore)}`}>
      {fitScore}% fit
    </span>
  </div>

  <h3 class="text-lg font-semibold text-slate-950 transition group-hover:text-coral-700">
    {match.opportunity.title}
  </h3>
  <p class="mt-1 text-sm text-slate-600">
    {match.opportunity.organization} · {formatLocation(match.opportunity.location)}
  </p>

  {#if match.explanation.strengths[0]}
    <p class="mt-3 line-clamp-3 text-sm leading-6 text-slate-600">
      {match.explanation.strengths[0]}
    </p>
  {/if}

  <div class="mt-4 flex flex-wrap items-center gap-x-3 gap-y-2 text-sm">
    {#if match.opportunity.deadline}
      <span class={`flex items-center gap-1.5 font-medium ${getDeadlineUrgency(match.opportunity.deadline)}`}>
        <Clock3 class="size-4" />
        {formatDeadline(match.opportunity.deadline)}
      </span>
    {:else if match.opportunity.postedAt && match.opportunity.opportunityType !== 'event'}
      <span class={`flex items-center gap-1.5 ${getPostedAtColor(match.opportunity.postedAt)}`}>
        <Clock3 class="size-4" />
        {formatPostedAt(match.opportunity.postedAt)}
      </span>
    {/if}

    {#if match.opportunity.salaryRange && match.opportunity.salaryRange !== 'Not Found'}
      <span class="text-slate-600">{match.opportunity.salaryRange}</span>
    {/if}

    {#if match.opportunity.experienceLevel && EXPERIENCE_LEVEL_LABELS[match.opportunity.experienceLevel]}
      <span class="text-slate-600">
        {EXPERIENCE_LEVEL_LABELS[match.opportunity.experienceLevel]}
      </span>
    {/if}
  </div>

  {#if onDismiss}
    <div class="mt-4 flex justify-end">
      <button
        type="button"
        class="inline-flex items-center gap-1 rounded-lg px-2.5 py-1.5 text-xs font-medium text-slate-500 transition hover:bg-rose-50 hover:text-rose-700"
        onclick={(event) => stopAndRun(event, onDismiss)}
      >
        <X class="size-3.5" />
        Dismiss
      </button>
    </div>
  {/if}
</a>
