// src/routes/opportunities/index.tsx
import { createFileRoute } from "@tanstack/react-router";
import { usePaginatedQuery, useQuery } from "convex/react";
import { useCallback } from "react";
import { api } from "../../../convex/_generated/api";
import { AuthHeader } from "~/components/layout/auth-header";
import { GradientBg } from "~/components/layout/GradientBg";
import { MobileShell } from "~/components/layout/mobile-shell";
import { useIsMobile } from "~/hooks/use-media-query";
import { PullToRefresh } from "~/components/ui/pull-to-refresh";
import { OpportunityFilters } from "~/components/opportunities/opportunity-filters";
import { OpportunityList } from "~/components/opportunities/opportunity-list";

// Define search params schema for this route
type OpportunitySearchParams = {
  role?: string;
  location?: string;
  q?: string;
};

export const Route = createFileRoute("/opportunities/")({
  validateSearch: (search: Record<string, unknown>): OpportunitySearchParams => {
    return {
      role: search.role as string | undefined,
      location: search.location as string | undefined,
      q: search.q as string | undefined,
    };
  },
  component: OpportunitiesPage,
});

const PAGE_SIZE = 20;

function OpportunitiesPage() {
  const { role: roleType, location: locationFilter, q: searchTerm } = Route.useSearch();
  const isMobile = useIsMobile();
  const profile = useQuery(api.profiles.getOrCreateProfile);
  const user = profile ? { name: profile.name || "User" } : null;

  // Determine which query to use based on filters
  const isRemote =
    locationFilter === "remote"
      ? true
      : locationFilter === "onsite"
        ? false
        : undefined;

  // Use search query if there's a search term, otherwise use list query
  const searchPagination = usePaginatedQuery(
    api.opportunities.searchPaginated,
    searchTerm
      ? {
          searchTerm,
          roleType: roleType && roleType !== "all" ? roleType : undefined,
          isRemote,
        }
      : "skip",
    { initialNumItems: PAGE_SIZE }
  );

  const listPagination = usePaginatedQuery(
    api.opportunities.listPaginated,
    !searchTerm
      ? {
          roleType: roleType && roleType !== "all" ? roleType : undefined,
          isRemote,
        }
      : "skip",
    { initialNumItems: PAGE_SIZE }
  );

  const { results, status, loadMore } = searchTerm ? searchPagination : listPagination;
  const isLoading = status === "LoadingFirstPage";

  // Pull-to-refresh handler - Convex is real-time, so data is already fresh
  // This provides visual feedback acknowledging the gesture
  const handlePullRefresh = useCallback(async () => {
    await new Promise((resolve) => setTimeout(resolve, 500));
  }, []);

  const pageContent = (
    <>
      <OpportunityFilters />
      <main className="container mx-auto px-4 py-8">
        <div className="mb-6">
          <h1 className="text-2xl font-display font-semibold text-foreground">Opportunities</h1>
          <p className="text-sm text-muted-foreground mt-1">
            {results.length} {results.length !== 1 ? "opportunities" : "opportunity"} loaded
            {status !== "Exhausted" && " (more available)"}
          </p>
        </div>
        <PullToRefresh
          onRefresh={handlePullRefresh}
          className="min-h-[200px]"
        >
          <OpportunityList
            opportunities={results}
            isLoading={isLoading}
            status={status}
            onLoadMore={() => loadMore(PAGE_SIZE)}
          />
        </PullToRefresh>
      </main>
    </>
  );

  if (isMobile) {
    return (
      <MobileShell user={user}>
        <GradientBg variant="subtle">
          {pageContent}
        </GradientBg>
      </MobileShell>
    );
  }

  return (
    <GradientBg variant="subtle">
      <AuthHeader />
      {pageContent}
    </GradientBg>
  );
}

// src/routes/(app)/opportunities/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import { useQuery } from 'convex-svelte'
  import { api } from '$convex/_generated/api'
  import { getClerkContext } from '$lib/stores/clerk.svelte'
  import { useIsMobile } from '$lib/stores/media-query.svelte'
  import GradientBg from '~/components/layout/GradientBg.svelte'
  import AuthHeader from '~/components/layout/auth-header.svelte'
  import MobileShell from '~/components/layout/mobile-shell.svelte'
  import OpportunityFilters from '~/components/opportunities/opportunity-filters.svelte'
  import OpportunityList from '~/components/opportunities/opportunity-list.svelte'
  import PullToRefresh from '~/components/ui/pull-to-refresh.svelte'
  import {
    getFilterParams,
    readOpportunitySearchParams,
  } from '~/components/opportunities/filters'

  const LIST_LIMIT = 50
  const SEARCH_LIMIT = 50

  type SearchOpportunity = {
    opportunityType?: string
    eventType?: string
    roleType: string
    isRemote: boolean
    title: string
  }

  const clerkContext = getClerkContext()
  const isMobile = useIsMobile()

  const search = $derived(readOpportunitySearchParams(page.url))
  const filters = $derived(getFilterParams(search))
  const searchTerm = $derived(search.q?.trim() ?? '')
  const hasFilters = $derived(
    Boolean(searchTerm || search.type || search.role || search.location),
  )
  const searchRoleType = $derived(
    search.type === 'event' ? undefined : filters.roleType,
  )
  const mobileUser = $derived(
    clerkContext.currentUser
      ? {
          name:
            clerkContext.currentUser.firstName ??
            clerkContext.currentUser.fullName ??
            'User',
        }
      : null,
  )

  const listQuery = useQuery(api.opportunities.list, () =>
    searchTerm
      ? 'skip'
      : {
          ...filters,
          limit: LIST_LIMIT,
        },
  )

  const searchQuery = useQuery(api.opportunities.search, () =>
    searchTerm
      ? {
          searchTerm,
          roleType: searchRoleType,
          isRemote: filters.isRemote,
          limit: SEARCH_LIMIT,
        }
      : 'skip',
  )

  const opportunities = $derived.by(() => {
    const base = searchTerm ? searchQuery.data ?? [] : listQuery.data ?? []

    if (!searchTerm) {
      return base
    }

    return base.filter((opportunity: SearchOpportunity) => {
      if (
        filters.opportunityType === 'job' &&
        opportunity.opportunityType === 'event'
      ) {
        return false
      }

      if (
        filters.opportunityType === 'event' &&
        opportunity.opportunityType !== 'event'
      ) {
        return false
      }

      if (filters.eventType && opportunity.eventType !== filters.eventType) {
        return false
      }

      return true
    })
  })

  const isLoading = $derived(searchTerm ? searchQuery.isLoading : listQuery.isLoading)

  const clearFilters = async () => {
    await goto('/opportunities')
  }

  const handleRefresh = async () => {
    await new Promise((resolve) => setTimeout(resolve, 500))
  }
</script>

<svelte:head>
  <title>Opportunities | ASTN</title>
</svelte:head>

{#snippet listEmptyAction()}
  <button
    type="button"
    class="inline-flex rounded-xl border border-border px-4 py-2 text-sm font-medium text-foreground transition hover:bg-accent"
    onclick={clearFilters}
  >
    Clear filters
  </button>
{/snippet}

{#snippet content()}
  <OpportunityFilters />

  <main class="container mx-auto px-4 py-8">
    <div class="mb-6 flex flex-col gap-2 sm:flex-row sm:items-end sm:justify-between">
      <div>
        <h1 class="font-display text-3xl text-slate-950">Opportunities</h1>
        <p class="mt-1 text-sm text-slate-600">
          {opportunities.length}
          {' '}
          {opportunities.length === 1 ? 'opportunity' : 'opportunities'}
          {#if searchTerm}
            {' '}matching "{searchTerm}"
          {/if}
        </p>
      </div>
    </div>

    <PullToRefresh onRefresh={handleRefresh} class="min-h-[200px]">
      <OpportunityList
        {isLoading}
        opportunities={opportunities}
        {hasFilters}
        emptyAction={listEmptyAction}
      />
    </PullToRefresh>
  </main>
{/snippet}

{#if $isMobile}
  <MobileShell user={mobileUser}>
    <GradientBg variant="subtle">
      {@render content()}
    </GradientBg>
  </MobileShell>
{:else}
  <GradientBg variant="subtle">
    <AuthHeader />
    {@render content()}
  </GradientBg>
{/if}
