// src/components/session/SessionSetup.svelte
<script lang="ts">
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import type { Id } from '$convex/_generated/dataModel'
  import { api } from '$convex/_generated/api'

  let {
    sessionId,
  }: {
    sessionId: Id<'programSessions'>
  } = $props()

  const convex = useConvexClient()
  const phases = useQuery(api.course.sessionQueries.getSessionPhases, () => ({ sessionId }))

  let title = $state('')
  let durationMinutes = $state(20)
  let notes = $state('')
  let saving = $state(false)
  let starting = $state(false)

  const createPhase = async () => {
    if (!title.trim()) return

    saving = true
    try {
      await convex.mutation(api.course.sessionSetup.createPhase, {
        sessionId,
        title: title.trim(),
        durationMs: durationMinutes * 60_000,
        notes: notes.trim() || undefined,
      })
      title = ''
      notes = ''
      durationMinutes = 20
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to create phase')
    } finally {
      saving = false
    }
  }

  const startSession = async () => {
    starting = true
    try {
      await convex.mutation(api.course.sessionRunner.startSession, { sessionId })
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to start session')
    } finally {
      starting = false
    }
  }
</script>

<section class="space-y-6">
  <div class="rounded-[1.75rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
    <h2 class="text-xl font-semibold text-slate-950">Session setup</h2>
    <p class="mt-2 text-sm text-slate-600">
      Add phases and then start the live session when you are ready.
    </p>

    <div class="mt-5 grid gap-4 md:grid-cols-[1fr_180px]">
      <div>
        <label class="mb-2 block text-sm font-medium text-slate-700" for="phase-title">
          Phase title
        </label>
        <input
          id="phase-title"
          bind:value={title}
          class="w-full rounded-2xl border border-border bg-white px-4 py-3 text-sm outline-none transition focus:border-coral-400 focus:ring-2 focus:ring-coral-100"
          placeholder="Opening check-in"
        />
      </div>
      <div>
        <label class="mb-2 block text-sm font-medium text-slate-700" for="phase-duration">
          Minutes
        </label>
        <input
          id="phase-duration"
          bind:value={durationMinutes}
          type="number"
          min="1"
          class="w-full rounded-2xl border border-border bg-white px-4 py-3 text-sm outline-none transition focus:border-coral-400 focus:ring-2 focus:ring-coral-100"
        />
      </div>
    </div>

    <div class="mt-4">
      <label class="mb-2 block text-sm font-medium text-slate-700" for="phase-notes">
        Facilitator notes
      </label>
      <textarea
        id="phase-notes"
        bind:value={notes}
        rows="4"
        class="w-full rounded-2xl border border-border bg-white px-4 py-3 text-sm outline-none transition focus:border-coral-400 focus:ring-2 focus:ring-coral-100"
        placeholder="What should facilitators watch for?"
      ></textarea>
    </div>

    <div class="mt-4 flex flex-wrap gap-3">
      <button
        type="button"
        class="rounded-full bg-slate-950 px-4 py-2 text-sm font-medium text-white transition hover:bg-slate-800 disabled:opacity-60"
        disabled={saving || !title.trim()}
        onclick={createPhase}
      >
        Add phase
      </button>
      <button
        type="button"
        class="rounded-full bg-coral-500 px-4 py-2 text-sm font-medium text-white transition hover:bg-coral-600 disabled:opacity-60"
        disabled={starting || !(phases.data?.length)}
        onclick={startSession}
      >
        Start session
      </button>
    </div>
  </div>

  <div class="rounded-[1.75rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
    <h3 class="text-lg font-semibold text-slate-950">Planned phases</h3>
    <div class="mt-4 space-y-3">
      {#if phases.data?.length}
        {#each phases.data as phase (phase._id)}
          <div class="rounded-2xl bg-slate-50 px-4 py-3">
            <div class="flex items-start justify-between gap-3">
              <div>
                <p class="font-medium text-slate-950">{phase.title}</p>
                {#if phase.notes}
                  <p class="mt-1 text-sm text-slate-600">{phase.notes}</p>
                {/if}
              </div>
              <span class="rounded-full border border-border bg-white px-3 py-1 text-xs font-medium text-slate-600">
                {Math.round(phase.durationMs / 60000)} min
              </span>
            </div>
          </div>
        {/each}
      {:else}
        <p class="text-sm text-slate-500">No phases defined yet.</p>
      {/if}
    </div>
  </div>
</section>

// src/components/session/SessionSetup.tsx
import { useMutation, useQuery } from 'convex/react'
import { AlertTriangle, Clock, Plus } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { api } from '../../../convex/_generated/api'
import { PhaseCard } from './PhaseCard'
import type { Id } from '../../../convex/_generated/dataModel'
import { Button } from '~/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'
import { Textarea } from '~/components/ui/textarea'

interface SessionSetupProps {
  sessionId: Id<'programSessions'>
  programId: Id<'programs'>
  onStartSession: () => void
}

export function SessionSetup({ sessionId, onStartSession }: SessionSetupProps) {
  const phases = useQuery(api.course.sessionQueries.getSessionPhases, {
    sessionId,
  })
  const liveState = useQuery(api.course.sessionQueries.getLiveState, {
    sessionId,
  })

  const createPhase = useMutation(api.course.sessionSetup.createPhase)
  const reorderPhases = useMutation(api.course.sessionSetup.reorderPhases)
  const startSession = useMutation(api.course.sessionRunner.startSession)

  const [showAddForm, setShowAddForm] = useState(false)
  const [title, setTitle] = useState('')
  const [durationMin, setDurationMin] = useState(10)
  const [notes, setNotes] = useState('')
  const [saving, setSaving] = useState(false)
  const [starting, setStarting] = useState(false)

  const isLive = liveState?.status === 'running'

  const handleAdd = async () => {
    if (!title.trim()) {
      toast.error('Title is required')
      return
    }
    setSaving(true)
    try {
      await createPhase({
        sessionId,
        title,
        durationMs: durationMin * 60000,
        notes: notes || undefined,
      })
      toast.success('Phase added')
      setTitle('')
      setDurationMin(10)
      setNotes('')
      setShowAddForm(false)
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Failed to add phase')
    } finally {
      setSaving(false)
    }
  }

  const handleReorder = async (
    phaseIds: Array<Id<'sessionPhases'>>,
    direction: -1 | 1,
    index: number,
  ) => {
    const swapIndex = index + direction
    if (swapIndex < 0 || swapIndex >= phaseIds.length) return
    const newIds = [...phaseIds]
    ;[newIds[index], newIds[swapIndex]] = [newIds[swapIndex], newIds[index]]
    try {
      await reorderPhases({ sessionId, phaseIds: newIds })
    } catch {
      toast.error('Failed to reorder')
    }
  }

  const handleStart = async () => {
    setStarting(true)
    try {
      await startSession({ sessionId })
      toast.success('Session started!')
      onStartSession()
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Failed to start session')
    } finally {
      setStarting(false)
    }
  }

  const allPhaseIds = (phases ?? []).map((p) => p._id)
  const totalDurationMin = (phases ?? []).reduce(
    (sum, p) => sum + Math.round(p.durationMs / 60000),
    0,
  )

  return (
    <div className="space-y-6">
      {isLive && (
        <div className="flex items-center gap-2 p-3 rounded-lg bg-amber-50 text-amber-800 border border-amber-200">
          <AlertTriangle className="size-4 shrink-0" />
          <span className="text-sm">
            Session is live — phases cannot be edited
          </span>
        </div>
      )}

      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <h3 className="text-lg font-semibold">Session Phases</h3>
          {phases && phases.length > 0 && (
            <span className="text-sm text-muted-foreground flex items-center gap-1">
              <Clock className="size-3.5" />
              {totalDurationMin} min total
            </span>
          )}
        </div>
        {!isLive && phases && phases.length > 0 && (
          <Button onClick={handleStart} disabled={starting}>
            {starting ? 'Starting...' : 'Start Session'}
          </Button>
        )}
      </div>

      {/* Phase list */}
      <div className="space-y-2">
        {phases?.map((phase, i) => (
          <PhaseCard
            key={phase._id}
            phase={phase}
            index={i}
            total={phases.length}
            isLive={isLive}
            onReorder={handleReorder}
            allPhaseIds={allPhaseIds}
          />
        ))}
      </div>

      {/* Add phase */}
      {!isLive &&
        (showAddForm ? (
          <Card>
            <CardHeader>
              <CardTitle className="text-sm">Add Phase</CardTitle>
            </CardHeader>
            <CardContent className="space-y-3">
              <div className="space-y-2">
                <Label>Title</Label>
                <Input
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  placeholder="e.g., Welcome & Check-in"
                />
              </div>
              <div className="space-y-2">
                <Label>Duration (minutes)</Label>
                <Input
                  type="number"
                  min={1}
                  value={durationMin}
                  onChange={(e) =>
                    setDurationMin(parseInt(e.target.value) || 1)
                  }
                />
              </div>
              <div className="space-y-2">
                <Label>Notes (facilitator only, optional)</Label>
                <Textarea
                  value={notes}
                  onChange={(e) => setNotes(e.target.value)}
                  rows={2}
                  placeholder="Talking points, reminders..."
                />
              </div>
              <div className="flex justify-end gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  onClick={() => setShowAddForm(false)}
                >
                  Cancel
                </Button>
                <Button size="sm" onClick={handleAdd} disabled={saving}>
                  {saving ? 'Adding...' : 'Add Phase'}
                </Button>
              </div>
            </CardContent>
          </Card>
        ) : (
          <Button
            variant="outline"
            className="w-full gap-1"
            onClick={() => setShowAddForm(true)}
          >
            <Plus className="size-4" />
            Add Phase
          </Button>
        ))}

      {/* Empty state */}
      {phases && phases.length === 0 && !showAddForm && (
        <p className="text-center text-sm text-muted-foreground py-8">
          No phases yet. Add phases to define the session agenda.
        </p>
      )}
    </div>
  )
}
