// src/components/session/SessionRunner.svelte
<script lang="ts">
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import type { Id } from '$convex/_generated/dataModel'
  import { api } from '$convex/_generated/api'
  import PromptResponseViewer from '~/components/course/PromptResponseViewer.svelte'
  import LiveTimer from '~/components/session/LiveTimer.svelte'
  import PairDisplay from '~/components/session/PairDisplay.svelte'
  import PresenceIndicator from '~/components/session/PresenceIndicator.svelte'

  let { sessionId }: { sessionId: Id<'programSessions'> } = $props()

  const convex = useConvexClient()
  const liveState = useQuery(api.course.sessionQueries.getLiveState, () => ({ sessionId }))
  const phases = useQuery(api.course.sessionQueries.getSessionPhases, () => ({ sessionId }))
  const phaseResults = useQuery(api.course.sessionQueries.getPhaseResults, () => ({ sessionId }))

  let mutating = $state(false)

  const currentPhase = $derived(
    phases.data?.find((phase) => phase._id === liveState.data?.currentPhaseId) ?? null,
  )
  const currentIndex = $derived(
    phases.data?.findIndex((phase) => phase._id === liveState.data?.currentPhaseId) ?? -1,
  )

  const runAction = async (action: () => Promise<unknown>) => {
    mutating = true
    try {
      await action()
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Action failed')
    } finally {
      mutating = false
    }
  }
</script>

{#if liveState.data?.status === 'completed'}
  <section class="rounded-[1.75rem] border border-emerald-200 bg-emerald-50/70 p-6 shadow-warm-sm">
    <h2 class="text-xl font-semibold text-emerald-900">Session complete</h2>
    <p class="mt-2 text-sm text-emerald-800">
      {phaseResults.data?.length ?? 0} phase result{phaseResults.data?.length === 1 ? '' : 's'} recorded.
    </p>
  </section>
{:else if liveState.data && currentPhase}
  <div class="grid gap-6 xl:grid-cols-[1.4fr_0.9fr]">
    <div class="space-y-6">
      <section class="rounded-[1.75rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
        <div class="flex flex-wrap items-start justify-between gap-4">
          <div>
            <p class="text-xs font-medium uppercase tracking-[0.18em] text-coral-700">
              Live session
            </p>
            <h2 class="mt-2 text-2xl font-semibold text-slate-950">{currentPhase.title}</h2>
            <p class="mt-2 text-sm text-slate-600">
              Phase {currentIndex + 1} of {phases.data?.length ?? 0}
            </p>
          </div>
          <LiveTimer
            startedAt={liveState.data.phaseStartedAt}
            durationMs={liveState.data.phaseDurationMs}
          />
        </div>

        {#if currentPhase.notes}
          <div class="mt-4 rounded-2xl bg-slate-50 p-4 text-sm text-slate-700">
            {currentPhase.notes}
          </div>
        {/if}

        <div class="mt-5 flex flex-wrap gap-3">
          <button
            type="button"
            class="rounded-full bg-slate-950 px-4 py-2 text-sm font-medium text-white transition hover:bg-slate-800 disabled:opacity-60"
            disabled={mutating}
            onclick={() =>
              runAction(() => convex.mutation(api.course.sessionRunner.advancePhase, { sessionId }))}
          >
            Next phase
          </button>
          <button
            type="button"
            class="rounded-full border border-border bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-accent disabled:opacity-60"
            disabled={mutating}
            onclick={() =>
              runAction(() =>
                convex.mutation(api.course.sessionRunner.extendPhase, {
                  sessionId,
                  additionalMs: 60_000,
                }),
              )}
          >
            +1 minute
          </button>
          <button
            type="button"
            class="rounded-full border border-border bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-accent disabled:opacity-60"
            disabled={mutating}
            onclick={() =>
              runAction(() => convex.mutation(api.course.sessionRunner.skipPhase, { sessionId }))}
          >
            Skip phase
          </button>
          <button
            type="button"
            class="rounded-full bg-rose-500 px-4 py-2 text-sm font-medium text-white transition hover:bg-rose-600 disabled:opacity-60"
            disabled={mutating}
            onclick={() =>
              runAction(() => convex.mutation(api.course.sessionRunner.endSession, { sessionId }))}
          >
            End session
          </button>
        </div>
      </section>

      <section class="rounded-[1.75rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
        <h3 class="text-lg font-semibold text-slate-950">Presence</h3>
        <div class="mt-4">
          <PresenceIndicator {sessionId} />
        </div>
      </section>

      {#if liveState.data.activePromptIds.length}
        <section class="space-y-4">
          {#each liveState.data.activePromptIds as promptId (promptId)}
            <PromptResponseViewer {promptId} />
          {/each}
        </section>
      {/if}

      {#if liveState.data.currentPhaseId && currentPhase.pairConfig}
        <PairDisplay
          sessionId={sessionId}
          phaseId={liveState.data.currentPhaseId}
          strategy={currentPhase.pairConfig.strategy === 'manual'
            ? 'random'
            : currentPhase.pairConfig.strategy}
        />
      {/if}
    </div>

    <aside class="rounded-[1.75rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
      <h3 class="text-lg font-semibold text-slate-950">Timeline</h3>
      <div class="mt-4 space-y-3">
        {#each phases.data ?? [] as phase (phase._id)}
          {@const result = phaseResults.data?.find((item) => item.phaseId === phase._id)}
          <div class={`rounded-2xl border px-4 py-3 ${
            phase._id === liveState.data.currentPhaseId
              ? 'border-coral-200 bg-coral-50/70'
              : result
                ? 'border-emerald-200 bg-emerald-50/70'
                : 'border-border/70 bg-slate-50'
          }`}>
            <p class="font-medium text-slate-950">{phase.title}</p>
            <p class="mt-1 text-xs text-slate-600">
              {Math.round(phase.durationMs / 60000)} min
              {#if result}
                · ran {Math.round(result.actualDurationMs / 60000)} min
              {/if}
            </p>
          </div>
        {/each}
      </div>
    </aside>
  </div>
{:else}
  <section class="rounded-[1.75rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
    <p class="text-sm text-slate-600">Waiting for live session state…</p>
  </section>
{/if}

// src/components/session/SessionRunner.tsx
import { useMutation, useQuery } from 'convex/react'
import {
  CheckCircle2,
  ChevronRight,
  Clock,
  Pause,
  SkipForward,
  Square,
} from 'lucide-react'
import { useMemo, useState } from 'react'
import { toast } from 'sonner'
import { api } from '../../../convex/_generated/api'
import { AdHocPromptDialog } from './AdHocPromptDialog'
import { LiveTimer } from './LiveTimer'
import { PairDisplay } from './PairDisplay'
import { PresenceIndicator } from './PresenceIndicator'
import type { Id } from '../../../convex/_generated/dataModel'
import { PromptResponseViewer } from '~/components/course/PromptResponseViewer'
import { Badge } from '~/components/ui/badge'
import { Button } from '~/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { cn } from '~/lib/utils'

interface SessionRunnerProps {
  sessionId: Id<'programSessions'>
  programId: Id<'programs'>
}

export function SessionRunner({ sessionId }: SessionRunnerProps) {
  const liveState = useQuery(api.course.sessionQueries.getLiveState, {
    sessionId,
  })
  const phases = useQuery(api.course.sessionQueries.getSessionPhases, {
    sessionId,
  })
  const phaseResults = useQuery(api.course.sessionQueries.getPhaseResults, {
    sessionId,
  })

  const advancePhase = useMutation(api.course.sessionRunner.advancePhase)
  const extendPhase = useMutation(api.course.sessionRunner.extendPhase)
  const skipPhase = useMutation(api.course.sessionRunner.skipPhase)
  const endSession = useMutation(api.course.sessionRunner.endSession)

  const [mutating, setMutating] = useState(false)

  const currentPhase = useMemo(
    () => phases?.find((p) => p._id === liveState?.currentPhaseId),
    [phases, liveState?.currentPhaseId],
  )

  const currentIdx = useMemo(
    () => phases?.findIndex((p) => p._id === liveState?.currentPhaseId) ?? -1,
    [phases, liveState?.currentPhaseId],
  )

  const phaseResultMap = useMemo(() => {
    const map = new Map<string, number>()
    if (phaseResults) {
      for (const r of phaseResults) {
        map.set(r.phaseId, r.actualDurationMs)
      }
    }
    return map
  }, [phaseResults])

  const runMutation = async (fn: () => Promise<unknown>) => {
    setMutating(true)
    try {
      await fn()
    } catch (e) {
      toast.error(e instanceof Error ? e.message : 'Action failed')
    } finally {
      setMutating(false)
    }
  }

  if (!liveState || !phases) return null

  const isCompleted = liveState.status === 'completed'
  const isRunning = liveState.status === 'running'

  if (isCompleted) {
    const totalDuration = liveState.completedAt
      ? liveState.completedAt - liveState.startedAt
      : 0
    return (
      <Card className="border-green-200 bg-green-50/50">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-green-800">
            <CheckCircle2 className="size-5" />
            Session Complete
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm text-green-700">
          <p>Total duration: {Math.round(totalDuration / 60000)} minutes</p>
          <p>
            Phases completed: {phaseResults?.length ?? 0} / {phases.length}
          </p>
        </CardContent>
      </Card>
    )
  }

  return (
    <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
      {/* Main area */}
      <div className="lg:col-span-2 space-y-6">
        {/* Current phase header */}
        <Card>
          <CardHeader className="pb-3">
            <div className="flex items-center justify-between">
              <div>
                <div className="flex items-center gap-2 mb-1">
                  <Badge className="bg-green-500 hover:bg-green-500 text-white gap-1">
                    <span className="size-2 rounded-full bg-white animate-pulse" />
                    Live
                  </Badge>
                  <span className="text-sm text-muted-foreground">
                    Phase {currentIdx + 1} of {phases.length}
                  </span>
                </div>
                <CardTitle className="text-xl">
                  {currentPhase?.title ?? 'Unknown phase'}
                </CardTitle>
              </div>
              {isRunning && (
                <LiveTimer
                  startedAt={liveState.phaseStartedAt}
                  durationMs={liveState.phaseDurationMs}
                />
              )}
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            {/* Facilitator notes */}
            {currentPhase?.notes && (
              <div className="p-3 rounded-lg bg-muted text-sm">
                <p className="text-xs font-medium text-muted-foreground mb-1">
                  Facilitator Notes
                </p>
                {currentPhase.notes}
              </div>
            )}

            {/* Controls */}
            <div className="flex flex-wrap gap-2">
              <Button
                onClick={() => runMutation(() => advancePhase({ sessionId }))}
                disabled={mutating}
                className="gap-1"
              >
                <ChevronRight className="size-4" />
                Next Phase
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() =>
                  runMutation(() =>
                    extendPhase({ sessionId, additionalMs: 60000 }),
                  )
                }
                disabled={mutating}
              >
                +1 min
              </Button>
              <Button
                variant="outline"
                size="sm"
                onClick={() =>
                  runMutation(() =>
                    extendPhase({ sessionId, additionalMs: 300000 }),
                  )
                }
                disabled={mutating}
              >
                +5 min
              </Button>
              <Button
                variant="secondary"
                size="sm"
                className="gap-1"
                onClick={() => runMutation(() => skipPhase({ sessionId }))}
                disabled={mutating}
              >
                <SkipForward className="size-3.5" />
                Skip
              </Button>
              <AdHocPromptDialog sessionId={sessionId} />
              <Button
                variant="destructive"
                size="sm"
                className="gap-1 ml-auto"
                onClick={() => {
                  if (confirm('End this session?')) {
                    void runMutation(() => endSession({ sessionId }))
                  }
                }}
                disabled={mutating}
              >
                <Square className="size-3.5" />
                End Session
              </Button>
            </div>

            {/* Presence */}
            <PresenceIndicator sessionId={sessionId} />
          </CardContent>
        </Card>

        {/* Active prompts */}
        {liveState.activePromptIds.length > 0 && (
          <Card>
            <CardHeader>
              <CardTitle className="text-sm">Active Prompts</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {liveState.activePromptIds.map((promptId) => (
                <PromptResponseViewer key={promptId} promptId={promptId} />
              ))}
            </CardContent>
          </Card>
        )}

        {/* Pair display */}
        {currentPhase?.pairConfig && liveState.currentPhaseId && (
          <Card>
            <CardContent className="pt-6">
              <PairDisplay
                sessionId={sessionId}
                phaseId={liveState.currentPhaseId}
                isRunning={isRunning}
              />
            </CardContent>
          </Card>
        )}
      </div>

      {/* Phase timeline sidebar */}
      <div className="space-y-4">
        <h3 className="text-sm font-semibold">Phase Timeline</h3>
        <div className="space-y-1">
          {phases.map((phase) => {
            const isCurrent = phase._id === liveState.currentPhaseId
            const phaseCompleted = phaseResultMap.has(phase._id)
            const actualMs = phaseResultMap.get(phase._id)

            return (
              <div
                key={phase._id}
                className={cn(
                  'flex items-center gap-2 rounded-lg px-3 py-2 text-sm transition-colors',
                  isCurrent && 'ring-2 ring-primary bg-primary/5',
                  phaseCompleted && !isCurrent && 'opacity-60',
                  !isCurrent && !phaseCompleted && 'text-muted-foreground',
                )}
              >
                <span className="w-5 text-center shrink-0">
                  {phaseCompleted ? (
                    <CheckCircle2 className="size-4 text-green-500" />
                  ) : isCurrent ? (
                    <Pause className="size-4 text-primary" />
                  ) : (
                    <Clock className="size-4" />
                  )}
                </span>
                <span className="flex-1 truncate">{phase.title}</span>
                <span className="text-xs shrink-0 tabular-nums">
                  {actualMs
                    ? `${Math.round(actualMs / 60000)}m`
                    : `${Math.round(phase.durationMs / 60000)}m`}
                </span>
              </div>
            )
          })}
        </div>
      </div>
    </div>
  )
}
