// src/components/opportunities/opportunity-detail.svelte
<script lang="ts">
  import { format, formatDistanceToNow } from 'date-fns'
  import {
    BadgeCheck,
    Briefcase,
    Building2,
    Calendar,
    Clock3,
    ExternalLink,
    MapPin,
    Wallet,
  } from 'lucide-svelte'
  import type { Id } from '$convex/_generated/dataModel'
  import { formatLocation } from '$lib/formatLocation'
  import { renderMarkdown } from '$lib/render-markdown'
  import { ROLE_TYPE_COLORS } from '$lib/roleTypes'

  type Opportunity = {
    _id: Id<'opportunities'>
    title: string
    organization: string
    organizationLogoUrl?: string
    location: string
    isRemote: boolean
    roleType: string
    experienceLevel?: string
    description: string
    requirements?: string[]
    salaryRange?: string
    deadline?: number
    sourceUrl: string
    source: '80k_hours' | 'aisafety_com' | 'aisafety_events' | 'manual'
    alternateSources?: Array<{
      sourceId: string
      source: string
      sourceUrl: string
    }>
    lastVerified: number
    createdAt: number
  }

  const SOURCE_NAMES: Record<string, string> = {
    '80k_hours': '80,000 Hours',
    aisafety_com: 'aisafety.com',
    aisafety_events: 'aisafety.com (Events)',
    manual: 'Direct submission',
  }

  let { opportunity }: { opportunity: Opportunity } = $props()

  const roleColorClass = $derived(
    ROLE_TYPE_COLORS[opportunity.roleType] ?? ROLE_TYPE_COLORS.other,
  )
  const descriptionHtml = $derived(renderMarkdown(opportunity.description))
</script>

<div class="mx-auto max-w-4xl">
  <section class="mb-6 rounded-[2rem] border border-border/70 bg-white/92 p-5 shadow-warm-sm sm:p-6">
    <div class="flex flex-col gap-5 sm:flex-row">
      {#if opportunity.organizationLogoUrl}
        <img
          src={opportunity.organizationLogoUrl}
          alt={`${opportunity.organization} logo`}
          class="size-16 rounded-2xl border border-border bg-muted object-contain"
        />
      {:else}
        <div class="grid size-16 place-items-center rounded-2xl border border-border bg-muted">
          <Building2 class="size-8 text-muted-foreground" />
        </div>
      {/if}

      <div class="min-w-0 flex-1">
        <div class="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
          <div class="min-w-0">
            <h1 class="font-display text-3xl leading-tight text-slate-950">
              {opportunity.title}
            </h1>
            <p class="mt-1 text-lg text-slate-600">{opportunity.organization}</p>
          </div>

          <span class={`inline-flex self-start rounded-full border px-3 py-1 text-xs font-medium capitalize ${roleColorClass}`}>
            {opportunity.roleType}
          </span>
        </div>

        <div class="mt-4 flex flex-wrap items-center gap-x-5 gap-y-2 text-sm text-slate-600">
          <span class="flex items-center gap-1.5">
            <MapPin class="size-4" />
            {formatLocation(opportunity.location)}
          </span>

          {#if opportunity.isRemote}
            <span class="inline-flex rounded-full border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-700">
              Remote
            </span>
          {/if}

          {#if opportunity.experienceLevel}
            <span class="flex items-center gap-1.5">
              <Briefcase class="size-4" />
              {opportunity.experienceLevel.charAt(0).toUpperCase() +
                opportunity.experienceLevel.slice(1)} level
            </span>
          {/if}

          {#if opportunity.salaryRange && opportunity.salaryRange !== 'Not Found'}
            <span class="flex items-center gap-1.5">
              <Wallet class="size-4" />
              {opportunity.salaryRange}
            </span>
          {/if}

          {#if opportunity.deadline}
            <span class="flex items-center gap-1.5">
              <Clock3 class="size-4" />
              Deadline: {format(opportunity.deadline, 'MMM d, yyyy')}
            </span>
          {/if}
        </div>

        <div class="mt-6 flex flex-wrap gap-3">
          <a
            href={opportunity.sourceUrl}
            target="_blank"
            rel="noopener noreferrer"
            class="inline-flex items-center gap-2 rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600"
          >
            Apply now
            <ExternalLink class="size-4" />
          </a>
          <a
            href="/opportunities"
            class="inline-flex items-center gap-2 rounded-xl border border-border px-4 py-2.5 text-sm font-medium text-foreground transition hover:bg-accent"
          >
            Back to opportunities
          </a>
        </div>
      </div>
    </div>
  </section>

  <section class="mb-6 rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
    <h2 class="mb-4 text-xl font-semibold text-slate-950">About this role</h2>
    <div class="prose prose-slate max-w-none text-slate-700">
      {@html descriptionHtml}
    </div>
  </section>

  {#if opportunity.requirements?.length}
    <section class="mb-6 rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
      <h2 class="mb-4 text-xl font-semibold text-slate-950">Requirements</h2>
      <ul class="space-y-3 text-slate-700">
        {#each opportunity.requirements as requirement}
          <li class="flex gap-3">
            <BadgeCheck class="mt-0.5 size-4 shrink-0 text-coral-600" />
            <span>{requirement}</span>
          </li>
        {/each}
      </ul>
    </section>
  {/if}

  <section class="rounded-[2rem] border border-border/70 bg-white/92 p-5 text-sm text-slate-600 shadow-warm-sm">
    <div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
      <div class="flex items-center gap-2">
        <Calendar class="size-4 shrink-0" />
        Last verified {formatDistanceToNow(opportunity.lastVerified, { addSuffix: true })}
      </div>

      <div class="flex flex-wrap items-center gap-2">
        <span>Source:</span>
        <a
          href={opportunity.sourceUrl}
          target="_blank"
          rel="noopener noreferrer"
          class="font-medium text-coral-700 hover:underline"
        >
          {SOURCE_NAMES[opportunity.source] ?? opportunity.source}
        </a>

        {#if opportunity.alternateSources?.length}
          <span class="text-slate-300">|</span>
          <span>Also on:</span>
          {#each opportunity.alternateSources as source}
            <a
              href={source.sourceUrl}
              target="_blank"
              rel="noopener noreferrer"
              class="font-medium text-coral-700 hover:underline"
            >
              {SOURCE_NAMES[source.source] ?? source.source}
            </a>
          {/each}
        {/if}
      </div>
    </div>
  </section>
</div>

// src/components/opportunities/opportunity-detail.tsx
import { Link } from '@tanstack/react-router'
import {
  Banknote,
  Briefcase,
  Building2,
  Calendar,
  Clock,
  ExternalLink,
  MapPin,
} from 'lucide-react'
import { format, formatDistanceToNow } from 'date-fns'
import type { Id } from '../../../convex/_generated/dataModel'
import { Button } from '~/components/ui/button'
import { Badge } from '~/components/ui/badge'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { formatLocation } from '~/lib/formatLocation'

type Opportunity = {
  _id: Id<'opportunities'>
  title: string
  organization: string
  organizationLogoUrl?: string
  location: string
  isRemote: boolean
  roleType: string
  experienceLevel?: string
  description: string
  requirements?: Array<string>
  salaryRange?: string
  deadline?: number
  sourceUrl: string
  source: '80k_hours' | 'aisafety_com' | 'aisafety_events' | 'manual'
  alternateSources?: Array<{
    sourceId: string
    source: string
    sourceUrl: string
  }>
  lastVerified: number
  createdAt: number
}

const SOURCE_NAMES: Record<string, string> = {
  '80k_hours': '80,000 Hours',
  aisafety_com: 'aisafety.com',
  aisafety_events: 'aisafety.com (Events)',
  manual: 'Direct submission',
}

const ROLE_TYPE_COLORS: Record<string, string> = {
  research:
    'bg-purple-100 text-purple-800 dark:bg-purple-900/30 dark:text-purple-300',
  engineering:
    'bg-blue-100 text-blue-800 dark:bg-blue-900/30 dark:text-blue-300',
  operations:
    'bg-green-100 text-green-800 dark:bg-green-900/30 dark:text-green-300',
  policy:
    'bg-amber-100 text-amber-800 dark:bg-amber-900/30 dark:text-amber-300',
  other: 'bg-muted text-muted-foreground',
}

export function OpportunityDetail({
  opportunity,
}: {
  opportunity: Opportunity
}) {
  const roleColorClass =
    ROLE_TYPE_COLORS[opportunity.roleType] || ROLE_TYPE_COLORS.other

  return (
    <div className="max-w-4xl mx-auto">
      {/* Header */}
      <div className="bg-card rounded-sm border border-border p-4 sm:p-6 mb-6">
        <div className="flex flex-col sm:flex-row gap-4">
          {opportunity.organizationLogoUrl ? (
            <img
              src={opportunity.organizationLogoUrl}
              alt={`${opportunity.organization} logo`}
              className="w-16 h-16 rounded-sm object-contain bg-muted flex-shrink-0"
            />
          ) : (
            <div className="w-16 h-16 rounded-sm bg-muted flex items-center justify-center flex-shrink-0">
              <Building2 className="w-8 h-8 text-muted-foreground" />
            </div>
          )}

          <div className="flex-1 min-w-0">
            <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-2 sm:gap-4">
              <div className="min-w-0">
                <h1
                  style={{ viewTransitionName: 'opportunity-title' }}
                  className="text-xl sm:text-2xl font-display text-foreground break-words"
                >
                  {opportunity.title}
                </h1>
                <p className="text-base sm:text-lg text-muted-foreground mt-1">
                  {opportunity.organization}
                </p>
              </div>
              <Badge
                className={`${roleColorClass} capitalize rounded-sm shrink-0 self-start`}
              >
                {opportunity.roleType}
              </Badge>
            </div>

            <div className="flex flex-wrap items-center gap-x-4 gap-y-2 mt-4 text-muted-foreground text-sm sm:text-base">
              <span className="flex items-center gap-1.5">
                <MapPin className="w-4 h-4 shrink-0" />
                <span className="truncate max-w-[200px]">
                  {formatLocation(opportunity.location)}
                </span>
                {opportunity.isRemote && (
                  <Badge variant="outline" className="ml-1 rounded-sm shrink-0">
                    Remote
                  </Badge>
                )}
              </span>

              {opportunity.experienceLevel && (
                <span className="flex items-center gap-1.5">
                  <Briefcase className="w-4 h-4 shrink-0" />
                  {opportunity.experienceLevel.charAt(0).toUpperCase() +
                    opportunity.experienceLevel.slice(1)}{' '}
                  level
                </span>
              )}

              {opportunity.salaryRange &&
                opportunity.salaryRange !== 'Not Found' && (
                  <span className="flex items-center gap-1.5">
                    <Banknote className="w-4 h-4 shrink-0" />
                    {opportunity.salaryRange}
                  </span>
                )}

              {opportunity.deadline && (
                <span className="flex items-center gap-1.5">
                  <Clock className="w-4 h-4 shrink-0" />
                  Deadline: {format(opportunity.deadline, 'MMM d, yyyy')}
                </span>
              )}
            </div>

            <div className="mt-6">
              <Button asChild size="lg" className="rounded-sm w-full sm:w-auto">
                <a
                  href={opportunity.sourceUrl}
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Apply Now
                  <ExternalLink className="w-4 h-4 ml-2" />
                </a>
              </Button>
            </div>
          </div>
        </div>
      </div>

      <div className="detail-content-reveal">
        {/* Description */}
        <Card className="mb-6 rounded-sm">
          <CardHeader>
            <CardTitle>About This Role</CardTitle>
          </CardHeader>
          <CardContent>
            <div className="prose prose-neutral dark:prose-invert max-w-none">
              {opportunity.description.split('\n').map((paragraph, i) => (
                <p key={i}>{paragraph}</p>
              ))}
            </div>
          </CardContent>
        </Card>

        {/* Requirements */}
        {opportunity.requirements && opportunity.requirements.length > 0 && (
          <Card className="mb-6 rounded-sm">
            <CardHeader>
              <CardTitle>Requirements</CardTitle>
            </CardHeader>
            <CardContent>
              <ul className="list-disc list-inside space-y-2 text-foreground">
                {opportunity.requirements.map((req, i) => (
                  <li key={i}>{req}</li>
                ))}
              </ul>
            </CardContent>
          </Card>
        )}

        {/* Source attribution (OPPS-06 freshness + source) */}
        <div className="text-sm text-muted-foreground border-t border-border pt-4 mt-6">
          <div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-2 sm:gap-4">
            <div className="flex items-center gap-1 font-mono">
              <Calendar className="w-4 h-4 shrink-0" />
              <span>
                Last verified:{' '}
                {formatDistanceToNow(opportunity.lastVerified, {
                  addSuffix: true,
                })}
              </span>
            </div>

            <div className="flex flex-wrap items-center gap-2">
              <span>Source:</span>
              <a
                href={opportunity.sourceUrl}
                target="_blank"
                rel="noopener noreferrer"
                className="text-primary hover:underline"
              >
                {SOURCE_NAMES[opportunity.source] || opportunity.source}
              </a>

              {opportunity.alternateSources &&
                opportunity.alternateSources.length > 0 && (
                  <>
                    <span className="text-muted-foreground/50">|</span>
                    <span>Also on:</span>
                    {opportunity.alternateSources.map((alt, i) => (
                      <a
                        key={i}
                        href={alt.sourceUrl}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-primary hover:underline"
                      >
                        {SOURCE_NAMES[alt.source] || alt.source}
                      </a>
                    ))}
                  </>
                )}
            </div>
          </div>
        </div>

        {/* Back link */}
        <div className="mt-8">
          <Button variant="outline" asChild className="rounded-sm">
            <Link to="/opportunities" viewTransition>
              Back to all opportunities
            </Link>
          </Button>
        </div>
      </div>
    </div>
  )
}
