// src/components/opportunities/opportunity-filters.tsx
import { useNavigate, useSearch } from "@tanstack/react-router";
import { useCallback } from "react";
import { Search, X } from "lucide-react";
import { Input } from "~/components/ui/input";
import { Button } from "~/components/ui/button";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";

const ROLE_TYPES = [
  { value: "all", label: "All Roles" },
  { value: "research", label: "Research" },
  { value: "engineering", label: "Engineering" },
  { value: "operations", label: "Operations" },
  { value: "policy", label: "Policy" },
  { value: "other", label: "Other" },
];

const LOCATION_OPTIONS = [
  { value: "all", label: "All Locations" },
  { value: "remote", label: "Remote Only" },
  { value: "onsite", label: "On-site Only" },
];

// Search params type for the opportunities route
type OpportunitySearchParams = {
  role?: string;
  location?: string;
  q?: string;
};

export function OpportunityFilters() {
  const navigate = useNavigate();
  const search = useSearch({ from: "/opportunities/" });

  const roleType = search.role || "all";
  const locationFilter = search.location || "all";
  const searchTerm = search.q || "";

  const updateFilter = useCallback(
    (key: keyof OpportunitySearchParams, value: string) => {
      navigate({
        to: "/opportunities",
        search: (prev: OpportunitySearchParams) => {
          const newSearch = { ...prev };
          if (value === "" || value === "all") {
            delete newSearch[key];
          } else {
            newSearch[key] = value;
          }
          return newSearch;
        },
      });
    },
    [navigate]
  );

  const clearFilters = () => {
    navigate({
      to: "/opportunities",
      search: {},
    });
  };

  const hasActiveFilters =
    roleType !== "all" || locationFilter !== "all" || searchTerm !== "";

  return (
    <div className="bg-white dark:bg-card border-b border-slate-200 dark:border-border sticky top-0 z-10">
      <div className="container mx-auto px-4 py-4">
        <div className="flex flex-wrap items-center gap-3">
          {/* Search - Secondary per CONTEXT.md */}
          <div className="relative w-64">
            <Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400 dark:text-muted-foreground" />
            <Input
              type="search"
              placeholder="Search opportunities..."
              value={searchTerm}
              onChange={(e) => updateFilter("q", e.target.value)}
              className="pl-9"
            />
          </div>

          {/* Role Type Filter */}
          <Select value={roleType} onValueChange={(v) => updateFilter("role", v)}>
            <SelectTrigger className="w-40">
              <SelectValue placeholder="Role Type" />
            </SelectTrigger>
            <SelectContent>
              {ROLE_TYPES.map((type) => (
                <SelectItem key={type.value} value={type.value}>
                  {type.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          {/* Location/Remote Filter */}
          <Select
            value={locationFilter}
            onValueChange={(v) => updateFilter("location", v)}
          >
            <SelectTrigger className="w-40">
              <SelectValue placeholder="Location" />
            </SelectTrigger>
            <SelectContent>
              {LOCATION_OPTIONS.map((opt) => (
                <SelectItem key={opt.value} value={opt.value}>
                  {opt.label}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>

          {/* Clear Filters */}
          {hasActiveFilters && (
            <Button
              variant="ghost"
              size="sm"
              onClick={clearFilters}
              className="text-slate-500 dark:text-muted-foreground"
            >
              <X className="w-4 h-4 mr-1" />
              Clear
            </Button>
          )}
        </div>
      </div>
    </div>
  );
}

// src/components/opportunities/opportunity-filters.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import { Search, X } from 'lucide-svelte'
  import {
    getCategoryOptions,
    LOCATION_OPTIONS,
    readOpportunitySearchParams,
    TYPE_OPTIONS,
    type OpportunitySearchParams,
  } from './filters'

  const search = $derived(readOpportunitySearchParams(page.url))
  const typeFilter = $derived(search.type ?? 'all')
  const roleFilter = $derived(search.role ?? 'all')
  const locationFilter = $derived(search.location ?? 'all')
  const searchTerm = $derived(search.q ?? '')
  const categoryOptions = $derived(
    getCategoryOptions(typeFilter !== 'all' ? typeFilter : undefined),
  )
  const hasActiveFilters = $derived(
    typeFilter !== 'all' ||
      roleFilter !== 'all' ||
      locationFilter !== 'all' ||
      searchTerm.trim() !== '',
  )

  const navigateWith = async (
    mutate: (params: URLSearchParams) => void,
  ) => {
    const params = new URLSearchParams(page.url.searchParams)
    mutate(params)

    const query = params.toString()
    await goto(query ? `/opportunities?${query}` : '/opportunities', {
      keepFocus: true,
      noScroll: true,
      replaceState: true,
    })
  }

  const updateFilter = async (
    key: keyof OpportunitySearchParams,
    value: string,
  ) => {
    await navigateWith((params) => {
      if (value === '' || value === 'all') {
        params.delete(key)
      } else {
        params.set(key, value)
      }

      if (key === 'type') {
        params.delete('role')
      }
    })
  }

  const clearFilters = async () => {
    await goto('/opportunities', {
      keepFocus: true,
      noScroll: true,
      replaceState: true,
    })
  }
</script>

<section class="sticky top-0 z-10 border-b border-slate-200 bg-white/95 backdrop-blur supports-[backdrop-filter]:bg-white/80">
  <div class="container mx-auto px-4 py-4">
    <div class="grid gap-3 md:grid-cols-[minmax(0,1.4fr)_180px_180px_auto] md:items-end">
      <label class="block">
        <span class="mb-1.5 block text-xs font-medium uppercase tracking-wide text-slate-500">
          Search
        </span>
        <div class="flex items-center gap-2 rounded-xl border border-input bg-background px-3 py-2">
          <Search class="size-4 text-muted-foreground" />
          <input
            type="search"
            value={searchTerm}
            placeholder="Search opportunities..."
            class="w-full bg-transparent text-sm text-foreground outline-none placeholder:text-muted-foreground"
            oninput={(event) =>
              updateFilter('q', (event.currentTarget as HTMLInputElement).value)}
          />
        </div>
      </label>

      <label class="block">
        <span class="mb-1.5 block text-xs font-medium uppercase tracking-wide text-slate-500">
          Type
        </span>
        <select
          value={typeFilter}
          class="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm text-foreground outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
          onchange={(event) =>
            updateFilter('type', (event.currentTarget as HTMLSelectElement).value)}
        >
          {#each TYPE_OPTIONS as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
      </label>

      <label class="block">
        <span class="mb-1.5 block text-xs font-medium uppercase tracking-wide text-slate-500">
          Category
        </span>
        <select
          value={roleFilter}
          class="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm text-foreground outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
          onchange={(event) =>
            updateFilter('role', (event.currentTarget as HTMLSelectElement).value)}
        >
          {#each categoryOptions as option}
            <option value={option.value}>{option.label}</option>
          {/each}
        </select>
      </label>

      <div class="grid gap-3 sm:grid-cols-[1fr_auto] md:grid-cols-[1fr_auto]">
        <label class="block">
          <span class="mb-1.5 block text-xs font-medium uppercase tracking-wide text-slate-500">
            Location
          </span>
          <select
            value={locationFilter}
            class="w-full rounded-xl border border-input bg-background px-3 py-2 text-sm text-foreground outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
            onchange={(event) =>
              updateFilter('location', (event.currentTarget as HTMLSelectElement).value)}
          >
            {#each LOCATION_OPTIONS as option}
              <option value={option.value}>{option.label}</option>
            {/each}
          </select>
        </label>

        <div class="flex items-end">
          {#if hasActiveFilters}
            <button
              type="button"
              class="inline-flex w-full items-center justify-center gap-2 rounded-xl border border-border px-4 py-2.5 text-sm font-medium text-slate-600 transition hover:bg-accent hover:text-foreground md:w-auto"
              onclick={clearFilters}
            >
              <X class="size-4" />
              Clear
            </button>
          {/if}
        </div>
      </div>
    </div>
  </div>
</section>
