// src/components/opportunities/opportunity-card.tsx
import { Link } from '@tanstack/react-router'
import { Banknote, CalendarDays } from 'lucide-react'
import type { Id } from '../../../convex/_generated/dataModel'
import { Badge } from '~/components/ui/badge'
import { Card, CardContent } from '~/components/ui/card'
import { formatLocation } from '~/lib/formatLocation'
import { formatDeadline, getDeadlineUrgency } from '~/lib/formatDeadline'
import { EVENT_TYPE_COLORS, ROLE_TYPE_COLORS } from '~/lib/roleTypes'

const ACTIVE_OPPORTUNITY_KEY = 'view-transition-opportunity-id'

type Opportunity = {
  _id: Id<'opportunities'>
  title: string
  organization: string
  location: string
  isRemote: boolean
  roleType: string
  experienceLevel?: string
  salaryRange?: string
  deadline?: number
  opportunityType?: string
  eventType?: string
  startDate?: number
}

const EXPERIENCE_LEVEL_LABELS: Record<string, string> = {
  entry: 'Entry Level',
  mid: 'Mid Level',
  senior: 'Senior',
  lead: 'Lead',
}

export function OpportunityCard({
  opportunity,
  index = 0,
}: {
  opportunity: Opportunity
  index?: number
}) {
  const isEvent = opportunity.opportunityType === 'event'
  const roleColorClass =
    ROLE_TYPE_COLORS[opportunity.roleType] || ROLE_TYPE_COLORS.other
  const eventColorClass = opportunity.eventType
    ? EVENT_TYPE_COLORS[opportunity.eventType] || EVENT_TYPE_COLORS.conference
    : undefined

  // Check if this card should have view-transition-name (for back navigation)
  const isActiveTransition =
    typeof window !== 'undefined' &&
    sessionStorage.getItem(ACTIVE_OPPORTUNITY_KEY) === opportunity._id

  return (
    <Link
      to="/opportunities/$id"
      params={{ id: opportunity._id }}
      viewTransition
      onClick={(e) => {
        // Clear existing view-transition-names to prevent duplicates, then set on clicked card
        document
          .querySelectorAll<HTMLElement>("[style*='view-transition-name']")
          .forEach((el) => {
            el.style.viewTransitionName = ''
          })

        sessionStorage.setItem(ACTIVE_OPPORTUNITY_KEY, opportunity._id)

        const h3 = e.currentTarget.querySelector('h3') as HTMLElement | null
        if (h3) h3.style.viewTransitionName = 'opportunity-title'
      }}
    >
      <Card
        className="
          hover:shadow-lg transition-all duration-200 cursor-pointer
          border-slate-200 dark:border-border hover:border-primary/30
          hover:-translate-y-0.5 active:translate-y-0
          rounded-none sm:rounded-sm
        "
        style={{
          animationDelay: `${index * 50}ms`,
        }}
      >
        <CardContent className="p-5">
          {/* Row 1: Badges */}
          <div className="flex flex-wrap items-center gap-2 mb-2">
            {isEvent && eventColorClass ? (
              <Badge
                className={`${eventColorClass} capitalize flex-shrink-0 rounded-sm border`}
              >
                {opportunity.eventType}
              </Badge>
            ) : (
              <Badge
                className={`${roleColorClass} capitalize flex-shrink-0 rounded-sm border`}
              >
                {opportunity.roleType}
              </Badge>
            )}
            {isEvent && (
              <Badge
                variant="outline"
                className="text-xs rounded-sm border-teal-300 text-teal-700 dark:border-teal-700 dark:text-teal-400"
              >
                Event
              </Badge>
            )}
            {opportunity.isRemote && (
              <Badge variant="outline" className="text-xs rounded-sm">
                Remote
              </Badge>
            )}
            {opportunity.experienceLevel &&
              EXPERIENCE_LEVEL_LABELS[opportunity.experienceLevel] && (
                <Badge variant="outline" className="text-xs rounded-sm">
                  {EXPERIENCE_LEVEL_LABELS[opportunity.experienceLevel]}
                </Badge>
              )}
          </div>

          {/* Row 2: Title */}
          <h3
            suppressHydrationWarning
            style={
              isActiveTransition
                ? { viewTransitionName: 'opportunity-title' }
                : undefined
            }
            className="font-semibold text-foreground leading-tight"
          >
            {opportunity.title}
          </h3>

          {/* Row 3: Org + Location */}
          <p className="text-sm text-muted-foreground mt-0.5">
            {opportunity.organization} · {formatLocation(opportunity.location)}
          </p>

          {/* Row 4: Dates / Salary + Deadline */}
          {(opportunity.salaryRange ||
            opportunity.deadline ||
            (isEvent && opportunity.startDate)) && (
            <div className="flex flex-wrap items-center gap-x-3 gap-y-1 mt-2.5 text-sm">
              {isEvent && opportunity.startDate && (
                <span className="flex items-center gap-1 text-muted-foreground">
                  <CalendarDays className="w-3.5 h-3.5" />
                  {new Date(opportunity.startDate).toLocaleDateString('en-US', {
                    month: 'short',
                    day: 'numeric',
                    year: 'numeric',
                  })}
                </span>
              )}

              {opportunity.salaryRange &&
                opportunity.salaryRange !== 'Not Found' && (
                  <span className="flex items-center gap-1 text-muted-foreground">
                    <Banknote className="w-3.5 h-3.5" />
                    {opportunity.salaryRange}
                  </span>
                )}

              {opportunity.deadline && (
                <span className={getDeadlineUrgency(opportunity.deadline)}>
                  {formatDeadline(opportunity.deadline)}
                </span>
              )}
            </div>
          )}
        </CardContent>
      </Card>
    </Link>
  )
}

// src/components/opportunities/opportunity-card.svelte
<script lang="ts">
  import { CalendarDays, MapPin, Wallet } from 'lucide-svelte'
  import type { Id } from '$convex/_generated/dataModel'
  import { formatDeadline, getDeadlineUrgency } from '$lib/formatDeadline'
  import { formatLocation } from '$lib/formatLocation'
  import { EVENT_TYPE_COLORS, ROLE_TYPE_COLORS } from '$lib/roleTypes'

  type Opportunity = {
    _id: Id<'opportunities'>
    title: string
    organization: string
    location: string
    isRemote: boolean
    roleType: string
    experienceLevel?: string
    salaryRange?: string
    deadline?: number
    opportunityType?: string
    eventType?: string
    startDate?: number
  }

  const EXPERIENCE_LEVEL_LABELS: Record<string, string> = {
    entry: 'Entry Level',
    mid: 'Mid Level',
    senior: 'Senior',
    lead: 'Lead',
  }

  let {
    opportunity,
    index = 0,
  }: {
    opportunity: Opportunity
    index?: number
  } = $props()

  const isEvent = $derived(opportunity.opportunityType === 'event')
  const roleColorClass = $derived(
    ROLE_TYPE_COLORS[opportunity.roleType] ?? ROLE_TYPE_COLORS.other,
  )
  const eventColorClass = $derived(
    opportunity.eventType
      ? EVENT_TYPE_COLORS[opportunity.eventType] ?? EVENT_TYPE_COLORS.conference
      : '',
  )
</script>

<a
  href={`/opportunities/${opportunity._id}`}
  class="block rounded-2xl border border-slate-200 bg-white/92 p-5 shadow-sm transition duration-200 hover:-translate-y-0.5 hover:border-coral-200 hover:shadow-md"
  style={`animation-delay: ${Math.min(index, 19) * 50}ms; animation-fill-mode: backwards;`}
>
  <div class="mb-3 flex flex-wrap items-center gap-2">
    {#if isEvent}
      <span class={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium capitalize ${eventColorClass}`}>
        {opportunity.eventType ?? 'event'}
      </span>
      <span class="inline-flex rounded-full border border-teal-300 px-2.5 py-1 text-xs font-medium text-teal-700">
        Event
      </span>
    {:else}
      <span class={`inline-flex rounded-full border px-2.5 py-1 text-xs font-medium capitalize ${roleColorClass}`}>
        {opportunity.roleType}
      </span>
    {/if}

    {#if opportunity.isRemote}
      <span class="inline-flex rounded-full border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-700">
        Remote
      </span>
    {/if}

    {#if opportunity.experienceLevel && EXPERIENCE_LEVEL_LABELS[opportunity.experienceLevel]}
      <span class="inline-flex rounded-full border border-slate-200 px-2.5 py-1 text-xs font-medium text-slate-700">
        {EXPERIENCE_LEVEL_LABELS[opportunity.experienceLevel]}
      </span>
    {/if}
  </div>

  <h3 class="text-lg font-semibold leading-tight text-slate-950">
    {opportunity.title}
  </h3>
  <p class="mt-1 text-sm text-slate-600">
    {opportunity.organization} · {formatLocation(opportunity.location)}
  </p>

  {#if opportunity.salaryRange || opportunity.deadline || (isEvent && opportunity.startDate)}
    <div class="mt-3 flex flex-wrap items-center gap-x-4 gap-y-2 text-sm">
      {#if isEvent && opportunity.startDate}
        <span class="flex items-center gap-1.5 text-slate-600">
          <CalendarDays class="size-4" />
          {new Date(opportunity.startDate).toLocaleDateString('en-US', {
            month: 'short',
            day: 'numeric',
            year: 'numeric',
          })}
        </span>
      {/if}

      {#if opportunity.salaryRange && opportunity.salaryRange !== 'Not Found'}
        <span class="flex items-center gap-1.5 text-slate-600">
          <Wallet class="size-4" />
          {opportunity.salaryRange}
        </span>
      {/if}

      {#if !isEvent}
        <span class="flex items-center gap-1.5 text-slate-600">
          <MapPin class="size-4" />
          {formatLocation(opportunity.location)}
        </span>
      {/if}

      {#if opportunity.deadline}
        <span class={`font-medium ${getDeadlineUrgency(opportunity.deadline)}`}>
          {formatDeadline(opportunity.deadline)}
        </span>
      {/if}
    </div>
  {/if}
</a>
