// src/components/public-org/member-directory.svelte
<script lang="ts">
  import { useQuery } from 'convex-svelte'
  import { MapPin, Shield, Users } from 'lucide-svelte'
  import { api } from '$convex/_generated/api'
  import type { Id } from '$convex/_generated/dataModel'

  let { orgId }: { orgId: Id<'organizations'> } = $props()

  const members = useQuery(api.orgs.directory.getVisibleMembers, () => ({
    orgId,
  }))
</script>

{#if members.isLoading}
  <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
    {#each Array.from({ length: 3 }) as _, index (`loading-${index}`)}
      <div class="rounded-[1.5rem] border border-border/70 bg-white/88 p-4 shadow-warm-sm">
        <div class="mb-2 h-6 w-3/4 animate-pulse rounded bg-slate-100"></div>
        <div class="mb-4 h-4 w-1/2 animate-pulse rounded bg-slate-100"></div>
        <div class="flex gap-2">
          <div class="h-5 w-16 animate-pulse rounded-full bg-slate-100"></div>
          <div class="h-5 w-16 animate-pulse rounded-full bg-slate-100"></div>
        </div>
      </div>
    {/each}
  </div>
{:else if !members.data?.length}
  <div class="rounded-[1.75rem] border border-border/70 bg-white/88 px-6 py-10 text-center shadow-warm-sm">
    <div class="mx-auto mb-4 flex size-14 items-center justify-center rounded-full bg-slate-100 text-slate-400">
      <Users class="size-7" />
    </div>
    <h2 class="font-display text-2xl text-slate-950">No visible members yet</h2>
    <p class="mx-auto mt-3 max-w-md text-sm leading-6 text-slate-600">
      Members can choose whether to appear in the organization directory when
      they join.
    </p>
  </div>
{:else}
  <div class="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
    {#each members.data as member (member.membershipId)}
      <article class="rounded-[1.5rem] border border-border/70 bg-white/92 p-5 shadow-warm-sm transition hover:-translate-y-0.5 hover:shadow-warm-md">
        <div class="flex items-start justify-between gap-3">
          <div class="min-w-0">
            <h3 class="truncate text-base font-semibold text-slate-950">
              {member.profile.name}
            </h3>
            {#if member.profile.headline}
              <p class="mt-1 line-clamp-2 text-sm leading-6 text-slate-600">
                {member.profile.headline}
              </p>
            {/if}
          </div>

          {#if member.role === 'admin'}
            <span class="inline-flex shrink-0 items-center gap-1 rounded-full border border-coral-200 bg-coral-50 px-2.5 py-1 text-xs font-medium text-coral-700">
              <Shield class="size-3.5" />
              Admin
            </span>
          {/if}
        </div>

        {#if member.profile.location}
          <div class="mt-3 flex items-center gap-1.5 text-sm text-slate-500">
            <MapPin class="size-3.5 shrink-0" />
            <span class="truncate">{member.profile.location}</span>
          </div>
        {/if}

        {#if member.profile.skills.length > 0}
          <div class="mt-4 flex flex-wrap gap-2">
            {#each member.profile.skills as skill (skill)}
              <span class="rounded-full border border-slate-200 bg-slate-50 px-2.5 py-1 text-xs font-medium text-slate-600">
                {skill}
              </span>
            {/each}
          </div>
        {/if}
      </article>
    {/each}
  </div>
{/if}

// src/components/org/MemberDirectory.tsx
import { useQuery } from "convex/react";
import { MapPin, Shield, Users } from "lucide-react";
import { api } from "../../../convex/_generated/api";
import type { Id } from "../../../convex/_generated/dataModel";
import { Card } from "~/components/ui/card";
import { Badge } from "~/components/ui/badge";

interface MemberDirectoryProps {
  orgId: Id<"organizations">;
}

export function MemberDirectory({ orgId }: MemberDirectoryProps) {
  const members = useQuery(api.orgs.directory.getVisibleMembers, { orgId });

  if (members === undefined) {
    return (
      <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
        {[1, 2, 3].map((i) => (
          <Card key={i} className="p-4 animate-pulse">
            <div className="h-6 bg-slate-100 rounded w-3/4 mb-2" />
            <div className="h-4 bg-slate-100 rounded w-1/2 mb-4" />
            <div className="flex gap-2">
              <div className="h-5 bg-slate-100 rounded w-16" />
              <div className="h-5 bg-slate-100 rounded w-16" />
            </div>
          </Card>
        ))}
      </div>
    );
  }

  if (members.length === 0) {
    return (
      <Card className="p-8 text-center">
        <div className="size-12 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
          <Users className="size-6 text-slate-400" />
        </div>
        <h3 className="text-lg font-medium text-slate-900 mb-2">
          No visible members yet
        </h3>
        <p className="text-slate-500 text-sm">
          Members can choose to appear in the directory when they join.
        </p>
      </Card>
    );
  }

  return (
    <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">
      {members.map((member: Member) => (
        <MemberCard key={member.membershipId} member={member} />
      ))}
    </div>
  );
}

type Member = {
  membershipId: Id<"orgMemberships">;
  userId: string;
  role: "admin" | "member";
  profile: {
    name: string;
    headline?: string;
    skills: Array<string>;
    location?: string;
  };
};

interface MemberCardProps {
  member: Member;
}

function MemberCard({ member }: MemberCardProps) {
  return (
    <Card className="p-4 hover:shadow-md transition-shadow">
      <div className="flex items-start justify-between mb-2">
        <div>
          <h3 className="font-medium text-slate-900">{member.profile.name}</h3>
          {member.profile.headline && (
            <p className="text-sm text-slate-600 line-clamp-2">
              {member.profile.headline}
            </p>
          )}
        </div>
        {member.role === "admin" && (
          <Badge variant="secondary" className="shrink-0 ml-2">
            <Shield className="size-3 mr-1" />
            Admin
          </Badge>
        )}
      </div>

      {member.profile.location && (
        <div className="flex items-center gap-1 text-sm text-slate-500 mb-3">
          <MapPin className="size-3" />
          {member.profile.location}
        </div>
      )}

      {member.profile.skills.length > 0 && (
        <div className="flex flex-wrap gap-1">
          {member.profile.skills.map((skill) => (
            <Badge key={skill} variant="outline" className="text-xs">
              {skill}
            </Badge>
          ))}
        </div>
      )}
    </Card>
  );
}
