// src/components/org/OrgCard.tsx
import { Link, useNavigate } from '@tanstack/react-router'
import { Building2, Calendar, Check, MapPin, Users } from 'lucide-react'
import type { Id } from '../../../convex/_generated/dataModel'
import { Badge } from '~/components/ui/badge'
import { Card } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { cn } from '~/lib/utils'

export interface OrgCardProps {
  org: {
    _id: Id<'organizations'>
    name: string
    slug?: string
    logoUrl?: string
    description?: string
    city?: string
    country?: string
    memberCount?: number
    upcomingEventCount?: number
    isJoined?: boolean
  }
  variant?: 'carousel' | 'list'
}

export function OrgCard({ org, variant = 'carousel' }: OrgCardProps) {
  const location = [org.city, org.country].filter(Boolean).join(', ')
  const slug = org.slug ?? org._id
  const navigate = useNavigate()

  const handleNavigate = () => {
    navigate({ to: '/org/$slug', params: { slug } })
  }

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter' || e.key === ' ') {
      e.preventDefault()
      handleNavigate()
    }
  }

  return (
    <Card
      role="link"
      tabIndex={0}
      aria-label={org.name}
      onClick={handleNavigate}
      onKeyDown={handleKeyDown}
      className={cn(
        variant === 'carousel' ? 'w-72' : 'w-full',
        'p-4 flex flex-col cursor-pointer hover:shadow-md transition-shadow',
        'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2',
      )}
    >
      {/* Logo and name */}
      <div className="flex items-start gap-3 mb-3">
        {org.logoUrl ? (
          <img
            src={org.logoUrl}
            alt={`${org.name} logo`}
            className="size-12 rounded-lg object-cover shrink-0"
          />
        ) : (
          <div className="size-12 rounded-lg bg-slate-100 flex items-center justify-center shrink-0">
            <Building2 className="size-6 text-slate-400" />
          </div>
        )}
        <div className="min-w-0 flex-1">
          <div className="flex items-center gap-1.5">
            <h3 className="font-medium text-foreground truncate">{org.name}</h3>
            {org.isJoined && (
              <Badge
                variant="secondary"
                className="shrink-0 text-[10px] px-1.5 py-0 h-4 gap-0.5"
              >
                <Check className="size-2.5" />
                Joined
              </Badge>
            )}
          </div>
          {location && (
            <div className="flex items-center gap-1 text-sm text-slate-500 mt-0.5">
              <MapPin className="size-3 shrink-0" />
              <span className="truncate">{location}</span>
            </div>
          )}
        </div>
      </div>

      {/* Description */}
      {org.description && (
        <p className="text-sm text-slate-600 line-clamp-2 mb-3 flex-1">
          {org.description}
        </p>
      )}

      {/* Stats row */}
      <div className="flex items-center gap-4 text-sm text-slate-500 mb-4">
        {org.memberCount !== undefined && org.memberCount > 0 && (
          <div className="flex items-center gap-1">
            <Users className="size-3.5" />
            <span>
              {org.memberCount} {org.memberCount === 1 ? 'member' : 'members'}
            </span>
          </div>
        )}
        {org.upcomingEventCount !== undefined && org.upcomingEventCount > 0 && (
          <div className="flex items-center gap-1">
            <Calendar className="size-3.5" />
            <span>
              {org.upcomingEventCount} upcoming{' '}
              {org.upcomingEventCount === 1 ? 'event' : 'events'}
            </span>
          </div>
        )}
      </div>

      {/* Action button - not a separate tab stop since card handles navigation */}
      <Button
        asChild
        variant="outline"
        size="sm"
        className="w-full mt-auto"
        tabIndex={-1}
      >
        <Link to="/org/$slug" params={{ slug }} tabIndex={-1}>
          View Organization
        </Link>
      </Button>
    </Card>
  )
}

// src/components/org/OrgCard.svelte
<script lang="ts">
  import { Building2, Calendar, Check, MapPin, Users } from 'lucide-svelte'
  import { cn } from '~/lib/utils'
  import {
    type OrgDirectoryOrg,
    getOrgHref,
    getOrgLocation,
  } from './org-directory.types'

  let {
    org,
    variant = 'carousel',
    selected = false,
    onselect,
  }: {
    org: OrgDirectoryOrg
    variant?: 'carousel' | 'list'
    selected?: boolean
    onselect?: (org: OrgDirectoryOrg) => void
  } = $props()

  const location = $derived(getOrgLocation(org))
  const orgHref = $derived(getOrgHref(org))

  const selectOrg = () => {
    onselect?.(org)
  }
</script>

{#if variant === 'carousel'}
  <a
    href={orgHref}
    class={cn(
      'group flex w-72 flex-col rounded-[1.5rem] border border-border/70 bg-white/92 p-4 shadow-warm-sm transition-all duration-200 hover:-translate-y-0.5 hover:shadow-lg',
      selected && 'ring-2 ring-coral-400 ring-offset-2 ring-offset-background',
    )}
  >
    <div class="mb-3 flex items-start gap-3">
      {#if org.logoUrl}
        <img
          src={org.logoUrl}
          alt={`${org.name} logo`}
          class="size-12 rounded-2xl border border-border/60 object-cover shadow-sm"
        />
      {:else}
        <div
          class="flex size-12 items-center justify-center rounded-2xl border border-border/60 bg-slate-100 text-slate-400"
        >
          <Building2 class="size-6" />
        </div>
      {/if}

      <div class="min-w-0 flex-1">
        <div class="flex items-start gap-2">
          <h3 class="truncate text-base font-semibold text-slate-950">
            {org.name}
          </h3>
          {#if org.isJoined}
            <span
              class="inline-flex shrink-0 items-center gap-1 rounded-full bg-emerald-100 px-2 py-0.5 text-[11px] font-medium text-emerald-800"
            >
              <Check class="size-3" />
              Joined
            </span>
          {/if}
        </div>
        {#if location}
          <p class="mt-1 flex items-center gap-1 text-sm text-slate-500">
            <MapPin class="size-3.5 shrink-0" />
            <span class="truncate">{location}</span>
          </p>
        {/if}
      </div>
    </div>

    {#if org.description}
      <p class="mb-4 line-clamp-3 text-sm leading-6 text-slate-600">
        {org.description}
      </p>
    {/if}

    <div class="mt-auto flex flex-wrap gap-3 text-sm text-slate-500">
      {#if org.memberCount}
        <span class="inline-flex items-center gap-1.5">
          <Users class="size-3.5" />
          {org.memberCount} {org.memberCount === 1 ? 'member' : 'members'}
        </span>
      {/if}
      {#if org.upcomingEventCount}
        <span class="inline-flex items-center gap-1.5">
          <Calendar class="size-3.5" />
          {org.upcomingEventCount} upcoming {org.upcomingEventCount === 1
            ? 'event'
            : 'events'}
        </span>
      {/if}
    </div>

    <span
      class="mt-4 inline-flex w-full items-center justify-center rounded-xl border border-border/70 px-3 py-2 text-sm font-medium text-slate-800 transition-colors group-hover:border-coral-300 group-hover:bg-coral-50 group-hover:text-coral-800"
    >
      View organization
    </span>
  </a>
{:else}
  <article
    class={cn(
      'rounded-[1.5rem] border bg-white/92 p-4 shadow-warm-sm transition-all duration-200',
      selected
        ? 'border-coral-300 ring-2 ring-coral-300/80 ring-offset-2 ring-offset-background'
        : 'border-border/70 hover:border-coral-200 hover:shadow-md',
    )}
  >
    <button
      type="button"
      class={cn(
        'block w-full text-left',
        onselect &&
          'cursor-pointer rounded-[1rem] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-coral-300/80',
      )}
      aria-pressed={onselect ? selected : undefined}
      onclick={onselect ? selectOrg : undefined}
    >
      <div class="flex items-start gap-3">
        {#if org.logoUrl}
          <img
            src={org.logoUrl}
            alt={`${org.name} logo`}
            class="size-14 rounded-2xl border border-border/60 object-cover shadow-sm"
          />
        {:else}
          <div
            class="flex size-14 items-center justify-center rounded-2xl border border-border/60 bg-slate-100 text-slate-400"
          >
            <Building2 class="size-7" />
          </div>
        {/if}

        <div class="min-w-0 flex-1">
          <div class="flex flex-wrap items-center gap-2">
            <h3 class="min-w-0 flex-1 truncate text-lg font-semibold text-slate-950">
              {org.name}
            </h3>
            {#if org.isJoined}
              <span
                class="inline-flex items-center gap-1 rounded-full bg-emerald-100 px-2 py-0.5 text-[11px] font-medium text-emerald-800"
              >
                <Check class="size-3" />
                Joined
              </span>
            {/if}
          </div>

          {#if location}
            <p class="mt-1 flex items-center gap-1 text-sm text-slate-500">
              <MapPin class="size-3.5 shrink-0" />
              <span class="truncate">{location}</span>
            </p>
          {/if}
        </div>
      </div>

      {#if org.description}
        <p class="mt-4 line-clamp-3 text-sm leading-6 text-slate-600">
          {org.description}
        </p>
      {/if}
    </button>

    <div class="mt-4 flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
      <div class="flex flex-wrap gap-3 text-sm text-slate-500">
        {#if org.memberCount}
          <span class="inline-flex items-center gap-1.5">
            <Users class="size-3.5" />
            {org.memberCount} {org.memberCount === 1 ? 'member' : 'members'}
          </span>
        {/if}
        {#if org.upcomingEventCount}
          <span class="inline-flex items-center gap-1.5">
            <Calendar class="size-3.5" />
            {org.upcomingEventCount} upcoming {org.upcomingEventCount === 1
              ? 'event'
              : 'events'}
          </span>
        {/if}
      </div>

      <a
        href={orgHref}
        class="inline-flex items-center justify-center rounded-xl border border-border/70 px-3 py-2 text-sm font-medium text-slate-800 transition-colors hover:border-coral-300 hover:bg-coral-50 hover:text-coral-800"
        onclick={(event) => event.stopPropagation()}
      >
        View organization
      </a>
    </div>
  </article>
{/if}
