// src/components/org/OrgFilters.svelte
<script lang="ts">
  import { useQuery } from 'convex-svelte'
  import { MapPin, Search, X } from 'lucide-svelte'
  import { api } from '$convex/_generated/api'

  let {
    searchQuery,
    onSearchChange,
    country,
    onCountryChange,
  }: {
    searchQuery: string
    onSearchChange: (value: string) => void
    country?: string
    onCountryChange: (value: string | undefined) => void
  } = $props()

  const countries = useQuery(api.orgs.discovery.getOrgCountries, () => ({}))
  const hasFilters = $derived(Boolean(searchQuery || country))
</script>

<div class="mb-6 flex flex-col gap-3 lg:flex-row lg:items-center">
  <label
    class="flex min-w-0 flex-1 items-center gap-3 rounded-2xl border border-border/70 bg-white/90 px-4 py-3 shadow-warm-sm"
  >
    <Search class="size-4 shrink-0 text-slate-400" />
    <input
      type="text"
      value={searchQuery}
      placeholder="Search organizations..."
      class="min-w-0 flex-1 bg-transparent text-sm text-slate-900 outline-none placeholder:text-slate-400"
      oninput={(event) =>
        onSearchChange((event.currentTarget as HTMLInputElement).value)}
    />
  </label>

  <label
    class="flex items-center gap-3 rounded-2xl border border-border/70 bg-white/90 px-4 py-3 shadow-warm-sm lg:w-60"
  >
    <MapPin class="size-4 shrink-0 text-slate-400" />
    <select
      class="min-w-0 flex-1 bg-transparent text-sm text-slate-900 outline-none"
      value={country ?? ''}
      onchange={(event) => {
        const value = (event.currentTarget as HTMLSelectElement).value
        onCountryChange(value || undefined)
      }}
    >
      <option value="">All countries</option>
      {#each countries.data ?? [] as item}
        <option value={item}>{item}</option>
      {/each}
    </select>
  </label>

  {#if hasFilters}
    <button
      type="button"
      class="inline-flex h-12 items-center justify-center gap-2 rounded-2xl border border-border/70 bg-white/90 px-4 text-sm font-medium text-slate-700 shadow-warm-sm transition-colors hover:border-coral-300 hover:bg-coral-50 hover:text-coral-800"
      onclick={() => {
        onSearchChange('')
        onCountryChange(undefined)
      }}
    >
      <X class="size-4" />
      Clear
    </button>
  {/if}
</div>

// src/components/org/OrgFilters.tsx
import { useQuery } from 'convex/react'
import { MapPin, Search, X } from 'lucide-react'
import { api } from '../../../convex/_generated/api'
import {
  InputGroup,
  InputGroupAddon,
  InputGroupInput,
} from '~/components/ui/input-group'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '~/components/ui/select'
import { Button } from '~/components/ui/button'

interface OrgFiltersProps {
  searchQuery: string
  onSearchChange: (value: string) => void
  country: string | undefined
  onCountryChange: (value: string | undefined) => void
}

export function OrgFilters({
  searchQuery,
  onSearchChange,
  country,
  onCountryChange,
}: OrgFiltersProps) {
  const countries = useQuery(api.orgs.discovery.getOrgCountries)

  const hasFilters = searchQuery || country

  const clearFilters = () => {
    onSearchChange('')
    onCountryChange(undefined)
  }

  return (
    <div className="flex flex-col sm:flex-row gap-3 mb-4">
      {/* Search input */}
      <InputGroup className="flex-1">
        <InputGroupAddon>
          <Search />
        </InputGroupAddon>
        <InputGroupInput
          type="text"
          placeholder="Search organizations..."
          value={searchQuery}
          onChange={(e) => onSearchChange(e.target.value)}
        />
      </InputGroup>

      {/* Country filter */}
      <Select
        value={country ?? 'all'}
        onValueChange={(val) =>
          onCountryChange(val === 'all' ? undefined : val)
        }
      >
        <SelectTrigger className="w-full sm:w-48">
          <MapPin className="size-4 mr-2 text-slate-400" />
          <SelectValue placeholder="All countries" />
        </SelectTrigger>
        <SelectContent>
          <SelectItem value="all">All countries</SelectItem>
          {countries?.map((c) => (
            <SelectItem key={c} value={c}>
              {c}
            </SelectItem>
          ))}
        </SelectContent>
      </Select>

      {/* Clear filters button */}
      {hasFilters && (
        <Button variant="ghost" size="icon" onClick={clearFilters}>
          <X className="size-4" />
        </Button>
      )}
    </div>
  )
}
