// src/components/layout/public-header.tsx
import { Link } from "@tanstack/react-router";
import { Button } from "~/components/ui/button";

export function PublicHeader() {
  return (
    <header className="border-b bg-white">
      <div className="container mx-auto px-4 py-4 flex items-center justify-between">
        <Link to="/" className="font-semibold text-foreground font-mono">
          AI Safety Talent Network
        </Link>
        <nav className="flex items-center gap-4">
          <Link
            to="/opportunities"
            className="text-sm text-slate-600 hover:text-foreground [&.active]:text-foreground [&.active]:font-medium"
          >
            Opportunities
          </Link>
          <Button size="sm" variant="outline" asChild>
            <Link to="/admin">Admin</Link>
          </Button>
        </nav>
      </div>
    </header>
  );
}

// src/components/layout/public-header.svelte
<header class="border-b bg-white/90 backdrop-blur">
  <div
    class="container mx-auto flex items-center justify-between px-4 py-4"
  >
    <a href="/" class="font-mono font-semibold text-foreground">
      AI Safety Talent Network
    </a>
    <nav class="flex items-center gap-4">
      <a
        href="/opportunities"
        class="text-sm text-slate-600 transition-colors hover:text-foreground"
      >
        Opportunities
      </a>
      <a
        href="/orgs"
        class="text-sm text-slate-600 transition-colors hover:text-foreground"
      >
        Organizations
      </a>
      <a
        href="/login"
        class="rounded-md border border-slate-300 px-3 py-1.5 text-sm font-medium text-foreground transition-colors hover:bg-slate-50"
      >
        Sign In
      </a>
    </nav>
  </div>
</header>
