// src/routes/org/$slug/admin/opportunities/index.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { useQuery } from 'convex/react'
import { useState } from 'react'
import { toast } from 'sonner'
import {
  Building2,
  FileText,
  Link2,
  Pencil,
  Plus,
  Shield,
  Star,
} from 'lucide-react'
import { api } from '../../../../../../convex/_generated/api'
import { OpportunityFormDialog } from '~/components/opportunities/OpportunityFormDialog'
import { AuthHeader } from '~/components/layout/auth-header'
import { Card } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Badge } from '~/components/ui/badge'
import { Spinner } from '~/components/ui/spinner'
import { useDotGridStyle } from '~/hooks/use-dot-grid-style'

export const Route = createFileRoute('/org/$slug/admin/opportunities/')({
  component: AdminOpportunitiesPage,
})

const STATUS_COLORS: Record<string, string> = {
  active: 'bg-green-50 text-green-700 border-green-200',
  closed: 'bg-slate-50 text-slate-600 border-slate-200',
  draft: 'bg-yellow-50 text-yellow-700 border-yellow-200',
}

const TYPE_LABELS: Record<string, string> = {
  course: 'Course',
  fellowship: 'Fellowship',
  job: 'Job',
  other: 'Other',
}

function AdminOpportunitiesPage() {
  const { slug } = Route.useParams()
  const dotGridStyle = useDotGridStyle()

  const org = useQuery(api.orgs.directory.getOrgBySlug, { slug })
  const membership = useQuery(
    api.orgs.membership.getMembership,
    org ? { orgId: org._id } : 'skip',
  )
  const opportunities = useQuery(
    api.orgOpportunities.listAllByOrg,
    org && membership?.role === 'admin' ? { orgId: org._id } : 'skip',
  )

  const [dialogOpen, setDialogOpen] = useState(false)

  // Loading
  if (org === undefined || membership === undefined) {
    return (
      <div className="min-h-screen" style={dotGridStyle}>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-5xl mx-auto">
            <Spinner className="size-8 mx-auto" />
          </div>
        </main>
      </div>
    )
  }

  if (!org) {
    return (
      <div className="min-h-screen" style={dotGridStyle}>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <Building2 className="size-8 text-slate-400 mx-auto mb-4" />
            <h1 className="text-2xl font-display mb-4">
              Organization Not Found
            </h1>
          </div>
        </main>
      </div>
    )
  }

  if (!membership || membership.role !== 'admin') {
    return (
      <div className="min-h-screen" style={dotGridStyle}>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <Shield className="size-8 text-slate-400 mx-auto mb-4" />
            <h1 className="text-2xl font-display mb-4">
              Admin Access Required
            </h1>
            <Button asChild>
              <Link to="/org/$slug" params={{ slug }}>
                Back to Organization
              </Link>
            </Button>
          </div>
        </main>
      </div>
    )
  }

  return (
    <div className="min-h-screen" style={dotGridStyle}>
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-5xl mx-auto">
          {/* Breadcrumb */}
          <div className="flex items-center gap-2 text-muted-foreground text-sm mb-2">
            <Link
              to="/org/$slug/admin"
              params={{ slug }}
              className="hover:text-slate-700 transition-colors"
            >
              Admin
            </Link>
            <span>/</span>
            <span className="text-slate-700">Opportunities</span>
          </div>

          <div className="flex items-center justify-between mb-8">
            <div>
              <h1 className="text-2xl font-display font-semibold text-foreground">
                Opportunities
              </h1>
              <p className="text-muted-foreground mt-1">
                Manage your organization&apos;s opportunities and application
                forms
              </p>
            </div>
            <Button onClick={() => setDialogOpen(true)}>
              <Plus className="size-4 mr-2" />
              New Opportunity
            </Button>
          </div>

          {/* List */}
          {opportunities === undefined ? (
            <div className="py-12 text-center">
              <Spinner className="size-8 mx-auto" />
            </div>
          ) : opportunities.length === 0 ? (
            <Card className="p-8 text-center">
              <FileText className="size-8 text-slate-400 mx-auto mb-4" />
              <p className="text-muted-foreground mb-4">
                No opportunities yet. Create one to start receiving
                applications.
              </p>
              <Button onClick={() => setDialogOpen(true)}>
                <Plus className="size-4 mr-2" />
                Create First Opportunity
              </Button>
            </Card>
          ) : (
            <div className="space-y-3">
              {opportunities.map((opp) => {
                const fieldCount = Array.isArray(opp.formFields)
                  ? (opp.formFields as Array<unknown>).length
                  : 0
                return (
                  <Card key={opp._id} className="px-4 py-3">
                    <div className="flex items-center gap-3">
                      <div className="flex-1 min-w-0">
                        <div className="flex items-center gap-2">
                          <span className="font-medium text-sm truncate">
                            {opp.title}
                          </span>
                          {opp.featured && (
                            <Star className="size-3.5 text-amber-500 fill-amber-500 shrink-0" />
                          )}
                        </div>
                        <div className="flex items-center gap-2 mt-1 text-xs text-muted-foreground">
                          <span>{TYPE_LABELS[opp.type] ?? opp.type}</span>
                          <span className="text-slate-300">|</span>
                          <span>
                            {fieldCount} form field
                            {fieldCount !== 1 ? 's' : ''}
                          </span>
                          {opp.deadline && (
                            <>
                              <span className="text-slate-300">|</span>
                              <span>
                                Deadline:{' '}
                                {new Date(opp.deadline).toLocaleDateString()}
                              </span>
                            </>
                          )}
                        </div>
                      </div>

                      <Badge
                        variant="outline"
                        className={STATUS_COLORS[opp.status] ?? ''}
                      >
                        {opp.status}
                      </Badge>

                      <Button
                        variant="ghost"
                        size="sm"
                        title="Copy application link"
                        onClick={async () => {
                          const url = `${window.location.origin}/org/${slug}/apply/${opp._id}`
                          try {
                            await navigator.clipboard.writeText(url)
                            toast.success('Application link copied')
                          } catch {
                            toast.error('Failed to copy link')
                          }
                        }}
                      >
                        <Link2 className="size-4" />
                      </Button>

                      <Button variant="ghost" size="sm" asChild>
                        <Link
                          to="/org/$slug/admin/opportunities/$oppId"
                          params={{ slug, oppId: opp._id }}
                        >
                          <Pencil className="size-4" />
                        </Link>
                      </Button>
                    </div>
                  </Card>
                )
              })}
            </div>
          )}

          {/* Create dialog */}
          <OpportunityFormDialog
            open={dialogOpen}
            onOpenChange={setDialogOpen}
            orgId={org._id}
            slug={slug}
          />
        </div>
      </main>
    </div>
  )
}

// src/routes/(app)/org/[slug]/admin/opportunities/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import { Link2 } from 'lucide-svelte'
  import { api } from '$convex/_generated/api'

  const convex = useConvexClient()
  const slug = $derived(page.params.slug ?? null)

  const org = useQuery(api.orgs.directory.getOrgBySlug, () => (slug ? { slug } : 'skip'))
  const membership = useQuery(api.orgs.membership.getMembership, () =>
    org.data ? { orgId: org.data._id } : 'skip',
  )
  const opportunities = useQuery(api.orgOpportunities.listAllByOrg, () =>
    org.data && membership.data?.role === 'admin' ? { orgId: org.data._id } : 'skip',
  )

  let title = $state('')
  let description = $state('')
  let type = $state<'job' | 'course' | 'fellowship' | 'other'>('job')
  let status = $state<'active' | 'closed' | 'draft'>('draft')
  let deadline = $state('')
  let externalUrl = $state('')
  let featured = $state(false)
  let creating = $state(false)

  const createOpportunity = async () => {
    if (!org.data) return
    creating = true
    try {
      await convex.mutation(api.orgOpportunities.create, {
        orgId: org.data._id,
        title: title.trim(),
        description: description.trim(),
        type,
        status,
        deadline: deadline ? new Date(`${deadline}T00:00:00`).getTime() : undefined,
        externalUrl: externalUrl.trim() || undefined,
        featured,
      })
      title = ''
      description = ''
      deadline = ''
      externalUrl = ''
      featured = false
      status = 'draft'
      type = 'job'
      toast.success('Opportunity created')
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to create opportunity')
    } finally {
      creating = false
    }
  }
</script>

<div class="space-y-6">
  <section class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-6 shadow-warm-sm">
    <h1 class="font-display text-3xl text-slate-950">Org opportunities</h1>
    <p class="mt-3 text-sm leading-6 text-slate-600">Create and manage the opportunities attached to this organization.</p>
  </section>

  <section class="rounded-[1.75rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
    <h2 class="text-lg font-semibold text-slate-950">Create opportunity</h2>
    <div class="mt-4 grid gap-4 md:grid-cols-2">
      <input bind:value={title} class="rounded-2xl border border-border px-4 py-3 text-sm" placeholder="Title" />
      <input bind:value={externalUrl} class="rounded-2xl border border-border px-4 py-3 text-sm" placeholder="External URL" />
      <select bind:value={type} class="rounded-2xl border border-border px-4 py-3 text-sm">
        <option value="job">Job</option>
        <option value="course">Course</option>
        <option value="fellowship">Fellowship</option>
        <option value="other">Other</option>
      </select>
      <select bind:value={status} class="rounded-2xl border border-border px-4 py-3 text-sm">
        <option value="draft">Draft</option>
        <option value="active">Active</option>
        <option value="closed">Closed</option>
      </select>
      <input bind:value={deadline} type="date" class="rounded-2xl border border-border px-4 py-3 text-sm" />
      <label class="flex items-center gap-3 rounded-2xl border border-border px-4 py-3 text-sm text-slate-700">
        <input bind:checked={featured} type="checkbox" class="size-4" />
        <span>Featured opportunity</span>
      </label>
    </div>
    <textarea bind:value={description} rows="6" class="mt-4 w-full rounded-2xl border border-border px-4 py-3 text-sm" placeholder="Description"></textarea>
    <button type="button" class="mt-4 rounded-full bg-slate-950 px-4 py-2 text-sm font-medium text-white disabled:opacity-60" disabled={creating || !title.trim()} onclick={createOpportunity}>
      Create
    </button>
  </section>

  <div class="space-y-3">
    {#each opportunities.data ?? [] as opportunity (opportunity._id)}
      <article class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-4 shadow-warm-sm">
        <div class="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div class="flex items-center gap-2">
              <h2 class="text-lg font-semibold text-slate-950">{opportunity.title}</h2>
              <span class="rounded-full border border-border px-3 py-1 text-xs font-medium text-slate-600">{opportunity.status}</span>
            </div>
            <p class="mt-2 text-sm text-slate-600">{opportunity.description}</p>
          </div>
          <div class="flex gap-2">
            <button
              type="button"
              class="flex items-center gap-1.5 rounded-full border border-border px-3 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
              title="Copy application link"
              onclick={async () => {
                const url = `${window.location.origin}/org/${slug}/apply/${opportunity._id}`
                try {
                  await navigator.clipboard.writeText(url)
                  toast.success('Application link copied')
                } catch {
                  toast.error('Failed to copy link')
                }
              }}
            >
              <Link2 class="size-4" />
              Copy link
            </button>
            <a href={`/org/${slug}/admin/opportunities/${opportunity._id}`} class="rounded-full border border-border px-4 py-2 text-sm font-medium text-slate-700">Manage</a>
            <a href={`/org/${slug}/admin/opportunities/${opportunity._id}/email`} class="rounded-full border border-border px-4 py-2 text-sm font-medium text-slate-700">Email</a>
          </div>
        </div>
      </article>
    {/each}
  </div>
</div>
