// src/components/opportunities/DynamicFormRenderer.tsx
import type { FormField } from '../../../convex/lib/formFields'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'
import { Textarea } from '~/components/ui/textarea'
import { Checkbox } from '~/components/ui/checkbox'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '~/components/ui/select'

interface DynamicFormRendererProps {
  formFields: Array<FormField>
  responses: Record<string, unknown>
  onChange: (key: string, value: unknown) => void
}

export function DynamicFormRenderer({
  formFields,
  responses,
  onChange,
}: DynamicFormRendererProps) {
  // Group fields into sections. Each section_header starts a new card.
  // Fields before the first section_header go into an untitled card.
  const sections: Array<{
    title?: string
    description?: string
    fields: Array<FormField>
  }> = []
  let current: {
    title?: string
    description?: string
    fields: Array<FormField>
  } = {
    fields: [],
  }

  for (const field of formFields) {
    if (field.kind === 'section_header') {
      if (current.fields.length > 0 || current.title) {
        sections.push(current)
      }
      current = {
        title: field.label,
        description: field.description,
        fields: [],
      }
    } else {
      current.fields.push(field)
    }
  }
  if (current.fields.length > 0 || current.title) {
    sections.push(current)
  }

  return (
    <div className="space-y-6">
      {sections.map((section, sIdx) => (
        <Card key={sIdx}>
          {section.title && (
            <CardHeader>
              <CardTitle>{section.title}</CardTitle>
              {section.description && (
                <p className="text-sm text-muted-foreground">
                  {section.description}
                </p>
              )}
            </CardHeader>
          )}
          <CardContent
            className={section.title ? 'space-y-4' : 'space-y-4 pt-6'}
          >
            {section.fields.map((field) => (
              <FieldRenderer
                key={field.key}
                field={field}
                value={responses[field.key]}
                onChange={(val) => onChange(field.key, val)}
              />
            ))}
          </CardContent>
        </Card>
      ))}
    </div>
  )
}

function FieldRenderer({
  field,
  value,
  onChange,
}: {
  field: FormField
  value: unknown
  onChange: (val: unknown) => void
}) {
  switch (field.kind) {
    case 'text':
    case 'email':
    case 'url':
      return (
        <div className="space-y-2">
          <Label htmlFor={field.key}>
            {field.label}
            {field.required && <span className="text-red-500"> *</span>}
          </Label>
          {field.description && (
            <p className="text-xs text-muted-foreground">{field.description}</p>
          )}
          <Input
            id={field.key}
            type={field.kind}
            value={
              typeof value === 'string'
                ? value
                : typeof value === 'number'
                  ? String(value)
                  : ''
            }
            onChange={(e) => onChange(e.target.value)}
            placeholder={field.placeholder}
          />
        </div>
      )

    case 'textarea':
      return (
        <div className="space-y-2">
          <Label htmlFor={field.key}>
            {field.label}
            {field.required && <span className="text-red-500"> *</span>}
          </Label>
          {field.description && (
            <p className="text-xs text-muted-foreground">{field.description}</p>
          )}
          <Textarea
            id={field.key}
            value={
              typeof value === 'string'
                ? value
                : typeof value === 'number'
                  ? String(value)
                  : ''
            }
            onChange={(e) => onChange(e.target.value)}
            placeholder={field.placeholder}
            rows={field.rows ?? 4}
          />
        </div>
      )

    case 'select':
      return (
        <div className="space-y-2">
          <Label>
            {field.label}
            {field.required && <span className="text-red-500"> *</span>}
          </Label>
          {field.description && (
            <p className="text-xs text-muted-foreground">{field.description}</p>
          )}
          <Select
            value={
              typeof value === 'string'
                ? value
                : typeof value === 'number'
                  ? String(value)
                  : ''
            }
            onValueChange={(val) => onChange(val)}
          >
            <SelectTrigger>
              <SelectValue placeholder={field.placeholder ?? 'Select...'} />
            </SelectTrigger>
            <SelectContent>
              {(field.options ?? []).map((opt) => (
                <SelectItem key={opt} value={opt}>
                  {opt}
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>
      )

    case 'multi_select':
      return (
        <MultiSelectField field={field} value={value} onChange={onChange} />
      )

    case 'checkbox':
      return (
        <div className="space-y-2">
          {field.description && (
            <div className="space-y-1">
              <Label>{field.label}</Label>
              <p className="text-xs text-muted-foreground">
                {field.description}
              </p>
            </div>
          )}
          <label className="flex items-start gap-2 cursor-pointer">
            <Checkbox
              checked={value === true}
              onCheckedChange={(checked) => onChange(checked === true)}
              className="mt-0.5"
            />
            <span className="text-sm">
              {field.description ? `Yes` : field.label}
            </span>
          </label>
        </div>
      )

    case 'radio':
      return (
        <div className="space-y-2">
          <Label>
            {field.label}
            {field.required && <span className="text-red-500"> *</span>}
          </Label>
          {field.description && (
            <p className="text-xs text-muted-foreground">{field.description}</p>
          )}
          <div className="flex gap-4">
            {(field.options ?? ['Yes', 'No']).map((opt) => (
              <label
                key={opt}
                className="flex items-center gap-2 cursor-pointer"
              >
                <input
                  type="radio"
                  name={field.key}
                  checked={
                    opt === 'Yes'
                      ? value === true
                      : opt === 'No'
                        ? value === false
                        : value === opt
                  }
                  onChange={() => {
                    if (opt === 'Yes') onChange(true)
                    else if (opt === 'No') onChange(false)
                    else onChange(opt)
                  }}
                  className="size-4 accent-primary"
                />
                <span className="text-sm">{opt}</span>
              </label>
            ))}
          </div>
        </div>
      )

    case 'rating': {
      const labels =
        field.options?.length === 5 ? field.options : ['1', '2', '3', '4', '5']
      const current = typeof value === 'number' ? value : null
      return (
        <div className="space-y-2">
          <Label>
            {field.label}
            {field.required && <span className="text-red-500"> *</span>}
          </Label>
          {field.description && (
            <p className="text-xs text-muted-foreground">{field.description}</p>
          )}
          <div className="flex gap-2">
            {labels.map((label, i) => {
              const score = i + 1
              const isSelected = current === score
              return (
                <button
                  key={score}
                  type="button"
                  onClick={() => onChange(score)}
                  className={`flex-1 py-2 px-3 rounded-md border text-sm font-medium transition-colors ${
                    isSelected
                      ? 'bg-primary text-primary-foreground border-primary'
                      : 'border-slate-200 text-slate-600 hover:border-primary hover:text-primary'
                  }`}
                >
                  {label}
                </button>
              )
            })}
          </div>
        </div>
      )
    }

    case 'nps': {
      const current = typeof value === 'number' ? value : null
      return (
        <div className="space-y-2">
          <Label>
            {field.label}
            {field.required && <span className="text-red-500"> *</span>}
          </Label>
          {field.description && (
            <p className="text-xs text-muted-foreground">{field.description}</p>
          )}
          <div className="flex gap-1">
            {Array.from({ length: 11 }, (_, i) => {
              const isSelected = current === i
              const bg = isSelected
                ? i <= 6
                  ? 'bg-red-500 text-white border-red-500'
                  : i <= 8
                    ? 'bg-yellow-500 text-white border-yellow-500'
                    : 'bg-green-500 text-white border-green-500'
                : 'border-slate-200 text-slate-600 hover:border-slate-400'
              return (
                <button
                  key={i}
                  type="button"
                  onClick={() => onChange(i)}
                  className={`flex-1 py-2 rounded-md border text-sm font-medium transition-colors ${bg}`}
                >
                  {i}
                </button>
              )
            })}
          </div>
          <div className="flex justify-between text-xs text-muted-foreground">
            <span>Not at all likely</span>
            <span>Extremely likely</span>
          </div>
        </div>
      )
    }

    default:
      return null
  }
}

function MultiSelectField({
  field,
  value,
  onChange,
}: {
  field: FormField
  value: unknown
  onChange: (val: unknown) => void
}) {
  const selected = Array.isArray(value) ? (value as Array<string>) : []
  const max = field.maxSelections ?? Infinity

  const toggle = (opt: string) => {
    if (selected.includes(opt)) {
      onChange(selected.filter((v) => v !== opt))
    } else if (selected.length < max) {
      onChange([...selected, opt])
    }
  }

  return (
    <div className="space-y-2">
      <Label>
        {field.label}
        {field.required && <span className="text-red-500"> *</span>}
      </Label>
      {field.description && (
        <p className="text-xs text-muted-foreground">{field.description}</p>
      )}
      <div className="flex flex-wrap gap-2">
        {(field.options ?? []).map((opt) => {
          const isSelected = selected.includes(opt)
          const isDisabled = !isSelected && selected.length >= max
          return (
            <button
              key={opt}
              type="button"
              onClick={() => toggle(opt)}
              disabled={isDisabled}
              className={`px-3 py-1 rounded-full text-xs border transition-colors ${
                isSelected
                  ? 'bg-primary text-primary-foreground border-primary'
                  : isDisabled
                    ? 'opacity-40 cursor-not-allowed border-slate-200 text-slate-400'
                    : 'border-slate-300 text-slate-600 hover:border-primary hover:text-primary'
              }`}
            >
              {opt}
            </button>
          )
        })}
      </div>
    </div>
  )
}

// src/components/public-org/DynamicFormRenderer.svelte
<script lang="ts">
  import type { FormField } from '$convex/lib/formFields'
  import { cn } from '~/lib/utils'

  let {
    formFields,
    responses,
    onChange,
  }: {
    formFields: Array<FormField>
    responses: Record<string, unknown>
    onChange: (key: string, value: unknown) => void
  } = $props()

  const sections = $derived.by(() => {
    const values: Array<{
      title?: string
      description?: string
      fields: Array<FormField>
    }> = []

    let current: { title?: string; description?: string; fields: Array<FormField> } = {
      fields: [],
    }

    for (const field of formFields) {
      if (field.kind === 'section_header') {
        if (current.fields.length > 0 || current.title) {
          values.push(current)
        }
        current = {
          title: field.label,
          description: field.description,
          fields: [],
        }
      } else {
        current.fields.push(field)
      }
    }

    if (current.fields.length > 0 || current.title) {
      values.push(current)
    }

    return values
  })

  const selectedValues = (value: unknown) =>
    Array.isArray(value) ? (value as Array<string>) : []
</script>

<div class="space-y-6">
  {#each sections as section, sectionIndex (`section-${sectionIndex}`)}
    <section class="rounded-[1.5rem] border border-border/70 bg-white/92 p-5 shadow-warm-sm">
      {#if section.title}
        <header class="mb-4">
          <h2 class="text-lg font-semibold text-slate-950">{section.title}</h2>
          {#if section.description}
            <p class="mt-1 text-sm text-slate-600">{section.description}</p>
          {/if}
        </header>
      {/if}

      <div class="space-y-4">
        {#each section.fields as field (field.key)}
          <div class="space-y-2">
            {#if field.kind !== 'checkbox'}
              <label class="block text-sm font-medium text-slate-800" for={field.key}>
                {field.label}
                {#if field.required}
                  <span class="text-rose-500"> *</span>
                {/if}
              </label>
            {/if}

            {#if field.description}
              <p class="text-xs text-slate-500">{field.description}</p>
            {/if}

            {#if field.kind === 'text' || field.kind === 'email' || field.kind === 'url'}
              <input
                id={field.key}
                type={field.kind}
                value={typeof responses[field.key] === 'string' ? String(responses[field.key]) : ''}
                class="h-10 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
                placeholder={field.placeholder}
                oninput={(event) => onChange(field.key, (event.currentTarget as HTMLInputElement).value)}
              />
            {:else if field.kind === 'textarea'}
              <textarea
                id={field.key}
                rows={field.rows ?? 4}
                class="min-h-28 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
                placeholder={field.placeholder}
                oninput={(event) => onChange(field.key, (event.currentTarget as HTMLTextAreaElement).value)}
              >{typeof responses[field.key] === 'string' ? String(responses[field.key]) : ''}</textarea>
            {:else if field.kind === 'select'}
              <select
                id={field.key}
                class="h-10 w-full rounded-xl border border-input bg-background px-3 py-2 text-sm outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
                value={typeof responses[field.key] === 'string' ? String(responses[field.key]) : ''}
                onchange={(event) => onChange(field.key, (event.currentTarget as HTMLSelectElement).value)}
              >
                <option value="">{field.placeholder ?? 'Select...'}</option>
                {#each field.options ?? [] as option}
                  <option value={option}>{option}</option>
                {/each}
              </select>
            {:else if field.kind === 'multi_select'}
              {@const current = selectedValues(responses[field.key])}
              <div class="flex flex-wrap gap-2">
                {#each field.options ?? [] as option}
                  {@const isSelected = current.includes(option)}
                  {@const isDisabled = !isSelected && current.length >= (field.maxSelections ?? Infinity)}
                  <button
                    type="button"
                    class={cn(
                      'rounded-full border px-3 py-1.5 text-xs font-medium transition',
                      isSelected
                        ? 'border-coral-500 bg-coral-500 text-white'
                        : isDisabled
                          ? 'cursor-not-allowed border-slate-200 text-slate-400 opacity-50'
                          : 'border-slate-300 text-slate-600 hover:border-coral-300 hover:text-coral-700',
                    )}
                    disabled={isDisabled}
                    onclick={() => {
                      if (isSelected) {
                        onChange(
                          field.key,
                          current.filter((value) => value !== option),
                        )
                      } else {
                        onChange(field.key, [...current, option])
                      }
                    }}
                  >
                    {option}
                  </button>
                {/each}
              </div>
            {:else if field.kind === 'checkbox'}
              <label class="flex items-start gap-3 rounded-xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-700">
                <input
                  id={field.key}
                  type="checkbox"
                  checked={responses[field.key] === true}
                  class="mt-0.5 size-4 accent-coral-500"
                  onchange={(event) => onChange(field.key, (event.currentTarget as HTMLInputElement).checked)}
                />
                <span>
                  {field.label}
                  {#if field.required}
                    <span class="text-rose-500"> *</span>
                  {/if}
                </span>
              </label>
            {:else if field.kind === 'radio'}
              <div class="flex flex-wrap gap-3">
                {#each field.options ?? ['Yes', 'No'] as option}
                  <label class="flex items-center gap-2 text-sm text-slate-700">
                    <input
                      type="radio"
                      name={field.key}
                      checked={responses[field.key] === option || (option === 'Yes' && responses[field.key] === true) || (option === 'No' && responses[field.key] === false)}
                      class="size-4 accent-coral-500"
                      onchange={() => {
                        if (option === 'Yes') onChange(field.key, true)
                        else if (option === 'No') onChange(field.key, false)
                        else onChange(field.key, option)
                      }}
                    />
                    <span>{option}</span>
                  </label>
                {/each}
              </div>
            {:else if field.kind === 'rating'}
              <div class="flex flex-wrap gap-2">
                {#each field.options?.length === 5 ? field.options : ['1', '2', '3', '4', '5'] as option, index}
                  {@const score = index + 1}
                  <button
                    type="button"
                    class={cn(
                      'rounded-lg border px-3 py-2 text-sm font-medium transition',
                      responses[field.key] === score
                        ? 'border-coral-500 bg-coral-500 text-white'
                        : 'border-slate-200 text-slate-600 hover:border-coral-300 hover:text-coral-700',
                    )}
                    onclick={() => onChange(field.key, score)}
                  >
                    {option}
                  </button>
                {/each}
              </div>
            {:else if field.kind === 'nps'}
              <div class="space-y-2">
                <div class="grid grid-cols-11 gap-1">
                  {#each Array.from({ length: 11 }) as _, index}
                    <button
                      type="button"
                      class={cn(
                        'rounded-lg border py-2 text-sm font-medium transition',
                        responses[field.key] === index
                          ? index <= 6
                            ? 'border-red-500 bg-red-500 text-white'
                            : index <= 8
                              ? 'border-amber-400 bg-amber-400 text-slate-950'
                              : 'border-green-500 bg-green-500 text-white'
                          : 'border-slate-200 text-slate-600 hover:border-slate-400',
                      )}
                      onclick={() => onChange(field.key, index)}
                    >
                      {index}
                    </button>
                  {/each}
                </div>
                <div class="flex justify-between text-xs text-slate-500">
                  <span>Not at all likely</span>
                  <span>Extremely likely</span>
                </div>
              </div>
            {/if}
          </div>
        {/each}
      </div>
    </section>
  {/each}
</div>
