// src/routes/admin/opportunities/$id/edit.tsx
import { createFileRoute } from '@tanstack/react-router'
import { useSuspenseQuery } from '@tanstack/react-query'
import { convexQuery } from '@convex-dev/react-query'
import { api } from '../../../../../convex/_generated/api'
import type { Id } from '../../../../../convex/_generated/dataModel'
import { OpportunityForm } from '~/components/admin/opportunity-form'

export const Route = createFileRoute('/admin/opportunities/$id/edit')({
  loader: async ({ context, params }) => {
    await context.queryClient.ensureQueryData(
      convexQuery(api.opportunities.get, {
        id: params.id as Id<'opportunities'>,
      }),
    )
  },
  component: EditOpportunityPage,
})

function EditOpportunityPage() {
  const { id } = Route.useParams()

  const { data: opportunity } = useSuspenseQuery(
    convexQuery(api.opportunities.get, { id: id as Id<'opportunities'> }),
  )

  if (opportunity === null) {
    return <div className="text-red-600">Opportunity not found</div>
  }

  return (
    <div>
      <h1 className="text-2xl font-display text-foreground mb-6">
        Edit Opportunity
      </h1>
      <OpportunityForm
        mode="edit"
        initialData={{
          ...opportunity,
          requirements: opportunity.requirements || undefined,
          deadline: opportunity.deadline || undefined,
        }}
      />
    </div>
  )
}

// src/routes/(app)/admin/opportunities/[id]/edit/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { useQuery } from 'convex-svelte'
  import { api } from '$convex/_generated/api'
  import OpportunityEditor from '~/components/platform-admin/OpportunityEditor.svelte'

  const id = $derived(page.params.id as any)
  const opportunity = useQuery(api.opportunities.get, () => ({ id }))
</script>

<section class="space-y-6">
  <div>
    <h1 class="font-display text-3xl text-slate-950">Edit opportunity</h1>
    <p class="mt-2 text-sm text-slate-600">Update the opportunity record and archive status.</p>
  </div>

  {#if opportunity.data}
    <OpportunityEditor mode="edit" initialData={opportunity.data} />
  {:else if opportunity.isLoading}
    <div class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">Loading opportunity…</div>
  {:else}
    <div class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">Opportunity not found.</div>
  {/if}
</section>
