// src/routes/org/$slug/space/bookings.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { useMutation, useQuery } from 'convex/react'
import { format, isBefore, startOfDay } from 'date-fns'
import {
  ArrowLeft,
  Building2,
  Calendar,
  CalendarDays,
  Clock,
  Edit2,
  Loader2,
  MapPin,
  Save,
  Shield,
  Trash2,
  X,
} from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { api } from '../../../../../convex/_generated/api'
import type { Doc } from '../../../../../convex/_generated/dataModel'
import { AuthHeader } from '~/components/layout/auth-header'
import { GradientBg } from '~/components/layout/GradientBg'
import { Button } from '~/components/ui/button'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { Label } from '~/components/ui/label'
import { Textarea } from '~/components/ui/textarea'
import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogCancel,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
  AlertDialogTrigger,
} from '~/components/ui/alert-dialog'

export const Route = createFileRoute('/org/$slug/space/bookings')({
  component: MyBookingsPage,
})

function MyBookingsPage() {
  const { slug } = Route.useParams()

  // Three-query cascade: org -> membership -> space
  const org = useQuery(api.orgs.directory.getOrgBySlug, { slug })
  const membership = useQuery(
    api.orgs.membership.getMembership,
    org ? { orgId: org._id } : 'skip',
  )
  const space = useQuery(
    api.coworkingSpaces.getSpaceByOrgPublic,
    org && membership ? { orgId: org._id } : 'skip',
  )
  const bookings = useQuery(
    api.spaceBookings.getMyBookings,
    space ? { spaceId: space._id } : 'skip',
  )

  // Loading state
  if (org === undefined || membership === undefined) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-3xl mx-auto">
            <div className="animate-pulse space-y-6">
              <div className="h-12 bg-slate-100 rounded-xl w-1/3" />
              <div className="h-64 bg-slate-100 rounded-xl" />
            </div>
          </div>
        </main>
      </GradientBg>
    )
  }

  // Org not found
  if (org === null) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Building2 className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-display text-foreground mb-4">
              Organization Not Found
            </h1>
            <Button asChild>
              <Link to="/">Go Home</Link>
            </Button>
          </div>
        </main>
      </GradientBg>
    )
  }

  // Not a member
  if (!membership) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Shield className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-display text-foreground mb-4">
              Membership Required
            </h1>
            <Button asChild>
              <Link to="/org/$slug" params={{ slug }}>
                Back to Organization
              </Link>
            </Button>
          </div>
        </main>
      </GradientBg>
    )
  }

  // Loading space/bookings
  if (space === undefined || bookings === undefined) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-3xl mx-auto">
            <div className="animate-pulse space-y-6">
              <div className="h-12 bg-slate-100 rounded-xl w-1/3" />
              <div className="h-64 bg-slate-100 rounded-xl" />
            </div>
          </div>
        </main>
      </GradientBg>
    )
  }

  // No space configured
  if (space === null) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <MapPin className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-display text-foreground mb-4">
              No Co-working Space
            </h1>
            <Button asChild>
              <Link to="/org/$slug" params={{ slug }}>
                Back to Organization
              </Link>
            </Button>
          </div>
        </main>
      </GradientBg>
    )
  }

  // Render the bookings page
  return (
    <MyBookingsContent
      org={org}
      space={space}
      slug={slug}
      bookings={bookings}
    />
  )
}

// Separate component to ensure types are non-null
interface MyBookingsContentProps {
  org: Doc<'organizations'>
  space: Doc<'coworkingSpaces'>
  slug: string
  bookings: Array<Doc<'spaceBookings'>>
}

function MyBookingsContent({
  org,
  space,
  slug,
  bookings,
}: MyBookingsContentProps) {
  const today = startOfDay(new Date())

  // Split bookings into upcoming and past
  const upcomingBookings = bookings.filter(
    (b) => !isBefore(new Date(b.date), today),
  )
  const pastBookings = bookings.filter((b) => isBefore(new Date(b.date), today))

  return (
    <GradientBg>
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-3xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <div className="flex items-center gap-2 text-slate-500 text-sm mb-2">
              <Link
                to="/org/$slug"
                params={{ slug }}
                className="hover:text-slate-700 transition-colors"
              >
                {org.name}
              </Link>
              <span>/</span>
              <Link
                to="/org/$slug/space"
                params={{ slug }}
                className="hover:text-slate-700 transition-colors"
              >
                {space.name}
              </Link>
              <span>/</span>
              <span className="text-slate-700">My Bookings</span>
            </div>
            <div className="flex items-center justify-between flex-wrap gap-4">
              <h1 className="text-2xl font-display text-foreground">
                <CalendarDays className="size-6 inline-block mr-2 -mt-1" />
                My Bookings
              </h1>
              <Button variant="outline" asChild>
                <Link to="/org/$slug/space" params={{ slug }}>
                  <ArrowLeft className="size-4 mr-2" />
                  Book a Spot
                </Link>
              </Button>
            </div>
          </div>

          {/* Upcoming bookings */}
          <Card className="mb-6">
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <Calendar className="size-5" />
                Upcoming Bookings
              </CardTitle>
            </CardHeader>
            <CardContent>
              {upcomingBookings.length === 0 ? (
                <div className="text-center py-8 text-muted-foreground">
                  <Calendar className="size-10 mx-auto mb-3 opacity-50" />
                  <p className="mb-4">You have no upcoming bookings</p>
                  <Button asChild>
                    <Link to="/org/$slug/space" params={{ slug }}>
                      Book a Spot
                    </Link>
                  </Button>
                </div>
              ) : (
                <div className="space-y-4">
                  {upcomingBookings.map((booking) => (
                    <BookingCard
                      key={booking._id}
                      booking={booking}
                      showActions
                    />
                  ))}
                </div>
              )}
            </CardContent>
          </Card>

          {/* Past bookings */}
          {pastBookings.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2 text-muted-foreground">
                  <Clock className="size-5" />
                  Past Bookings
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  {pastBookings.map((booking) => (
                    <BookingCard
                      key={booking._id}
                      booking={booking}
                      showActions={false}
                    />
                  ))}
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      </main>
    </GradientBg>
  )
}

// Format minutes to display time
function formatTime(minutes: number): string {
  const hours = Math.floor(minutes / 60)
  const mins = minutes % 60
  const period = hours >= 12 ? 'PM' : 'AM'
  const displayHours = hours === 0 ? 12 : hours > 12 ? hours - 12 : hours
  return `${displayHours}:${mins.toString().padStart(2, '0')} ${period}`
}

interface BookingCardProps {
  booking: Doc<'spaceBookings'>
  showActions: boolean
}

function BookingCard({ booking, showActions }: BookingCardProps) {
  const [isEditing, setIsEditing] = useState(false)
  const [workingOn, setWorkingOn] = useState(booking.workingOn ?? '')
  const [interestedInMeeting, setInterestedInMeeting] = useState(
    booking.interestedInMeeting ?? '',
  )
  const [isSaving, setIsSaving] = useState(false)
  const [isCancelling, setIsCancelling] = useState(false)

  const updateTags = useMutation(api.spaceBookings.updateBookingTags)
  const cancelBooking = useMutation(api.spaceBookings.cancelBooking)

  const handleSaveTags = async () => {
    setIsSaving(true)
    try {
      await updateTags({
        bookingId: booking._id,
        workingOn: workingOn.trim() || undefined,
        interestedInMeeting: interestedInMeeting.trim() || undefined,
      })
      toast.success('Tags updated')
      setIsEditing(false)
    } catch (error) {
      console.error('Failed to update tags:', error)
      toast.error(
        error instanceof Error ? error.message : 'Failed to update tags',
      )
    } finally {
      setIsSaving(false)
    }
  }

  const handleCancel = async () => {
    setIsCancelling(true)
    try {
      await cancelBooking({ bookingId: booking._id })
      toast.success('Booking cancelled')
    } catch (error) {
      console.error('Failed to cancel booking:', error)
      toast.error(
        error instanceof Error ? error.message : 'Failed to cancel booking',
      )
    } finally {
      setIsCancelling(false)
    }
  }

  const dateObj = new Date(booking.date)

  return (
    <div className="p-4 rounded-lg border bg-card">
      <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
        <div className="space-y-2 flex-1">
          {/* Date and time */}
          <div className="flex items-center gap-2 flex-wrap">
            <span className="font-medium">
              {format(dateObj, 'EEEE, MMMM d, yyyy')}
            </span>
            <span className="text-muted-foreground">
              {formatTime(booking.startMinutes)} -{' '}
              {formatTime(booking.endMinutes)}
            </span>
          </div>

          {/* Tags display or edit */}
          {isEditing ? (
            <div className="space-y-3 pt-2">
              <div className="space-y-1.5">
                <Label htmlFor={`workingOn-${booking._id}`} className="text-xs">
                  Can help with
                </Label>
                <Textarea
                  id={`workingOn-${booking._id}`}
                  value={workingOn}
                  onChange={(e) => setWorkingOn(e.target.value.slice(0, 140))}
                  placeholder="e.g., ML expertise, grant writing..."
                  rows={2}
                  className="text-sm"
                />
                <p className="text-xs text-muted-foreground">
                  {workingOn.length}/140
                </p>
              </div>
              <div className="space-y-1.5">
                <Label
                  htmlFor={`interestedInMeeting-${booking._id}`}
                  className="text-xs"
                >
                  Looking for
                </Label>
                <Textarea
                  id={`interestedInMeeting-${booking._id}`}
                  value={interestedInMeeting}
                  onChange={(e) =>
                    setInterestedInMeeting(e.target.value.slice(0, 140))
                  }
                  placeholder="e.g., feedback on research, introductions..."
                  rows={2}
                  className="text-sm"
                />
                <p className="text-xs text-muted-foreground">
                  {interestedInMeeting.length}/140
                </p>
              </div>
              <div className="flex gap-2">
                <Button size="sm" onClick={handleSaveTags} disabled={isSaving}>
                  {isSaving ? (
                    <Loader2 className="size-3 mr-1 animate-spin" />
                  ) : (
                    <Save className="size-3 mr-1" />
                  )}
                  Save
                </Button>
                <Button
                  size="sm"
                  variant="outline"
                  onClick={() => {
                    setIsEditing(false)
                    setWorkingOn(booking.workingOn ?? '')
                    setInterestedInMeeting(booking.interestedInMeeting ?? '')
                  }}
                >
                  <X className="size-3 mr-1" />
                  Cancel
                </Button>
              </div>
            </div>
          ) : (
            <>
              {(booking.workingOn || booking.interestedInMeeting) && (
                <div className="text-sm space-y-1 text-muted-foreground">
                  {booking.workingOn && (
                    <p>
                      <span className="text-foreground">Can help with:</span>{' '}
                      {booking.workingOn}
                    </p>
                  )}
                  {booking.interestedInMeeting && (
                    <p>
                      <span className="text-foreground">Looking for:</span>{' '}
                      {booking.interestedInMeeting}
                    </p>
                  )}
                </div>
              )}
            </>
          )}
        </div>

        {/* Actions */}
        {showActions && !isEditing && (
          <div className="flex gap-2 sm:flex-col">
            <Button
              size="sm"
              variant="outline"
              onClick={() => setIsEditing(true)}
            >
              <Edit2 className="size-3 mr-1" />
              Edit Tags
            </Button>
            <AlertDialog>
              <AlertDialogTrigger asChild>
                <Button
                  size="sm"
                  variant="outline"
                  className="text-destructive border-destructive hover:bg-destructive/10"
                  disabled={isCancelling}
                >
                  {isCancelling ? (
                    <Loader2 className="size-3 mr-1 animate-spin" />
                  ) : (
                    <Trash2 className="size-3 mr-1" />
                  )}
                  Cancel
                </Button>
              </AlertDialogTrigger>
              <AlertDialogContent>
                <AlertDialogHeader>
                  <AlertDialogTitle>Cancel this booking?</AlertDialogTitle>
                  <AlertDialogDescription>
                    Are you sure you want to cancel your booking for{' '}
                    {format(dateObj, 'MMMM d, yyyy')}? This action cannot be
                    undone.
                  </AlertDialogDescription>
                </AlertDialogHeader>
                <AlertDialogFooter>
                  <AlertDialogCancel>Keep Booking</AlertDialogCancel>
                  <AlertDialogAction
                    onClick={handleCancel}
                    className="bg-destructive text-destructive-foreground hover:bg-destructive/90"
                  >
                    Yes, Cancel Booking
                  </AlertDialogAction>
                </AlertDialogFooter>
              </AlertDialogContent>
            </AlertDialog>
          </div>
        )}
      </div>
    </div>
  )
}

// src/routes/(app)/org/[slug]/space/bookings/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { format, isBefore, startOfDay } from 'date-fns'
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import {
    ArrowLeft,
    Building2,
    Calendar,
    CalendarDays,
    LoaderCircle,
    MapPin,
    Shield,
    Trash2,
  } from 'lucide-svelte'
  import { api } from '$convex/_generated/api'
  import type { Doc } from '$convex/_generated/dataModel'
  import AuthHeader from '~/components/layout/auth-header.svelte'
  import GradientBg from '~/components/layout/GradientBg.svelte'

  const convex = useConvexClient()
  const slug = $derived(page.params.slug ?? null)

  const org = useQuery(api.orgs.directory.getOrgBySlug, () =>
    slug
      ? {
          slug,
        }
      : 'skip',
  )

  const membership = useQuery(
    api.orgs.membership.getMembership,
    () =>
      org.data
        ? {
            orgId: org.data._id,
          }
        : 'skip',
  )

  const space = useQuery(
    api.coworkingSpaces.getSpaceByOrgPublic,
    () =>
      org.data && membership.data
        ? {
            orgId: org.data._id,
          }
        : 'skip',
  )

  const bookings = useQuery(
    api.spaceBookings.getMyBookings,
    () =>
      space.data
        ? {
            spaceId: space.data._id,
          }
        : 'skip',
  )

  let cancellingId = $state<string | null>(null)

  const today = startOfDay(new Date())
  const upcomingBookings = $derived(
    (bookings.data ?? []).filter((booking) => !isBefore(new Date(booking.date), today)),
  )
  const pastBookings = $derived(
    (bookings.data ?? []).filter((booking) => isBefore(new Date(booking.date), today)),
  )

  const formatMinutes = (minutes: number) => {
    const hours = Math.floor(minutes / 60)
    const mins = minutes % 60
    const period = hours >= 12 ? 'PM' : 'AM'
    const displayHours = hours === 0 ? 12 : hours > 12 ? hours - 12 : hours
    return `${displayHours}:${String(mins).padStart(2, '0')} ${period}`
  }

  const cancelBooking = async (bookingId: Doc<'spaceBookings'>['_id']) => {
    cancellingId = bookingId
    try {
      await convex.mutation(api.spaceBookings.cancelBooking, { bookingId })
      toast.success('Booking cancelled')
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to cancel booking')
    } finally {
      cancellingId = null
    }
  }
</script>

<svelte:head>
  <title>{org.data ? `${org.data.name} Bookings | ASTN` : 'My Bookings | ASTN'}</title>
</svelte:head>

<GradientBg>
  <AuthHeader />

  <main class="container mx-auto px-4 py-8">
    {#if org.isLoading || membership.isLoading}
      <div class="flex min-h-[60vh] items-center justify-center">
        <LoaderCircle class="size-8 animate-spin text-slate-400" />
      </div>
    {:else if !org.data}
      <div class="mx-auto max-w-lg rounded-[2rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">
        <div class="mx-auto mb-4 grid size-16 place-items-center rounded-full bg-slate-100 text-slate-400">
          <Building2 class="size-8" />
        </div>
        <h1 class="font-display text-3xl text-slate-950">Organization not found</h1>
      </div>
    {:else if !membership.data}
      <div class="mx-auto max-w-lg rounded-[2rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">
        <div class="mx-auto mb-4 grid size-16 place-items-center rounded-full bg-slate-100 text-slate-400">
          <Shield class="size-8" />
        </div>
        <h1 class="font-display text-3xl text-slate-950">Membership required</h1>
        <p class="mt-3 text-sm leading-6 text-slate-600">
          Join this organization to view and manage space bookings.
        </p>
      </div>
    {:else if !space.data}
      <div class="mx-auto max-w-lg rounded-[2rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">
        <div class="mx-auto mb-4 grid size-16 place-items-center rounded-full bg-slate-100 text-slate-400">
          <MapPin class="size-8" />
        </div>
        <h1 class="font-display text-3xl text-slate-950">No space configured</h1>
      </div>
    {:else}
      <div class="mx-auto max-w-4xl space-y-6">
        <div class="flex flex-wrap items-center justify-between gap-3">
          <div>
            <a
              href={`/org/${slug}/space`}
              class="inline-flex items-center gap-1 text-sm text-slate-500 transition hover:text-slate-900"
            >
              <ArrowLeft class="size-4" />
              Back to {space.data.name}
            </a>
            <h1 class="mt-3 font-display text-3xl text-slate-950">My Bookings</h1>
          </div>
          <a
            href={`/org/${slug}/space`}
            class="inline-flex items-center gap-2 rounded-xl border border-border bg-white px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
          >
            <CalendarDays class="size-4" />
            Book another day
          </a>
        </div>

        <section class="rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
          <div class="mb-4 flex items-center gap-2">
            <Calendar class="size-5 text-coral-600" />
            <h2 class="text-lg font-semibold text-slate-950">Upcoming bookings</h2>
          </div>

          {#if upcomingBookings.length === 0}
            <p class="text-sm text-slate-600">You have no upcoming bookings.</p>
          {:else}
            <div class="space-y-3">
              {#each upcomingBookings as booking}
                <div class="rounded-[1.25rem] border border-border/70 bg-slate-50/70 px-4 py-4">
                  <div class="flex flex-wrap items-start justify-between gap-3">
                    <div class="space-y-1">
                      <div class="font-medium text-slate-900">
                        {format(new Date(booking.date), 'EEEE, MMMM d, yyyy')}
                      </div>
                      <div class="text-sm text-slate-500">
                        {formatMinutes(booking.startMinutes)} - {formatMinutes(booking.endMinutes)}
                      </div>
                      {#if booking.workingOn}
                        <div class="pt-1 text-sm text-slate-700">
                          <strong>Can help with:</strong> {booking.workingOn}
                        </div>
                      {/if}
                      {#if booking.interestedInMeeting}
                        <div class="text-sm text-slate-700">
                          <strong>Looking to meet:</strong> {booking.interestedInMeeting}
                        </div>
                      {/if}
                    </div>

                    <button
                      type="button"
                      class="inline-flex items-center gap-2 rounded-xl border border-red-200 bg-white px-3 py-2 text-sm font-medium text-red-700 transition hover:bg-red-50 disabled:pointer-events-none disabled:opacity-50"
                      disabled={cancellingId === booking._id}
                      onclick={() => {
                        void cancelBooking(booking._id)
                      }}
                    >
                      {#if cancellingId === booking._id}
                        <LoaderCircle class="size-4 animate-spin" />
                        Cancelling...
                      {:else}
                        <Trash2 class="size-4" />
                        Cancel
                      {/if}
                    </button>
                  </div>
                </div>
              {/each}
            </div>
          {/if}
        </section>

        {#if pastBookings.length > 0}
          <section class="rounded-[2rem] border border-border/70 bg-white/92 p-6 shadow-warm-sm">
            <div class="mb-4 flex items-center gap-2">
              <Calendar class="size-5 text-slate-400" />
              <h2 class="text-lg font-semibold text-slate-950">Past bookings</h2>
            </div>

            <div class="space-y-3">
              {#each pastBookings as booking}
                <div class="rounded-[1.25rem] border border-border/70 bg-slate-50/70 px-4 py-4">
                  <div class="font-medium text-slate-900">
                    {format(new Date(booking.date), 'EEEE, MMMM d, yyyy')}
                  </div>
                  <div class="mt-1 text-sm text-slate-500">
                    {formatMinutes(booking.startMinutes)} - {formatMinutes(booking.endMinutes)}
                  </div>
                </div>
              {/each}
            </div>
          </section>
        {/if}
      </div>
    {/if}
  </main>
</GradientBg>
