// src/routes/org/$slug/join.tsx
import { createFileRoute, useNavigate } from '@tanstack/react-router'
import {
  AuthLoading,
  Authenticated,
  Unauthenticated,
  useMutation,
  useQuery,
} from 'convex/react'
import { Building2, Eye, EyeOff, Link2Off, Loader2 } from 'lucide-react'
import { useState } from 'react'
import { toast } from 'sonner'
import { api } from '../../../../convex/_generated/api'
import type { Id } from '../../../../convex/_generated/dataModel'
import { AuthHeader } from '~/components/layout/auth-header'
import { GradientBg } from '~/components/layout/GradientBg'
import { Card } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Spinner } from '~/components/ui/spinner'
import { savePendingInvite } from '~/lib/pendingInvite'

export const Route = createFileRoute('/org/$slug/join')({
  component: JoinOrgPage,
  validateSearch: (search: Record<string, unknown>) => ({
    token: (search.token as string) || '',
  }),
})

function JoinOrgPage() {
  const { slug } = Route.useParams()
  const { token } = Route.useSearch()

  // If token provided, validate it
  const validation = useQuery(
    api.orgs.directory.validateInviteToken,
    token ? { token } : 'skip',
  )

  // If no token, look up org by slug directly
  const orgBySlug = useQuery(
    api.orgs.directory.getOrgBySlug,
    !token ? { slug } : 'skip',
  )

  // No token: use slug-based lookup
  if (!token) {
    if (orgBySlug === undefined) {
      return (
        <GradientBg>
          <AuthHeader />
          <main className="container mx-auto px-4 py-8">
            <div className="flex items-center justify-center min-h-[60vh]">
              <Spinner />
            </div>
          </main>
        </GradientBg>
      )
    }

    if (orgBySlug === null) {
      return (
        <GradientBg>
          <AuthHeader />
          <main className="container mx-auto px-4 py-8">
            <InvalidTokenMessage message="Organization not found. Please check the link and try again." />
          </main>
        </GradientBg>
      )
    }

    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <AuthLoading>
            <div className="flex items-center justify-center min-h-[60vh]">
              <Spinner />
            </div>
          </AuthLoading>

          <Unauthenticated>
            <SignInPrompt orgName={orgBySlug.name} slug={slug} />
          </Unauthenticated>

          <Authenticated>
            <JoinForm
              orgId={orgBySlug._id}
              orgName={orgBySlug.name}
              orgSlug={slug}
            />
          </Authenticated>
        </main>
      </GradientBg>
    )
  }

  // Token-based flow
  if (validation === undefined) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="flex items-center justify-center min-h-[60vh]">
            <Spinner />
          </div>
        </main>
      </GradientBg>
    )
  }

  if (!validation.valid) {
    return (
      <GradientBg>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <InvalidTokenMessage message="This invite link is invalid or has expired. Please request a new link from an organization admin." />
        </main>
      </GradientBg>
    )
  }

  return (
    <GradientBg>
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <AuthLoading>
          <div className="flex items-center justify-center min-h-[60vh]">
            <Spinner />
          </div>
        </AuthLoading>

        <Unauthenticated>
          <SignInPrompt
            orgName={validation.orgName}
            slug={slug}
            token={token}
          />
        </Unauthenticated>

        <Authenticated>
          <JoinForm
            token={token}
            orgId={validation.orgId}
            orgName={validation.orgName}
            orgSlug={validation.orgSlug}
          />
        </Authenticated>
      </main>
    </GradientBg>
  )
}

function InvalidTokenMessage({ message }: { message: string }) {
  return (
    <div className="max-w-md mx-auto text-center py-12">
      <div className="size-16 rounded-full bg-red-50 flex items-center justify-center mx-auto mb-4">
        <Link2Off className="size-8 text-red-500" />
      </div>
      <h1 className="text-2xl font-display text-foreground mb-4">
        Invalid Invite Link
      </h1>
      <p className="text-slate-600">{message}</p>
    </div>
  )
}

function SignInPrompt({
  orgName,
  slug,
  token,
}: {
  orgName: string
  slug: string
  token?: string
}) {
  const navigate = useNavigate()

  const handleSignIn = () => {
    savePendingInvite({ slug, token: token || undefined })
    navigate({ to: '/login' })
  }

  return (
    <Card className="max-w-md mx-auto p-8 text-center">
      <div className="size-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
        <Building2 className="size-8 text-primary" />
      </div>
      <h1 className="text-2xl font-display text-foreground mb-2">
        Join {orgName}
      </h1>
      <p className="text-slate-600 mb-6">
        Sign in to join this organization and access the member directory.
      </p>
      <Button onClick={handleSignIn}>Sign In to Continue</Button>
    </Card>
  )
}

interface JoinFormProps {
  token?: string
  orgId: Id<'organizations'>
  orgName: string
  orgSlug?: string
}

function JoinForm({ token, orgId, orgName, orgSlug }: JoinFormProps) {
  const navigate = useNavigate()
  const joinOrg = useMutation(api.orgs.membership.joinOrg)
  const existingMembership = useQuery(api.orgs.membership.getMembership, {
    orgId,
  })

  const [visibility, setVisibility] = useState<'visible' | 'hidden' | null>(
    null,
  )
  const [isJoining, setIsJoining] = useState(false)

  // Already a member
  if (existingMembership) {
    return (
      <Card className="max-w-md mx-auto p-8 text-center">
        <div className="size-16 rounded-full bg-green-50 flex items-center justify-center mx-auto mb-4">
          <Building2 className="size-8 text-green-600" />
        </div>
        <h1 className="text-2xl font-display text-foreground mb-2">
          Already a Member
        </h1>
        <p className="text-slate-600 mb-6">
          You&apos;re already a member of {orgName}.
        </p>
        <Button
          onClick={() =>
            navigate({
              to: '/org/$slug',
              params: { slug: orgSlug || 'unknown' },
            })
          }
        >
          View Organization
        </Button>
      </Card>
    )
  }

  const handleJoin = async () => {
    if (!visibility) return

    setIsJoining(true)
    try {
      await joinOrg({
        orgId,
        inviteToken: token,
        directoryVisibility: visibility,
      })
      toast.success(`Welcome to ${orgName}!`)

      navigate({
        to: '/org/$slug',
        params: { slug: orgSlug || 'unknown' },
      })
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : 'Failed to join organization',
      )
    } finally {
      setIsJoining(false)
    }
  }

  return (
    <Card className="max-w-lg mx-auto p-8">
      <div className="text-center mb-6">
        <div className="size-16 rounded-full bg-primary/10 flex items-center justify-center mx-auto mb-4">
          <Building2 className="size-8 text-primary" />
        </div>
        <h1 className="text-2xl font-display text-foreground mb-2">
          Join {orgName}
        </h1>
        <p className="text-slate-600">
          By joining, organization admins will be able to view your profile. If
          you prefer to keep your profile private, you can use the platform
          without joining an organization.
        </p>
      </div>

      <div className="space-y-3 mb-6">
        <p className="text-sm font-medium text-slate-700">
          Directory visibility
        </p>
        <VisibilityOption
          value="visible"
          selected={visibility === 'visible'}
          onSelect={() => setVisibility('visible')}
          icon={Eye}
          title="Visible in Directory"
          description="Your name and profile summary appear in the public member directory. Other members can see you're part of the organization."
        />

        <VisibilityOption
          value="hidden"
          selected={visibility === 'hidden'}
          onSelect={() => setVisibility('hidden')}
          icon={EyeOff}
          title="Hidden from Directory"
          description="You won't appear in the public member directory, but organization admins can still view your profile."
        />
      </div>

      <Button
        className="w-full"
        disabled={!visibility || isJoining}
        onClick={handleJoin}
      >
        {isJoining ? (
          <>
            <Loader2 className="size-4 mr-2 animate-spin" />
            Joining...
          </>
        ) : (
          'Join Organization'
        )}
      </Button>
    </Card>
  )
}

interface VisibilityOptionProps {
  value: 'visible' | 'hidden'
  selected: boolean
  onSelect: () => void
  icon: React.ComponentType<{ className?: string }>
  title: string
  description: string
}

function VisibilityOption({
  selected,
  onSelect,
  icon: Icon,
  title,
  description,
}: VisibilityOptionProps) {
  return (
    <button
      type="button"
      onClick={onSelect}
      className={`w-full p-4 rounded-lg border-2 text-left transition-colors ${
        selected
          ? 'border-primary bg-primary/5'
          : 'border-slate-200 hover:border-slate-300'
      }`}
    >
      <div className="flex items-start gap-3">
        <div
          className={`size-10 rounded-full flex items-center justify-center shrink-0 ${
            selected ? 'bg-primary/10' : 'bg-slate-100'
          }`}
        >
          <Icon
            className={`size-5 ${selected ? 'text-primary' : 'text-slate-500'}`}
          />
        </div>
        <div>
          <h3
            className={`font-medium ${selected ? 'text-primary' : 'text-foreground'}`}
          >
            {title}
          </h3>
          <p className="text-sm text-slate-500 mt-1">{description}</p>
        </div>
      </div>
    </button>
  )
}

// src/routes/(app)/org/[slug]/join/+page.svelte
<script lang="ts">
  import { goto } from '$app/navigation'
  import { page } from '$app/state'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import {
    Building2,
    Eye,
    EyeOff,
    Link2Off,
    LoaderCircle,
  } from 'lucide-svelte'
  import { toast } from 'svelte-sonner'
  import { api } from '$convex/_generated/api'
  import type { Id } from '$convex/_generated/dataModel'
  import { getClerkContext } from '$lib/stores/clerk.svelte'
  import { savePendingInvite } from '$lib/pendingInvite'
  import AuthHeader from '~/components/layout/auth-header.svelte'
  import GradientBg from '~/components/layout/GradientBg.svelte'

  type Visibility = 'visible' | 'hidden'

  const clerkContext = getClerkContext()
  const convex = useConvexClient()
  const slug = $derived(page.params.slug ?? null)

  const token = $derived(page.url.searchParams.get('token') ?? '')

  const validation = useQuery(api.orgs.directory.validateInviteToken, () =>
    token
      ? {
          token,
        }
      : 'skip',
  )

  const orgBySlug = useQuery(api.orgs.directory.getOrgBySlug, () =>
    token || !slug
      ? 'skip'
      : {
          slug,
        },
  )

  const activeOrg = $derived.by(() => {
    if (token) {
      return validation.data?.valid
        ? {
            orgId: validation.data.orgId,
            orgName: validation.data.orgName,
            orgSlug: validation.data.orgSlug,
          }
        : null
    }

    return orgBySlug.data
      ? {
          orgId: orgBySlug.data._id,
          orgName: orgBySlug.data.name,
          orgSlug: slug,
        }
      : null
  })

  const existingMembership = useQuery(api.orgs.membership.getMembership, () =>
    clerkContext.currentUser && activeOrg
      ? {
          orgId: activeOrg.orgId,
        }
      : 'skip',
  )

  let visibility = $state<Visibility | null>(null)
  let isJoining = $state(false)

  const saveInviteAndSignIn = async () => {
    if (!slug) {
      return
    }

    savePendingInvite({
      slug,
      token: token || undefined,
    })
    await goto('/login')
  }

  const joinOrg = async () => {
    if (!activeOrg || !visibility) {
      return
    }

    isJoining = true

    try {
      await convex.mutation(api.orgs.membership.joinOrg, {
        orgId: activeOrg.orgId,
        inviteToken: token || undefined,
        directoryVisibility: visibility,
      })

      toast.success(`Welcome to ${activeOrg.orgName}`)
      await goto(`/org/${activeOrg.orgSlug || slug}`)
    } catch (error) {
      toast.error(
        error instanceof Error ? error.message : 'Failed to join organization',
      )
    } finally {
      isJoining = false
    }
  }
</script>

<svelte:head>
  <title>Join Organization | ASTN</title>
</svelte:head>

<GradientBg>
  <AuthHeader />

  <main class="container mx-auto px-4 py-8">
    {#if (token && validation.isLoading) || (!token && orgBySlug.isLoading) || !clerkContext.isClerkLoaded}
      <div class="flex min-h-[60vh] items-center justify-center">
        <LoaderCircle class="size-8 animate-spin text-slate-400" />
      </div>
    {:else if (token && !validation.data?.valid) || (!token && !orgBySlug.data)}
      <div class="mx-auto max-w-md rounded-[2rem] border border-border/70 bg-white/92 px-6 py-12 text-center shadow-warm-sm">
        <div class="mx-auto mb-4 flex size-16 items-center justify-center rounded-full bg-rose-50 text-rose-500">
          <Link2Off class="size-8" />
        </div>
        <h1 class="font-display text-3xl text-slate-950">Invalid invite link</h1>
        <p class="mt-3 text-sm leading-6 text-slate-600">
          {token
            ? 'This invite link is invalid or expired. Please request a new link from an organization admin.'
            : 'Organization not found. Please check the link and try again.'}
        </p>
      </div>
    {:else if !clerkContext.currentUser}
      <div class="mx-auto max-w-md rounded-[2rem] border border-border/70 bg-white/92 p-8 text-center shadow-warm-sm">
        <div class="mx-auto mb-4 flex size-16 items-center justify-center rounded-full bg-coral-50 text-coral-600">
          <Building2 class="size-8" />
        </div>
        <h1 class="font-display text-3xl text-slate-950">
          Join {activeOrg?.orgName}
        </h1>
        <p class="mt-3 text-sm leading-6 text-slate-600">
          Sign in to join this organization and access its member directory,
          programs, and space pages.
        </p>
        <button
          type="button"
          class="mt-6 inline-flex rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600"
          onclick={saveInviteAndSignIn}
        >
          Sign in to continue
        </button>
      </div>
    {:else if existingMembership.data}
      <div class="mx-auto max-w-md rounded-[2rem] border border-border/70 bg-white/92 p-8 text-center shadow-warm-sm">
        <div class="mx-auto mb-4 flex size-16 items-center justify-center rounded-full bg-emerald-50 text-emerald-600">
          <Building2 class="size-8" />
        </div>
        <h1 class="font-display text-3xl text-slate-950">Already a member</h1>
        <p class="mt-3 text-sm leading-6 text-slate-600">
          You’re already a member of {activeOrg?.orgName}.
        </p>
        <a
          href={`/org/${activeOrg?.orgSlug || page.params.slug}`}
          class="mt-6 inline-flex rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600"
        >
          View organization
        </a>
      </div>
    {:else}
      <div class="mx-auto max-w-2xl rounded-[2rem] border border-border/70 bg-white/92 p-8 shadow-warm-sm">
        <div class="text-center">
          <div class="mx-auto mb-4 flex size-16 items-center justify-center rounded-full bg-coral-50 text-coral-600">
            <Building2 class="size-8" />
          </div>
          <h1 class="font-display text-3xl text-slate-950">
            Join {activeOrg?.orgName}
          </h1>
          <p class="mx-auto mt-3 max-w-xl text-sm leading-6 text-slate-600">
            By joining, organization admins will be able to view your profile.
            If you prefer to keep your profile private, you can still use the
            platform without joining an organization.
          </p>
        </div>

        <section class="mt-8 space-y-3">
          <p class="text-sm font-medium uppercase tracking-[0.18em] text-coral-600">
            Directory visibility
          </p>

          <button
            type="button"
            class={`w-full rounded-[1.5rem] border p-5 text-left transition ${
              visibility === 'visible'
                ? 'border-coral-300 bg-coral-50 shadow-warm-sm'
                : 'border-border/70 bg-white hover:border-coral-200'
            }`}
            onclick={() => {
              visibility = 'visible'
            }}
          >
            <div class="flex items-start gap-4">
              <div class="mt-1 rounded-xl bg-coral-100 p-2 text-coral-700">
                <Eye class="size-5" />
              </div>
              <div>
                <div class="text-base font-semibold text-slate-950">
                  Visible in directory
                </div>
                <p class="mt-1 text-sm leading-6 text-slate-600">
                  Your name and profile summary appear in the public member
                  directory so other members can see you’re part of the
                  organization.
                </p>
              </div>
            </div>
          </button>

          <button
            type="button"
            class={`w-full rounded-[1.5rem] border p-5 text-left transition ${
              visibility === 'hidden'
                ? 'border-slate-300 bg-slate-50 shadow-warm-sm'
                : 'border-border/70 bg-white hover:border-slate-300'
            }`}
            onclick={() => {
              visibility = 'hidden'
            }}
          >
            <div class="flex items-start gap-4">
              <div class="mt-1 rounded-xl bg-slate-100 p-2 text-slate-700">
                <EyeOff class="size-5" />
              </div>
              <div>
                <div class="text-base font-semibold text-slate-950">
                  Hidden from directory
                </div>
                <p class="mt-1 text-sm leading-6 text-slate-600">
                  You won’t appear in the public member directory, but
                  organization admins can still view your profile.
                </p>
              </div>
            </div>
          </button>
        </section>

        <button
          type="button"
          class="mt-8 inline-flex w-full items-center justify-center rounded-xl bg-coral-500 px-4 py-3 text-sm font-medium text-white transition hover:bg-coral-600 disabled:cursor-not-allowed disabled:opacity-60"
          disabled={!visibility || isJoining}
          onclick={joinOrg}
        >
          {#if isJoining}
            <span class="inline-flex items-center gap-2">
              <LoaderCircle class="size-4 animate-spin" />
              Joining...
            </span>
          {:else}
            Join organization
          {/if}
        </button>
      </div>
    {/if}
  </main>
</GradientBg>
