// src/routes/(app)/admin/opportunities/+page.svelte
<script lang="ts">
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import { api } from '$convex/_generated/api'
  import { formatDistanceToNow } from 'date-fns'

  const convex = useConvexClient()
  const opportunities = useQuery(api.opportunities.listAll, () => ({ includeArchived: true }))

  const archiveOpportunity = async (id: string) => {
    try {
      await convex.mutation(api.admin.archiveOpportunity, { id: id as any })
      toast.success('Opportunity archived')
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to archive')
    }
  }

  const deleteOpportunity = async (id: string) => {
    if (!window.confirm('Delete this opportunity?')) return
    try {
      await convex.mutation(api.admin.deleteOpportunity, { id: id as any })
      toast.success('Opportunity deleted')
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to delete')
    }
  }
</script>

<section class="space-y-6">
  <div class="flex items-end justify-between gap-4">
    <div>
      <h1 class="font-display text-3xl text-slate-950">Platform opportunities</h1>
      <p class="mt-2 text-sm text-slate-600">Manual opportunity entries managed across the platform.</p>
    </div>
    <a href="/admin/opportunities/new" class="rounded-full bg-coral-500 px-4 py-2 text-sm font-medium text-white transition hover:bg-coral-600">
      Add opportunity
    </a>
  </div>

  <div class="space-y-3">
    {#each opportunities.data ?? [] as opportunity (opportunity._id)}
      <article class={`rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-4 shadow-warm-sm ${opportunity.status === 'archived' ? 'opacity-60' : ''}`}>
        <div class="flex flex-wrap items-start justify-between gap-4">
          <div>
            <div class="flex items-center gap-2">
              <h2 class="text-lg font-semibold text-slate-950">{opportunity.title}</h2>
              <span class="rounded-full border border-border px-3 py-1 text-xs font-medium text-slate-600">{opportunity.status}</span>
              <span class="rounded-full border border-border px-3 py-1 text-xs font-medium text-slate-600">{opportunity.source}</span>
            </div>
            <p class="mt-2 text-sm text-slate-600">
              {opportunity.organization} · {opportunity.location}{opportunity.isRemote ? ' · Remote' : ''}
            </p>
            <p class="mt-1 text-xs text-slate-500">
              Last verified {formatDistanceToNow(opportunity.lastVerified, { addSuffix: true })}
            </p>
          </div>
          <div class="flex gap-2">
            <a href={`/admin/opportunities/${opportunity._id}/edit`} class="rounded-full border border-border px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50">
              Edit
            </a>
            {#if opportunity.status === 'active'}
              <button type="button" class="rounded-full border border-border px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50" onclick={() => archiveOpportunity(opportunity._id)}>
                Archive
              </button>
            {/if}
            <button type="button" class="rounded-full bg-rose-500 px-4 py-2 text-sm font-medium text-white" onclick={() => deleteOpportunity(opportunity._id)}>
              Delete
            </button>
          </div>
        </div>
      </article>
    {/each}
  </div>
</section>

// src/routes/admin/opportunities/index.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { useMutation, useSuspenseQuery } from '@tanstack/react-query'
import { convexQuery, useConvexMutation } from '@convex-dev/react-query'
import { Archive, Pencil, Plus, Trash2 } from 'lucide-react'
import { formatDistanceToNow } from 'date-fns'
import { api } from '../../../../convex/_generated/api'
import { Button } from '~/components/ui/button'
import { Card, CardContent } from '~/components/ui/card'
import { Badge } from '~/components/ui/badge'

export const Route = createFileRoute('/admin/opportunities/')({
  loader: async ({ context }) => {
    await context.queryClient.ensureQueryData(
      convexQuery(api.opportunities.listAll, { includeArchived: true }),
    )
  },
  component: AdminOpportunitiesPage,
})

function AdminOpportunitiesPage() {
  const { data: opportunities } = useSuspenseQuery(
    convexQuery(api.opportunities.listAll, { includeArchived: true }),
  )

  const deleteMutationFn = useConvexMutation(api.admin.deleteOpportunity)
  const { mutate: deleteOpportunity } = useMutation({
    mutationFn: deleteMutationFn,
  })

  const archiveMutationFn = useConvexMutation(api.admin.archiveOpportunity)
  const { mutate: archiveOpportunity } = useMutation({
    mutationFn: archiveMutationFn,
  })

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-display text-foreground">Opportunities</h1>
        <Button asChild>
          <Link to="/admin/opportunities/new">
            <Plus className="w-4 h-4 mr-2" />
            Add Opportunity
          </Link>
        </Button>
      </div>

      {opportunities.length === 0 ? (
        <Card>
          <CardContent className="py-8 text-center text-slate-600">
            No opportunities yet. Add your first one!
          </CardContent>
        </Card>
      ) : (
        <div className="space-y-3">
          {opportunities.map((opp) => (
            <Card
              key={opp._id}
              className={opp.status === 'archived' ? 'opacity-60' : ''}
            >
              <CardContent className="py-4">
                <div className="flex items-start justify-between">
                  <div className="flex-1">
                    <div className="flex items-center gap-2 mb-1">
                      <h3 className="font-medium text-foreground">
                        {opp.title}
                      </h3>
                      <Badge
                        variant={
                          opp.status === 'active' ? 'default' : 'secondary'
                        }
                      >
                        {opp.status}
                      </Badge>
                      <Badge variant="outline">{opp.source}</Badge>
                    </div>
                    <p className="text-sm text-slate-600">
                      {opp.organization} &bull; {opp.location}
                      {opp.isRemote && ' - Remote'}
                    </p>
                    <p className="text-xs text-slate-500 mt-1">
                      Last verified:{' '}
                      {formatDistanceToNow(opp.lastVerified, {
                        addSuffix: true,
                      })}
                    </p>
                  </div>
                  <div className="flex items-center gap-2">
                    <Button variant="ghost" size="sm" asChild>
                      <Link
                        to="/admin/opportunities/$id/edit"
                        params={{ id: opp._id }}
                      >
                        <Pencil className="w-4 h-4" />
                      </Link>
                    </Button>
                    {opp.status === 'active' && (
                      <Button
                        variant="ghost"
                        size="sm"
                        onClick={() => archiveOpportunity({ id: opp._id })}
                      >
                        <Archive className="w-4 h-4" />
                      </Button>
                    )}
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => {
                        if (confirm('Delete this opportunity?')) {
                          deleteOpportunity({ id: opp._id })
                        }
                      }}
                    >
                      <Trash2 className="w-4 h-4 text-red-500" />
                    </Button>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  )
}
