// src/routes/(app)/admin/opportunities/new/+page.svelte
<script lang="ts">
  import OpportunityEditor from '~/components/platform-admin/OpportunityEditor.svelte'
</script>

<section class="space-y-6">
  <div>
    <h1 class="font-display text-3xl text-slate-950">Add opportunity</h1>
    <p class="mt-2 text-sm text-slate-600">Create a new platform-managed opportunity.</p>
  </div>
  <OpportunityEditor mode="create" />
</section>

// src/routes/admin/opportunities/new.tsx
import { createFileRoute } from '@tanstack/react-router'
import { OpportunityForm } from '~/components/admin/opportunity-form'

export const Route = createFileRoute('/admin/opportunities/new')({
  component: NewOpportunityPage,
})

function NewOpportunityPage() {
  return (
    <div>
      <h1 className="text-2xl font-display text-foreground mb-6">
        Add New Opportunity
      </h1>
      <OpportunityForm mode="create" />
    </div>
  )
}
