// src/components/agent-sidebar/AgentSidebarProvider.tsx
import {
  createContext,
  useCallback,
  useContext,
  useEffect,
  useRef,
  useState,
} from 'react'
import { useMutation, useQuery } from 'convex/react'
import { api } from '../../../convex/_generated/api'
import type { Id } from '../../../convex/_generated/dataModel'
import { ConsentDialog } from '~/components/consent/ConsentDialog'

interface AgentSidebarContextValue {
  isOpen: boolean
  toggle: () => void
  open: () => void
  close: () => void
  profileId: Id<'profiles'> | null
  threadId: string | null
  isReady: boolean
  sidebarWidth: number
  setSidebarWidth: (width: number) => void
  isResizing: boolean
  setIsResizing: (v: boolean) => void
  pendingMessage: string | null
  clearPendingMessage: () => void
  openWithMessage: (message: string) => void
}

const AgentSidebarContext = createContext<AgentSidebarContextValue | null>(null)

const STORAGE_KEY = 'agent-sidebar-open'
const WIDTH_STORAGE_KEY = 'agent-sidebar-width'
const DEFAULT_WIDTH = 400
const MIN_WIDTH = 280
const MAX_WIDTH = 600

export function AgentSidebarProvider({
  children,
}: {
  children: React.ReactNode
}) {
  const [isOpen, setIsOpen] = useState(() => {
    if (typeof window === 'undefined') return false
    return localStorage.getItem(STORAGE_KEY) === 'true'
  })
  const [sidebarWidth, setSidebarWidthRaw] = useState(() => {
    if (typeof window === 'undefined') return DEFAULT_WIDTH
    const stored = localStorage.getItem(WIDTH_STORAGE_KEY)
    return stored
      ? Math.max(MIN_WIDTH, Math.min(MAX_WIDTH, Number(stored)))
      : DEFAULT_WIDTH
  })
  const [isResizing, setIsResizing] = useState(false)

  const setSidebarWidth = useCallback((width: number) => {
    const clamped = Math.max(MIN_WIDTH, Math.min(MAX_WIDTH, width))
    setSidebarWidthRaw(clamped)
    localStorage.setItem(WIDTH_STORAGE_KEY, String(clamped))
  }, [])

  const profile = useQuery(api.profiles.getOrCreateProfile)
  const createThread = useMutation(api.agent.threadOps.createAgentThread)
  const sendMessage = useMutation(api.agent.threadOps.sendMessage)
  const threadCreating = useRef(false)
  const autoGreetSent = useRef(false)
  const autoOpenedRef = useRef(false)
  const previousFocusRef = useRef<HTMLElement | null>(null)
  const [showConsentDialog, setShowConsentDialog] = useState(false)
  const [pendingMessage, setPendingMessage] = useState<string | null>(null)
  const clearPendingMessage = useCallback(() => setPendingMessage(null), [])

  // Persist open state
  useEffect(() => {
    localStorage.setItem(STORAGE_KEY, String(isOpen))
  }, [isOpen])

  // Keyboard shortcut: Cmd+. / Ctrl+. to toggle sidebar
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === '.') {
        e.preventDefault()
        setIsOpen((v) => !v)
      }
    }
    window.addEventListener('keydown', handler)
    return () => window.removeEventListener('keydown', handler)
  }, [])

  // Ensure profile + thread exist when sidebar is open and user has a profile
  // (profile being non-null means user is authenticated AND has a profile)
  useEffect(() => {
    if (!profile) return // Loading, unauthenticated, or no profile
    if (!profile.consentedAt) return // Don't create thread without consent
    if (threadCreating.current) return
    if (profile.agentThreadId) return // Already has thread

    if (!isOpen) return // Don't create thread until sidebar is opened

    const setup = async () => {
      threadCreating.current = true
      try {
        const newThreadId = await createThread({ profileId: profile._id })

        // Auto-send greeting for new profiles to trigger BAISH CRM lookup
        // A profile is "new" if it has no name and no enrichment conversation yet
        if (
          !profile.name &&
          !profile.hasEnrichmentConversation &&
          !autoGreetSent.current
        ) {
          autoGreetSent.current = true
          const browserLocale =
            typeof navigator !== 'undefined' ? navigator.language : undefined
          const isSpanish = browserLocale?.startsWith('es')
          await sendMessage({
            threadId: newThreadId,
            prompt: isSpanish
              ? 'Hola! Acabo de registrarme.'
              : 'Hi! I just signed up.',
            profileId: profile._id,
            browserLocale,
          })
        }
      } finally {
        threadCreating.current = false
      }
    }

    setup()
  }, [profile, isOpen, createThread, sendMessage])

  // Auto-open for new users: profile exists but no thread yet
  // If no consent, show consent dialog instead of opening sidebar
  useEffect(() => {
    if (!profile) return
    if (autoOpenedRef.current) return
    if (!profile.agentThreadId) {
      autoOpenedRef.current = true
      if (profile.consentedAt) {
        setIsOpen(true)
      } else {
        setShowConsentDialog(true)
      }
    }
  }, [profile])

  const toggle = useCallback(() => {
    if (!isOpen && profile && !profile.consentedAt) {
      setShowConsentDialog(true)
      return
    }
    setIsOpen((v) => !v)
  }, [isOpen, profile])
  const open = useCallback(() => {
    if (profile && !profile.consentedAt) {
      setShowConsentDialog(true)
      return
    }
    previousFocusRef.current = document.activeElement as HTMLElement | null
    setIsOpen(true)
  }, [profile])
  const openWithMessage = useCallback(
    (message: string) => {
      setPendingMessage(message)
      if (profile && !profile.consentedAt) {
        setShowConsentDialog(true)
        return
      }
      previousFocusRef.current = document.activeElement as HTMLElement | null
      setIsOpen(true)
    },
    [profile],
  )
  const close = useCallback(() => {
    setIsOpen(false)
    const el = previousFocusRef.current
    if (el) {
      requestAnimationFrame(() => el.focus())
      previousFocusRef.current = null
    }
  }, [])

  const profileId = profile?._id ?? null
  const threadId = profile?.agentThreadId ?? null
  const isReady = profileId !== null && threadId !== null

  const handleConsented = useCallback(() => {
    setShowConsentDialog(false)
    setIsOpen(true)
  }, [])

  return (
    <AgentSidebarContext.Provider
      value={{
        isOpen,
        toggle,
        open,
        close,
        profileId,
        threadId,
        isReady,
        sidebarWidth,
        setSidebarWidth,
        isResizing,
        setIsResizing,
        pendingMessage,
        clearPendingMessage,
        openWithMessage,
      }}
    >
      {children}
      <ConsentDialog open={showConsentDialog} onConsented={handleConsented} />
    </AgentSidebarContext.Provider>
  )
}

export function useAgentSidebar() {
  const ctx = useContext(AgentSidebarContext)
  if (!ctx) {
    throw new Error('useAgentSidebar must be used within AgentSidebarProvider')
  }
  return ctx
}

// src/components/agent-sidebar/AgentSidebarProvider.svelte
<script lang="ts">
  import { onMount } from 'svelte'
  import { api } from '$convex/_generated/api'
  import { getClerkContext } from '$lib/stores/clerk.svelte'
  import {
    setAgentSidebarContext,
    type AgentSidebarStore,
  } from '$lib/stores/agent-sidebar.svelte'
  import AgentConsentDialog from '~/components/agent-sidebar/AgentConsentDialog.svelte'
  import { useConvexClient, useQuery } from 'convex-svelte'

  const { children } = $props()

  const clerkContext = getClerkContext()
  const convex = useConvexClient()
  const sidebar = setAgentSidebarContext()

  const profile = useQuery(api.profiles.getOrCreateProfile, () =>
    clerkContext.currentUser ? {} : 'skip',
  )

  let hasAutoOpened = $state(false)
  let isCreatingThread = $state(false)
  let hasSentGreeting = $state(false)

  onMount(() => {
    const handleShortcut = (event: KeyboardEvent) => {
      if ((event.metaKey || event.ctrlKey) && event.key === '.') {
        event.preventDefault()
        sidebar.toggle()
      }
    }

    window.addEventListener('keydown', handleShortcut)

    return () => {
      window.removeEventListener('keydown', handleShortcut)
    }
  })

  $effect(() => {
    sidebar.syncProfile(profile.data ?? null)
  })

  $effect(() => {
    const currentProfile = profile.data

    if (!currentProfile || hasAutoOpened) return
    if (currentProfile.agentThreadId) return

    hasAutoOpened = true

    if (currentProfile.consentedAt) {
      sidebar.open()
      return
    }

    sidebar.showConsentDialog = true
  })

  $effect(() => {
    const currentProfile = profile.data

    if (!currentProfile || !sidebar.isOpen || isCreatingThread) return
    if (!currentProfile.consentedAt || currentProfile.agentThreadId) return

    isCreatingThread = true

    void convex
      .mutation(api.agent.threadOps.createAgentThread, {
        profileId: currentProfile._id,
      })
      .then(async (threadId) => {
        if (
          currentProfile.name ||
          currentProfile.hasEnrichmentConversation ||
          hasSentGreeting
        ) {
          return
        }

        hasSentGreeting = true
        const browserLocale =
          typeof navigator === 'undefined' ? undefined : navigator.language

        await convex.mutation(api.agent.threadOps.sendMessage, {
          threadId,
          prompt: browserLocale?.startsWith('es')
            ? 'Hola! Acabo de registrarme.'
            : 'Hi! I just signed up.',
          profileId: currentProfile._id,
          browserLocale,
        })
      })
      .catch(() => {
        // Thread bootstrap is best effort.
      })
      .finally(() => {
        isCreatingThread = false
      })
  })

  const handleConsented = () => {
    sidebar.showConsentDialog = false
    sidebar.hasConsent = true
    sidebar.open()
  }
</script>

{@render children()}

<AgentConsentDialog open={sidebar.showConsentDialog} onConsented={handleConsented} />
