// src/components/agent-sidebar/AgentSidebar.tsx
import { X } from 'lucide-react'
import { Authenticated } from 'convex/react'

import { useAgentSidebar } from './AgentSidebarProvider'
import { AgentChat } from '~/components/profile/agent/AgentChat'
import { useAgentPageContext } from '~/hooks/use-agent-page-context'
import { useIsMobile } from '~/hooks/use-media-query'
import { Spinner } from '~/components/ui/spinner'
import { Button } from '~/components/ui/button'
import { Sheet, SheetContent, SheetTitle } from '~/components/ui/sheet'
import { cn } from '~/lib/utils'

function AgentSidebarInner() {
  const { isOpen, close, profileId, threadId, isReady } = useAgentSidebar()
  const pageContext = useAgentPageContext()
  const isMobile = useIsMobile()

  if (isMobile) {
    return (
      <Sheet open={isOpen} onOpenChange={(open) => !open && close()}>
        <SheetContent
          side="bottom"
          className="h-[85vh] max-h-[85vh] rounded-t-xl p-0"
          showCloseButton={false}
        >
          <SheetTitle className="sr-only">AI Assistant</SheetTitle>
          {/* Drag handle */}
          <div className="flex justify-center py-2">
            <div className="w-10 h-1 rounded-full bg-muted-foreground/30" />
          </div>
          {isReady ? (
            <div className="flex-1 min-h-0 h-[calc(85vh-24px)]">
              <AgentChat
                profileId={profileId!}
                threadId={threadId!}
                pageContext={pageContext}
              />
            </div>
          ) : (
            <div className="flex items-center justify-center h-full">
              <Spinner />
            </div>
          )}
        </SheetContent>
      </Sheet>
    )
  }

  // Desktop: fixed right panel
  return (
    <div
      className={cn(
        'fixed top-0 right-0 h-full w-[400px] z-40 bg-background border-l shadow-lg',
        'transition-transform duration-300 ease-in-out',
        isOpen ? 'translate-x-0' : 'translate-x-full',
      )}
    >
      {/* Close button overlaid on top-right */}
      <Button
        variant="ghost"
        size="icon"
        onClick={close}
        className="absolute top-1.5 right-2 z-10 size-7"
      >
        <X className="size-3.5" />
      </Button>
      {isReady ? (
        <div className="h-full">
          <AgentChat
            profileId={profileId!}
            threadId={threadId!}
            pageContext={pageContext}
          />
        </div>
      ) : (
        <div className="flex items-center justify-center h-full">
          <Spinner />
        </div>
      )}
    </div>
  )
}

export function AgentSidebar() {
  return (
    <Authenticated>
      <AgentSidebarInner />
    </Authenticated>
  )
}

// src/components/agent-sidebar/AgentSidebar.svelte
<script lang="ts">
  import { ChevronLeft } from 'lucide-svelte'
  import { useIsMobile } from '$lib/stores/media-query.svelte'
  import { getAgentSidebarContext } from '$lib/stores/agent-sidebar.svelte'
  import AgentFAB from '~/components/agent-sidebar/AgentFAB.svelte'
  import AgentProfileBuilder from '~/components/profile/agent/AgentProfileBuilder.svelte'
  import Spinner from '~/components/ui/spinner.svelte'

  const sidebar = getAgentSidebarContext()
  const isMobile = useIsMobile()
</script>

{#if !sidebar.isOpen}
  <AgentFAB />
{:else}
  {#if $isMobile}
    <div class="fixed inset-x-0 bottom-0 z-50 h-[84dvh] rounded-t-[2rem] border border-border/70 bg-background shadow-2xl">
      <div class="flex items-center justify-between border-b border-border/70 px-4 py-3">
        <div>
          <p class="text-xs font-medium uppercase tracking-[0.16em] text-coral-700">AI Assistant</p>
          <p class="text-sm text-slate-600">Profile copilot</p>
        </div>
        <button
          type="button"
          class="rounded-full border border-border px-3 py-1.5 text-sm text-slate-700 transition hover:bg-accent"
          onclick={() => sidebar.close()}
        >
          Close
        </button>
      </div>

      <div class="h-[calc(84dvh-73px)] p-4">
        {#if sidebar.profileId && sidebar.threadId}
          <AgentProfileBuilder profileId={sidebar.profileId} threadId={sidebar.threadId} />
        {:else}
          <div class="flex h-full items-center justify-center">
            <Spinner />
          </div>
        {/if}
      </div>
    </div>
  {:else}
    <div
      class="fixed inset-y-0 left-0 z-40 border-r border-border/70 bg-background shadow-2xl"
      style={`width:${sidebar.sidebarWidth}px`}
    >
      <button
        type="button"
        class="absolute right-4 top-4 inline-flex items-center gap-2 rounded-full border border-border bg-white px-3 py-1.5 text-sm text-slate-700 transition hover:bg-accent"
        onclick={() => sidebar.close()}
      >
        <ChevronLeft class="size-4" />
        Close
      </button>

      <div class="h-full p-4 pt-16">
        {#if sidebar.profileId && sidebar.threadId}
          <AgentProfileBuilder profileId={sidebar.profileId} threadId={sidebar.threadId} />
        {:else}
          <div class="flex h-full items-center justify-center">
            <Spinner />
          </div>
        {/if}
      </div>
    </div>
  {/if}
{/if}
