// src/components/agent-sidebar/SidebarAwareWrapper.svelte
<script lang="ts">
  import { getAgentSidebarContext } from '$lib/stores/agent-sidebar.svelte'
  import { useMediaQuery } from '$lib/stores/media-query.svelte'
  import { cn } from '~/lib/utils'

  const { children } = $props<{ children?: () => unknown }>()

  const sidebar = getAgentSidebarContext()
  const hasRoomForSidebar = useMediaQuery('(min-width: 900px)')
</script>

<div
  class={cn(!sidebar.isResizing && 'transition-[margin-left] duration-300 ease-in-out')}
  style:margin-left={sidebar.isOpen && $hasRoomForSidebar ? `${sidebar.sidebarWidth}px` : '0px'}
>
  {@render children?.()}
</div>

// src/components/agent-sidebar/SidebarAwareWrapper.tsx
import { useAgentSidebar } from './AgentSidebarProvider'
import { useMediaQuery } from '~/hooks/use-media-query'
import { cn } from '~/lib/utils'

export function SidebarAwareWrapper({
  children,
}: {
  children: React.ReactNode
}) {
  const { isOpen, sidebarWidth, isResizing } = useAgentSidebar()
  // Only push content when there's enough room
  // Below 900px, the sidebar overlays content instead
  const hasRoomForSidebar = useMediaQuery('(min-width: 900px)')
  const shouldPush = isOpen && hasRoomForSidebar

  return (
    <div
      className={cn(
        !isResizing && 'transition-[margin-left] duration-300 ease-in-out',
      )}
      style={{ marginLeft: shouldPush ? sidebarWidth : 0 }}
    >
      {children}
    </div>
  )
}
