// src/routes/admin/index.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'

export const Route = createFileRoute('/admin/')({
  component: AdminDashboard,
})

function AdminDashboard() {
  return (
    <div>
      <h1 className="text-2xl font-display text-foreground mb-6">
        Admin Dashboard
      </h1>
      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">
        <Link to="/admin/opportunities">
          <Card className="hover:shadow-md transition-shadow cursor-pointer">
            <CardHeader>
              <CardTitle className="text-lg">Opportunities</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-slate-600">
                Manage job opportunities, add new listings, edit existing ones.
              </p>
            </CardContent>
          </Card>
        </Link>
        <Link to="/admin/applications">
          <Card className="hover:shadow-md transition-shadow cursor-pointer">
            <CardHeader>
              <CardTitle className="text-lg">Org Applications</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-slate-600">
                Review and approve organization applications to join ASTN.
              </p>
            </CardContent>
          </Card>
        </Link>
        <Link to="/admin/users">
          <Card className="hover:shadow-md transition-shadow cursor-pointer">
            <CardHeader>
              <CardTitle className="text-lg">Users</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-slate-600">
                Browse user profiles, view agent conversations, and review data.
              </p>
            </CardContent>
          </Card>
        </Link>
        <Link to="/admin/costs">
          <Card className="hover:shadow-md transition-shadow cursor-pointer">
            <CardHeader>
              <CardTitle className="text-lg">LLM Costs</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="text-sm text-slate-600">
                Monitor AI model usage, costs, and token consumption across all
                operations.
              </p>
            </CardContent>
          </Card>
        </Link>
      </div>
    </div>
  )
}

// src/routes/(app)/admin/+page.svelte
<section class="space-y-6">
  <div class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-6 shadow-warm-sm">
    <p class="text-xs font-semibold uppercase tracking-[0.22em] text-coral-600">Platform admin</p>
    <h1 class="mt-2 font-display text-3xl text-slate-950">Operations center</h1>
    <p class="mt-3 max-w-2xl text-sm leading-6 text-slate-600">
      Review organization applications, inspect user profiles, manage platform-wide opportunities, and watch model spend.
    </p>
  </div>

  <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-4">
    <a href="/admin/applications" class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-5 shadow-warm-sm transition hover:-translate-y-0.5 hover:shadow-lg">
      <h2 class="text-lg font-semibold text-slate-950">Applications</h2>
      <p class="mt-2 text-sm text-slate-600">Review pending org applications and decisions.</p>
    </a>
    <a href="/admin/users" class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-5 shadow-warm-sm transition hover:-translate-y-0.5 hover:shadow-lg">
      <h2 class="text-lg font-semibold text-slate-950">Users</h2>
      <p class="mt-2 text-sm text-slate-600">Inspect profiles, matches, and agent history.</p>
    </a>
    <a href="/admin/opportunities" class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-5 shadow-warm-sm transition hover:-translate-y-0.5 hover:shadow-lg">
      <h2 class="text-lg font-semibold text-slate-950">Opportunities</h2>
      <p class="mt-2 text-sm text-slate-600">Create and edit platform opportunities.</p>
    </a>
    <a href="/admin/costs" class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-5 shadow-warm-sm transition hover:-translate-y-0.5 hover:shadow-lg">
      <h2 class="text-lg font-semibold text-slate-950">LLM Costs</h2>
      <p class="mt-2 text-sm text-slate-600">Track model usage and total spend over time.</p>
    </a>
  </div>
</section>
