// src/components/admin-agent/AdminAgentSidebar.svelte
<script lang="ts">
  import { ChevronLeft, ChevronRight } from 'lucide-svelte'
  import { useIsMobile, useMediaQuery } from '$lib/stores/media-query.svelte'
  import { getAdminAgentContext } from '$lib/stores/admin-agent.svelte'
  import AdminAgentChat from './AdminAgentChat.svelte'

  const agent = getAdminAgentContext()
  const isMobile = useIsMobile()
  const hasRoomForSidebar = useMediaQuery('(min-width: 900px)')

  const startResize = (event: MouseEvent) => {
    event.preventDefault()
    agent.isResizing = true

    const handleMove = (moveEvent: MouseEvent) => {
      agent.setSidebarWidth(window.innerWidth - moveEvent.clientX)
    }

    const handleUp = () => {
      agent.isResizing = false
      window.removeEventListener('mousemove', handleMove)
      window.removeEventListener('mouseup', handleUp)
    }

    window.addEventListener('mousemove', handleMove)
    window.addEventListener('mouseup', handleUp)
  }
</script>

{#if $isMobile}
  {#if agent.isOpen}
    <div
      class="fixed inset-0 z-40 bg-black/30"
      onclick={() => agent.close()}
      onkeydown={(event) => {
        if (event.key === 'Enter' || event.key === ' ') {
          agent.close()
        }
      }}
      role="button"
      tabindex="0"
      aria-label="Close admin agent overlay"
    ></div>
    <div class="fixed inset-x-0 bottom-0 z-50 h-[84dvh] rounded-t-[2rem] border border-border/70 bg-background shadow-2xl">
      <div class="flex items-center justify-between border-b border-border/70 px-4 py-3">
        <div>
          <p class="text-xs font-medium uppercase tracking-[0.16em] text-coral-700">
            Org Agent
          </p>
          <p class="text-sm text-slate-600">Admin operations copilot</p>
        </div>
        <button
          type="button"
          class="rounded-full border border-border px-3 py-1.5 text-sm text-slate-700 transition hover:bg-accent"
          onclick={() => agent.close()}
        >
          Close
        </button>
      </div>
      <div class="h-[calc(84dvh-73px)]">
        <AdminAgentChat />
      </div>
    </div>
  {/if}
{:else}
  <button
    type="button"
    class={`fixed top-1/2 z-50 flex h-12 w-7 -translate-y-1/2 items-center justify-center rounded-l-xl border border-r-0 border-border/70 bg-white shadow-md ${
      agent.isResizing ? '' : 'transition-[right] duration-300 ease-in-out'
    }`}
    onclick={() => agent.toggle()}
    style:right={agent.isOpen ? `${agent.sidebarWidth}px` : '0px'}
    aria-label={agent.isOpen ? 'Close admin agent' : 'Open admin agent'}
  >
    {#if agent.isOpen}
      <ChevronRight class="size-4 text-slate-500" />
    {:else}
      <ChevronLeft class="size-4 text-slate-500" />
    {/if}
  </button>

  {#if agent.isOpen && !$hasRoomForSidebar}
    <div
      class="fixed inset-0 z-30 bg-black/20"
      onclick={() => agent.close()}
      onkeydown={(event) => {
        if (event.key === 'Enter' || event.key === ' ') {
          agent.close()
        }
      }}
      role="button"
      tabindex="0"
      aria-label="Close admin agent overlay"
    ></div>
  {/if}

  <aside
    class={`fixed inset-y-0 right-0 z-40 border-l border-border/70 bg-background shadow-2xl ${
      agent.isResizing ? '' : 'transition-transform duration-300 ease-in-out'
    } ${agent.isOpen ? 'translate-x-0' : 'translate-x-full'}`}
    style={`width:${agent.sidebarWidth}px`}
  >
    <AdminAgentChat />

    {#if agent.isOpen}
      <div
        class="absolute -left-px top-0 h-full w-1 cursor-col-resize hover:bg-coral-200"
        onmousedown={startResize}
        role="presentation"
      ></div>
    {/if}
  </aside>
{/if}

// src/components/admin-agent/AdminAgentSidebar.tsx
import { useRef } from 'react'
import { ChevronLeft, ChevronRight } from 'lucide-react'

import { useAdminAgentSidebar } from './AdminAgentProvider'
import { AdminAgentChat } from './AdminAgentChat'
import { useIsMobile, useMediaQuery } from '~/hooks/use-media-query'
import { Sheet, SheetContent, SheetTitle } from '~/components/ui/sheet'
import { cn } from '~/lib/utils'

export function AdminAgentSidebar() {
  const {
    isOpen,
    open,
    close,
    sidebarWidth,
    setSidebarWidth,
    isResizing,
    setIsResizing,
    agent,
    orgSlug,
  } = useAdminAgentSidebar()
  const isMobile = useIsMobile()
  const hasRoomForSidebar = useMediaQuery('(min-width: 900px)')
  const resizeRef = useRef(false)

  const handleResizeStart = (e: React.MouseEvent) => {
    e.preventDefault()
    resizeRef.current = true
    setIsResizing(true)

    const handleMouseMove = (ev: MouseEvent) => {
      if (!resizeRef.current) return
      // Right-side sidebar: width = viewport width - mouse X
      setSidebarWidth(window.innerWidth - ev.clientX)
    }

    const handleMouseUp = () => {
      resizeRef.current = false
      setIsResizing(false)
      document.removeEventListener('mousemove', handleMouseMove)
      document.removeEventListener('mouseup', handleMouseUp)
    }

    document.addEventListener('mousemove', handleMouseMove)
    document.addEventListener('mouseup', handleMouseUp)
  }

  if (isMobile) {
    return (
      <Sheet open={isOpen} onOpenChange={(v) => !v && close()}>
        <SheetContent
          side="bottom"
          className="h-[85dvh] max-h-[85dvh] rounded-t-xl p-0 pb-[env(safe-area-inset-bottom,0px)]"
          showCloseButton={false}
        >
          <SheetTitle className="sr-only">Admin Agent</SheetTitle>
          {/* Drag handle */}
          <div className="flex justify-center py-2">
            <div className="w-10 h-1 rounded-full bg-muted-foreground/30" />
          </div>
          <div className="flex-1 min-h-0 h-[calc(85dvh-24px)]">
            <AdminAgentChat agent={agent} orgSlug={orgSlug} />
          </div>
        </SheetContent>
      </Sheet>
    )
  }

  // Desktop: fixed right panel
  return (
    <>
      {/* Backdrop overlay for narrow desktop */}
      {isOpen && !hasRoomForSidebar && (
        <div
          className="fixed inset-0 z-30 bg-black/20 transition-opacity"
          onClick={close}
        />
      )}

      {/* Edge chevron tab -- slides with the sidebar */}
      <button
        onClick={isOpen ? close : open}
        className={cn(
          'fixed top-1/2 -translate-y-1/2 z-50 flex items-center justify-center',
          'h-12 w-6 rounded-l-lg bg-background border border-r-0 shadow-md',
          'hover:bg-accent',
          !isResizing && 'transition-[right] duration-300 ease-in-out',
        )}
        style={{ right: isOpen ? sidebarWidth : 0 }}
        aria-label={isOpen ? 'Close admin agent' : 'Open admin agent'}
      >
        {isOpen ? (
          <ChevronRight className="size-4 text-muted-foreground" />
        ) : (
          <ChevronLeft className="size-4 text-muted-foreground" />
        )}
      </button>

      <div
        className={cn(
          'fixed top-0 right-0 h-full z-40 bg-background shadow-lg',
          !isResizing && 'transition-transform duration-300 ease-in-out',
          isOpen ? 'translate-x-0' : 'translate-x-full',
        )}
        style={{ width: sidebarWidth }}
      >
        <div className="h-full">
          <AdminAgentChat agent={agent} orgSlug={orgSlug} />
        </div>

        {/* Resize handle on left edge */}
        {isOpen && (
          <div
            onMouseDown={handleResizeStart}
            className={cn(
              'absolute top-0 -left-px w-1 h-full cursor-col-resize group z-50',
              'hover:bg-primary/30 active:bg-primary/50',
              isResizing && 'bg-primary/50',
            )}
          >
            <div className="absolute inset-y-0 -left-1 -right-1" />
          </div>
        )}
      </div>
    </>
  )
}
