// src/routes/(app)/org/[slug]/admin/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import {
    ArrowRight,
    Briefcase,
    CalendarCheck2,
    CheckCircle2,
    Copy,
    FileText,
    FolderKanban,
    MapPin,
    Settings,
    UserPlus,
    Users,
    Wrench,
  } from 'lucide-svelte'
  import { toast } from 'svelte-sonner'
  import { api } from '$convex/_generated/api'
  import AdminSection from '~/components/org-admin/core/AdminSection.svelte'

  type TimeRange = '7d' | '30d' | '90d' | 'all'

  const convex = useConvexClient()
  const slug = $derived(page.params.slug ?? null)

  let timeRange = $state<TimeRange>('30d')
  let inviteActionPending = $state(false)

  const org = useQuery(api.orgs.directory.getOrgBySlug, () =>
    slug
      ? {
          slug,
        }
      : 'skip',
  )

  const membership = useQuery(api.orgs.membership.getMembership, () =>
    org.data
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  const onboarding = useQuery(api.orgs.admin.getOnboardingProgress, () =>
    org.data && membership.data?.role === 'admin'
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  const stats = useQuery(api.orgs.stats.getEnhancedOrgStats, () =>
    org.data && membership.data?.role === 'admin'
      ? {
          orgId: org.data._id,
          timeRange,
        }
      : 'skip',
  )

  const space = useQuery(api.coworkingSpaces.getSpaceByOrg, () =>
    org.data && membership.data?.role === 'admin'
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  const applicationCount = useQuery(api.opportunityApplications.getOrgApplicationCount, () =>
    org.data && membership.data?.role === 'admin'
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  const inviteLinks = useQuery(api.orgs.admin.getInviteLinks, () =>
    org.data && membership.data?.role === 'admin'
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  const activeInviteUrl = $derived.by(() => {
    if (!inviteLinks.data?.length || !slug || typeof window === 'undefined') {
      return null
    }

    return `${window.location.origin}/org/${slug}/join?token=${inviteLinks.data[0].token}`
  })

  const engagementEntries = $derived.by(() =>
    stats.data?.engagementDistribution
      ? Object.entries(stats.data.engagementDistribution).filter(([, count]) => count > 0)
      : [],
  )

  const topSkills = $derived(stats.data?.skillsDistribution ?? [])

  const adminState = $derived.by(() => {
    if (org.isLoading || membership.isLoading) return 'loading'
    if (!org.data) return 'missing'
    if (membership.data?.role !== 'admin') return 'forbidden'
    return 'ready'
  })

  const handleInviteAction = async () => {
    if (!org.data) return

    try {
      inviteActionPending = true

      if (activeInviteUrl) {
        await navigator.clipboard.writeText(activeInviteUrl)
        toast.success('Invite link copied')
        return
      }

      const result = await convex.mutation(api.orgs.admin.getOrCreateInviteLink, {
        orgId: org.data._id,
      })

      const url = `${window.location.origin}/org/${slug}/join?token=${result.token}`
      await navigator.clipboard.writeText(url)
      toast.success('Invite link created and copied')
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to manage invite link')
    } finally {
      inviteActionPending = false
    }
  }
</script>

{#if adminState === 'loading'}
  <div class="space-y-6">
    <div class="h-32 animate-pulse rounded-[1.75rem] bg-slate-100"></div>
    <div class="grid gap-4 md:grid-cols-3">
      {#each Array.from({ length: 3 }) as _, index (index)}
        <div class="h-32 animate-pulse rounded-[1.75rem] bg-slate-100"></div>
      {/each}
    </div>
  </div>
{:else if adminState === 'missing'}
  <div class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-10 text-center shadow-warm-sm">
    <h1 class="font-display text-3xl text-slate-950">Organization not found</h1>
    <p class="mt-3 text-sm leading-6 text-slate-600">
      The organization for this admin workspace could not be found.
    </p>
    <a
      href="/orgs"
      class="mt-6 inline-flex rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600"
    >
      Browse organizations
    </a>
  </div>
{:else if adminState === 'forbidden'}
  <div class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-10 text-center shadow-warm-sm">
    <h1 class="font-display text-3xl text-slate-950">Admin access required</h1>
    <p class="mt-3 text-sm leading-6 text-slate-600">
      You need to be an organization admin to use this dashboard.
    </p>
    <a
      href={`/org/${slug}`}
      class="mt-6 inline-flex rounded-xl border border-border px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50"
    >
      Back to organization
    </a>
  </div>
{:else}
  <div class="space-y-6">
    <section class="overflow-hidden rounded-[1.75rem] border border-border/70 bg-[linear-gradient(135deg,rgba(255,247,237,0.92),rgba(255,255,255,0.96))] shadow-warm-sm">
      <div class="grid gap-4 px-6 py-6 md:grid-cols-[minmax(0,1fr)_auto] md:items-end">
        <div>
          <p class="text-xs font-semibold uppercase tracking-[0.22em] text-coral-600">
            Admin overview
          </p>
          <h1 class="mt-2 font-display text-3xl text-slate-950 md:text-4xl">
            {org.data?.name}
          </h1>
          <p class="mt-3 max-w-2xl text-sm leading-6 text-slate-600">
            Track members, keep onboarding moving, and jump into operational work
            without leaving the org workspace.
          </p>
        </div>

        <div class="flex flex-wrap gap-3">
          <button
            type="button"
            class="inline-flex items-center gap-2 rounded-xl bg-slate-950 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-slate-800 disabled:cursor-not-allowed disabled:opacity-60"
            onclick={handleInviteAction}
            disabled={inviteActionPending}
          >
            <Copy class="size-4" />
            <span>{activeInviteUrl ? 'Copy invite link' : 'Create invite link'}</span>
          </button>
          <a
            href={`/org/${slug}`}
            class="inline-flex items-center gap-2 rounded-xl border border-border bg-white/85 px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-white"
          >
            View public page
            <ArrowRight class="size-4" />
          </a>
        </div>
      </div>
    </section>

    <div class="grid gap-4 md:grid-cols-2 xl:grid-cols-5">
      <div class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-4 shadow-warm-sm">
        <div class="flex items-center justify-between">
          <span class="text-sm text-slate-500">Members</span>
          <Users class="size-4 text-slate-400" />
        </div>
        <div class="mt-3 text-3xl font-semibold text-slate-950">
          {stats.data?.memberCount ?? '—'}
        </div>
      </div>

      <div class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-4 shadow-warm-sm">
        <div class="flex items-center justify-between">
          <span class="text-sm text-slate-500">Admins</span>
          <UserPlus class="size-4 text-slate-400" />
        </div>
        <div class="mt-3 text-3xl font-semibold text-slate-950">
          {stats.data?.adminCount ?? '—'}
        </div>
      </div>

      <div class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-4 shadow-warm-sm">
        <div class="flex items-center justify-between">
          <span class="text-sm text-slate-500">New in range</span>
          <CheckCircle2 class="size-4 text-slate-400" />
        </div>
        <div class="mt-3 text-3xl font-semibold text-slate-950">
          {stats.data?.joinedThisMonth ?? '—'}
        </div>
      </div>

      <div class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-4 shadow-warm-sm">
        <div class="flex items-center justify-between">
          <span class="text-sm text-slate-500">Applications</span>
          <FileText class="size-4 text-slate-400" />
        </div>
        <div class="mt-3 text-3xl font-semibold text-slate-950">
          {applicationCount.data ?? '—'}
        </div>
      </div>

      <div class="rounded-[1.5rem] border border-border/70 bg-white/92 px-5 py-4 shadow-warm-sm">
        <div class="flex items-center justify-between">
          <span class="text-sm text-slate-500">Event attendance</span>
          <CalendarCheck2 class="size-4 text-slate-400" />
        </div>
        <div class="mt-3 text-3xl font-semibold text-slate-950">
          {stats.data?.eventMetrics.attendanceRate ?? 0}%
        </div>
      </div>
    </div>

    <AdminSection
      title="Quick actions"
      subtitle="Jump directly into the most common admin tasks."
    >
      <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        <a href={`/org/${slug}/admin/members`} class="rounded-2xl border border-border p-4 transition hover:border-slate-300 hover:bg-slate-50">
          <Users class="size-5 text-coral-500" />
          <h3 class="mt-3 font-medium text-slate-950">Members</h3>
          <p class="mt-1 text-sm text-slate-600">Manage roles, review profiles, and keep the directory healthy.</p>
        </a>
        <a href={`/org/${slug}/admin/applications`} class="rounded-2xl border border-border p-4 transition hover:border-slate-300 hover:bg-slate-50">
          <FileText class="size-5 text-coral-500" />
          <h3 class="mt-3 font-medium text-slate-950">Applications</h3>
          <p class="mt-1 text-sm text-slate-600">Review incoming opportunity applications and export responses.</p>
        </a>
        <a href={`/org/${slug}/admin/opportunities`} class="rounded-2xl border border-border p-4 transition hover:border-slate-300 hover:bg-slate-50">
          <Briefcase class="size-5 text-coral-500" />
          <h3 class="mt-3 font-medium text-slate-950">Opportunities</h3>
          <p class="mt-1 text-sm text-slate-600">Publish openings, edit forms, and monitor applicant funnels.</p>
        </a>
        <a href={`/org/${slug}/admin/setup`} class="rounded-2xl border border-border p-4 transition hover:border-slate-300 hover:bg-slate-50">
          <Wrench class="size-5 text-coral-500" />
          <h3 class="mt-3 font-medium text-slate-950">Setup</h3>
          <p class="mt-1 text-sm text-slate-600">Tune branding, invitations, and basic org information.</p>
        </a>
        <a href={`/org/${slug}/admin/programs`} class="rounded-2xl border border-border p-4 transition hover:border-slate-300 hover:bg-slate-50">
          <FolderKanban class="size-5 text-coral-500" />
          <h3 class="mt-3 font-medium text-slate-950">Programs</h3>
          <p class="mt-1 text-sm text-slate-600">Run cohorts, track attendance, and coordinate sessions.</p>
        </a>
        <a href={`/org/${slug}/admin/space`} class="rounded-2xl border border-border p-4 transition hover:border-slate-300 hover:bg-slate-50">
          <MapPin class="size-5 text-coral-500" />
          <h3 class="mt-3 font-medium text-slate-950">Space</h3>
          <p class="mt-1 text-sm text-slate-600">Configure co-working details and manage visit workflows.</p>
        </a>
        <a href={`/org/${slug}/admin/bookings`} class="rounded-2xl border border-border p-4 transition hover:border-slate-300 hover:bg-slate-50">
          <CalendarCheck2 class="size-5 text-coral-500" />
          <h3 class="mt-3 font-medium text-slate-950">Bookings</h3>
          <p class="mt-1 text-sm text-slate-600">Track reservation volume and daily usage for the workspace.</p>
        </a>
        <a href={`/org/${slug}/admin/settings`} class="rounded-2xl border border-border p-4 transition hover:border-slate-300 hover:bg-slate-50">
          <Settings class="size-5 text-coral-500" />
          <h3 class="mt-3 font-medium text-slate-950">Settings</h3>
          <p class="mt-1 text-sm text-slate-600">Connect Lu.ma and other integrations that power the org page.</p>
        </a>
      </div>
    </AdminSection>

    <div class="grid gap-6 xl:grid-cols-[minmax(0,1.1fr)_minmax(0,0.9fr)]">
      <AdminSection
        title="Onboarding progress"
        subtitle="The highest leverage setup steps for getting the org fully live."
      >
        {#if onboarding.data}
          <div class="space-y-4">
            <div class="rounded-2xl border border-border bg-slate-50 px-4 py-4">
              <div class="flex items-center justify-between gap-4">
                <div>
                  <p class="text-sm font-medium text-slate-900">
                    {onboarding.data.completedCount} of {onboarding.data.totalCount} steps complete
                  </p>
                  <p class="mt-1 text-sm text-slate-600">
                    {onboarding.data.isComplete
                      ? 'Your organization setup is complete.'
                      : 'Finish the remaining steps to unlock a smoother member experience.'}
                  </p>
                </div>
                <div class="text-3xl font-semibold text-slate-950">
                  {onboarding.data.percentage}%
                </div>
              </div>
              <div class="mt-4 h-2 rounded-full bg-slate-200">
                <div
                  class="h-2 rounded-full bg-coral-500 transition-[width]"
                  style={`width:${onboarding.data.percentage}%`}
                ></div>
              </div>
            </div>

            <div class="grid gap-3">
              {#each onboarding.data.steps as step}
                <a
                  href={`/org/${slug}/admin/${step.route}`}
                  class={`flex items-start gap-3 rounded-2xl border px-4 py-3 transition ${
                    step.complete
                      ? 'border-emerald-200 bg-emerald-50/70'
                      : 'border-border bg-white hover:bg-slate-50'
                  }`}
                >
                  <div class={`mt-0.5 flex size-6 items-center justify-center rounded-full ${
                    step.complete ? 'bg-emerald-500 text-white' : 'bg-slate-200 text-slate-500'
                  }`}>
                    {#if step.complete}
                      <CheckCircle2 class="size-4" />
                    {:else}
                      <span class="text-xs font-semibold">•</span>
                    {/if}
                  </div>
                  <div class="min-w-0">
                    <p class="text-sm font-medium text-slate-900">{step.label}</p>
                    <p class="mt-1 text-xs uppercase tracking-[0.18em] text-slate-500">
                      {step.route}
                    </p>
                  </div>
                </a>
              {/each}
            </div>
          </div>
        {:else}
          <p class="text-sm text-slate-500">Loading setup progress…</p>
        {/if}
      </AdminSection>

      <AdminSection
        title="Community snapshot"
        subtitle="A lightweight view of engagement and profile quality."
      >
        {#snippet actions()}
          <div class="inline-flex rounded-full border border-border bg-slate-50 p-1 text-xs">
            {#each (['7d', '30d', '90d', 'all'] as TimeRange[]) as range}
              <button
                type="button"
                class={`rounded-full px-3 py-1.5 transition ${
                  timeRange === range
                    ? 'bg-slate-950 text-white'
                    : 'text-slate-600 hover:text-slate-950'
                }`}
                onclick={() => {
                  timeRange = range
                }}
              >
                {range}
              </button>
            {/each}
          </div>
        {/snippet}
        <div class="space-y-5">
          <div>
            <div class="mb-2 flex items-center justify-between text-sm text-slate-600">
              <span>Profile completeness</span>
              <span>{stats.data ? `${stats.data.completenessDistribution.high} high` : '—'}</span>
            </div>
            <div class="grid grid-cols-3 gap-2 text-center text-xs">
              <div class="rounded-2xl border border-emerald-200 bg-emerald-50 px-3 py-3">
                <div class="text-xl font-semibold text-emerald-700">
                  {stats.data?.completenessDistribution.high ?? 0}
                </div>
                <div class="mt-1 text-emerald-700/80">High</div>
              </div>
              <div class="rounded-2xl border border-amber-200 bg-amber-50 px-3 py-3">
                <div class="text-xl font-semibold text-amber-700">
                  {stats.data?.completenessDistribution.medium ?? 0}
                </div>
                <div class="mt-1 text-amber-700/80">Medium</div>
              </div>
              <div class="rounded-2xl border border-slate-200 bg-slate-50 px-3 py-3">
                <div class="text-xl font-semibold text-slate-700">
                  {stats.data?.completenessDistribution.low ?? 0}
                </div>
                <div class="mt-1 text-slate-700/80">Low</div>
              </div>
            </div>
          </div>

          <div>
            <p class="text-sm font-medium text-slate-900">Engagement mix</p>
            <div class="mt-3 space-y-2">
              {#if engagementEntries.length}
                {#each engagementEntries as [label, count]}
                  <div>
                    <div class="mb-1 flex items-center justify-between text-sm text-slate-600">
                      <span>{label.replaceAll('_', ' ')}</span>
                      <span>{count}</span>
                    </div>
                    <div class="h-2 rounded-full bg-slate-200">
                      <div
                        class="h-2 rounded-full bg-slate-950"
                        style={`width:${stats.data?.memberCount ? Math.max((count / stats.data.memberCount) * 100, 6) : 0}%`}
                      ></div>
                    </div>
                  </div>
                {/each}
              {:else}
                <p class="text-sm text-slate-500">No engagement data yet.</p>
              {/if}
            </div>
          </div>

          <div>
            <p class="text-sm font-medium text-slate-900">Top skills</p>
            <div class="mt-3 flex flex-wrap gap-2">
              {#if topSkills.length}
                {#each topSkills as skill}
                  <span class="rounded-full border border-border bg-slate-50 px-3 py-1.5 text-xs font-medium text-slate-700">
                    {skill.name} · {skill.count}
                  </span>
                {/each}
              {:else}
                <p class="text-sm text-slate-500">No skills captured yet.</p>
              {/if}
            </div>
          </div>

          <div class="rounded-2xl border border-border bg-slate-50 px-4 py-3 text-sm text-slate-600">
            <span class="font-medium text-slate-900">Space status:</span>
            {space.data ? ` ${space.data.name} is configured for member bookings.` : ' No co-working space is configured yet.'}
          </div>
        </div>
      </AdminSection>
    </div>
  </div>
{/if}

// src/routes/org/$slug/admin/index.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { useMutation, useQuery } from 'convex/react'
import { useState } from 'react'
import {
  Briefcase,
  Building2,
  Calendar,
  CalendarCheck,
  FileText,
  FolderPlus,
  MapPin,
  Settings,
  Shield,
  UserPlus,
  Users,
  Wrench,
} from 'lucide-react'
import { api } from '../../../../../convex/_generated/api'
import type { Id } from '../../../../../convex/_generated/dataModel'
import { AuthHeader } from '~/components/layout/auth-header'
import { GuestConversionCard } from '~/components/org/GuestConversionCard'
import { OnboardingChecklist } from '~/components/org/OnboardingChecklist'
import { OrgStats } from '~/components/org/OrgStats'
import { SpaceUtilizationCard } from '~/components/org/SpaceUtilizationCard'
import { Card, CardContent, CardHeader, CardTitle } from '~/components/ui/card'
import { Button } from '~/components/ui/button'
import { Spinner } from '~/components/ui/spinner'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '~/components/ui/select'
import { useDotGridStyle } from '~/hooks/use-dot-grid-style'

export const Route = createFileRoute('/org/$slug/admin/')({
  component: OrgAdminDashboard,
})

type TimeRange = '7d' | '30d' | '90d' | 'all'

function OrgAdminDashboard() {
  const { slug } = Route.useParams()
  const [timeRange, setTimeRange] = useState<TimeRange>('30d')
  const dotGridStyle = useDotGridStyle()

  const org = useQuery(api.orgs.directory.getOrgBySlug, { slug })
  const membership = useQuery(
    api.orgs.membership.getMembership,
    org ? { orgId: org._id } : 'skip',
  )
  const stats = useQuery(
    api.orgs.stats.getEnhancedOrgStats,
    org && membership?.role === 'admin'
      ? { orgId: org._id, timeRange }
      : 'skip',
  )
  const space = useQuery(
    api.coworkingSpaces.getSpaceByOrg,
    org && membership?.role === 'admin' ? { orgId: org._id } : 'skip',
  )
  const applicationCount = useQuery(
    api.opportunityApplications.getOrgApplicationCount,
    org && membership?.role === 'admin' ? { orgId: org._id } : 'skip',
  )

  // Loading state
  if (org === undefined || membership === undefined) {
    return (
      <div className="min-h-screen" style={dotGridStyle}>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-5xl mx-auto">
            <div className="animate-pulse space-y-6">
              <div className="h-12 bg-slate-100 rounded-xl w-1/3" />
              <div className="grid gap-4 sm:grid-cols-3">
                {[1, 2, 3].map((i) => (
                  <div key={i} className="h-24 bg-slate-100 rounded-xl" />
                ))}
              </div>
            </div>
          </div>
        </main>
      </div>
    )
  }

  // Org not found
  if (org === null) {
    return (
      <div className="min-h-screen" style={dotGridStyle}>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Building2 className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-display text-foreground mb-4">
              Organization Not Found
            </h1>
            <p className="text-slate-600 mb-6">
              This organization doesn&apos;t exist or the link is incorrect.
            </p>
            <Button asChild>
              <Link to="/">Go Home</Link>
            </Button>
          </div>
        </main>
      </div>
    )
  }

  // Not an admin - redirect to org page
  if (!membership || membership.role !== 'admin') {
    return (
      <div className="min-h-screen" style={dotGridStyle}>
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Shield className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-display text-foreground mb-4">
              Admin Access Required
            </h1>
            <p className="text-slate-600 mb-6">
              You need to be an admin of this organization to access this page.
            </p>
            <Button asChild>
              <Link to="/org/$slug" params={{ slug }}>
                Back to Organization
              </Link>
            </Button>
          </div>
        </main>
      </div>
    )
  }

  return (
    <div className="min-h-screen" style={dotGridStyle}>
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-5xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <div className="flex items-center gap-2 text-muted-foreground text-sm mb-2">
              <Link
                to="/org/$slug"
                params={{ slug }}
                className="hover:text-slate-700 transition-colors"
              >
                {org.name}
              </Link>
              <span>/</span>
              <span className="text-slate-700">Admin Dashboard</span>
            </div>
            <h1 className="text-2xl font-display font-semibold text-foreground">
              Admin Dashboard
            </h1>
            <p className="text-muted-foreground mt-1">
              Manage members and view organization statistics
            </p>
          </div>

          {/* Onboarding Checklist */}
          <OnboardingChecklist orgId={org._id} orgSlug={slug} />

          {/* Quick Stats Cards */}
          <div className="grid gap-4 sm:grid-cols-5 mb-8">
            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium text-slate-500">
                  Total Members
                </CardTitle>
                <Users className="size-4 text-slate-400" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold text-foreground">
                  {stats?.memberCount ?? <Spinner className="size-6" />}
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium text-slate-500">
                  Admins
                </CardTitle>
                <Shield className="size-4 text-slate-400" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold text-foreground">
                  {stats?.adminCount ?? <Spinner className="size-6" />}
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium text-slate-500">
                  {timeRange === '7d'
                    ? 'New This Week'
                    : timeRange === '30d'
                      ? 'New This Month'
                      : timeRange === '90d'
                        ? 'New (90 days)'
                        : 'Total Joined'}
                </CardTitle>
                <UserPlus className="size-4 text-slate-400" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold text-foreground">
                  {stats?.joinedThisMonth ?? <Spinner className="size-6" />}
                </div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium text-slate-500">
                  Events
                </CardTitle>
                <Calendar className="size-4 text-slate-400" />
              </CardHeader>
              <CardContent>
                {org.lumaCalendarUrl ? (
                  <div className="flex items-center gap-2">
                    <div className="size-2 rounded-full bg-green-500" />
                    <span className="text-sm font-medium text-slate-700">
                      Connected
                    </span>
                  </div>
                ) : (
                  <Link
                    to="/org/$slug/admin/settings"
                    params={{ slug }}
                    className="text-sm text-primary hover:underline"
                  >
                    Not configured
                  </Link>
                )}
              </CardContent>
            </Card>

            <Card>
              <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
                <CardTitle className="text-sm font-medium text-slate-500">
                  Applications
                </CardTitle>
                <FileText className="size-4 text-slate-400" />
              </CardHeader>
              <CardContent>
                <div className="text-3xl font-bold text-foreground">
                  {applicationCount ?? <Spinner className="size-6" />}
                </div>
              </CardContent>
            </Card>
          </div>

          {/* Quick Actions */}
          <div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4 mb-8">
            <Button asChild className="h-auto py-4">
              <Link to="/org/$slug/admin/members" params={{ slug }}>
                <Users className="size-5 mr-2" />
                View Members
              </Link>
            </Button>

            <Button variant="outline" className="h-auto py-4" asChild>
              <Link to="/org/$slug/admin/applications" params={{ slug }}>
                <FileText className="size-5 mr-2" />
                Applications
              </Link>
            </Button>

            <Button variant="outline" className="h-auto py-4" asChild>
              <Link to="/org/$slug/admin/opportunities" params={{ slug }}>
                <Briefcase className="size-5 mr-2" />
                Opportunities
              </Link>
            </Button>

            <Button variant="outline" className="h-auto py-4" asChild>
              <Link to="/org/$slug/admin/programs" params={{ slug }}>
                <FolderPlus className="size-5 mr-2" />
                Programs
              </Link>
            </Button>

            <InviteLinkButton orgId={org._id} slug={slug} />

            <Button variant="outline" className="h-auto py-4" asChild>
              <Link to="/org/$slug/admin/setup" params={{ slug }}>
                <Wrench className="size-5 mr-2" />
                Setup
              </Link>
            </Button>

            <Button variant="outline" className="h-auto py-4" asChild>
              <Link to="/org/$slug/admin/space" params={{ slug }}>
                <MapPin className="size-5 mr-2" />
                Co-working
              </Link>
            </Button>

            <Button variant="outline" className="h-auto py-4" asChild>
              <Link to="/org/$slug/admin/bookings" params={{ slug }}>
                <CalendarCheck className="size-5 mr-2" />
                Bookings
              </Link>
            </Button>

            <Button variant="outline" className="h-auto py-4" asChild>
              <Link to="/org/$slug/admin/settings" params={{ slug }}>
                <Settings className="size-5 mr-2" />
                Settings
              </Link>
            </Button>
          </div>

          {/* Co-working Statistics */}
          {space && (
            <div className="mb-8">
              <div className="flex items-center justify-between mb-6">
                <div>
                  <h2 className="text-lg font-semibold text-foreground">
                    Co-working Statistics
                  </h2>
                  <p className="text-sm text-slate-500">
                    Space utilization and guest conversion tracking
                  </p>
                </div>
              </div>
              <div className="grid gap-4 md:grid-cols-2">
                <SpaceUtilizationCard
                  spaceId={space._id}
                  spaceName={space.name}
                />
                <GuestConversionCard spaceId={space._id} />
              </div>
            </div>
          )}

          {/* Statistics Section Header with Time Range Selector */}
          <div className="flex items-center justify-between mb-6">
            <div>
              <h2 className="text-lg font-semibold text-foreground">
                Community Statistics
              </h2>
              <p className="text-sm text-slate-500">
                Overview of member engagement and skills
              </p>
            </div>
            <Select
              value={timeRange}
              onValueChange={(value: TimeRange) => setTimeRange(value)}
            >
              <SelectTrigger className="w-[150px]">
                <SelectValue placeholder="Time range" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="7d">Last 7 days</SelectItem>
                <SelectItem value="30d">Last 30 days</SelectItem>
                <SelectItem value="90d">Last 90 days</SelectItem>
                <SelectItem value="all">All time</SelectItem>
              </SelectContent>
            </Select>
          </div>

          {/* Statistics Visualization */}
          {stats && <OrgStats stats={stats} />}
        </div>
      </main>
    </div>
  )
}

// Separate component for invite link creation
function InviteLinkButton({
  orgId,
  slug,
}: {
  orgId: Id<'organizations'>
  slug: string
}) {
  const inviteLinks = useQuery(api.orgs.admin.getInviteLinks, { orgId })
  const createInvite = useMutation(api.orgs.admin.createInviteLink)
  const [isCreating, setIsCreating] = useState(false)

  // If there's an active invite link, show it
  const activeLink = inviteLinks?.[0]

  if (activeLink) {
    const inviteUrl = `${window.location.origin}/org/${slug}/join?token=${activeLink.token}`

    const copyToClipboard = () => {
      navigator.clipboard.writeText(inviteUrl)
    }

    return (
      <Button
        variant="outline"
        className="h-auto py-4"
        onClick={copyToClipboard}
      >
        <UserPlus className="size-5 mr-2" />
        Copy Invite Link
      </Button>
    )
  }

  const handleCreate = async () => {
    setIsCreating(true)
    try {
      await createInvite({ orgId })
    } finally {
      setIsCreating(false)
    }
  }

  return (
    <Button
      variant="outline"
      className="h-auto py-4"
      onClick={handleCreate}
      disabled={isCreating}
    >
      <UserPlus className="size-5 mr-2" />
      {isCreating ? 'Creating...' : 'Create Invite Link'}
    </Button>
  )
}
