// src/routes/(app)/org/[slug]/admin/members/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import { Search, Shield, Trash2, UserCog, UserRound } from 'lucide-svelte'
  import { toast } from 'svelte-sonner'
  import { api } from '$convex/_generated/api'
  import type { Id } from '$convex/_generated/dataModel'
  import AdminSection from '~/components/org-admin/core/AdminSection.svelte'

  type MemberRecord = NonNullable<
    ReturnType<typeof useQuery<typeof api.orgs.admin.getAllMembersWithProfiles>>['data']
  >[number]

  type EngagementRecord = NonNullable<
    ReturnType<typeof useQuery<typeof api.engagement.queries.getOrgEngagementForAdmin>>['data']
  >[number]

  const convex = useConvexClient()
  const slug = $derived(page.params.slug ?? null)

  let search = $state('')
  let roleFilter = $state<'all' | 'admin' | 'member'>('all')
  let locationFilter = $state('all')
  let engagementFilter = $state('all')
  let pageNumber = $state(1)

  const pageSize = 25

  const org = useQuery(api.orgs.directory.getOrgBySlug, () =>
    slug
      ? {
          slug,
        }
      : 'skip',
  )

  const membership = useQuery(api.orgs.membership.getMembership, () =>
    org.data
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  const members = useQuery(api.orgs.admin.getAllMembersWithProfiles, () =>
    org.data && membership.data?.role === 'admin'
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  const engagement = useQuery(api.engagement.queries.getOrgEngagementForAdmin, () =>
    org.data && membership.data?.role === 'admin'
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  const adminState = $derived.by(() => {
    if (org.isLoading || membership.isLoading) return 'loading'
    if (!org.data) return 'missing'
    if (membership.data?.role !== 'admin') return 'forbidden'
    return 'ready'
  })

  const engagementMap = $derived.by(() => {
    const map = new Map<string, EngagementRecord>()
    for (const item of engagement.data ?? []) {
      map.set(item.userId, item)
    }
    return map
  })

  const availableLocations = $derived.by(() =>
    Array.from(
      new Set(
        (members.data ?? [])
          .map((member) => member.profile?.location?.trim())
          .filter((value): value is string => Boolean(value)),
      ),
    ).sort(),
  )

  const filteredMembers = $derived.by(() => {
    const query = search.trim().toLowerCase()

    return (members.data ?? []).filter((member) => {
      const name = member.profile?.name?.toLowerCase() ?? ''
      const email = member.email?.toLowerCase() ?? ''
      const location = member.profile?.location ?? ''
      const engagementLevel =
        engagementMap.get(member.membership.userId)?.level ?? 'pending'

      if (query && !name.includes(query) && !email.includes(query)) {
        return false
      }

      if (roleFilter !== 'all' && member.membership.role !== roleFilter) {
        return false
      }

      if (locationFilter !== 'all' && location !== locationFilter) {
        return false
      }

      if (engagementFilter !== 'all' && engagementLevel !== engagementFilter) {
        return false
      }

      return true
    })
  })

  const totalPages = $derived(Math.max(1, Math.ceil(filteredMembers.length / pageSize)))

  const paginatedMembers = $derived.by(() => {
    const start = (pageNumber - 1) * pageSize
    return filteredMembers.slice(start, start + pageSize)
  })

  $effect(() => {
    if (pageNumber > totalPages) {
      pageNumber = totalPages
    }
  })

  const mutateMember = async (
    action: 'promote' | 'demote' | 'remove',
    memberRecord: MemberRecord,
  ) => {
    if (!org.data) return

    try {
      if (action === 'remove') {
        const confirmed = window.confirm(
          `Remove ${memberRecord.profile?.name ?? 'this member'} from ${org.data.name}?`,
        )

        if (!confirmed) return

        await convex.mutation(api.orgs.admin.removeMember, {
          orgId: org.data._id,
          membershipId: memberRecord.membership._id,
        })
        toast.success('Member removed')
        return
      }

      if (action === 'promote') {
        await convex.mutation(api.orgs.admin.promoteToAdmin, {
          orgId: org.data._id,
          membershipId: memberRecord.membership._id,
        })
        toast.success('Member promoted to admin')
        return
      }

      await convex.mutation(api.orgs.admin.demoteToMember, {
        orgId: org.data._id,
        membershipId: memberRecord.membership._id,
      })
      toast.success('Admin demoted to member')
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to update member')
    }
  }

  const formatEngagement = (value: string | null | undefined) =>
    (value ?? 'pending').replaceAll('_', ' ')

  const isCurrentUserMembership = (membershipId: Id<'orgMemberships'>) =>
    membership.data?._id === membershipId
</script>

{#if adminState === 'loading'}
  <div class="space-y-6">
    <div class="h-28 animate-pulse rounded-[1.75rem] bg-slate-100"></div>
    <div class="h-96 animate-pulse rounded-[1.75rem] bg-slate-100"></div>
  </div>
{:else if adminState === 'missing'}
  <div class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-10 text-center shadow-warm-sm">
    <h1 class="font-display text-3xl text-slate-950">Organization not found</h1>
  </div>
{:else if adminState === 'forbidden'}
  <div class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-10 text-center shadow-warm-sm">
    <h1 class="font-display text-3xl text-slate-950">Admin access required</h1>
  </div>
{:else}
  <div class="space-y-6">
    <section class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-6 shadow-warm-sm">
      <p class="text-xs font-semibold uppercase tracking-[0.22em] text-coral-600">Members</p>
      <h1 class="mt-2 font-display text-3xl text-slate-950">Member directory</h1>
      <p class="mt-3 max-w-2xl text-sm leading-6 text-slate-600">
        Review organization membership, audit profile quality, and adjust roles in one place.
      </p>
    </section>

    <AdminSection
      title="Filters"
      subtitle={`${filteredMembers.length} member${filteredMembers.length === 1 ? '' : 's'} match the current view.`}
    >
      <div class="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        <label class="space-y-2">
          <span class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Search</span>
          <div class="relative">
            <Search class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" />
            <input
              class="w-full rounded-2xl border border-border bg-white px-10 py-3 text-sm text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-coral-300 focus:ring-2 focus:ring-coral-100"
              bind:value={search}
              placeholder="Search name or email"
            />
          </div>
        </label>

        <label class="space-y-2">
          <span class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Role</span>
          <select
            class="w-full rounded-2xl border border-border bg-white px-3 py-3 text-sm text-slate-800 outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-100"
            bind:value={roleFilter}
          >
            <option value="all">All roles</option>
            <option value="admin">Admins</option>
            <option value="member">Members</option>
          </select>
        </label>

        <label class="space-y-2">
          <span class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Location</span>
          <select
            class="w-full rounded-2xl border border-border bg-white px-3 py-3 text-sm text-slate-800 outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-100"
            bind:value={locationFilter}
          >
            <option value="all">All locations</option>
            {#each availableLocations as location}
              <option value={location}>{location}</option>
            {/each}
          </select>
        </label>

        <label class="space-y-2">
          <span class="text-xs font-semibold uppercase tracking-[0.18em] text-slate-500">Engagement</span>
          <select
            class="w-full rounded-2xl border border-border bg-white px-3 py-3 text-sm text-slate-800 outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-100"
            bind:value={engagementFilter}
          >
            <option value="all">All levels</option>
            <option value="highly_engaged">Highly engaged</option>
            <option value="moderate">Moderate</option>
            <option value="at_risk">At risk</option>
            <option value="new">New</option>
            <option value="inactive">Inactive</option>
            <option value="pending">Pending</option>
          </select>
        </label>
      </div>
    </AdminSection>

    <AdminSection
      title="Roster"
      subtitle="Use the member detail page for full profile, attendance, and engagement history."
    >
      {#if members.isLoading}
        <p class="text-sm text-slate-500">Loading members…</p>
      {:else if !filteredMembers.length}
        <p class="text-sm text-slate-500">No members matched the current filters.</p>
      {:else}
        <div class="overflow-x-auto">
          <table class="min-w-full divide-y divide-border">
            <thead>
              <tr class="text-left text-xs uppercase tracking-[0.18em] text-slate-500">
                <th class="pb-3 pr-4 font-semibold">Member</th>
                <th class="pb-3 pr-4 font-semibold">Role</th>
                <th class="pb-3 pr-4 font-semibold">Engagement</th>
                <th class="pb-3 pr-4 font-semibold">Completeness</th>
                <th class="pb-3 pr-4 font-semibold">Joined</th>
                <th class="pb-3 pr-4 font-semibold">Profile</th>
                <th class="pb-3 text-right font-semibold">Actions</th>
              </tr>
            </thead>
            <tbody class="divide-y divide-border">
              {#each paginatedMembers as member}
                {@const memberEngagement = engagementMap.get(member.membership.userId)}
                {@const selfMembership = isCurrentUserMembership(member.membership._id)}
                <tr class="align-top">
                  <td class="py-4 pr-4">
                    <div>
                      <p class="font-medium text-slate-950">{member.profile?.name ?? 'Unnamed member'}</p>
                      <p class="mt-1 text-sm text-slate-500">{member.email ?? 'No email on file'}</p>
                      {#if member.profile?.location}
                        <p class="mt-1 text-sm text-slate-500">{member.profile.location}</p>
                      {/if}
                    </div>
                  </td>
                  <td class="py-4 pr-4">
                    <span class={`inline-flex rounded-full px-3 py-1 text-xs font-medium ${
                      member.membership.role === 'admin'
                        ? 'bg-slate-950 text-white'
                        : 'bg-slate-100 text-slate-700'
                    }`}>
                      {member.membership.role}
                    </span>
                  </td>
                  <td class="py-4 pr-4">
                    <div class="space-y-1">
                      <span class="inline-flex rounded-full border border-border px-3 py-1 text-xs font-medium text-slate-700">
                        {formatEngagement(memberEngagement?.level)}
                      </span>
                      {#if memberEngagement?.hasOverride}
                        <p class="text-xs text-amber-700">Manual override active</p>
                      {/if}
                    </div>
                  </td>
                  <td class="py-4 pr-4">
                    <div class="w-24">
                      <div class="mb-1 flex items-center justify-between text-xs text-slate-500">
                        <span>{member.completeness}%</span>
                      </div>
                      <div class="h-2 rounded-full bg-slate-200">
                        <div
                          class={`h-2 rounded-full ${
                            member.completeness >= 80
                              ? 'bg-emerald-500'
                              : member.completeness >= 40
                                ? 'bg-amber-500'
                                : 'bg-slate-500'
                          }`}
                          style={`width:${member.completeness}%`}
                        ></div>
                      </div>
                    </div>
                  </td>
                  <td class="py-4 pr-4 text-sm text-slate-600">
                    {new Date(member.membership.joinedAt).toLocaleDateString()}
                  </td>
                  <td class="py-4 pr-4">
                    <a
                      href={`/org/${slug}/admin/members/${member.membership.userId}`}
                      class="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-sm text-slate-700 transition hover:bg-slate-50"
                    >
                      <UserRound class="size-4" />
                      View
                    </a>
                  </td>
                  <td class="py-4 text-right">
                    <div class="flex flex-wrap justify-end gap-2">
                      {#if member.membership.role === 'admin'}
                        <button
                          type="button"
                          class="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-sm text-slate-700 transition hover:bg-slate-50 disabled:opacity-60"
                          onclick={() => mutateMember('demote', member)}
                          disabled={selfMembership}
                        >
                          <Shield class="size-4" />
                          Demote
                        </button>
                      {:else}
                        <button
                          type="button"
                          class="inline-flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-sm text-slate-700 transition hover:bg-slate-50"
                          onclick={() => mutateMember('promote', member)}
                        >
                          <UserCog class="size-4" />
                          Promote
                        </button>
                      {/if}

                      <button
                        type="button"
                        class="inline-flex items-center gap-2 rounded-xl border border-rose-200 px-3 py-2 text-sm text-rose-700 transition hover:bg-rose-50 disabled:opacity-60"
                        onclick={() => mutateMember('remove', member)}
                        disabled={selfMembership}
                      >
                        <Trash2 class="size-4" />
                        Remove
                      </button>
                    </div>
                  </td>
                </tr>
              {/each}
            </tbody>
          </table>
        </div>

        {#if totalPages > 1}
          <div class="mt-5 flex flex-col gap-3 border-t border-border pt-5 text-sm text-slate-600 md:flex-row md:items-center md:justify-between">
            <span>
              Showing {(pageNumber - 1) * pageSize + 1}–{Math.min(pageNumber * pageSize, filteredMembers.length)} of {filteredMembers.length}
            </span>
            <div class="flex gap-2">
              <button
                type="button"
                class="rounded-xl border border-border px-3 py-2 transition hover:bg-slate-50 disabled:opacity-60"
                onclick={() => {
                  pageNumber = Math.max(1, pageNumber - 1)
                }}
                disabled={pageNumber === 1}
              >
                Previous
              </button>
              <button
                type="button"
                class="rounded-xl border border-border px-3 py-2 transition hover:bg-slate-50 disabled:opacity-60"
                onclick={() => {
                  pageNumber = Math.min(totalPages, pageNumber + 1)
                }}
                disabled={pageNumber === totalPages}
              >
                Next
              </button>
            </div>
          </div>
        {/if}
      {/if}
    </AdminSection>
  </div>
{/if}

// src/routes/org/$slug/admin/members.tsx
import { Link, createFileRoute } from "@tanstack/react-router";
import { useMutation, useQuery } from "convex/react";
import {
  Building2,
  ChevronLeft,
  ChevronRight,
  MoreHorizontal,
  Settings,
  Shield,
  ShieldOff,
  Trash2,
  Users,
} from "lucide-react";
import { useMemo, useState } from "react";
import { api } from "../../../../../convex/_generated/api";
import type { Doc, Id } from "../../../../../convex/_generated/dataModel";
import type { EngagementLevel } from "~/components/engagement/EngagementBadge";
import {
  EngagementBadge,
  PendingEngagementBadge,
} from "~/components/engagement/EngagementBadge";
import { OverrideDialog } from "~/components/engagement/OverrideDialog";
import { AuthHeader } from "~/components/layout/auth-header";
import { ExportButton } from "~/components/org/ExportButton";
import {
  MemberFilters,
  type MemberFiltersType,
} from "~/components/org/MemberFilters";
import { Badge } from "~/components/ui/badge";
import { Button } from "~/components/ui/button";
import { Card } from "~/components/ui/card";
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuSeparator,
  DropdownMenuTrigger,
} from "~/components/ui/dropdown-menu";
import { Spinner } from "~/components/ui/spinner";

export const Route = createFileRoute("/org/$slug/admin/members")({
  component: OrgAdminMembers,
});

// Type for engagement data from query
type EngagementData = {
  _id: Id<"memberEngagement">;
  userId: string;
  level: EngagementLevel;
  computedLevel: EngagementLevel;
  adminExplanation: string;
  hasOverride: boolean;
  overrideNotes?: string;
};

function OrgAdminMembers() {
  const { slug } = Route.useParams();
  const [filters, setFilters] = useState<MemberFiltersType>({});
  const [page, setPage] = useState(1);
  const pageSize = 25;

  // Reset page to 1 when filters change
  const handleFiltersChange = (newFilters: MemberFiltersType) => {
    setFilters(newFilters);
    setPage(1);
  };

  const org = useQuery(api.orgs.directory.getOrgBySlug, { slug });
  const membership = useQuery(
    api.orgs.membership.getMembership,
    org ? { orgId: org._id } : "skip"
  );
  const members = useQuery(
    api.orgs.admin.getAllMembersWithProfiles,
    org && membership?.role === "admin" ? { orgId: org._id } : "skip"
  );

  // Fetch engagement data for all members
  const engagementData = useQuery(
    api.engagement.queries.getOrgEngagementForAdmin,
    org && membership?.role === "admin" ? { orgId: org._id } : "skip"
  );

  // Create a Map for fast userId -> engagement lookup
  const engagementMap = useMemo(() => {
    const map = new Map<string, EngagementData>();
    if (engagementData) {
      for (const e of engagementData) {
        map.set(e.userId, e as EngagementData);
      }
    }
    return map;
  }, [engagementData]);

  // Extract available skills from members data
  const availableSkills = useMemo(() => {
    const skills = new Set<string>();
    members?.forEach((m) =>
      m.profile?.skills?.forEach((s) => skills.add(s))
    );
    return Array.from(skills).sort();
  }, [members]);

  // Extract available locations from members data
  const availableLocations = useMemo(() => {
    const locations = new Set<string>();
    members?.forEach((m) => {
      if (m.profile?.location) locations.add(m.profile.location);
    });
    return Array.from(locations).sort();
  }, [members]);

  // Filter members by all active filters
  const filteredMembers = useMemo(() => {
    if (!members) return [];
    return members.filter((member) => {
      // Search filter (name, email)
      if (filters.search) {
        const query = filters.search.toLowerCase();
        const name = member.profile?.name?.toLowerCase() ?? "";
        const email = member.email?.toLowerCase() ?? "";
        if (!name.includes(query) && !email.includes(query)) return false;
      }

      // Engagement filter
      if (filters.engagementLevels?.length) {
        const engagement = engagementMap.get(member.membership.userId);
        const level = engagement?.level ?? "new";
        if (!filters.engagementLevels.includes(level)) return false;
      }

      // Skills filter (any match)
      if (filters.skills?.length) {
        const memberSkills = member.profile?.skills ?? [];
        if (!filters.skills.some((s) => memberSkills.includes(s))) return false;
      }

      // Location filter
      if (filters.locations?.length) {
        const location = member.profile?.location ?? "";
        if (!filters.locations.includes(location)) return false;
      }

      // Join date range
      if (
        filters.joinedAfter &&
        member.membership.joinedAt < filters.joinedAfter
      ) {
        return false;
      }
      if (
        filters.joinedBefore &&
        member.membership.joinedAt > filters.joinedBefore
      ) {
        return false;
      }

      // Directory visibility filter
      if (
        filters.directoryVisibility &&
        filters.directoryVisibility !== "all"
      ) {
        if (member.membership.directoryVisibility !== filters.directoryVisibility) {
          return false;
        }
      }

      return true;
    });
  }, [members, engagementMap, filters]);

  // Calculate paginated members
  const paginatedMembers = useMemo(() => {
    const start = (page - 1) * pageSize;
    return filteredMembers.slice(start, start + pageSize);
  }, [filteredMembers, page, pageSize]);

  const totalPages = Math.ceil(filteredMembers.length / pageSize);

  // Loading state
  if (org === undefined || membership === undefined) {
    return (
      <div className="min-h-screen bg-slate-50">
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-5xl mx-auto">
            <div className="animate-pulse space-y-6">
              <div className="h-12 bg-slate-100 rounded-xl w-1/3" />
              <div className="h-64 bg-slate-100 rounded-xl" />
            </div>
          </div>
        </main>
      </div>
    );
  }

  // Org not found
  if (org === null) {
    return (
      <div className="min-h-screen bg-slate-50">
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Building2 className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-bold text-slate-900 mb-4">
              Organization Not Found
            </h1>
            <Button asChild>
              <Link to="/">Go Home</Link>
            </Button>
          </div>
        </main>
      </div>
    );
  }

  // Not an admin
  if (!membership || membership.role !== "admin") {
    return (
      <div className="min-h-screen bg-slate-50">
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Shield className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-bold text-slate-900 mb-4">
              Admin Access Required
            </h1>
            <Button asChild>
              <Link to="/org/$slug" params={{ slug }}>
                Back to Organization
              </Link>
            </Button>
          </div>
        </main>
      </div>
    );
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-6xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <div className="flex items-center gap-2 text-slate-500 text-sm mb-2">
              <Link
                to="/org/$slug"
                params={{ slug }}
                className="hover:text-slate-700 transition-colors"
              >
                {org.name}
              </Link>
              <span>/</span>
              <Link
                to="/org/$slug/admin"
                params={{ slug }}
                className="hover:text-slate-700 transition-colors"
              >
                Admin
              </Link>
              <span>/</span>
              <span className="text-slate-700">Members</span>
            </div>
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-2xl font-bold text-slate-900">Members</h1>
                <p className="text-slate-600 mt-1">
                  {members?.length ?? "..."} members in {org.name}
                </p>
              </div>
              <ExportButton orgId={org._id} orgSlug={slug} />
            </div>
          </div>

          {/* Filters */}
          <MemberFilters
            filters={filters}
            onFiltersChange={handleFiltersChange}
            availableSkills={availableSkills}
            availableLocations={availableLocations}
          />

          {/* Members Table */}
          {members === undefined ? (
            <Card className="p-8 text-center">
              <Spinner className="size-8 mx-auto" />
            </Card>
          ) : filteredMembers.length === 0 ? (
            <Card className="p-8 text-center">
              <div className="size-12 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
                <Users className="size-6 text-slate-400" />
              </div>
              <h3 className="text-lg font-medium text-slate-900 mb-2">
                {Object.keys(filters).length > 0
                  ? "No members found"
                  : "No members yet"}
              </h3>
              <p className="text-slate-500 text-sm">
                {Object.keys(filters).length > 0
                  ? "Try adjusting your filters"
                  : "Share an invite link to add members"}
              </p>
            </Card>
          ) : (
            <Card className="overflow-hidden">
              <div className="overflow-x-auto">
                <table className="w-full">
                  <thead>
                    <tr className="border-b bg-slate-50">
                      <th className="text-left text-sm font-medium text-slate-500 px-4 py-3">
                        Name
                      </th>
                      <th className="text-left text-sm font-medium text-slate-500 px-4 py-3">
                        Email
                      </th>
                      <th className="text-left text-sm font-medium text-slate-500 px-4 py-3">
                        Role
                      </th>
                      <th className="text-left text-sm font-medium text-slate-500 px-4 py-3">
                        Engagement
                      </th>
                      <th className="text-left text-sm font-medium text-slate-500 px-4 py-3">
                        Directory
                      </th>
                      <th className="text-left text-sm font-medium text-slate-500 px-4 py-3">
                        Joined
                      </th>
                      <th className="text-left text-sm font-medium text-slate-500 px-4 py-3">
                        Profile
                      </th>
                      <th className="text-right text-sm font-medium text-slate-500 px-4 py-3">
                        Actions
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y">
                    {paginatedMembers.map((member) => (
                      <MemberRow
                        key={member.membership._id}
                        member={member}
                        engagement={engagementMap.get(member.membership.userId) || null}
                        orgId={org._id}
                        currentMembershipId={membership._id}
                      />
                    ))}
                  </tbody>
                </table>
              </div>
              {/* Pagination Controls */}
              {totalPages > 1 && (
                <div className="flex items-center justify-between px-4 py-3 border-t">
                  <div className="text-sm text-slate-500">
                    Showing {(page - 1) * pageSize + 1} to{" "}
                    {Math.min(page * pageSize, filteredMembers.length)} of{" "}
                    {filteredMembers.length} members
                  </div>
                  <div className="flex items-center gap-2">
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setPage((p) => p - 1)}
                      disabled={page === 1}
                    >
                      <ChevronLeft className="size-4" />
                      Previous
                    </Button>
                    <span className="text-sm text-slate-600">
                      Page {page} of {totalPages}
                    </span>
                    <Button
                      variant="outline"
                      size="sm"
                      onClick={() => setPage((p) => p + 1)}
                      disabled={page === totalPages}
                    >
                      Next
                      <ChevronRight className="size-4" />
                    </Button>
                  </div>
                </div>
              )}
            </Card>
          )}
        </div>
      </main>
    </div>
  );
}

interface MemberRowProps {
  member: {
    membership: Doc<"orgMemberships">;
    profile: Doc<"profiles"> | null;
    email: string | null;
    completeness: number;
  };
  engagement: EngagementData | null;
  orgId: Id<"organizations">;
  currentMembershipId: Id<"orgMemberships">;
}

function MemberRow({ member, engagement, orgId, currentMembershipId }: MemberRowProps) {
  const [isLoading, setIsLoading] = useState(false);
  const [overrideDialogOpen, setOverrideDialogOpen] = useState(false);

  const removeMember = useMutation(api.orgs.admin.removeMember);
  const promoteToAdmin = useMutation(api.orgs.admin.promoteToAdmin);
  const demoteToMember = useMutation(api.orgs.admin.demoteToMember);

  const isSelf = member.membership._id === currentMembershipId;
  const isAdmin = member.membership.role === "admin";
  const joinedDate = new Date(member.membership.joinedAt).toLocaleDateString(
    "en-US",
    {
      month: "short",
      day: "numeric",
      year: "numeric",
    }
  );

  const handlePromote = async () => {
    setIsLoading(true);
    try {
      await promoteToAdmin({
        orgId,
        membershipId: member.membership._id,
      });
    } catch (error) {
      console.error("Failed to promote member:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleDemote = async () => {
    setIsLoading(true);
    try {
      await demoteToMember({
        orgId,
        membershipId: member.membership._id,
      });
    } catch (error) {
      console.error("Failed to demote member:", error);
    } finally {
      setIsLoading(false);
    }
  };

  const handleRemove = async () => {
    if (
      !confirm(
        `Are you sure you want to remove ${member.profile?.name || "this member"} from the organization?`
      )
    ) {
      return;
    }

    setIsLoading(true);
    try {
      await removeMember({
        orgId,
        membershipId: member.membership._id,
      });
    } catch (error) {
      console.error("Failed to remove member:", error);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <>
      <tr className="hover:bg-slate-50">
        <td className="px-4 py-3">
          <div className="font-medium text-slate-900">
            {member.profile?.name || "No name"}
          </div>
          {member.profile?.headline && (
            <div className="text-sm text-slate-500 truncate max-w-[200px]">
              {member.profile.headline}
            </div>
          )}
        </td>
        <td className="px-4 py-3 text-slate-600">
          {member.email || "—"}
        </td>
        <td className="px-4 py-3">
          <Badge variant={isAdmin ? "default" : "secondary"}>
            {isAdmin && <Shield className="size-3 mr-1" />}
            {isAdmin ? "Admin" : "Member"}
          </Badge>
        </td>
        <td className="px-4 py-3">
          {engagement ? (
            <EngagementBadge
              level={engagement.level}
              hasOverride={engagement.hasOverride}
              adminExplanation={engagement.adminExplanation}
              onClick={() => setOverrideDialogOpen(true)}
            />
          ) : (
            <PendingEngagementBadge />
          )}
        </td>
        <td className="px-4 py-3">
          <Badge
            variant={
              member.membership.directoryVisibility === "visible"
                ? "outline"
                : "secondary"
            }
          >
            {member.membership.directoryVisibility === "visible"
              ? "Visible"
              : "Hidden"}
          </Badge>
        </td>
        <td className="px-4 py-3 text-slate-600">{joinedDate}</td>
        <td className="px-4 py-3">
          <div className="flex items-center gap-2">
            <div className="w-20 h-2 bg-slate-100 rounded-full overflow-hidden">
              <div
                className={`h-full rounded-full ${
                  member.completeness > 70
                    ? "bg-green-500"
                    : member.completeness >= 40
                      ? "bg-amber-500"
                      : "bg-red-500"
                }`}
                style={{ width: `${member.completeness}%` }}
              />
            </div>
            <span className="text-sm text-slate-500">
              {member.completeness}%
            </span>
          </div>
        </td>
        <td className="px-4 py-3 text-right">
          <DropdownMenu>
            <DropdownMenuTrigger asChild>
              <Button
                variant="ghost"
                size="sm"
                disabled={isLoading}
              >
                {isLoading ? (
                  <Spinner className="size-4" />
                ) : (
                  <MoreHorizontal className="size-4" />
                )}
              </Button>
            </DropdownMenuTrigger>
            <DropdownMenuContent align="end">
              {engagement && (
                <>
                  <DropdownMenuItem onClick={() => setOverrideDialogOpen(true)}>
                    <Settings className="size-4 mr-2" />
                    Override Engagement
                  </DropdownMenuItem>
                  <DropdownMenuSeparator />
                </>
              )}
              {!isAdmin && (
                <DropdownMenuItem onClick={handlePromote}>
                  <Shield className="size-4 mr-2" />
                  Promote to Admin
                </DropdownMenuItem>
              )}
              {isAdmin && !isSelf && (
                <DropdownMenuItem onClick={handleDemote}>
                  <ShieldOff className="size-4 mr-2" />
                  Demote to Member
                </DropdownMenuItem>
              )}
              {isAdmin && isSelf && (
                <DropdownMenuItem disabled>
                  <ShieldOff className="size-4 mr-2 opacity-50" />
                  Cannot demote self
                </DropdownMenuItem>
              )}
              {!isSelf && (
                <>
                  <DropdownMenuSeparator />
                  <DropdownMenuItem
                    onClick={handleRemove}
                    className="text-red-600"
                  >
                    <Trash2 className="size-4 mr-2" />
                    Remove from Organization
                  </DropdownMenuItem>
                </>
              )}
              {isSelf && (
                <DropdownMenuItem disabled>
                  <Trash2 className="size-4 mr-2 opacity-50" />
                  Use &quot;Leave Org&quot; instead
                </DropdownMenuItem>
              )}
            </DropdownMenuContent>
          </DropdownMenu>
        </td>
      </tr>

      {/* Override Dialog */}
      {engagement && (
        <OverrideDialog
          open={overrideDialogOpen}
          onOpenChange={setOverrideDialogOpen}
          engagementId={engagement._id}
          memberName={member.profile?.name || "Member"}
          currentLevel={engagement.level}
          currentExplanation={engagement.adminExplanation}
          hasOverride={engagement.hasOverride}
          overrideNotes={engagement.overrideNotes}
          orgId={orgId}
          userId={member.membership.userId}
        />
      )}
    </>
  );
}
