// src/routes/(app)/org/[slug]/admin/settings/+page.svelte
<script lang="ts">
  import { page } from '$app/state'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import { CalendarDays, CheckCircle2, Link2 } from 'lucide-svelte'
  import { toast } from 'svelte-sonner'
  import { api } from '$convex/_generated/api'
  import AdminSection from '~/components/org-admin/core/AdminSection.svelte'

  const convex = useConvexClient()
  const slug = $derived(page.params.slug ?? null)

  let lumaCalendarUrl = $state('')
  let initialized = $state(false)
  let saving = $state(false)
  let resolved = $state(false)

  const org = useQuery(api.orgs.directory.getOrgBySlug, () =>
    slug
      ? {
          slug,
        }
      : 'skip',
  )

  const membership = useQuery(api.orgs.membership.getMembership, () =>
    org.data
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  const lumaConfig = useQuery(api.orgs.admin.getLumaConfig, () =>
    org.data && membership.data?.role === 'admin'
      ? {
          orgId: org.data._id,
        }
      : 'skip',
  )

  $effect(() => {
    if (lumaConfig.data && !initialized) {
      lumaCalendarUrl = lumaConfig.data.lumaCalendarUrl ?? ''
      resolved = Boolean(lumaConfig.data.lumaCalendarApiId)
      initialized = true
    }
  })

  const adminState = $derived.by(() => {
    if (org.isLoading || membership.isLoading) return 'loading'
    if (!org.data) return 'missing'
    if (membership.data?.role !== 'admin') return 'forbidden'
    return 'ready'
  })

  const saveSettings = async () => {
    if (!org.data) return

    try {
      saving = true
      const trimmed = lumaCalendarUrl.trim()
      let lumaCalendarApiId: string | undefined

      if (trimmed) {
        lumaCalendarApiId = await convex.action(api.events.sync.resolveLumaCalendar, {
          calendarUrl: trimmed,
        })
      }

      await convex.mutation(api.orgs.admin.updateLumaConfig, {
        orgId: org.data._id,
        lumaCalendarUrl: trimmed || undefined,
        lumaCalendarApiId,
      })

      resolved = Boolean(lumaCalendarApiId)
      toast.success('Settings saved')
    } catch (error) {
      toast.error(error instanceof Error ? error.message : 'Failed to save settings')
    } finally {
      saving = false
    }
  }
</script>

{#if adminState === 'loading'}
  <div class="space-y-6">
    <div class="h-28 animate-pulse rounded-[1.75rem] bg-slate-100"></div>
    <div class="h-80 animate-pulse rounded-[1.75rem] bg-slate-100"></div>
  </div>
{:else if adminState === 'missing'}
  <div class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-10 text-center shadow-warm-sm">
    <h1 class="font-display text-3xl text-slate-950">Organization not found</h1>
  </div>
{:else if adminState === 'forbidden'}
  <div class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-10 text-center shadow-warm-sm">
    <h1 class="font-display text-3xl text-slate-950">Admin access required</h1>
  </div>
{:else}
  <div class="space-y-6">
    <section class="rounded-[1.75rem] border border-border/70 bg-white/92 px-6 py-6 shadow-warm-sm">
      <p class="text-xs font-semibold uppercase tracking-[0.22em] text-coral-600">Settings</p>
      <h1 class="mt-2 font-display text-3xl text-slate-950">Integrations</h1>
      <p class="mt-3 max-w-2xl text-sm leading-6 text-slate-600">
        Connect external systems that feed the public org page and member dashboard.
      </p>
    </section>

    <AdminSection
      title="Lu.ma events integration"
      subtitle="Resolve your Lu.ma calendar once, then ASTN can sync org events automatically."
    >
      {#snippet actions()}
        <button
          type="button"
          class="rounded-xl bg-coral-500 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-coral-600 disabled:opacity-60"
          onclick={saveSettings}
          disabled={saving}
        >
          {saving ? 'Saving…' : 'Save settings'}
        </button>
      {/snippet}
      <div class="grid gap-6 lg:grid-cols-[minmax(0,1fr)_320px]">
        <div class="space-y-3">
          <label class="space-y-2">
            <span class="text-sm font-medium text-slate-900">Lu.ma calendar URL</span>
            <div class="relative">
              <Link2 class="pointer-events-none absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400" />
              <input
                class="w-full rounded-2xl border border-border bg-white px-10 py-3 text-sm text-slate-800 outline-none transition placeholder:text-slate-400 focus:border-coral-300 focus:ring-2 focus:ring-coral-100"
                bind:value={lumaCalendarUrl}
                placeholder="https://lu.ma/your-calendar"
                type="url"
                oninput={() => {
                  resolved = false
                }}
              />
            </div>
          </label>

          <p class="text-sm leading-6 text-slate-600">
            This should be the public Lu.ma calendar URL for the organization. On save,
            ASTN resolves the calendar API identifier and stores it for future syncs.
          </p>
        </div>

        <div class="rounded-[1.5rem] border border-border bg-slate-50 p-5">
          <div class="flex items-center gap-3">
            <div class={`flex size-11 items-center justify-center rounded-2xl ${
              resolved ? 'bg-emerald-500 text-white' : 'bg-slate-200 text-slate-500'
            }`}>
              {#if resolved}
                <CheckCircle2 class="size-5" />
              {:else}
                <CalendarDays class="size-5" />
              {/if}
            </div>
            <div>
              <p class="text-sm font-medium text-slate-900">
                {resolved ? 'Calendar connected' : 'Awaiting connection'}
              </p>
              <p class="mt-1 text-sm text-slate-600">
                {#if resolved}
                  Events can now sync into the org page and dashboard.
                {:else}
                  Save a valid Lu.ma URL to connect the feed.
                {/if}
              </p>
            </div>
          </div>

          {#if lumaConfig.data?.eventsLastSynced}
            <p class="mt-5 text-xs uppercase tracking-[0.18em] text-slate-500">
              Last synced {new Date(lumaConfig.data.eventsLastSynced).toLocaleString()}
            </p>
          {/if}
        </div>
      </div>
    </AdminSection>
  </div>
{/if}

// src/routes/org/$slug/admin/settings.tsx
import { Link, createFileRoute } from '@tanstack/react-router'
import { useAction, useMutation, useQuery } from 'convex/react'
import { Building2, CheckCircle2, Loader2, Save, Shield } from 'lucide-react'
import { useEffect, useState } from 'react'
import { toast } from 'sonner'
import { api } from '../../../../../convex/_generated/api'
import { AuthHeader } from '~/components/layout/auth-header'
import { Button } from '~/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '~/components/ui/card'
import { Input } from '~/components/ui/input'
import { Label } from '~/components/ui/label'
import { Spinner } from '~/components/ui/spinner'

export const Route = createFileRoute('/org/$slug/admin/settings')({
  component: OrgAdminSettings,
})

function OrgAdminSettings() {
  const { slug } = Route.useParams()

  const org = useQuery(api.orgs.directory.getOrgBySlug, { slug })
  const membership = useQuery(
    api.orgs.membership.getMembership,
    org ? { orgId: org._id } : 'skip',
  )
  const lumaConfig = useQuery(
    api.orgs.admin.getLumaConfig,
    org && membership?.role === 'admin' ? { orgId: org._id } : 'skip',
  )

  // Form state
  const [lumaCalendarUrl, setLumaCalendarUrl] = useState('')
  const [isSaving, setIsSaving] = useState(false)
  const [isResolved, setIsResolved] = useState(false)

  const updateLumaConfig = useMutation(api.orgs.admin.updateLumaConfig)
  const resolveLumaCalendar = useAction(api.events.sync.resolveLumaCalendar)

  // Populate form when config loads
  useEffect(() => {
    if (lumaConfig) {
      setLumaCalendarUrl(lumaConfig.lumaCalendarUrl || '')
      setIsResolved(!!lumaConfig.lumaCalendarApiId)
    }
  }, [lumaConfig])

  // Loading state
  if (org === undefined || membership === undefined) {
    return (
      <div className="min-h-screen bg-slate-50">
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-2xl mx-auto">
            <div className="animate-pulse space-y-6">
              <div className="h-12 bg-slate-100 rounded-xl w-1/3" />
              <div className="h-64 bg-slate-100 rounded-xl" />
            </div>
          </div>
        </main>
      </div>
    )
  }

  // Org not found
  if (org === null) {
    return (
      <div className="min-h-screen bg-slate-50">
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Building2 className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-display text-foreground mb-4">
              Organization Not Found
            </h1>
            <Button asChild>
              <Link to="/">Go Home</Link>
            </Button>
          </div>
        </main>
      </div>
    )
  }

  // Not an admin
  if (!membership || membership.role !== 'admin') {
    return (
      <div className="min-h-screen bg-slate-50">
        <AuthHeader />
        <main className="container mx-auto px-4 py-8">
          <div className="max-w-lg mx-auto text-center py-12">
            <div className="size-16 rounded-full bg-slate-100 flex items-center justify-center mx-auto mb-4">
              <Shield className="size-8 text-slate-400" />
            </div>
            <h1 className="text-2xl font-display text-foreground mb-4">
              Admin Access Required
            </h1>
            <Button asChild>
              <Link to="/org/$slug" params={{ slug }}>
                Back to Organization
              </Link>
            </Button>
          </div>
        </main>
      </div>
    )
  }

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault()
    setIsSaving(true)

    try {
      const trimmedUrl = lumaCalendarUrl.trim()
      let calendarApiId: string | undefined

      // Auto-resolve calendar API ID from URL
      if (trimmedUrl) {
        try {
          calendarApiId = await resolveLumaCalendar({
            calendarUrl: trimmedUrl,
          })
        } catch (resolveError) {
          console.error('Failed to resolve Lu.ma calendar:', resolveError)
          toast.error(
            'Could not resolve Lu.ma calendar. Please check the URL and try again.',
          )
          setIsSaving(false)
          return
        }
      }

      await updateLumaConfig({
        orgId: org._id,
        lumaCalendarUrl: trimmedUrl || undefined,
        lumaCalendarApiId: calendarApiId,
      })
      setIsResolved(!!calendarApiId)
      toast.success('Settings saved successfully')
    } catch (error) {
      console.error('Failed to save settings:', error)
      toast.error('Failed to save settings. Please try again.')
    } finally {
      setIsSaving(false)
    }
  }

  return (
    <div className="min-h-screen bg-slate-50">
      <AuthHeader />
      <main className="container mx-auto px-4 py-8">
        <div className="max-w-2xl mx-auto">
          {/* Header */}
          <div className="mb-8">
            <div className="flex items-center gap-2 text-slate-500 text-sm mb-2">
              <Link
                to="/org/$slug"
                params={{ slug }}
                className="hover:text-slate-700 transition-colors"
              >
                {org.name}
              </Link>
              <span>/</span>
              <Link
                to="/org/$slug/admin"
                params={{ slug }}
                className="hover:text-slate-700 transition-colors"
              >
                Admin
              </Link>
              <span>/</span>
              <span className="text-slate-700">Settings</span>
            </div>
            <h1 className="text-2xl font-display text-foreground">Settings</h1>
            <p className="text-slate-600 mt-1">
              Configure integrations and organization settings
            </p>
          </div>

          {/* Lu.ma Configuration */}
          <Card>
            <CardHeader>
              <CardTitle>Lu.ma Events Integration</CardTitle>
              <CardDescription>
                Connect your lu.ma calendar to display events on your
                organization page and dashboard
              </CardDescription>
            </CardHeader>
            <CardContent>
              {lumaConfig === undefined ? (
                <div className="flex justify-center py-8">
                  <Spinner className="size-6" />
                </div>
              ) : (
                <form onSubmit={handleSave} className="space-y-6">
                  <div className="space-y-2">
                    <Label htmlFor="lumaCalendarUrl">Lu.ma Calendar URL</Label>
                    <Input
                      id="lumaCalendarUrl"
                      type="url"
                      placeholder="https://lu.ma/your-calendar"
                      value={lumaCalendarUrl}
                      onChange={(e) => {
                        setLumaCalendarUrl(e.target.value)
                        setIsResolved(false)
                      }}
                    />
                    <p className="text-sm text-slate-500">
                      Your public lu.ma calendar URL (e.g.,
                      https://lu.ma/your-calendar). Events will be synced
                      automatically.
                    </p>
                  </div>

                  {isResolved && (
                    <div className="flex items-center gap-2 text-sm text-green-700">
                      <CheckCircle2 className="size-4" />
                      Calendar connected - events will sync daily
                    </div>
                  )}

                  {lumaConfig.eventsLastSynced && (
                    <div className="rounded-lg bg-slate-50 px-4 py-3 text-sm">
                      <span className="text-slate-600">Last synced: </span>
                      <span className="text-foreground">
                        {new Date(lumaConfig.eventsLastSynced).toLocaleString()}
                      </span>
                    </div>
                  )}

                  <Button type="submit" disabled={isSaving}>
                    {isSaving ? (
                      <>
                        <Loader2 className="size-4 mr-2 animate-spin" />
                        Saving...
                      </>
                    ) : (
                      <>
                        <Save className="size-4 mr-2" />
                        Save Changes
                      </>
                    )}
                  </Button>
                </form>
              )}
            </CardContent>
          </Card>
        </div>
      </main>
    </div>
  )
}
