// src/components/settings/AttendancePrivacyForm.svelte
<script lang="ts">
  import { Building2, CalendarCheck2, Eye } from 'lucide-svelte'
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import { api } from '$convex/_generated/api'
  import { getClerkContext } from '$lib/stores/clerk.svelte'
  import Spinner from '~/components/ui/spinner.svelte'

  const clerkContext = getClerkContext()
  const convex = useConvexClient()
  const privacyDefaults = useQuery(
    api.attendance.queries.getAttendancePrivacyDefaults,
    () => (clerkContext.currentUser ? {} : 'skip'),
  )

  let showOnProfile = $state(true)
  let showToOtherOrgs = $state(false)
  let hasChanges = $state(false)
  let saving = $state(false)

  $effect(() => {
    if (!privacyDefaults.data) {
      return
    }

    showOnProfile = privacyDefaults.data.showOnProfile
    showToOtherOrgs = privacyDefaults.data.showToOtherOrgs
    hasChanges = false
  })

  const toggleShowOnProfile = () => {
    showOnProfile = !showOnProfile
    if (!showOnProfile) {
      showToOtherOrgs = false
    }
    hasChanges = true
  }

  const save = async () => {
    saving = true

    try {
      await convex.mutation(api.attendance.mutations.updateAttendancePrivacy, {
        showOnProfile,
        showToOtherOrgs,
        updateExisting: true,
      })
      hasChanges = false
      toast.success('Attendance privacy settings saved')
    } catch (error) {
      console.error('Failed to update attendance privacy:', error)
      toast.error('Failed to save attendance privacy settings')
    } finally {
      saving = false
    }
  }
</script>

<section class="rounded-[1.75rem] border border-border/70 bg-white/92 shadow-warm-sm">
  <div class="border-b border-border/70 px-6 py-5">
    <div class="flex items-center gap-3">
      <div class="flex size-10 items-center justify-center rounded-2xl bg-violet-100 text-violet-700">
        <CalendarCheck2 class="size-5" />
      </div>
      <div>
        <h2 class="text-lg font-semibold text-slate-950">Attendance Privacy</h2>
        <p class="mt-1 text-sm text-slate-600">
          Decide who can see your event attendance history.
        </p>
      </div>
    </div>
  </div>

  <div class="space-y-6 px-6 py-6">
    {#if privacyDefaults.isLoading}
      <div class="flex items-center justify-center py-8">
        <Spinner />
      </div>
    {:else}
      <label class="flex items-start justify-between gap-4">
        <div class="space-y-1">
          <div class="flex items-center gap-2 text-base font-medium text-slate-950">
            <Eye class="size-4 text-coral-600" />
            Show on Profile
          </div>
          <p class="text-sm text-slate-600">
            Other users can see your attendance history on your profile.
          </p>
        </div>
        <input
          type="checkbox"
          checked={showOnProfile}
          onchange={() => {
            toggleShowOnProfile()
          }}
          class="mt-1 size-5 rounded border-border text-coral-600 focus:ring-coral-500"
        />
      </label>

      <label class="flex items-start justify-between gap-4">
        <div class="space-y-1">
          <div class="flex items-center gap-2 text-base font-medium text-slate-950">
            <Building2 class="size-4 text-coral-600" />
            Share with Other Organizations
          </div>
          <p class="text-sm text-slate-600">
            Organizations you are not a member of can see your attendance.
          </p>
        </div>
        <input
          type="checkbox"
          bind:checked={showToOtherOrgs}
          disabled={!showOnProfile}
          onchange={() => {
            hasChanges = true
          }}
          class="mt-1 size-5 rounded border-border text-coral-600 focus:ring-coral-500 disabled:cursor-not-allowed disabled:opacity-50"
        />
      </label>

      <div class="rounded-2xl border border-slate-200 bg-slate-50 px-4 py-3 text-sm text-slate-600">
        The host organization always sees attendance at its own events. Saving
        here also updates your existing attendance records.
      </div>

      <div class="border-t border-border/70 pt-4">
        <button
          type="button"
          disabled={!hasChanges || saving}
          onclick={save}
          class="inline-flex min-w-32 items-center justify-center rounded-xl bg-coral-500 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-coral-600 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {#if saving}
            Saving...
          {:else}
            Save Changes
          {/if}
        </button>

        {#if hasChanges}
          <p class="mt-2 text-xs text-slate-500">
            Changes will apply to all your attendance records.
          </p>
        {/if}
      </div>
    {/if}
  </div>
</section>

// src/components/settings/AttendancePrivacyForm.tsx
import { useMutation, useQuery } from "convex/react";
import { useEffect, useState } from "react";
import { Building2, CalendarCheck, Eye } from "lucide-react";
import { toast } from "sonner";
import { api } from "../../../convex/_generated/api";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "~/components/ui/card";
import { Switch } from "~/components/ui/switch";
import { Label } from "~/components/ui/label";
import { Button } from "~/components/ui/button";
import { Spinner } from "~/components/ui/spinner";

export function AttendancePrivacyForm() {
  const privacyDefaults = useQuery(
    api.attendance.queries.getAttendancePrivacyDefaults
  );
  const updatePrivacy = useMutation(
    api.attendance.mutations.updateAttendancePrivacy
  );

  const [showOnProfile, setShowOnProfile] = useState(true);
  const [showToOtherOrgs, setShowToOtherOrgs] = useState(false);
  const [hasChanges, setHasChanges] = useState(false);
  const [saving, setSaving] = useState(false);

  // Sync local state with loaded preferences
  useEffect(() => {
    if (privacyDefaults) {
      setShowOnProfile(privacyDefaults.showOnProfile);
      setShowToOtherOrgs(privacyDefaults.showToOtherOrgs);
      setHasChanges(false);
    }
  }, [privacyDefaults]);

  const handleShowOnProfileChange = (checked: boolean) => {
    setShowOnProfile(checked);
    setHasChanges(true);
    // If hiding from profile, also hide from other orgs
    if (!checked) {
      setShowToOtherOrgs(false);
    }
  };

  const handleShowToOtherOrgsChange = (checked: boolean) => {
    setShowToOtherOrgs(checked);
    setHasChanges(true);
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await updatePrivacy({
        showOnProfile,
        showToOtherOrgs,
        updateExisting: true, // Apply to existing records too
      });
      setHasChanges(false);
      toast.success("Attendance privacy settings saved");
    } catch (error) {
      toast.error("Failed to save attendance privacy settings");
      console.error("Failed to update attendance privacy:", error);
    } finally {
      setSaving(false);
    }
  };

  // Show loading state
  if (privacyDefaults === undefined) {
    return (
      <Card className="max-w-2xl">
        <CardContent className="flex items-center justify-center py-8">
          <Spinner />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="max-w-2xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <CalendarCheck className="size-5" />
          Attendance Privacy
        </CardTitle>
        <CardDescription>
          Control who can see your event attendance history
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Show on Profile Toggle */}
        <div className="flex items-center justify-between">
          <div className="space-y-0.5">
            <Label
              htmlFor="show-on-profile"
              className="flex items-center gap-2 text-base font-medium"
            >
              <Eye className="size-4 text-primary" />
              Show on Profile
            </Label>
            <p className="text-sm text-slate-500">
              Other users can see your attendance history on your profile
            </p>
          </div>
          <Switch
            id="show-on-profile"
            checked={showOnProfile}
            onCheckedChange={handleShowOnProfileChange}
          />
        </div>

        {/* Share with Other Orgs Toggle */}
        <div className="flex items-center justify-between">
          <div className="space-y-0.5">
            <Label
              htmlFor="show-to-other-orgs"
              className="flex items-center gap-2 text-base font-medium"
            >
              <Building2 className="size-4 text-primary" />
              Share with Other Organizations
            </Label>
            <p className="text-sm text-slate-500">
              Organizations you are not a member of can see your attendance
            </p>
          </div>
          <Switch
            id="show-to-other-orgs"
            checked={showToOtherOrgs}
            onCheckedChange={handleShowToOtherOrgsChange}
            disabled={!showOnProfile}
          />
        </div>

        {/* Informational note */}
        <div className="rounded-lg bg-slate-50 p-4 text-sm text-slate-600">
          <p>
            The hosting organization always sees attendance at their events,
            regardless of these settings. This helps orgs understand event
            engagement.
          </p>
        </div>

        {/* Save Button */}
        <div className="pt-4 border-t">
          <Button
            onClick={handleSave}
            disabled={!hasChanges || saving}
            className="w-full sm:w-auto"
          >
            {saving ? (
              <>
                <Spinner className="size-4 mr-2" />
                Saving...
              </>
            ) : (
              "Save Changes"
            )}
          </Button>
          {hasChanges && (
            <p className="text-xs text-slate-500 mt-2">
              Changes will apply to all your attendance records
            </p>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
