// src/components/settings/EventNotificationPrefsForm.tsx
import { useMutation, useQuery } from "convex/react";
import { useEffect, useState } from "react";
import { toast } from "sonner";
import { BellOff, Calendar } from "lucide-react";
import { api } from "../../../convex/_generated/api";
import type { Id } from "../../../convex/_generated/dataModel";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "~/components/ui/card";
import { Switch } from "~/components/ui/switch";
import { Label } from "~/components/ui/label";
import { Checkbox } from "~/components/ui/checkbox";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "~/components/ui/select";
import { Button } from "~/components/ui/button";
import { Spinner } from "~/components/ui/spinner";

type Frequency = "all" | "daily" | "weekly" | "none";

const FREQUENCY_OPTIONS: Array<{ value: Frequency; label: string; description: string }> = [
  { value: "all", label: "All new events", description: "Get notified immediately (rate limited)" },
  { value: "daily", label: "Daily digest", description: "One email per day summarizing new events" },
  { value: "weekly", label: "Weekly digest", description: "One email per week summarizing new events" },
  { value: "none", label: "None", description: "No event notifications" },
];

export function EventNotificationPrefsForm() {
  const preferences = useQuery(api.profiles.getEventNotificationPreferences);
  const memberships = useQuery(api.orgs.membership.getUserMemberships);
  const updatePreferences = useMutation(api.profiles.updateEventNotificationPreferences);

  // Local state for form
  const [frequency, setFrequency] = useState<Frequency>("weekly");
  const [oneWeekBefore, setOneWeekBefore] = useState(false);
  const [oneDayBefore, setOneDayBefore] = useState(true);
  const [oneHourBefore, setOneHourBefore] = useState(true);
  const [mutedOrgIds, setMutedOrgIds] = useState<Array<Id<"organizations">>>([]);
  const [hasChanges, setHasChanges] = useState(false);
  const [saving, setSaving] = useState(false);

  // Sync local state with loaded preferences
  useEffect(() => {
    if (preferences) {
      setFrequency(preferences.frequency);
      if (preferences.reminderTiming) {
        setOneWeekBefore(preferences.reminderTiming.oneWeekBefore);
        setOneDayBefore(preferences.reminderTiming.oneDayBefore);
        setOneHourBefore(preferences.reminderTiming.oneHourBefore);
      }
      setMutedOrgIds(preferences.mutedOrgIds as Array<Id<"organizations">>);
      setHasChanges(false);
    }
  }, [preferences]);

  // Track changes
  const handleFrequencyChange = (value: Frequency) => {
    setFrequency(value);
    setHasChanges(true);
  };

  const handleReminderChange = (
    setter: React.Dispatch<React.SetStateAction<boolean>>
  ) => (checked: boolean) => {
    setter(checked);
    setHasChanges(true);
  };

  const handleOrgMuteToggle = (orgId: Id<"organizations">) => {
    setMutedOrgIds((current) => {
      const isMuted = current.includes(orgId);
      const updated = isMuted
        ? current.filter((id) => id !== orgId)
        : [...current, orgId];
      setHasChanges(true);
      return updated;
    });
  };

  const handleSave = async () => {
    setSaving(true);
    try {
      await updatePreferences({
        frequency,
        reminderTiming: {
          oneWeekBefore,
          oneDayBefore,
          oneHourBefore,
        },
        mutedOrgIds,
      });
      setHasChanges(false);
      toast.success("Event notification preferences saved");
    } catch (error) {
      toast.error("Failed to save preferences");
      console.error("Failed to save preferences:", error);
    } finally {
      setSaving(false);
    }
  };

  // Show loading state
  if (preferences === undefined || memberships === undefined) {
    return (
      <Card className="max-w-2xl">
        <CardContent className="flex items-center justify-center py-8">
          <Spinner />
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="max-w-2xl">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <Calendar className="size-5" />
          Event Notifications
        </CardTitle>
        <CardDescription>
          Control how you receive updates about events from organizations you&apos;ve joined.
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {/* Frequency Select */}
        <div className="space-y-2">
          <Label htmlFor="frequency" className="text-base font-medium">
            Notification Frequency
          </Label>
          <p className="text-sm text-slate-500 mb-2">
            How often should we notify you about new events?
          </p>
          <Select value={frequency} onValueChange={handleFrequencyChange}>
            <SelectTrigger className="w-full">
              <SelectValue placeholder="Select frequency" />
            </SelectTrigger>
            <SelectContent>
              {FREQUENCY_OPTIONS.map((option) => (
                <SelectItem key={option.value} value={option.value}>
                  <div className="flex flex-col">
                    <span>{option.label}</span>
                    <span className="text-xs text-slate-500">{option.description}</span>
                  </div>
                </SelectItem>
              ))}
            </SelectContent>
          </Select>
        </div>

        {/* Reminder Timing Checkboxes */}
        <div className="space-y-3">
          <Label className="text-base font-medium">Event Reminders</Label>
          <p className="text-sm text-slate-500">
            Receive reminders before events you&apos;ve viewed
          </p>

          <div className="space-y-3 pt-2">
            <div className="flex items-center space-x-2">
              <Checkbox
                id="one-week"
                checked={oneWeekBefore}
                onCheckedChange={handleReminderChange(setOneWeekBefore)}
              />
              <Label htmlFor="one-week" className="text-sm font-normal cursor-pointer">
                1 week before
              </Label>
            </div>

            <div className="flex items-center space-x-2">
              <Checkbox
                id="one-day"
                checked={oneDayBefore}
                onCheckedChange={handleReminderChange(setOneDayBefore)}
              />
              <Label htmlFor="one-day" className="text-sm font-normal cursor-pointer">
                1 day before
              </Label>
            </div>

            <div className="flex items-center space-x-2">
              <Checkbox
                id="one-hour"
                checked={oneHourBefore}
                onCheckedChange={handleReminderChange(setOneHourBefore)}
              />
              <Label htmlFor="one-hour" className="text-sm font-normal cursor-pointer">
                1 hour before
              </Label>
            </div>
          </div>
        </div>

        {/* Org Muting Section */}
        <div className="space-y-3">
          <Label className="text-base font-medium flex items-center gap-2">
            <BellOff className="size-4" />
            Organization Notifications
          </Label>
          <p className="text-sm text-slate-500">
            Toggle notifications for specific organizations
          </p>

          {memberships.length === 0 ? (
            <p className="text-sm text-slate-400 italic py-2">
              No organizations joined yet. Join an organization to manage notifications.
            </p>
          ) : (
            <div className="space-y-3 pt-2">
              {memberships.map((membership) => {
                if (!membership.org) return null;
                const isMuted = mutedOrgIds.includes(membership.orgId);

                return (
                  <div key={membership._id} className="flex items-center justify-between">
                    <div className="flex items-center gap-3">
                      {membership.org.logoUrl ? (
                        <img
                          src={membership.org.logoUrl}
                          alt={membership.org.name}
                          className="size-8 rounded-full object-cover"
                        />
                      ) : (
                        <div className="size-8 rounded-full bg-primary/10 flex items-center justify-center">
                          <span className="text-xs font-medium text-primary">
                            {membership.org.name.charAt(0).toUpperCase()}
                          </span>
                        </div>
                      )}
                      <span className="text-sm font-medium">{membership.org.name}</span>
                    </div>
                    <Switch
                      checked={!isMuted}
                      onCheckedChange={() => handleOrgMuteToggle(membership.orgId)}
                      aria-label={`Toggle notifications for ${membership.org.name}`}
                    />
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Save Button */}
        <div className="pt-4 border-t">
          <Button
            onClick={handleSave}
            disabled={!hasChanges || saving}
            className="w-full sm:w-auto"
          >
            {saving ? (
              <>
                <Spinner className="size-4 mr-2" />
                Saving...
              </>
            ) : (
              "Save Changes"
            )}
          </Button>
        </div>
      </CardContent>
    </Card>
  );
}

// src/components/settings/EventNotificationPrefsForm.svelte
<script lang="ts">
  import { BellOff, Calendar } from 'lucide-svelte'
  import { toast } from 'svelte-sonner'
  import { useConvexClient, useQuery } from 'convex-svelte'
  import { api } from '$convex/_generated/api'
  import type { Id } from '$convex/_generated/dataModel'
  import { getClerkContext } from '$lib/stores/clerk.svelte'
  import Spinner from '~/components/ui/spinner.svelte'

  type Frequency = 'all' | 'daily' | 'weekly' | 'none'

  const FREQUENCY_OPTIONS: Array<{
    value: Frequency
    label: string
    description: string
  }> = [
    {
      value: 'all',
      label: 'All new events',
      description: 'Get notified immediately, with rate limiting.',
    },
    {
      value: 'daily',
      label: 'Daily digest',
      description: 'One email per day with new events.',
    },
    {
      value: 'weekly',
      label: 'Weekly digest',
      description: 'One email per week with new events.',
    },
    {
      value: 'none',
      label: 'None',
      description: 'Disable new event notifications.',
    },
  ]

  const clerkContext = getClerkContext()
  const convex = useConvexClient()
  const preferences = useQuery(api.profiles.getEventNotificationPreferences, () =>
    clerkContext.currentUser ? {} : 'skip',
  )
  const memberships = useQuery(api.orgs.membership.getUserMemberships, () =>
    clerkContext.currentUser ? {} : 'skip',
  )

  let frequency = $state<Frequency>('weekly')
  let oneWeekBefore = $state(false)
  let oneDayBefore = $state(true)
  let oneHourBefore = $state(true)
  let mutedOrgIds = $state<Array<Id<'organizations'>>>([])
  let hasChanges = $state(false)
  let saving = $state(false)

  $effect(() => {
    if (!preferences.data) {
      return
    }

    frequency = preferences.data.frequency
    oneWeekBefore = preferences.data.reminderTiming?.oneWeekBefore ?? false
    oneDayBefore = preferences.data.reminderTiming?.oneDayBefore ?? true
    oneHourBefore = preferences.data.reminderTiming?.oneHourBefore ?? true
    mutedOrgIds = [...preferences.data.mutedOrgIds] as Array<Id<'organizations'>>
    hasChanges = false
  })

  const toggleMutedOrg = (orgId: Id<'organizations'>) => {
    mutedOrgIds = mutedOrgIds.includes(orgId)
      ? mutedOrgIds.filter((id) => id !== orgId)
      : [...mutedOrgIds, orgId]
    hasChanges = true
  }

  const save = async () => {
    saving = true

    try {
      await convex.mutation(api.profiles.updateEventNotificationPreferences, {
        frequency,
        reminderTiming: {
          oneWeekBefore,
          oneDayBefore,
          oneHourBefore,
        },
        mutedOrgIds,
      })
      hasChanges = false
      toast.success('Event notification preferences saved')
    } catch (error) {
      console.error('Failed to save event notification preferences:', error)
      toast.error('Failed to save preferences')
    } finally {
      saving = false
    }
  }
</script>

<section class="rounded-[1.75rem] border border-border/70 bg-white/92 shadow-warm-sm">
  <div class="border-b border-border/70 px-6 py-5">
    <div class="flex items-center gap-3">
      <div class="flex size-10 items-center justify-center rounded-2xl bg-teal-100 text-teal-700">
        <Calendar class="size-5" />
      </div>
      <div>
        <h2 class="text-lg font-semibold text-slate-950">Event Notifications</h2>
        <p class="mt-1 text-sm text-slate-600">
          Control how ASTN updates you about events from organizations you've
          joined.
        </p>
      </div>
    </div>
  </div>

  <div class="space-y-6 px-6 py-6">
    {#if preferences.isLoading || memberships.isLoading}
      <div class="flex items-center justify-center py-8">
        <Spinner />
      </div>
    {:else}
      <div class="space-y-2">
        <label for="event-frequency" class="text-base font-medium text-slate-950">
          Notification Frequency
        </label>
        <p class="text-sm text-slate-600">
          Choose how often we should notify you about new events.
        </p>
        <select
          id="event-frequency"
          bind:value={frequency}
          onchange={() => {
            hasChanges = true
          }}
          class="w-full rounded-xl border border-border bg-background px-3 py-2 text-sm text-foreground outline-none transition focus:border-coral-300 focus:ring-2 focus:ring-coral-200"
        >
          {#each FREQUENCY_OPTIONS as option}
            <option value={option.value}>
              {option.label} - {option.description}
            </option>
          {/each}
        </select>
      </div>

      <fieldset class="space-y-3">
        <legend class="text-base font-medium text-slate-950">
          Event Reminders
        </legend>
        <p class="text-sm text-slate-600">
          Receive reminders before events you've viewed or saved.
        </p>

        <label class="flex items-center gap-3 text-sm text-slate-700">
          <input
            type="checkbox"
            bind:checked={oneWeekBefore}
            onchange={() => {
              hasChanges = true
            }}
            class="size-4 rounded border-border text-coral-600 focus:ring-coral-500"
          />
          <span>1 week before</span>
        </label>

        <label class="flex items-center gap-3 text-sm text-slate-700">
          <input
            type="checkbox"
            bind:checked={oneDayBefore}
            onchange={() => {
              hasChanges = true
            }}
            class="size-4 rounded border-border text-coral-600 focus:ring-coral-500"
          />
          <span>1 day before</span>
        </label>

        <label class="flex items-center gap-3 text-sm text-slate-700">
          <input
            type="checkbox"
            bind:checked={oneHourBefore}
            onchange={() => {
              hasChanges = true
            }}
            class="size-4 rounded border-border text-coral-600 focus:ring-coral-500"
          />
          <span>1 hour before</span>
        </label>
      </fieldset>

      <div class="space-y-3">
        <div class="flex items-center gap-2 text-base font-medium text-slate-950">
          <BellOff class="size-4 text-coral-600" />
          Organization Notifications
        </div>
        <p class="text-sm text-slate-600">
          Mute event notifications from individual organizations without leaving
          them.
        </p>

        {#if !(memberships.data?.length)}
          <div class="rounded-xl border border-dashed border-border bg-slate-50 px-4 py-3 text-sm text-slate-500">
            You haven't joined any organizations yet.
          </div>
        {:else}
          <div class="space-y-3">
            {#each memberships.data ?? [] as membership (membership._id)}
              {@const notificationsEnabled = !mutedOrgIds.includes(membership.orgId)}
              <div class="flex items-center justify-between gap-4 rounded-2xl border border-border/70 bg-slate-50/80 px-4 py-3">
                <div class="flex min-w-0 items-center gap-3">
                  {#if membership.org.logoUrl}
                    <img
                      src={membership.org.logoUrl}
                      alt={membership.org.name}
                      class="size-10 rounded-full object-cover"
                    />
                  {:else}
                    <div class="flex size-10 items-center justify-center rounded-full bg-coral-100 text-sm font-semibold text-coral-700">
                      {membership.org.name.charAt(0).toUpperCase()}
                    </div>
                  {/if}
                  <div class="min-w-0">
                    <div class="truncate font-medium text-slate-950">
                      {membership.org.name}
                    </div>
                    <p class="text-xs text-slate-500">
                      {#if notificationsEnabled}
                        Notifications enabled
                      {:else}
                        Notifications muted
                      {/if}
                    </p>
                  </div>
                </div>

                <input
                  type="checkbox"
                  checked={notificationsEnabled}
                  onchange={() => {
                    toggleMutedOrg(membership.orgId)
                  }}
                  aria-label={`Toggle notifications for ${membership.org.name}`}
                  class="size-5 rounded border-border text-coral-600 focus:ring-coral-500"
                />
              </div>
            {/each}
          </div>
        {/if}
      </div>

      <div class="border-t border-border/70 pt-4">
        <button
          type="button"
          disabled={!hasChanges || saving}
          onclick={save}
          class="inline-flex min-w-32 items-center justify-center rounded-xl bg-coral-500 px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-coral-600 disabled:cursor-not-allowed disabled:opacity-60"
        >
          {#if saving}
            Saving...
          {:else}
            Save Changes
          {/if}
        </button>
      </div>
    {/if}
  </div>
</section>
