// src/components/auth/onboarding-guard.tsx
import { usePostHog } from '@posthog/react'
import { useEffect, useRef } from 'react'
import { useMutation, useQuery } from 'convex/react'
import { api } from '../../../convex/_generated/api'
import { Spinner } from '~/components/ui/spinner'

/**
 * Guard that ensures a profile exists before rendering children.
 * Onboarding (profile building) now happens via the agent sidebar,
 * so this no longer redirects to the wizard or enrichment step.
 */
export function OnboardingGuard({ children }: { children: React.ReactNode }) {
  const posthog = usePostHog()
  const profile = useQuery(api.profiles.getOrCreateProfile)
  const createProfile = useMutation(api.profiles.create)
  const creating = useRef(false)

  // Auto-create profile for authenticated users who don't have one yet
  useEffect(() => {
    if (profile === null && !creating.current) {
      creating.current = true
      const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone
      createProfile({ timezone })
        .then(() => {
          posthog.capture('profile_created', { timezone })
        })
        .finally(() => {
          creating.current = false
        })
    }
  }, [profile, createProfile, posthog])

  // Loading or creating
  if (!profile) {
    return (
      <div className="flex items-center justify-center min-h-[calc(100vh-65px)]">
        <Spinner />
      </div>
    )
  }

  return <>{children}</>
}

// src/components/auth/OnboardingGuard.svelte
<script lang="ts">
  import { useConvexClient, useQuery } from 'convex-svelte'
  import { api } from '$convex/_generated/api'
  import { getClerkContext } from '$lib/stores/clerk.svelte'
  import { posthogStore } from '$lib/stores/posthog.svelte'

  const clerkContext = getClerkContext()
  const convex = useConvexClient()

  const profile = useQuery(
    api.profiles.getOrCreateProfile,
    () => (clerkContext.currentUser ? {} : 'skip'),
  )

  let creating = $state(false)
  const { children } = $props()

  $effect(() => {
    if (
      !clerkContext.currentUser ||
      profile.isLoading ||
      creating ||
      profile.data !== null
    ) {
      return
    }

    creating = true
    const timezone = Intl.DateTimeFormat().resolvedOptions().timeZone

    void convex
      .mutation(api.profiles.create, { timezone })
      .then(() => {
        posthogStore.capture('profile_created', { timezone })
      })
      .finally(() => {
        creating = false
      })
  })
</script>

{#if !clerkContext.currentUser}
  {@render children()}
{:else if profile.isLoading || creating || !profile.data}
  <div class="flex min-h-[calc(100vh-65px)] items-center justify-center">
    <div class="size-6 animate-spin rounded-full border-2 border-border border-t-coral-500"></div>
  </div>
{:else}
  {@render children()}
{/if}
