// src/components/ui/collapsible-section.svelte
<script lang="ts">
  import type { Snippet } from 'svelte'
  import { onMount } from 'svelte'
  import { cn } from '~/lib/utils'

  type Variant = 'default' | 'emerald' | 'violet'

  const triggerClasses: Record<Variant, string> = {
    default:
      'border bg-card text-foreground hover:bg-accent/50',
    emerald:
      'border border-emerald-200 bg-emerald-50 text-emerald-800 hover:bg-emerald-100/80',
    violet:
      'border border-violet-200 bg-violet-50 text-violet-800 hover:bg-violet-100/80',
  }

  const iconColorMap: Record<Variant, string> = {
    default: 'text-primary',
    emerald: 'text-emerald-600',
    violet: 'text-violet-600',
  }

  let {
    icon,
    iconClassName = '',
    title,
    count,
    subtitle,
    variant = 'default',
    defaultOpen = false,
    storageKey,
    itemCount,
    class: className = '',
    children,
  }: {
    icon?: any
    iconClassName?: string
    title: string
    count?: number
    subtitle?: string
    variant?: Variant
    defaultOpen?: boolean
    storageKey?: string
    itemCount?: number
    class?: string
    children?: Snippet
  } = $props()

  let open = $state(false)

  onMount(() => {
    open = defaultOpen

    if (!storageKey) return

    const stored = sessionStorage.getItem(storageKey)
    if (stored !== null) {
      open = stored === 'true'
    }
  })

  $effect(() => {
    if (!storageKey) return
    sessionStorage.setItem(storageKey, String(open))
  })

  const hiddenByPresence = $derived(itemCount != null && itemCount <= 0)
</script>

{#if !hiddenByPresence}
  <section class={cn('space-y-4', className)}>
    <button
      type="button"
      class={cn(
        'flex w-full items-center gap-3 rounded-lg px-4 py-3 text-left transition-colors',
        triggerClasses[variant],
      )}
      onclick={() => {
        open = !open
      }}
      aria-expanded={open}
    >
      {#if icon}
        <icon class={cn('size-5 shrink-0', iconColorMap[variant], iconClassName)}></icon>
      {/if}

      <div class="flex min-w-0 flex-1 items-center gap-2">
        <span class="text-sm font-semibold">
          {count != null ? `${count} ${title}` : title}
        </span>
        {#if subtitle}
          <span class="text-muted-foreground">·</span>
          <span class="text-sm text-muted-foreground">{subtitle}</span>
        {/if}
      </div>

      <svg
        class={cn(
          'size-4 shrink-0 text-muted-foreground transition-transform duration-200',
          open && 'rotate-180',
        )}
        viewBox="0 0 24 24"
        fill="none"
        stroke="currentColor"
        stroke-width="2"
      >
        <path d="M6 9l6 6 6-6" />
      </svg>
    </button>

    <div
      class={cn(
        'grid transition-[grid-template-rows] duration-200 ease-out',
        open ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]',
      )}
    >
      <div class="overflow-hidden">
        {@render children?.()}
      </div>
    </div>
  </section>
{/if}

// src/components/ui/collapsible-section.tsx
import { useEffect, useState } from 'react'
import { Collapsible as CollapsiblePrimitive } from 'radix-ui'
import { ChevronDown } from 'lucide-react'
import { cva } from 'class-variance-authority'
import type { ComponentType, ReactNode } from 'react'
import type { VariantProps } from 'class-variance-authority'
import { cn } from '~/lib/utils'

const triggerVariants = cva(
  'w-full flex items-center gap-3 px-4 py-3 rounded-lg transition-colors text-left hover:bg-accent/50',
  {
    variants: {
      variant: {
        default: 'border bg-card',
        emerald: 'bg-emerald-50 border border-emerald-200',
        violet: 'bg-violet-50 border border-violet-200',
      },
    },
    defaultVariants: { variant: 'default' },
  },
)

const iconColorMap = {
  default: 'text-primary',
  emerald: 'text-emerald-600',
  violet: 'text-violet-600',
} as const

const titleColorMap = {
  default: 'text-foreground',
  emerald: 'text-emerald-800',
  violet: 'text-violet-800',
} as const

interface CollapsibleSectionProps extends VariantProps<typeof triggerVariants> {
  icon: ComponentType<{ className?: string }>
  iconClassName?: string
  title: string
  count?: number
  subtitle?: ReactNode
  defaultOpen?: boolean
  storageKey?: string
  itemCount?: number
  children: ReactNode
  className?: string
}

export function CollapsibleSection({
  icon: Icon,
  iconClassName,
  title,
  count,
  subtitle,
  variant = 'default',
  defaultOpen = false,
  storageKey,
  itemCount,
  children,
  className,
}: CollapsibleSectionProps) {
  const v = variant ?? 'default'

  const [open, setOpen] = useState(() => {
    if (storageKey && typeof window !== 'undefined') {
      const stored = sessionStorage.getItem(storageKey)
      if (stored !== null) return stored === 'true'
    }
    return defaultOpen
  })

  // Persist to sessionStorage
  useEffect(() => {
    if (storageKey) {
      sessionStorage.setItem(storageKey, String(open))
    }
  }, [open, storageKey])

  // Presence fade: animate in/out based on itemCount
  const [isVisible, setIsVisible] = useState(
    itemCount != null ? itemCount > 0 : true,
  )

  useEffect(() => {
    if (itemCount == null) return
    if (itemCount > 0 && !isVisible) {
      requestAnimationFrame(() => setIsVisible(true))
    } else if (itemCount === 0 && isVisible) {
      setIsVisible(false)
    }
  }, [itemCount, isVisible])

  // Don't render if presence-managed and never had items
  if (itemCount != null && itemCount === 0 && !isVisible) return null

  const hasPresence = itemCount != null
  const isPresent = !hasPresence || (isVisible && itemCount > 0)

  return (
    <CollapsiblePrimitive.Root open={open} onOpenChange={setOpen} asChild>
      <section
        className={cn(
          hasPresence && 'overflow-hidden transition-all duration-300 ease-out',
          hasPresence && (isPresent ? 'opacity-100' : 'opacity-0'),
          className,
        )}
        style={
          hasPresence ? { maxHeight: isPresent ? '2000px' : '0px' } : undefined
        }
      >
        <CollapsiblePrimitive.CollapsibleTrigger
          className={cn(triggerVariants({ variant }))}
        >
          <Icon
            className={cn('size-5 shrink-0', iconColorMap[v], iconClassName)}
          />
          <div className="flex items-center gap-2 flex-1 min-w-0">
            <span className={cn('text-sm font-semibold', titleColorMap[v])}>
              {count != null ? `${count} ${title}` : title}
            </span>
            {subtitle && (
              <>
                <span className="text-muted-foreground">·</span>
                <span className="text-sm text-muted-foreground">
                  {subtitle}
                </span>
              </>
            )}
          </div>
          <ChevronDown
            suppressHydrationWarning
            className={cn(
              'size-4 shrink-0 transition-transform duration-200 text-muted-foreground',
              open && 'rotate-180',
            )}
          />
        </CollapsiblePrimitive.CollapsibleTrigger>

        {/* CSS grid-rows animation instead of Radix CollapsibleContent (display:none) */}
        <div
          suppressHydrationWarning
          className={cn(
            'grid mt-4 will-change-[grid-template-rows]',
            'transition-[grid-template-rows] duration-200 ease-out',
            open ? 'grid-rows-[1fr]' : 'grid-rows-[0fr]',
          )}
        >
          <div className="overflow-hidden">{children}</div>
        </div>
      </section>
    </CollapsiblePrimitive.Root>
  )
}
