// src/components/ui/spinner.svelte
<script lang="ts">
  import { cn } from '~/lib/utils'

  let {
    class: className = '',
    size = 'md',
    ...rest
  }: {
    class?: string
    size?: 'sm' | 'md' | 'lg'
  } = $props()

  const sizeClasses = {
    sm: 'size-4',
    md: 'size-6',
    lg: 'size-8',
  }
</script>

<div
  class={cn(
    'animate-spin rounded-full border-2 border-slate-200 border-t-slate-600',
    sizeClasses[size],
    className,
  )}
  role="status"
  aria-label="Loading"
  {...rest}
>
  <span class="sr-only">Loading...</span>
</div>

// src/components/ui/spinner.tsx
import * as React from 'react'
import { cn } from '~/lib/utils'

interface SpinnerProps extends React.ComponentProps<'div'> {
  size?: 'sm' | 'md' | 'lg'
}

export function Spinner({ className, size = 'md', ...props }: SpinnerProps) {
  const sizeClasses = {
    sm: 'w-4 h-4',
    md: 'w-6 h-6',
    lg: 'w-8 h-8',
  }

  return (
    <div
      className={cn(
        'animate-spin rounded-full border-2 border-slate-200 border-t-slate-600',
        sizeClasses[size],
        className,
      )}
      role="status"
      aria-label="Loading"
      {...props}
    >
      <span className="sr-only">Loading...</span>
    </div>
  )
}
